### ISSUE TITLE
"Try It Now" button adds incorrect tag to new post

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#10004]
### Please describe the problem

> What happened just before the problem occurred? 

Jeanette used the "Try it now" button on an activity post for the first time last week, and reported that this brings up a blank research note with pre-populated tags. 

> What did you expect to see that you didn't?

We expected to click "Try it now" on an activity, and have a new post editor open with blue alert box at the top that says "this is an attempt to replicate an activity." 

She noticed that one of the tags was `activity:nodenumber`, and was wondering if it's supposed to be `replication:nodenumber`, so she tested adding the `replication:nodenumber` tags to her post, and she successfully got the blue alert box I expected at the top that says "this is an attempt to replicate an activity." 

### Please show us where to look

Here's the activity she replicated: https://publiclab.org/notes/warren/03-01-2019/build-a-sound-generating-coqui-conductivity-sensor

### What's your PublicLab.org username?

liz 
bhamster

**Comment by max-keviv** [comment]
@ebarry "Try it now" button is working

**Comment by noi5e** [comment]
I was just able to reproduce this bug:
https://user-images.githubusercontent.com/4361605/128772903-8a299810-a969-40bc-b247-3e23315f411e.mov

Clicking on `Try It Now` leads to this outcome:

> a blank research note with pre-populated tags.

Instead of this desired outcome:

> a new post editor open with blue alert box at the top that says "this is an attempt to replicate an activity."

@ebarry Is the only thing that's missing here the _blue alert box_? Would you say that it's routing to the correct page? (https://publiclab.org/post)

**Comment by ebarry** [comment]
Thanks @noi5e !
Yes, that's what's missing in this case. And @bhamster thinks it might be because `activity:nodenumber` is being added instead of `replication:nodenumber`

**Comment by jywarren** [comment]
I want to say it's in this segment of code, but I can't find where `activity:_____` is being inserted:

https://github.com/publiclab/plots2/blob/aeb6c35f16c1944f1f524becae3c710ed4282822/app/views/notes/_responses.html.erb#L8-L17

Ah, wait -- here it is:

https://github.com/publiclab/plots2/blob/e646cfd248e46fe9cf11a2eb7860bbf29f949b7d/app/views/tag/_replication.html.erb#L1-L7

Now, what should we change? `response_type` should insert `replication` instead of `activity`, right?

**Comment by jywarren** [comment]
Is it a replication in either case, whether it's to an update or an activity?
