### ISSUE TITLE
DISCUSSION: spam tags with followers who have [not yet] been banned still displayed on /stats/subscriptions

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#10012]
**Please describe the desired behavior.**

I want to be able to delete spam tags which have more than 0 followers. 
UPDATE: I do not want to see spam tags on /stats/subscriptions

**Additional context (optional)**
This spammy tag "Which-are-the-best-content-and-article-writing-services-online" apparently has a follower, which means it shows up in our subscription statistics: https://publiclab.org/stats/subscriptions

--> https://publiclab.org/tag/Which-are-the-best-content-and-article-writing-services-online 

The tag page shows no content associated with this spam tag: 
<img width="1071" alt="Screen Shot 2021-08-10 at 9 34 54 AM" src="https://user-images.githubusercontent.com/161439/128876486-39ec4c78-5221-41e8-a1a6-9df34d1fa576.png">

How can moderators delete a tag like this?

**Comment by jywarren** [comment]
I'm looking and i see a filter for followers of status = 1, so i wonder if that follower is somehow not banned? We should dig a little deeper here. But tag deletion could work too...

https://github.com/publiclab/plots2/blob/aeb6c35f16c1944f1f524becae3c710ed4282822/app/controllers/stats_controller.rb#L4-L16

**Comment by jywarren** [comment]
@17sushmita would you be able to try the rails console on your database copy to see what's actually happening here?

**Comment by 17sushmita** [comment]
Hi @jywarren, yes I can look into this but my concern was should we completely delete such tags or hide them in some way so that data is not lost if some person was accidentally deleted. Or should we implement a mechanism to delete automatically such tags after 30 days or so. 
Just thinking of possible solutions. What do you think?

**Comment by jywarren** [comment]
Hmm. Well first, if the user has been banned, why are we still seeing the tags? Could it be a cache delay? Or something else?

I think we may be able to solve this with an adjusted query rather than deleting the tag records.

**Comment by jywarren** [comment]
Thanks!!

**Comment by 17sushmita** [comment]
Hi @ebarry, Can you confirm if this user is banned or not because I checked in the scrubbed DB and the user is not banned. If he was banned recently, then it may be possible scrubbed DB does not reflect those changes. Just need to confirm this.

**Comment by 17sushmita** [comment]
I think this is the person who added this tag - https://publiclab.org/profile/contentscribblers3 . He hasn't been banned.

**Comment by jywarren** [comment]
OK, so if the user is not banned, and is following the tag, do we need to do anything? 

https://publiclab.org/profile/contentscribblers3/ is /not/ banned.

https://publiclab.org/contributors/Which-are-the-best-content-and-article-writing-services-online <= why aren't we seeing this follower on this tag "people" tab?

**Comment by jywarren** [comment]
If you send me the query, @17sushmita i can run it on the live database to try to figure out why were aren't seeing the user, thanks!!

**Comment by jywarren** [comment]
According to this segment, if there are no contributors, we ALSO don't show followers:

https://github.com/publiclab/plots2/blob/f96f3ba275b84bf1c4229dcadc963c06de06c4d7/app/views/tag/_contributors.html.erb#L34-L68

Which we could fix. However, this is a really rare circumstance. Who would follow a tag if there is no content? It really only occurs in this situation with a spam tag whose content is deleted. 

Should we fix it or just leave it? Thanks, all!

**Comment by ebarry** [comment]
Whoops, missed the fact that there was a hanging question here at the end for @publiclab/community-reps . 

How can we remove spam tags from showing up on https://publiclab.org/stats/subscriptions? The goal is to honor the active moderation steps taken by the moderators to keep our site well-curated; it's hard to see work moderators have already done need _re-doing_ in a format that mods can't even fix. Currently a quick glance reveals the original report of https://publiclab.org/tag/Which-are-the-best-content-and-article-writing-services-online as well as some others, here is a non-exhaustive list: 

- https://publiclab.org/tag/Cosmetics-
- https://publiclab.org/tag/finance%7CGeneral%7CArts%20and%20Entertainment%7CBusiness%7CComputers%20and%20Technology%7CGaming%7CHome%20Based%20Business%7CInternet%20and%20Business%20Online%7CLegal%7CReal%20Estate%7CRelationships%7CTravel%20and%20Leisure%7CAutomotive%7CCancer%7CHealth%20and%20Fitness%7CHome%20Improvement%7CInvesting%7CNews%20and%20So
- https://publiclab.org/tag/TeethwhiteninginIslamabad
- https://publiclab.org/tag/sex

More broadly there's something our website does which i don't love, but also don't recommend fixing at this time, is that anyone can make up a URL that starts with publiclab.org/tag/foo and have our tag page template load. As long as we aren't linking to a tag page that we've already taken active moderation steps on  like is currently happening on /stats/subscriptions, it's ok. 

Thank you! Sorry again i missed the hanging question at the end of the last comment.

**Comment by jywarren** [comment]
Hi Liz, i believe the easiest step would be to ban the user who's following the spam tag. Then it will have no followers and won't be listed. 

The key here is that the page `/stats/subscriptions` is a listing of what tags have followers, so the action by a moderator to spam a note or wiki won't affect that listing. So it's not re-doing so much as that we provide moderation tools for nodes, but not for tags themselves. We do provide tools to moderate/ban individual users, but that wasn't done in this case; the user is still 
not banned. But yes, i think the easiest path is to ban the user:

> https://publiclab.org/profile/contentscribblers3/ 

The secondary question is, how do we make that process easy? The user is not listed on the tag page because we didn't expect this to happen -- that there are no posts but one follower. So we could adjust the listing of followers to expose the user, so it's easier for mods to find and ban them. I think that's pretty easy if that sounds good to @publiclab/community-reps?

We could consider additionally filtering /stats/subscriptions by whether they have content. But, it's a very big query already and that would add another join to the query and lengthen it, so I would advise against it. Does that make sense?

**Comment by jywarren** [comment]
I made a pull request for `So we could adjust the listing of followers to expose the user, so it's easier for mods to find and ban them.` at https://github.com/publiclab/plots2/pull/10520 - if folks are 👍 we can merge it!

**Comment by ebarry** [comment]
Great! Thank you! Visible just to mods, yes?

**Comment by jywarren** [comment]
No, this is for unbanned users, so it's visible to everyone. But it helps mods to identify followers of spam tags.
