### ISSUE TITLE
new question card formatting in https://publiclab.org/questions caused some issues

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#10043]
Uh oh - actually it looks like our question card formatting affecting https://publiclab.org/questions was affected by the changes in https://github.com/publiclab/plots2/issues/8731. I'm opening this just to try to resolve it:

Before:

![image](https://user-images.githubusercontent.com/24359/129810269-6521f5b5-f6fe-41af-90a5-64e769ab4d0e.png)

Now:

![image](https://user-images.githubusercontent.com/24359/129810456-9c0cf716-1c07-45c0-bb48-05e00755a862.png)

I think we need to fix the lazy loading on /questions, probably just by running this:

```js
$(function(){
  $("img").lazyload();
});
```

(see https://github.com/publiclab/plots2/pull/8043/files#diff-10d79f07bd4ae39a54ddd901d05832f6ea45f6ec427932edd966bed0b83e6714R20)

_Originally posted by @jywarren in https://github.com/publiclab/plots2/issues/8731#issuecomment-900682154_

**Comment by jywarren** [comment]
cc @Manasa2850 but I know you're busy now -- just whenever you are available!

**Comment by Tlazypanda** [comment]
Hey @jywarren  Just checked out this issue seems like it's not broken but maybe these questions don't have any images for them so it's showing this placeholder. For example - https://publiclab.org/questions?page=4 on navigating here the images take about 30 seconds but the ones with images load for example - https://publiclab.org/notes/iman/03-30-2021/why-the-color-of-infragram-picture-is-different-from-what-i-take-with-my-raspberry-pi-using-picamera-api

I tried locally too but wasn't able to reproduce :sweat_smile: 
![image](https://user-images.githubusercontent.com/33183263/131555305-ef4b72e6-1b8d-41ae-9ac0-ae8c796eb44f.png)

Not sure if this is what you meant by the issue though :p Maybe we can only show the images where they exist to not create confusion?

**Comment by ebarry** [comment]
Great idea @Tlazypanda ! I support this.

**Comment by jywarren** [comment]
Ah wait - so, i realize that we do need to be careful that the removal only affects /questions/ - as the way we manage missing images in /notes/ is distinct:

![image](https://user-images.githubusercontent.com/24359/133336657-ffa87ec9-0544-4d16-8588-9538531c66b9.png)

see i.e. https://publiclab.org/tag/helium

but that should be easy enough with a conditional!!!

**Comment by jywarren** [comment]
Wow, great catch here too @TildaDares. And I think i agree on the solution. Thanks!

**Comment by jywarren** [comment]
So if we could just switch back to displaying the question template that would seem to work, although please do confirm it ends up looking like the "before" image above. 

However if it doesn't, we could amend the conditional by using instead of `type == 'question'`, this function which helps determine if it's really a question:

https://github.com/publiclab/plots2/blob/9682cb895fae5fe2e2251eb6b87c2a01d74084f2/app/models/node.rb#L188-L190

**Comment by TildaDares** [comment]
Resolved in #10359
