### ISSUE TITLE
Markup Mistake

### ISSUE THREAD

**Issue by Vishal01-git** [publiclab/plots2#10231]
### In [Publiclab](https://publiclab.org/tag/education) I think there is mistake in markup because ,it shows in HTML language.

![isuue](https://user-images.githubusercontent.com/52890952/135570674-e3913f1e-268a-4d0c-bca3-4fa5e04858a8.png)

**Comment by AshishisLiquid** [comment]
Is it open so, i can work on it ?

**Comment by vishkrish200** [comment]
can i work on this?

**Comment by TildaDares** [comment]
Hi @AshishisLiquid, yes you can work on this 🚀.

**Comment by TildaDares** [comment]
Hi @vishkrish200, you can make a request for an FTO here #10153. Thanks!

**Comment by AshishisLiquid** [comment]
ok I'll just check and make pr when work done

**Comment by AshishisLiquid** [comment]
Just a query, where can i find this page code ? cause it seems full worked down in ruby

**Comment by TildaDares** [comment]
@AshishisLiquid You can find the code in https://github.com/publiclab/plots2/blob/a1b105fb6a50c939a9a303c1efb384ca7bcf389e/app/views/tag/show.html.erb#L116

You need to strip the tags from the string so that only normal text is displayed. You can use this method https://apidock.com/rails/ActionView/Helpers/SanitizeHelper/strip_tags to do that. I hope that's clear enough

**Comment by TildaDares** [comment]
Hi @AshishisLiquid, do you need any help with this?

**Comment by TildaDares** [comment]
This issue has been inactive for over a week so I'm reassigning it.

**Comment by Goodiec** [comment]
@TildaDares, can I work on this?
