### ISSUE TITLE
[DISCUSSION] Adding in a "Why did you sign up?" survey

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#10437]
Hi there! Thanks for reading. 

# The idea

The idea is to gather more information about why people first create a account on publiclab.org, such as what they intend to do, what they are looking for, what their interests are, etc. 

# Approaches and options

* Add a survey to the confirmation screen on account creation
* Add a survey to the email sent to confirm your email
* other!

# For discussion

It would be great to hear what moments in our UX flow might be good options for asking these sorts of questions. 

It would also be great to see examples of other websites doing this in great ways. 

Thanks in advance for sharing your thoughts!

**Comment by ebarry** [comment]
Dear @jywarren, would you be able to point me at where it's documented or write out the workflow for adding a survey to the Welcome message shown on the Dashboard as well as the workflow to adding a survey link to the Welcome Email? Thank you for any pointers here.

**Comment by jywarren** [comment]
Hi @ebarry - yes, the relevant feature for email is:

- `dashboard-feature` - https://publiclab.org/features/22426/edit

The [old dashboard message](https://github.com/publiclab/plots2/blob/4d662445527e5f0a9c070e684ad9a874ea99d955/app/views/dashboard/dashboard.html.erb#L1-L24) hadn't been made into a feature.

The new dashboard has a message that's hard-coded, which means it can be translated, and it has been integrated with the translation system:

https://github.com/publiclab/plots2/blob/4d662445527e5f0a9c070e684ad9a874ea99d955/app/views/dashboard_v2/_alerts.html.erb#L4-L9

If we'd like to change it, we would need to change the english entry on this line, and then look at how to trigger a new set of translations across other languages:

https://github.com/publiclab/plots2/blob/4d662445527e5f0a9c070e684ad9a874ea99d955/config/locales/en.yml#L403

We could change the translation string key so that it falls back to the new english text, or we could only change it in English, for now, and then perhaps work with our translation communities to move that into translated strings as well. So there's a little bit of workflow that'd have to be managed.

**Comment by ebarry** [comment]
perfect thanks! Closing.
