### ISSUE TITLE
Topic-specific "new comment" links on dashboard do not display topic-specific comments

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#10486]
## Please describe the desired behavior
I'm not sure if this is a new feature request that we just haven't gotten to yet, or a bug in what we thought we already had working, but i can report that i was surprised at the behavior I just experienced. 

## Description of behavior
I was on my https://publiclab.org/dashboard when i noticed that a small topic i subscribe to `maine` showed up high on the feed implying recent activity. I recognized all the photos and so I assumed there was not a new research note. I saw the link to *new comment* and clicked it. Here is where i was surprised. The page for all comments loaded: https://publiclab.org/comments/ and because the tags on the note where the comments were posted were not shown on that page, i was unable to discern which new comment had happened in the `maine` topic. 

## Documentation of behavior
![comments](https://user-images.githubusercontent.com/161439/140775249-e1f444d5-7539-4526-832d-b94cc1af818b.gif)

## What i expected to see

I expected to arrive at a refined URL such as https://publiclab.org/comments/?tag=maine or something so that i'm only seeing comments in the topic area that i clicked on. It would be great to have a link on a page like that to easily navigate to "All Comments". But it's hard to begin on a dump of all comments and then find the specific topic. 

Thank you for reading!

**Comment by jywarren** [comment]
Hi, yes, i think this is because we have never created a per-topic listing of comments. So this is a feature request - is that right? - to create a new view of, for example, `/tag/comments/TAGNAME` ? Thanks!

**Comment by jywarren** [comment]
Alternatives would be:

- to have that link auto-scroll you (permalink you) down to the comment it corresponds to, on /comments. 
- to have the link permalink you to the comment itself? Not sure about this one. But maybe.

**Comment by KarishmaVanwari** [comment]
Is this issue open? I can work on this. @jywarren @ebarry

**Comment by TildaDares** [comment]
> * to have that link auto-scroll you (permalink you) down to the comment it corresponds to, on /comments.

I prefer this option because it involves less change. All we need to change is where the `new comment` links to
https://github.com/publiclab/plots2/blob/883e081e0bbbd7cd25332798a4b27404f67f1035/app/views/dashboard_v2/_topicCard.html.erb#L69

But I still think there should be a per-topic listing of comments like we have for tags. It's great for searching for comments on a specific topic.

**Comment by ebarry** [comment]
Great! I had a chance to talk to Jeanette (Research Manager) about this also. 

Creating a "per-topic listing of comments" seems like part of the transition to forum-like organization. Similar to how we've transitioned https://publiclab.org/tags and https://publiclab.org/dashboard. 

This might have opportunities / implications for adding a comments tab to Tag Pages.

We might consider keeping the firehose view of comments somewhere, similar to how /research gives access to a firehose view. 

How does this sound?

**Comment by jywarren** [comment]
We do have breakpoints for the tabs so that many can fit. 

![image](https://user-images.githubusercontent.com/24359/142033204-9097cc28-f0c9-4b1d-a8f9-4dd2aa81baa1.png)

Here this breakpoint is actually failing, but it's not too bad a failure, just wrapping:

![image](https://user-images.githubusercontent.com/24359/142033455-ca763604-5d87-4271-9087-e052c7e20c9e.png)


![image](https://user-images.githubusercontent.com/24359/142033488-3885f465-5fcd-4c46-9175-b1651d98c547.png)

It still adds visual complexity so it's a judgement call, but if we carefully tweak the breakpoints, I think it's doable.

We still need to think about the design of the page. The current comments page doesn't really use a full width column. Should it, or should our new template? Should the new page at `/tag/comments/TAGNAME` preserve the top of the page with the explanatory card, like the other tabs? Probably. So then it'd look /something/ roughly like this, if it were all on one page:

![image](https://user-images.githubusercontent.com/24359/142034614-a94ae01d-9993-4f9d-a292-ca670568ee61.png)

How does that look as a rough plan? Anything else we need to think through?

**Comment by ebarry** [comment]
Looks amazing and really ideal to me. I've also posted to the staff #web channel we are in Jeff so there might be some input coming from there too

**Comment by ebarry** [comment]
Everyone really likes it! This is a "go" 😃

**Comment by jywarren** [comment]
OK, so to plan out this project we have a few different pieces:

* [ ] develop a new route at `/tag/comments/TAGNAME` and a corresponding entry in `tag_controller.rb` that collects `@comments` within a topic (i.e. on nodes tagged with `TAGNAME`) 
* [ ] write a functional test for the above
* [ ] publish to stable and test
* [ ] add an extra tabs after https://github.com/publiclab/plots2/blob/b8f3e4c0ec44c5511c161af28cb52329c32e0d71/app/views/tag/show/_nav_tabs.html.erb#L53-L57 with a comment icon, no count for now, leading to `/tag/comments/TAGNAME`
* [ ] see if we need to do the same for https://github.com/publiclab/plots2/blob/b8f3e4c0ec44c5511c161af28cb52329c32e0d71/app/views/tag/show/_nav_tabs.html.erb#L82-L86

Do we want to put a count of comments on the tab like the other tabs? It's computationally expensive to do so, but if you feel it's important we can do it.

**Comment by jywarren** [comment]
OK so, heard back from staff -- no comment count - that simplifies things a bit!

**Comment by jywarren** [comment]
For list item 1, this line is a great hint - it shows how you can collect all comments for a tag:

https://github.com/publiclab/plots2/blob/d2a89b0a22289341431faa09e8a8f355e44a0cef/app/models/tag.rb#L249

I believe it is 3 sequential but not nested SQL queries, so not too inefficient. 

- One to fetch all `tids` for a tagname (in case there are duplicate tagnames, which really shouldn't happen anyways, but just in case)
- a second to fetch all `nids` for those `tids` using the `NodeTag` table
- a third to fetch all comments by `nid`

I think the method in tags_controller.rb would then just be:

```ruby
def comments
  @pagy, @comments = pagy(Comment.where(nid: nids).order('timestamp DESC'), items: 24)
end
```

Then we can display them in a simple table, or however you think best - maybe we can use this template for starters, to not reinvent the wheel?

https://github.com/publiclab/plots2/blob/main/app/views/comments/_comments.html.erb

If we want to refine it, we can do it in a follow-up task.

**Comment by jywarren** [comment]
I believe this is completed thanks to @TildaDares -- 

![image](https://user-images.githubusercontent.com/24359/146026960-62a64ea6-fd25-4eb3-acf8-831ebac2b812.png)

We'll test it in stable and it should go live in the next few days.

**Comment by jywarren** [comment]
The only thing left perhaps is that we don't display the comments page under the standard tag page header as shown above. Once you click "Comments" we just display a page of comments. I'd like to try rendering the comments below a tag page header as above, and will open a new issue for that!

**Comment by jywarren** [comment]
Great, added it here! https://github.com/publiclab/plots2/issues/10570
