### ISSUE TITLE
Controlling projects shown on the front page by 'project:featured'

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#10549]
## Area of interest

The Community Projects section on the front page: 
![community-projects](https://user-images.githubusercontent.com/161439/144264204-8aaed6d4-7446-4610-90ce-929295bd5564.gif)

## Current understanding of Feature 16602

I think that the HTML in https://publiclab.org/features/16602/ drives the display of Community Projects, is this correct? 

```
<div class="col-12" style="margin-top:40px;">
  <h2 class="text-center">Community Projects</h2>
</div>

<style>
.projects .project-image img {
  max-width: 100%;
}
/* These should be present in /app/views/home/home.html.erb so can be removed from here soon - Nov 25 2019 */
.projects {
    width: 100vw !important;
    margin: 0 calc((100% / 2) - 50vw) !important;
    position: relative !important;
    padding: 40px 15px !important;
}
```
This code references a view of projects, does this mean that these three projects are hard coded to appear on the front page? 

## the power tag "project:featured"

A little clicking around revealed that projects featured on the front page had the tag `project:featured`. 
I removed that tag from https://publiclab.org/wiki/the-sand-sentinel-program and added it to https://publiclab.org/wiki/the-mountains-and-mines-monitoring-project. However, this did not change which projects were displayed on the front page. 

## Request

I would like to explore if the `project:featured` tag could be used to drive which projects appear on the front page. The programmatic trigger for this request is that now that we have ongoing Fellowship programs, our most active projects will be more frequently refreshing, and it would be great if site Admins could control what projects are featured on the front page by either feature 16602 or by this powertag or both! What do Code Coordinators think?

**Comment by anirudhprabhakaran3** [comment]
Hello!

When I am loading the home page, I can see the following three projects:
Mountains and Mines monitoring project
Urban Greening in Nottingham 
Unearthing Providence

Searching for the powertag `project:featured`, I can see 4 different wikis, which include the top 3 and one more - Bourj Al Shamali Refugee Camp.

The code is taking three of the four projects - however, it is picking them **randomly**. 
https://github.com/publiclab/plots2/blob/a6a96c315481d3588cf0f5a04a1d1314790160d4/app/controllers/home_controller.rb#L17-L18

Maybe because of this random sampling, the projects displayed on your dashboard were different. I think instead of sampling it randomly, we should pick the projects that got the tag most recently. (Are we tracking the time when tags are being added?)

**Comment by jywarren** [comment]
Hi @ebarry - the `project:featured` tag does indeed dynamically populate the front page posts; the feature only controls the styling a bit. Thanks @anirudhprabhakaran3 for checking too!

The reason it didn't work immediately is because the front page is heavily cached, so time must pass before you see the effects. Probably 24 hours? Or at least an hour? I can check if you like. Closing this now and relaying to your Slack message, but feel free to re-open if you'd like any follow-up.
