### ISSUE TITLE
Weekly Community Check-In #130 - Web 3 

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#10723]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Web 3 

There has been a lot of talk about Web 3 in the tech community in the last few months. This week lets discuss all about it! Are you working on anything on web 3, what are you building? what stacks are you using, any new stacks or technologies you are learning in preparation for web 3?  any thoughts,  or opinions on Web 3. Tell us all about it and lets learn from each other :slightly_smiling_face: 

### Summer of Code preparations
We are planning to participate in Outreachy and GSoC programs this coming summer. We have opened a call for mentors [here](https://github.com/publiclab/plots2/issues/10728) 

### Thank you note

 Many thanks to the contributors of the past two weeks 🥇🥇🥇 @kirti1211c @lokcito @TildaDares @sakshi-2412 @Suprajashetty @anirudhprabhakaran3 @NARUDESIGNS @Georjane @mittal-parth  @jywarren  @Tlazypanda @anythingoes @HeZean @Zach-Clay🥇🥇🥇

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by RaviAnand111** [comment]
I got really interesting about Web3 and tried to explore it watched some videos on youtube, organised some webinars for my college club so everyone can learn about the Web3. I think I have got the basics of what web3 is and how it works, I know react.js so I am thinking of creating some dapps. So to do that I am trying to learn about wallets and how to connect them to your website and how to host your website on blockchain. I really like it. 

At last I would like to thank my mentors here at PublicLab who taught me alot and would like to know what they are learning nowadays.
@NARUDESIGNS @TildaDares @jywarren

**Comment by NARUDESIGNS** [comment]
I spoke to @Tlazypanda about web3 because I'm also interested in learning about it. She was kind to point me in the right direction but I'm yet to fully begin learning about it. Other than that, I've been focusing more on learning Data structures and algorithms as well as studying interview/resume tips.

**Comment by Ash-KODES** [comment]
I just attended a WEB3 bootcamp at girlscript foundation!

**Comment by anirudhprabhakaran3** [comment]
Hello! I haven't had much time to try out the Web3 stuff - to be completely honest, I haven't even wrapped my head around the very concept of it 😅 I will have to look into it.

If there are any resources that you all recommend for a complete beginner, please drop them below! Thank you!

**Comment by mittal-parth** [comment]
Hi! I would agree with @anirudhprabhakaran3. Haven't explored enough about Web3 yet. But definitely looking to do it in the future!

**Comment by Georjane** [comment]
Wow 💯  very interesting concept @cesswairimu 👍🏽 

I don't know much about web 3. 😞  I have heard a couple of people talk about it and all that I could grasp out of it was that it's a big deal and it is the future or the present I would say 😄 
Now that you mentioned it, I would definitely do some research on it. Thank you! 🙏🏽

**Comment by jywarren** [comment]
Hi all - i also haven't yet gotten familiar with web3 besides seeing it talked about a lot on Twitter 😄 

I guess I've been hesitant about blockchain tech due to the environmental costs which we know will impact less privileged folks as a result. But I know there are some "very low footprint" options there. But maybe my question is first, what problem solving abilities does blockchain bring to, for example, software we need at Public Lab? I just dont know the applications we're talking about because it's pretty abstract. Can we store files in https://js.ipfs.io/ like MapKnitter uploads? Can we generate MapKnitter map exports somehow? would we be able to run database-backed apps without paying for database storage using https://thegraph.com/en/ or something? 

I guess I have to do some research! Thanks Cess for the check-in and the topic!!!! 🎉 ❤️

**Comment by cesswairimu** [comment]
Thanks all, would anyone like to open next week's check-in?

**Comment by RaviAnand111** [comment]
Hey @cesswairimu, I would like to open next week's check-in.

**Comment by cesswairimu** [comment]
awesome :tada: thanks @RaviAnand111. You could open it anytime on monday and feel free to ping me incase of anything. Thanks!

**Comment by cesswairimu** [comment]
Hi @RaviAnand111, please do let me know if you need any help with the check-in. Thanks again :)
