### ISSUE TITLE
Punctuation at end of URL in comments incorporated into link, breaking the link

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#10944]
Posting for BHamster: 

### Please describe the problem

> What happened just before the problem occurred?

When making a comment on a post, if people paste a whole URL at the end of a sentence and put a period at the end of the URL, the hyperlink that automatically generates in the published comment incorporates the period and then becomes a bad link. e.g., [this recent comment](https://publiclab.org/questions/bhamster/02-10-2022/is-there-federal-level-recourse-that-communities-can-take-when-mine-reclamation-is-not-being-done-properly#c29860).

> What did you expect to see that you didn't?
I would expect that our editor is smart enough not to add the period or comma to the end of a link. 
Or perhaps this expectation is too high, because it is actually quite difficult to achieve this? Perhaps corporate social media platforms have spent a lot of money to stop this from happening? 

### Please show us where to look

https://publiclab.org/questions/bhamster/02-10-2022/is-there-federal-level-recourse-that-communities-can-take-when-mine-reclamation-is-not-being-done-properly#c29860

Thank you!

**Comment by jywarren** [comment]
Thank you! I think we should be able to address this by tweaking the markdown interpreter. The comment body is rendered here:

https://github.com/publiclab/plots2/blob/7c3af440498624f5dca5ce9ee07f04bc3ad90e73/app/views/notes/_comment.html.erb#L146-L149

But it's parsed from markdown here:

https://github.com/publiclab/plots2/blob/ecae3b9f48825fadab8d0be0ddf413d153e97fae/app/models/comment.rb#L505-L524

Yes, so the RDiscount markdown parser we use does the same thing:

```ruby
RDiscount.new("the BLM Surface Management Handbook: https://www.blm.gov/sites/blm.gov/files/H-3809-1.pdf.",:autolink).to_html
 => "<p>the BLM Surface Management Handbook: <a href=\"https://www.blm.gov/sites/blm.gov/files/H-3809-1.pdf.\">https://www.blm.gov/sites/blm.gov/files/H-3809-1.pdf.</a></p>\n" 
```

Other systems [are affected](https://www.reddit.com/r/redesign/comments/8jthug/link_doesnt_look_right_when_trying_to_use_a_link/) but [GFM](https://github.github.com/gfm/#autolinks-extension-) says `Trailing punctuation (specifically, ?, !, ., ,, :, *, _, and ~) will not be considered part of the autolink, though they may be included in the interior of the link:`

[Commonmark](https://spec.commonmark.org/0.28/#autolinks) doesn't address the issue. Other platforms have had to [make this fix too](https://github.com/ckan/ckan/pull/1990/files) and even in [earlier versions of Ruby](https://rails.lighthouseapp.com/projects/8994/tickets/2504-auto_link-should-ignore-multiple-trailing-punctuation-marks). 

Also noting this is only affecting comments, not wikis; see the link to the Gitter chatroom at https://publiclab.org/wiki/gsoc-ideas#Get+in+touch where the URL is correctly parsed. 

I think this is because we don't use RDiscount's `auto_link` for nodes; we use Ruby's (fixed) `auto_link`:

https://github.com/publiclab/plots2/blob/7c3af440498624f5dca5ce9ee07f04bc3ad90e73/app/views/notes/show.html.erb#L76

Let's try the same for comments. That means we remove the `:autolink` on [this line](https://github.com/publiclab/plots2/blob/ecae3b9f48825fadab8d0be0ddf413d153e97fae/app/models/comment.rb#L508) and we wrap the following line in `auto_link`:

https://github.com/publiclab/plots2/blob/7c3af440498624f5dca5ce9ee07f04bc3ad90e73/app/views/notes/_comment.html.erb#L148

So it would look like this:

`raw auto_link(insert_extras(filtered_comment_body(comment_body)), :sanitize => false)`

This could be a good FTO, but we have to watch out for whether it breaks any tests, as it's a pretty obscure change!


****

ALSO: Noting that this could come up again potentially if the React comment renderer is different? @noi5e do you think this might be an issue? 

****

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

**Comment by PeculiarE** [comment]
> ALSO: Noting that this could come up again potentially if the React comment renderer is different? @noi5e do you think this might be an issue?

So I decided to implement the fix on my local branch and visually check out the effects on GitPod. Looks like the React comment renderer is being affected. Links don't appear as hyperlinks once the react flag is set to true. Everything is rendered as normal text. I've attached a short demo.

https://user-images.githubusercontent.com/75625011/161832217-c497dd0b-ca3b-4a42-bcb5-8ae3d65f7edc.mp4

Wasn't able to verify if the change was breaking any test on my local. I'm using sqlite3 for my db and so, not all my tests pass on a normal day.

**Comment by jywarren** [comment]
Excellent digging, @PeculiarE! And thorough testing, thank you!

Hmm, ok, so I think what's happening is that we removed autolink from early in the process, and added it AFTER the react and non-react processes diverge. So possibly it is now working in non-react, but we have to find the corresponding spot where the react version needs an autolink step added. 

We may need some help from @noi5e to track where that is. I can see comment body templates in React are here: https://github.com/publiclab/plots2/blob/main/app/javascript/components/CommentDisplay.js

Could the spot to re-introduce autolink be here? 

https://github.com/publiclab/plots2/blob/5ec93e0bb8cbd29e1396cd840f29bc09e550afd4/app/helpers/comment_helper.rb#L17

**Comment by noi5e** [comment]
Excellent work @PeculiarE! Yes, feel free to add this to the open FTO you mentioned, or even create a new one.

**Comment by PeculiarE** [comment]
Thank you ❤️  @noi5e! I've created a new FTO issue for this..

**Comment by jywarren** [comment]
Yes sounds good!! Thank you!
