### ISSUE TITLE
Bug - part of the page ../wiki/welcome is in English and another in Spanish 🙂 

### ISSUE THREAD

**Issue by illyShelly** [publiclab/plots2#10993]
Hi 👋 

### Please describe the problem (or idea)
When I visit this site on PublicLab.org [wiki welcome](https://publiclab.org/wiki/welcome) the alert button  and some part of page are in different language - Spanish instead of English. I tried to change language and refresh page - but no change.

I enclosed the printscreen just small part with the alert.

> What did you expect to see that you didn't?
One chosen language - EN.

### Please show us where to look
https://publiclab.org/wiki/welcome

### What's your PublicLab.org username?
- illy

### Browser, version, and operating system
Safari, Mac OS Monterey 12.2.1

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

<img width="830" alt="Screenshot 2022-04-08 at 16 44 18" src="https://user-images.githubusercontent.com/26350915/162466616-38a72eef-a195-476b-83e0-5581c7dff50e.png">

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by mittal-parth** [comment]
Hi @illyShelly!
So if you notice the page you have linked https://publiclab.org/wiki/welcome, has a `/wiki` in the URL. All wikis come under user generated content on PublicLab (More info on the Data Model can be found [here](https://github.com/publiclab/plots2/blob/main/doc/DATA_MODEL.md). This means that the language changes are rather chosen by the author(s) of the page and is not as such a problem with the code. 
Also, half the page is English and the other half is in Spanish. If you translate the Spanish text into English, you would realize that its the exact same content as in English mentioned above! 😄 
So yes, the page can be confusing but this could only be fixed by the authors of the page!

**Comment by illyShelly** [comment]
@mittal-parth 😄 Got it. Ok, I thought it makes copy with somehow mixed-up translation files etc. 😆
