### ISSUE TITLE
Overflow of video in post

### ISSUE THREAD

**Issue by on2onyekachi** [publiclab/plots2#11073]
Overflow of video across the screen size. which makes it difficult to view the content of the video on a mobile device. 

https://user-images.githubusercontent.com/66228222/163877540-e85b6a82-7259-434e-873c-d357cd743b6b.mov

<img width="1440" alt="Screenshot 2022-04-18 at 21 21 01" src="https://user-images.githubusercontent.com/66228222/163877832-73e80f2f-ae19-4c00-a7e0-ab8b9608ced4.png">

The video should have a defined width and a responsive width size. 

This page location: https://publiclab.org/notes/junior_walk1337/01-30-2022/water-monitoring-101-with-vernon-haltom

**Comment by Abhijeet-kadance** [comment]
Try adding the container

width:100%;

Inside which the player is added

**Comment by cesswairimu** [comment]
You are right @Abhijeet-kadance, when adding the youtube iframe we have a dialog box that recommends the use of the 100% width and gives recommedations for smaller screens too 
![Peek 2022-09-12 11-50](https://user-images.githubusercontent.com/17081074/189614502-43f0a7b4-cfbc-4650-9cd7-80ef22eb85a6.gif)

The above note has this set `<iframe width="1280" height="720" src="https://www.youtube.com/embed/FKqA5C9ZBhQ" frameborder="0" allowfullscreen=""></iframe>` hence the overflow. It seems this was a user preference rather than a system bug. Closing this, Thanks all.
