### ISSUE TITLE
Inline grids redundantly display questions (on pages that already have a questions grid)

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#1132]
I have been working on the [photo-monitoring](https://publiclab.org/wiki/photo-monitoring) page and noticed that the /updates section which I thought should just include Research Notes about the topic also includes questions. Is there anyway to parse these out since we already have Questions in a different space? 

On another note, I didn't see the same thing happening when I looked the [Project Page Sara Sage](https://publiclab.org/wiki/mapping-the-waste-stream-of-southern-california) and I have been working on. Looks like that question tag didn't move into the /updates (Research Notes)

Anyone have ideas?

### Relevant URLs

https://publiclab.org/wiki/photo-monitoring
https://publiclab.org/wiki/mapping-the-waste-stream-of-southern-california

**Comment by steviepubliclab** [comment]
Think I figured it out, if we tag questions with normal tags, they show up as Research Notes in the updates, but if they have the "question:" before, they only show up in the /questions tables. Is there anyway to make sure all question tags get the "question:" first so we don't overwhelm the tables as we start adding them to other wiki pages? 

here's another one new for reference:
- https://publiclab.org/wiki/stormwater

**Comment by jywarren** [comment]
Some notes are tagged with both `stormwater` and `question:stormwater`, for example -- which would make them appear in both. We currently have the `Ask a question about X` buttons set up this way. We could remove it but I'd worry that the questions wouldn't show up in tag listings, for example. 

We don't currently have a way to exclude a tag from a listing, and the main reason is that the syntax would be tough -- what would you write, do you think? Something like:

`[notes:stormwater|not:question:stormwater]` <= to show `stormwater` notes but not `question:stormwater` posts? 

I can't think of a relatively simple way around this, unless we wanted the `[notes:stormwater]` inline grid to simply ignore anything that has a `question:___` tag... and that itself might be a bit complex to implement. 

Sorry, there doesn't seem to be an easy answer for this!

**Comment by jywarren** [comment]
Partial solution here! https://github.com/publiclab/plots2/issues/1340

**Comment by jywarren** [comment]
That's almost complete -- resolving now!

**Comment by ebarry** [comment]
Hi @warren, could you explain what the partial solution to this is? 
@steviepubliclab and I were just reviewing https://publiclab.org/wiki/stormwater and see that same problem happening, that questions appear in the Updates grid. 

We feel that the [notes:xxxxxxxxxx] inline grid should simply ignore anything that has a question:___ tag

**Comment by jywarren** [comment]
I wanted to bring this up again - i think it's possible that people will get really confused if `[notes:water]` doesn't show notes that are tagged `water` if they ALSO are tagged `question:water`.

But @steviepubliclab asked again about whether `[notes:water]` could exclude notes tagged `question:water` regardless of whether they also have the tag `water` (i.e. my suggestion in my [last comment](https://github.com/publiclab/plots2/issues/1132#issuecomment-416244102)) -- and I think it's possible to make this a universal behavior, but want to consider adding a short explanatory text somewhere so that people understand that questions are being excluded. 

If that's interesting, we could brainstorm how to display this message -- it'll be especially important if people who used a "Add yours to here" type button prompts later choose to classify their post as a question during or after the posting process, and then get confused as to why their post didn't actually get added to that listing. Could be a simple text message like `Displaying notes only, no questions` or could link to `see  _related questions_ here` possibly. 

Happy to take the next step here with some +1!
