### ISSUE TITLE
Define Gemfile.lock policy

### ISSUE THREAD

**Issue by icarito** [publiclab/plots2#1175]
We should decide what to do about the automatically generated Gemfile.lock file.

This file is created by bundler by resolving dependencies including the local Ruby versions.

While this is great for production, it can become an issue for developers that don't have the exact Ruby version.

The proposed idea is having .gitignore with Gemfile.lock and tweaking Gemfile.lock manually to use Semantic Versioning to relax version locking.

### Relevant URLs

http://bundler.io/v1.3/man/bundle-install.1.html
http://stackoverflow.com/questions/9208240/gemfile-lock-use-in-rails

**Comment by jywarren** [comment]
Related to #1168 which removes ruby version specification from Gemfile.lock

**Comment by ananyo2012** [comment]
@icarito @jywarren I think we should remove the Gemfile.lock from .gitignore since we won't be able to update it in case we add a new gem. Running `bundle install` won't update the Gemfile for breaking changes and changes in patch version can be safely accepted. If we wan't to be extra careful we can add the pessimistic operator `~>` for each gem. That won't update the gem major and minor version even for a manual `bundle update`

**Comment by jywarren** [comment]
Hi, Ananyo - i think the idea is that we can manually add it if need be; is
that right, @icarito? The problem is that people keep updating it with, for
example, their Ruby version.

@icarito - interested in your input on this too, thank you!

**Comment by ananyo2012** [comment]
@icarito @jywarren Well I guess you need to remove the file from repo as well to start ignoring changes. As you can see in #1193 the Gemfile.lock got updated as I added the gem. Indeed actually we need the Gemfile.lock to be version control so that on addition of a gem it gets updated. So keeping it in .gitignore seems irrelevant. To solve the issue with the ruby version just remove the `ruby 2.1.2` line from Gemfile and the the ruby version from Gemfile.lock and bundler will no longer add a ruby version to Gemfile.lock from the next time. I think we don't need a specific ruby version to run the app so I guess we can safely remove it.

**Comment by jywarren** [comment]
> To solve the issue with the ruby version just remove the ruby 2.1.2 line from Gemfile and the the ruby version from Gemfile.lock and bundler will no longer add a ruby version to Gemfile.lock from the next time.

Hmm, ok. @icarito, does this sound good?

**Comment by ananyo2012** [comment]
See PR #1324 regarding this.

**Comment by icarito** [comment]
If this solution works for new developers, it shouldn't conflict with production.

**Comment by ananyo2012** [comment]
@icarito Yes this should work pretty well. And also we don't need the application to be version specific.
