### ISSUE TITLE
Enable Google Analytics to track what is commonly searched for in our site 

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1184]
I'm looking to use what Google Analytics offers in their "Content Site Search Overview" dashboard in terms of visualizing what people search for within our site using https://publiclab.org/search, and would like to know what to add to our site to enable this because right now ours is blank: 

https://analytics.google.com/analytics/web/#report/content-site-search-overview/

![screen shot 2017-01-12 at 3 48 39 pm](https://cloud.githubusercontent.com/assets/161439/21907701/9e92166e-d8de-11e6-87de-861af6f9afb6.png)

**Comment by Pk13055** [comment]
@ebarry I would like to pick this up. Can you link relevant parts of the codebase, and possibly give me some pointers on how to proceed?

**Comment by jywarren** [comment]
Liz and pratik, i believe this is already happening. Pratik, would you be
interested in choosing an issue marked "help wanted"? Thanks!

On Jan 16, 2017 9:05 AM, "Pratik Kamble" <notifications@github.com> wrote:

@ebarry <https://github.com/ebarry> I would like to pick this up. Can you
link relevant parts of the codebase, and possibly give me some pointers on
how to proceed?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/issues/1184#issuecomment-272869516>,
or mute the thread

**Comment by jywarren** [comment]
@ebarry - i'm guessing we have to set up some kind of extra configuration on GA to get its "site search" analytics running. But it should already be organically recording traffic flow through our existing search interface, since it maps how people get places. Would you like to look into this with me at some point over screen sharing?

**Comment by jywarren** [comment]
Found this guidance: https://support.google.com/analytics/answer/1012264?hl=en

but our searching may not be compatible as they're looking for a query like `/search?q=` -- ours is JavaScript based and goes to, for example, https://publiclab.org/api/typeahead/all?srchString=coqui

But i added `srchString` and we'll see if it registers!

**Comment by jywarren** [comment]
For searches like https://publiclab.org/search/coqui i'm not sure how to do it although we may be able to add a "virtual" thingy to the results page like: 

`analytics.js: ga('send', 'pageview', '/search/?q=keyword');`

according to the docs i linked to.

**Comment by ebarry** [comment]
If we disable Typeahead so that our search string is not, for example, https://publiclab.org/api/typeahead/all?srchString=coqui, will we be able to use Google Analytics more easily to track what is commonly searched for in our site?

**Comment by jywarren** [comment]
Just tried this via JS and it didn't seem to register anything on live Google Analytics:

```
ga('send', 'pageview', '/search/?q=keyword');
undefined
ga('send', 'pageview', '/search/?q=LIZ');
undefined
ga('send', 'pageview', '/search/?q=keyword');
undefined
```

![image](https://user-images.githubusercontent.com/24359/58037988-bf385c80-7afc-11e9-9082-0630c534364a.png)

**Comment by jywarren** [comment]
OK, i was able to get it to work with this: 

`tracker = ga.getAll()[0];tracker.send("pageview", "search/JEFF", "Test GA");` using:

https://developers.google.com/analytics/devguides/collection/analyticsjs/accessing-trackers

https://stackoverflow.com/questions/15744042/events-not-being-tracked-in-new-google-analytics-analytics-js-setup#40761709
