### ISSUE TITLE
Grids not displaying

### ISSUE THREAD

**Issue by mathewlippincott** [publiclab/plots2#1248]
Activities, Questions, and other grids don't appear to be displaying:
Two examples, MiniVol and Spectrometry:
https://publiclab.org/wiki/spectrometry
https://publiclab.org/wiki/minivol

![screen shot 2017-02-07 at 12 39 22 pm](https://cloud.githubusercontent.com/assets/1203280/22710549/977ac548-ed32-11e6-9081-7d422936b8a2.png)
![screen shot 2017-02-07 at 12 39 13 pm](https://cloud.githubusercontent.com/assets/1203280/22710548/9778ee12-ed32-11e6-802f-4c65afa7cef6.png)

**Comment by jywarren** [comment]
Thks for the thorough report, v helpful.

Should be related to this line and similar ones:

https://github.com/publiclab/plots2/blob/master/app/models/concerns/node_shared.rb#L60

On Feb 7, 2017 3:41 PM, "mathew lippincott" <notifications@github.com>
wrote:

Activities, Questions, and other grids don't appear to be displaying:
Two examples, MiniVol and Spectrometry:
https://publiclab.org/wiki/spectrometry
https://publiclab.org/wiki/minivol

[image: screen shot 2017-02-07 at 12 39 22 pm]
<https://cloud.githubusercontent.com/assets/1203280/22710549/977ac548-ed32-11e6-9081-7d422936b8a2.png>
[image: screen shot 2017-02-07 at 12 39 13 pm]
<https://cloud.githubusercontent.com/assets/1203280/22710548/9778ee12-ed32-11e6-802f-4c65afa7cef6.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/issues/1248>, or mute the thread

**Comment by jywarren** [comment]
Test to reproduce added in #1248, once confirmed I'll file a fix.
