### ISSUE TITLE
Posting a new question - funniness with editors

### ISSUE THREAD

**Issue by pdhixenbaugh** [publiclab/plots2#1328]
### Steps to reproduce

0. While logged into public lab (e.g. from dashboard)
1. Use the "Share Your Work" button to ask a question
2. Type the question (notice that it's in the legacy editor) using markdown features such as bullet points
3. (Notice: the powertag "question:question" is pre-populated)

### What I expect to happen:
- Question is posted in the formatting I expect

### What actually happens
- Question is entirely italicized, and bullet points are all on one line, without bullets.
- Clicking on the "edit" button takes you to the new editor
- Fixing the formatting in the new editor doesn't seem to help. (In fact, bulleted list creator makes the bulleted list at the top of the text box, regardless of where the cursor is placed).

Let me know if this is a useful issue-report

### Relevant URLs

https://publiclab.org/questions/pdhixenbaugh/03-10-2017/testing-please-ignore
https://publiclab.org/questions/pdhixenbaugh/03-09-2017/how-to-use-alkaline-batteries-with-the-riffle

### PublicLab.org username
pdhixenbaugh

### Browser, version, and operating system
Firefox 51.0.1 (32-bit), Windows 10

**Comment by ryzokuken** [comment]
@jywarren Any idea why this might be happening?

**Comment by jywarren** [comment]
Hi, I looked through this and I believe strict Markdown needs a space between each `*` and the item following it, so:

```
* one
* two
* three
```

Not all Markdown is equal, but we use the CommonMark spec: http://commonmark.org/

The rich editor does produce this, although it uses (allowable) hyphens: `-` instead of asterisks.

I'm going to close this, and I think the rich Question form (which is an issue, can't recall the #) will make this more clear too. 

Thank you!
