### ISSUE TITLE
Publishing a new wiki page after getting a validation error fails

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1333]
### What happened just before the problem occurred

I went to a new page, like https://publiclab.org/wiki/newpage

Then I entered info, but left the body blank, and pressed Publish. I got an error and a URL of:

https://publiclab.org/wiki/create?id=newpage

Then, I added text in the body, and hit Publish again, but I got a 404 error on this URL:

https://publiclab.org/wiki/update/14008

This seems to suggest it'd created a node id already. But the page https://publiclab.org/wiki/newpage still didn't exist.

## Solution

First, we need to capture this error with a test -- most likely an integration test, since it spans multiple requests. So it could be similar to this test suite for notes:

https://github.com/publiclab/plots2/blob/master/test/integration/node_update_test.rb

Perhaps called `wiki_creation_test.rb`.

Once we properly identify the bug through a good test, we can fix it!

**Comment by amiedes** [comment]
Hello @jywarren!

I was able to reproduce this issue on my machine and I'd like to give it a try. I don't have yet experience with the plots2 project but I do know some Rails and testing with RSpec. 

Do you think this is a good issue for a newcomer to try?

Thanks!

**Comment by jywarren** [comment]
Yes, I think it's a reasonable one, and I'm happy to help you out. Our test suite is not as full featured as RSpec, but it's the one build in in Rails. Take a look at the existing integration tests for an example! Thank you!

**Comment by amiedes** [comment]
I've been investigating the bug and I think I've found the potential cause of the problem.

I think there is an error in the execution flow of the creation of a new wiki article. What is happening is the following:

1. When an attempt is made to create a wiki page, a POST request is submitted to `/wiki/create`, resulting in the execution of the `WikiController#create` method.
2. When the wiki article (`DrupalNode`) fails to be created because of a validation error, the database remains untouched and the `views/wiki/edit.html.erb` template is rendered, where he/she has a second change to fill in the form fields which were rejected (the body in our case).
3. During the `WikiController#create` method execution, the `@node` variable was assigned a new instance of `DrupalNode`, even if it has not been saved into the database due to the validation error.
4. When the user submites the form from the 2nd step, the `WikiController#update` method is executed because of this logic inside `views/wiki/edit.html.erb` template:

  ```ruby
<% if @node && @node.path
  url = { :controller => "wiki", :action => "update", :id => @node.id }
else 
  url = { :controller => "wiki", :action => "create", :id => params[:id] }
end %>
  ```

  In our case both `@node` and `@node.path` have a value assigned, but we don't want the *update* action to be executed, but the *create* one.

  `WikiController#update` tries to update an existing `DrupalNode`, running `@node = DrupalNode.find(params[:id])`. Since the node corresponding to this id wasn't saved to the database, the process ends up failing.

I think the best solution to this problem is to create a new `views/wiki/new.html.erb` for this case instead of trying to control this case by adding more logic to a *view* file.

Any thoughts on this?

I'll open a PR with the corresponding code and tests as soon as I have a working solution.

**Comment by jywarren** [comment]
Ah! I think we had previously assumed that if the node.path was not set,
the node had not been saved. Could we alternatively change that conditional
so that we check if it's saved -- more directly?

(also noting that based on your investigation, an integration test might
not have caught this, since it doesn't directly use the forms generated on
a page, but simply submits a second query according to what we /think/ the
form ought to generate -- tricky!)

I see what you're saying on a new.html.erb -- that'd put the logic in the
controller, and I like that. But could we also look for (or create, as it
seems likely ActiveRecord has this already and we wouldn't have to add a
test, then) a node.saved method and switch based on that? I'd like to keep
as little repetition as possible in the template code, to make maintenance
easier.

Another way to reduce repetition might be to have a common partial template
with the common code, but it's sort of a judgement call whether that's
easier and more readable than just a conditional inside a template. Open to
suggestions. Thanks for so thoroughly thinking this through!

**Comment by amiedes** [comment]
@jywarren  You've made me realise it's simpler to change the conditional inside the template, so I decided to take your approach. 😄 

You are right about that the integration tests did not catch this, but they ended up pointing me in the right direction so starting by writing them has been a useful advice 😄 . I've decided to include them in the PR as they can be handy for the future.

I've opened a PR that I think solves this problem [here](https://github.com/publiclab/plots2/pull/1338).

Any feedback is really appreciated!
