### ISSUE TITLE
Some recently edited methods pages don't sort to the top of /methods

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1337]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

### Problem

Some edits were made to https://publiclab.org/wiki/balloon-mapping, but it's still listed at the bottom of https://publiclab.org/methods

But that page is supposed to sort by last updated, descending, according to this code: https://github.com/publiclab/plots2/blob/master/app/controllers/notes_controller.rb#L14-L18

We can see that the latest revisions have reasonable timestamps, here: https://publiclab.org/wiki/revisions/balloon-mapping

Not sure why this is happening, but we should be able to narrow in on this error using a functional test, in this document:

https://github.com/publiclab/plots2/blob/master/test/functional/notes_controller_test.rb#L189-L201 (which can also use some indentation formatting help 😄 )

We ought to be able to test if `assigns(:notes)` is actually sorted by timestamp, maybe using Ruby's `sort_by` method.

**Comment by amiedes** [comment]
I've noticed that the different methods are indeed sorted by last updated, but within each page. This makes me think that maybe the problem is that methods are being paginated before being sorted. 🤔

I've submitted [this PR](https://github.com/publiclab/plots2/pull/1341), but I'm unsure about how to test it because there are no seeds in the development database related to *"methods"*  and I don't know how to "create fake data" for tests with Minitest. I'd appreciate a little help with this 😅

Is it feasible to test this directly with the data available in production to see if the order changes as expected?

**Comment by jywarren** [comment]
Yes, we can merge this in and see how it does on staging, which has a copy of live data. But if you want to write a test, just add the tags "tool" and "method" to two wiki pages, and they should get listed (also fixtures are in `/test/fixtures/node.yml` - and I think we could try to reproduce this situation. 

Thanks!

**Comment by jywarren** [comment]
OK, just published to the site -- and it looks like the reordering didn't change this particular issue, so I'm re-opening. No worries, though -- we'll figure it out!

https://publiclab.org/methods?page=2

Can we run through the same exact query from this line, in a test, and test the expected order? https://github.com/publiclab/plots2/blob/master/app/controllers/notes_controller.rb#L14-L18

**Comment by jcotillo** [comment]
Hi all! I'm going to work on this 😃

**Comment by jywarren** [comment]
Oh, super! Tell us if you need anything! Probably best to look over the earlier fix and try to develop a theory of why this is happening, and reproduce it with a good test. Then open a PR and then try for a fix!

**Comment by ryzokuken** [comment]
Hey, @jcotillo! What's the status on this? If you require any assistance from our side, feel free to ask for help or hop on to one of the chatrooms.

**Comment by jcotillo** [comment]
Hi @ryzokuken! Thanks for the offer! Where are the chatrooms? I was able to reproduce the bug locally and I suspect that it's due how it's including the associated model...still testing though. I also never worked with fixtures or done functional testing so there is a bit of learning curve there for me. I will throw more time into it this weekend though and will reach out if I have any questions!

**Comment by ryzokuken** [comment]
Hey, @jcotillo! Thanks for your patience and hardwork. You can join our Matrix chatroom at #publiclab:matrix.org (if you prefer Riot, you can just join at https://riot.im/app/#/room/#publiclab:matrix.org).

Also, we have a Gitter channel at https://gitter.im/publiclab/publiclab.

We also have #publiclab on OFTC's IRC servers.

You can contact us by whichever way you find convenient. As all the chatrooms are linked and the messages are bridged, there won't be any problem.

**Comment by scosbet** [comment]
Hi all! Is anyone actively looking at this? Happy to give it a whirl if nobody is on it...

**Comment by jcotillo** [comment]
@scosbet i never figured it out! something to do with drupal tables....wasn't as easy as I expected >.< feel free to take it :)

**Comment by ryzokuken** [comment]
@scosbet: If @jcotillo is okay with it, you can feel free to try this one out.  
@jcotillo: What went wrong though? Did you try talking to the people at the IRC channel?

**Comment by scosbet** [comment]
Thanks @jcotillo! You mentioned you were able to recreate it locally before. Are you able to give me some more details on how you did that? 

I had a brief go yesterday while familiarising myself with the code but couldn't seem to recreate it easily. Thanks!

**Comment by jywarren** [comment]
Folks just a heads up that in a new PR (#1488), we're moving to a more complex version of this page, but the base code is the same -- these four lines:

https://github.com/publiclab/plots2/blob/master/app/controllers/notes_controller.rb#L13-L16

Will be displaced by these four lines:

https://github.com/publiclab/plots2/blob/master/app/controllers/wiki_controller.rb#L346-L349

So this shouldn't disrupt your work here that much -- thanks!

**Comment by scosbet** [comment]
It seems like the problem is around the pagination so having removed it in that PR the issue seems to be resolved for the methods page.

However, the similar code is being used in the places method of the notes_controller so it's still an issue there.

I've managed to recreate the problem locally so will do my best to get to the bottom of it and put a fix in place.

**Comment by jywarren** [comment]
Awesome, thank you! If there's enough repeated code we could make a new
issue for the node model and unit test it.

**Comment by scosbet** [comment]
Good news: 
I have figured out what the problem is and am pretty sure I've fixed it in [this PR](https://github.com/publiclab/plots2/pull/1512)

In short, the query used to retrieve the nodes isn't correct. During pagination the first thing it does is get the most recent 30 distinct node ids based on node_revision timestamp, however as there are multiple timestamps for each node the 'distinct' part of the query doesn't maintain the order.

After these 30 are obtained they are then sorted again which is why each page is sorted correctly but they're not in the correct order overall.

I changed the query using the info found here: https://stackoverflow.com/questions/5391564/how-to-use-distinct-and-order-by-in-same-select-statement. It's been tested locally and seems to work well but there might be a smarter way to write it than the way I translated from the SQL.


Bad news: 
In order to write a test for it I'll need a to add a LOT of nodes to the fixtures. The bug only shows itself when you have more than 1 pages worth of nodes with the 'chapter' tag meaning I'd need to add at least 30 to nodes.yml along with all the associated node_revisions and community_tags.

That seems like a lot to add for one test. Is it worth it? Or is there another neater way of creating the data I need?
