### ISSUE TITLE
Dropdown does not work with parameter raw=true

### ISSUE THREAD

**Issue by aspriya** [publiclab/plots2#1434]
### What happened just before the problem occurred
Without login in I was reading a wiki page which had a query string parameter `raw=true`. And then only remembered I should login to see some features of inline-markdown-editor work. But the dropdown link does not work for me to login. Once logged in without the parameter, it still does not work with `raw=true` parameter.

### Relevant URLs

https://publiclab.org/wiki/sandbox?raw=true

**Comment by ananyo2012** [comment]
After quite a bit of searching I observed that if I remove the `PublicLab.Editor.js` the dropdown works fine. The Editor is somehow blocking the bootstrap dropdown. Same thing happens in the `/post` page to. @jywarren Can you have a look at this ?

**Comment by jywarren** [comment]
Ohhhh yes this came up before -- since publiclab.editor includes jQuery,
the listeners for clicks run twice so its opened and closed at the same
time. I had been trying to develop a way to get the editor to detect if
jQuery were already loaded, and no reload it, but didn't come up with a
solution. I believe I had a pull request open for it, let me look.

**Comment by jywarren** [comment]
I guess I never opened one. I had been testing code at the point where I do
the "require('jquery')" step but couldn't get tests to pass. It seemed like
quite a tough problem!

**Comment by jywarren** [comment]
But we should open an issue over there and ask for help!
https://github.com/publiclab/PublicLab.Editor/issues

**Comment by ananyo2012** [comment]
Ok I will open an issue there and link to this one. So this can be closed here.

**Comment by jywarren** [comment]
Thanks Ananyo!!!

On May 27, 2017 4:38 PM, "Ananyo Maiti" <notifications@github.com> wrote:

Ok I will open an issue there and link to this one. So this can be closed
here.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/issues/1434#issuecomment-304475316>,
or mute the thread
