### ISSUE TITLE
Find place to put link to advanced formatting?

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1505]
Making a note that whenever i need to find our guide on formatting, i have to leave the page i'm on, go to publiclab.org/post, click "legacy editor" and click the link in the sidebar for advanced formatting. 

That is a bit much. 

Let's brainstorm other places we can put the link to https://publiclab.org/wiki/authoring-help#Advanced+formatting

**Comment by ebarry** [comment]
Also, i'd like to update what our div class definitions are. Right now the color is indicated by word choices that is not widely in use on publiclab.org: 
info = blue
success = green
alert = yellow
error = red

i think we should just have blue=blue etc.
--------------------------------
from https://publiclab.org/wiki/authoring-help#Advanced+formatting

####Alert Flags

<div class="alert">Learn more about the new <a href="https://publiclab.org/notes/warren/02-10-2016/announcing-spectral-workbench-2">Spectral Workbench 2</a>.</div>

You can also say class="alert alert-info" for blue, "alert alert-success" for green, "alert alert-error" for red boxes:

<div class="alert alert-success">This tool has been <a href="/wiki/tool-development">thoroughly tested in the field</a>.</div>

**Comment by jywarren** [comment]
Hi, Liz - these class names are Bootstrap styles, from
http://getbootstrap.com/css/ - it gets a little complicated to be forking
that project and modifying it, so I guess I'd like to suggest an inline
power tag (essentially a Markdown extension) for alert messages; something
like `[alert] Your message would go here [/alert]` and `[alert:green] Your
message would go here [/alert]`, instead of opening a can of worms.

And I'd like to think about a way to provide the link to advanced
formatting without distracting the folks who are not writing in Markdown.
But these are two separate issues; can you break it in two please?

**Comment by ebarry** [comment]
OK i deleted my 2nd comment, now this issue is only about where to put the link to Advanced Formatting so that it doesn't distract people who aren't writing in markdown, or worse -- html.
