### ISSUE TITLE
Profile bio information deleted? 

### ISSUE THREAD

**Issue by shapironick** [publiclab/plots2#1549]
### What happened just before the problem occurred
 I went to my profile to get the URL to link it to another project and found that my profile had no bio. I had updated it a month or so ago. 

### Relevant URLs
https://publiclab.org/profile/nshapiro
I also went to gretchen's and saw she didn't have anything either. 

### PublicLab.org username
nshapiro
(to help reproduce the issue)

### Browser, version, and operating system
chrome, latest version, pc

For bug reports, fill out the above template; for feature requests, you can delete the template.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
@ryzokuken could this be related to the migration we ran? We can recover
all bios from backups, but it was the same commit as the token -- just a
note.

Nick, sorry, looks like there was an error in a recent update. I'm
traveling right now but will take a look asap.

On Jul 25, 2017 1:15 AM, "Nick Shapiro" <notifications@github.com> wrote:

What happened just before the problem occurred

I went to my profile to get the URL to link it to another project and found
that my profile had no bio. I had updated it a month or so ago.
Relevant URLs

https://publiclab.org/profile/nshapiro
I also went to gretchen's and saw she didn't have anything either.
PublicLab.org username

nshapiro
(to help reproduce the issue)
Browser, version, and operating system

chrome, latest version, pc

For bug reports, fill out the above template; for feature requests, you can
delete the template.

To learn how to write really great issues, which increases the chances
they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/issues/1549>, or mute the thread

**Comment by shapironick** [comment]
No worries on my end. Just wanted to let you know.  I actually kind of like the "you are what you post to pl" minimalism. 

Sent on the move

**Comment by ryzokuken** [comment]
@jywarren I think so. There's also a persistent issue with the tokens I'm trying to solve. I'll try to crack this ASAP.

Thanks @shapironick for bringing this to our notice and for your patience.

**Comment by icarito** [comment]
This looks like it has something to do with the failing migration we had a couple of weeks ago, here's the [migration file](https://github.com/publiclab/plots2/blob/c00234b6357cc6e8d4d52e402955081d9ff55b25/db/migrate/20170704165711_add_user_bio_and_token.rb) as it ran in production and more information on the topic at https://github.com/publiclab/plots2/issues/1515

**Comment by icarito** [comment]
@ryzokuken it sounds related, yes. Note I've given you full access to staging, including Jenkins, ping me if you need some help with the container setup ;-)

**Comment by ryzokuken** [comment]
I would need help debugging this. The saddest part seems to be the fact that I'm sort-of stuck because of the token issue.

**Comment by icarito** [comment]
@ryzokuken kudos on asking for help. I'm terribly bad at asking when stuck. 

If we'll need to recover the columns from a backup, then it could take a little while to recover the exact date and construct and sql incantation to update each record.

In the meantime, can I offer to help you add a token manually if it will facilitate your testing?

I think I did a db dump just before this migration, so maybe we are in luck.

**Comment by ryzokuken** [comment]
@icarito please help me add a token to the plotsbot account manually for the time-being. I think adding the token manually now and going ahead with the project instead of waiting around for a global fix would be good fior my project as the second evaluation is here already. Meanwhile, we will also keep working on this, but "the show must go on".

Please either write in brief how I could setup a token (`SecureRandom.uuid`) for the bot account or add it yourself if you'd prefer and let me know that it's done so that we can test the API function.

Thanks.

**Comment by icarito** [comment]
As we were discussing earlier on the chat, you have the rails console at staging to add the token. Staging is up and running at https://testing.laboratoriopublico.org/ -

**Comment by jywarren** [comment]
I think this was the bio issue: 

> user.bio = DrupalProfileValue.find_by_uid(user.id, conditions: { fid: 7 }) || ''

That should have been (i think):

> user.bio = DrupalProfileValue.find_by_uid(user.id, conditions: { fid: 7 }).try(:value) || ''

My fault!

But I think it may not be worth modifying the migration itself. And we're not aware of other instances besides PublicLab.org which would be damaged by this... perhaps we could run a new migration with the correct bio transfer. 

You know, I think the bios are still in the db, just not copied over. 

Confirmed -- the bios are still there, just need to be copied properly. Will try now.

**Comment by ryzokuken** [comment]
@jywarren yay! finally.

**Comment by jywarren** [comment]
OK, i think we should do this in a migration. @icarito can we do this now without going through staging? 

I just opened a PR: #1551

But do we know why the tokens didn't get generated? We can at least confirm if #1551 generates them on the testing server. 

@icarito - also, why is staging up at testing...? I thought stable would build to staging.*, unstable to tesitng.*?

**Comment by jywarren** [comment]
but i am a bit jetlagged...

**Comment by jywarren** [comment]
Fixed finally!
