### ISSUE TITLE
deep links in wiki pages load underneath top menu bar

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#156]
The black menu bar itself is placed over the heading, obscuring it. 
see http://publiclab.org/wiki/forum-planning#Planning+Grassroots+Mapping+Forum+7

**Comment by jywarren** [comment]
Notes: this happens only on initial page load, not on internal deep link following. This is because the anchors are added using JavaScript, but the initial deep link anchor is followed before the JavaScript adjustments. We could have the JS re-execute the hash, but it has to be a different hash (possibly a null one like "#reset") in order to actually move the window scroll position. So we could say `window.location.hash = "#reset"; window.location.hash = "#Real+anchor";`
