### ISSUE TITLE
comment form preview button should change to edit on click

### ISSUE THREAD

**Issue by sethwoodworth** [publiclab/plots2#158]
Steps to reproduce:
- From the comment window box there are two buttons, `publish` and `preview`.
- write markdown and click `preview`
- edit window has changed to markdown preview of rendered html
- `preview` button should now say `edit`

**Comment by pdhixenbaugh** [comment]
Found this issue when about to open my own.

The button now says (Click to edit) or something, but it lies because you actually don't need to click it to edit -- you can type in the box as before. Then you have to click the button twice before it updates the preview. (I will add a screencap showing this). The button could instead say "Update Preview" or "Refresh Preview" and take just one click to update.
[plab preview button.zip](https://github.com/publiclab/plots2/files/473883/plab.preview.button.zip)

**Comment by gauravano** [comment]
Closing this as we have improved many things and this is not an issue now. Thanks!

cc @jywarren
