### ISSUE TITLE
spectralworkbench online is unaccesible 

### ISSUE THREAD

**Issue by reallygeek** [publiclab/plots2#1592]
When I attempt to go to spectralworkbench.org I get a message "my connection may not be private" and I can't get to the website.
I am using chrome (Version 60.0.3112.101)

**Comment by icarito** [comment]
Thanks for reporting! The automatic certificate renewal seems to have
failed without notice. I'll update it now.

**Comment by icarito** [comment]
Okay I've updated the cert. Just leaving a note here that letsencrypt `certbot`'s virtualenv broke somehow and I had to delete it to recreate it. Found a reference to the issue here: https://community.letsencrypt.org/t/cant-use-letsencrypt-auto-importerror-no-module-named--io/2345/8 - will also be checking other sites for this bug. Thanks again, solved now!

**Comment by jywarren** [comment]
thanks Sebastian!!!
