### ISSUE TITLE
Progressive/iterative improvements to header navbar menu items

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1621]
PL staff had a great navbar session and we're moving forward with an agreed-upon basic design, with some follow-ups. Those in parentheses will be discussed in follow-up. 

![Screen Shot 2019-09-27 at 3 57 42 PM](https://user-images.githubusercontent.com/24359/65798412-90339680-e13f-11e9-8b18-93fc8770f2d1.png)

## Code Follow-up

* [x] figure out if we can do this in a feature, or at least most of it in a feature
* [x] (later) Determine what has to be programmatic or not
* [x] (later) Test at various screen sizes (on stable)

## Design Follow-up

* [ ] Get started/Welcome page, with Ask a question
* [ ] Decide on a [Get support] item
* [ ] Finalize Regions/Places/Locations item, hide for now
* [ ] Design extra support/welcome content for non-logged-in folks; a dismissable Welcome ribbon.
* [ ] consider featuring more MEDIA (under About?): CSF/Forum, Newsletter, Stories, PL in the News
* [x] Brainstorm a name for the header item above Methods, or ditch it!

**Comment by jywarren** [comment]
Are we done with the store menu now? And maybe the About menu as well?

**Comment by ebarry** [comment]
I still have a lingering proposal for the About dropdown that there hasn't been a convenient time to discuss with Shannon, who blocked any changes without her review. 

We are done with store (the only proposal was to switch it from looking like a dropdown menu since there was no dropdown, and to looking like a button so people had some warning that they were going to be directed off the main website. Which we did!

**Comment by jywarren** [comment]
Initial start at #6508!

**Comment by jywarren** [comment]
Hi @ebarry there are a few leftover items here that are content oriented, and once complete can be added into the navbar, so I'm leaving this open! Thanks!

**Comment by jywarren** [comment]
Closing this as we seem to be OK now!
