### ISSUE TITLE
Add "accepted_answers" method to Node model, then add grey checkmark for as-yet unaccepted answers

### ISSUE THREAD

**Issue by gretchengehrke** [publiclab/plots2#1645]
### What happened just before the problem occurred
When looking at the new /wiki/hydrogen-sulfide, in a section including a table of things that had been tagged with hydrogen-sulfide, I saw one of my questions included there had been marked "(Answered)". However, I had not marked that question answered since the answer contributed was really more like comment material, and my question still stands. So, I'm concerned about it being so boldly marked as answered in the table. Would it be possible to only mark something as answered if the author has accepted an answer (rather than just an answer having been posted)? 

**Update: proposed solution (green/grey checkmark icons) added below with detail**

### Relevant URLs

https://publiclab.org/wiki/hydrogen-sulfide and https://publiclab.org/questions/gretchengehrke/08-23-2017/methods-for-or-experience-measuring-workplace-hydrogen-sulfide-gas

### PublicLab.org username

@gretchengehrke

### Browser, version, and operating system
Chrome, MacOS Sierra 10.12.6
<img width="1081" alt="screen shot 2017-09-26 at 10 51 46 am" src="https://user-images.githubusercontent.com/10854595/30867883-2aed2982-a2ab-11e7-95d1-9581550eabf4.png">

For bug reports, fill out the above template; for feature requests, you can delete the template.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
Hi, Gretchen - as of last week, any admin or moderator can also mark a question as answered, but we don't track who actually accepted it. (we discussed this in the comdev channel, maybe you missed it) So I'd guess an admin or moderator marked that as answered.

So I don't think this is a bug, but if you want to talk through how the feature works or request a change, that sounds good. (maybe w/ @steviepubliclab and @ebarry) Maybe we could try to track who marked things as answered?

Also, we are about to publish a new change where instead of (Answered) there is just a green checkbox icon, which is a bit less emphatic. Maybe that does something to help too. 

I'm going to mark this as closed, but if you'd like to rename and reformat it as a feature request or change, please feel free to re-open it once you've done so. Thanks!

**Comment by jywarren** [comment]
Actually, on second thought, i'm going to leave it open so we don't forget to discuss.

**Comment by gretchengehrke** [comment]
Hi Jeff,
I actually think it is a bug. If you look at the question itself (the link
is in the issue I filed), there is no indication that an answer has been
accepted. Please take a look.
As for who can accept an answer, I did see that convo. I don't think that's
what is going on here though.
Thanks,
Gretchen

**Comment by jywarren** [comment]
Ah, i see -- you're right, i misunderstood. The current check for whether it's answered is `does it have any answers written`, not `are any answers accepted`. I'm going to rename your issue to clarify this and i think it's a great point of distinction to figure out.

**Comment by jywarren** [comment]
@ebarry sez:

> seems like accepted is important
> i dont know
> in my head all sumbitted "answers" are actually just comments until one of them actually answers it all the way and than that's a real answer. i know, not helpful

Also, it now no longer says "Answered" but just shows a checkmark, due to a first-timer contribution: https://github.com/publiclab/plots2/pull/1633

![screenshot 2017-09-27 at 3 40 47 pm](https://user-images.githubusercontent.com/24359/30934031-458b024c-a39a-11e7-80b3-6e6e8ed09ece.png)

**Comment by jywarren** [comment]
Just a note - the definition (behind the scenes) of "answered" is currently "whether there are any answers" -- we'd maybe need a separate "accepted_answers" 

https://github.com/publiclab/plots2/blob/master/app/models/node.rb#L182-L184

**Comment by jywarren** [comment]
OK, changed title to suggest the "grey checkbox" could indicate that it's been answered, and "green checkbox" to indicate that at least one of the answers has been accepted. 

https://github.com/publiclab/plots2/blob/master/app/models/answer.rb doesn't reflect this clearly, but to check for answers that have been accepted, you can add `.where(accepted: true)` to the ActiveRecord query. So that would be part of an `accepted_answers` method on the Node model. Happy to clean up and repost this issue with these hints sometime soon, or if someone can follow this, go ahead and add the extra method!

**Comment by Diksha2008** [comment]
Hey @jywarren, I am new to open source. Can I work on this issue for my first time fix?

**Comment by jywarren** [comment]
Yes please, we'd love that! Thanks!

**Comment by jywarren** [comment]
Solved by @Diksha2008 in https://github.com/publiclab/plots2/pull/1665 !!!
