### ISSUE TITLE
Detect if first row of uploaded CSV is time-based, and use as x-axis

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1698]
When you use the new shortcode `[graph:____.csv]`, you get a chart like this:

![screenshot 2017-10-13 at 10 21 10 pm](https://user-images.githubusercontent.com/24359/31571702-bba50496-b065-11e7-8bd9-e0c90ca8f718.png)

But the x-axis is by default just `0,1,2,3,4...` by row number. If the first column is time-based -- maybe we can use already-installed `moment.js` to determine this -- let's use it as the x-axis. This'll take some research. 

https://chartjs.org/ has docs on how to display the charts

https://momentjs.com/docs/ has docs on how to read dates

The chart code template itself is at https://github.com/publiclab/plots2/blob/master/app/views/grids/_graph.html.erb

And the JavaScript to set up the chart is in this file:

https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/graph.js

Any help appreciated! You can test this out right now on the Sandbox 2 page: https://publiclab.org/wiki/sandbox-2

**Comment by JustusFT** [comment]
Hi, I'm a new contributor and would like to help on this issue. Can I give this a try?

**Comment by jywarren** [comment]
Yes please! This is not the easiest first timers issue but I would be happy
to help you out if you run into trouble or need any tips!

**Comment by JustusFT** [comment]
@jywarren The graph in the sandbox page seems to only display the first row data for me.
![screenshot-2017-10-24 public lab sandbox-2 1](https://user-images.githubusercontent.com/7854367/31923745-05b9a022-b8af-11e7-8e71-7e9c656795bf.png)

But it should like this right?
![screenshot-2017-10-24 public lab look at this graph 1](https://user-images.githubusercontent.com/7854367/31923979-b7c06c50-b8b0-11e7-8a01-c8fdf53cafa4.png)

I made it so that every row gets displayed across the x axis

**Comment by jywarren** [comment]
oh, that's super! if you'd like to submit a PR for that initial change,
that's great. Thanks!

**Comment by jywarren** [comment]
Ah, this was solved in #1698-- thanks!!!
