### ISSUE TITLE
Planning issue to reduce visual overload of left sidebar

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1706]
Hello! I'm starting this issue for a discussion of reducing the visual overload of the left sidebar. Thoughts, comments, ideas, needs, goals all welcome!

**Comment by steviepubliclab** [comment]
Hello, I have a personal visual preference towards reducing these. For example I worry about giving direct links to new people, that they wont see what I'm trying to direct them to on a page because of all the material in the margin.

**Comment by ebarry** [comment]
Perhaps we could take another look at the way related content by other contributors is shown in the sidebar?

Perhaps we could look at the standard sidebar which shows banners, perhaps this type of sidebar use can be removed?

<img width="238" alt="screen shot 2017-10-19 at 4 56 53 pm" src="https://user-images.githubusercontent.com/161439/31953381-0a74ba00-b8b1-11e7-88dc-d2c9731543f7.png">

What do you guys think?

**Comment by jywarren** [comment]
Great - added some tags here too. I think the first thing we can do is break out an issue to remove the "featured" sidebars that show banners as Liz suggests above. That's a pretty easy one; it's actually run from a "feature" -- so we can wipe it now, if you can get an OK from Margie (since one of those banners is now hers). 

For rethinking how related content appears, I can think of a few things. 

1. we could look at some of what Siyuan suggested re: moving sidebar to the right side (see the last comment): https://publiclab.org/notes/siyuan/06-12-2017/a-questions-page-to-encourage-discussions-through-better-ux
2. we could think through where displaying related content would be more helpful (at the end of the page? See references from, for example, nytimes.com articles)
3. we could look into Google Analytics to see if we can learn about how often people do cross-navigate into related content
4. we could think through how related content is auto-identified, and try to do a better job, to make it /more/ relevant

FWIW, the related sidebar code is here: https://github.com/publiclab/plots2/blob/master/app/views/sidebar/_related.html.erb 

and is one of the oldest pieces of code on the site, interestingly!

**Comment by jywarren** [comment]
I've introduced a `first-timers-only` issue for overriding tag that completely omits the sidebar, although I'm not sure if it leaves an empty space or moves the main content column over: #1735

**Comment by ebarry** [comment]
Quick update, I have emailed Margie to ask her.

**Comment by jywarren** [comment]
Another suggestion: we could use the sidebar space for a table of contents for longer documents.

**Comment by jywarren** [comment]
Also noting that for pages where no sidebar is desired, there's now a `sidebar:none` powertag: https://publiclab.org/wiki/power-tags

**Comment by ebarry** [comment]
Reading through @jywarren's list above, i think it would be great to **either** 1) take Siyuan's idea to move the sidebar to the right (https://publiclab.org/notes/siyuan/06-12-2017/a-questions-page-to-encourage-discussions-through-better-ux#c17461) **or** 2) put it at the bottom of the page similar to many news websites. 

I'm not a UI expert though. I think i like the idea of moving it to the bottom more, but perhaps it's easier of an initial fix to just move the sidebar to the right?

**Comment by jywarren** [comment]
I'm going to break out one option to make the "related content" collapsible, so it's still there but there's more of a hierarchy of importance: #2493

**Comment by ebarry** [comment]
Sounds great! it'll be helpful to see how that looks, and then revisit Siyuan's recommendations about testing out a righthand sidebar or look at other contemporary ways to show related content (like, at the bottom of pages)

**Comment by jywarren** [comment]
I did a mockup of a more minimal sidebar that also hints at the kinds of "related work" the current sidebar shows, but through the tagging display (here, the # of posts with a tag is shown in the tag label). This would be kind of two birds with one stone 🐦 🗿  -- but just an idea. The basic idea could also still work in the current tags location at the bottom of the post. 

Broadly speaking, this kind of "gradual reveal" of complexity should help with the visual overload. 

![image](https://user-images.githubusercontent.com/24359/37424326-8ff2290c-2796-11e8-9620-54c6d5667d62.png)

This could pair nicely with #2494's idea of a popover interface for tags, sort of combining the current sidebar function with the tagging interface. 

![popover](https://user-images.githubusercontent.com/24359/37420992-9b8c272a-278e-11e8-9a76-4873fc652be0.png)

**Comment by ebarry** [comment]
I REALLY LIKE THIS 
- it moves the sidebar to the right, and gives a great amount of explanation!

**Comment by jywarren** [comment]
Awesome. Let's get it queued up! It may be a few days as I travel!

**Comment by jywarren** [comment]
OK, so #3091 having been created, I'm going to close this one out!
