### ISSUE TITLE
co-authored content should be shown on co-author's profile

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1782]
This issue is a piece of https://github.com/publiclab/plots2/issues/761

### overview 

The co-authorship feature is great, and just needs a little bit more tweaking to be AWESOME. 

I suggest that co-authored notes should appear not only on the first author's profile, but also on the co-author's profile. 

### Please show us where to look

This note is basically me writing about Benjamin Sugar's work: https://publiclab.org/notes/liz/09-15-2016/first-draft-of-tag-graph

I have tagged him as a co-author, but the note does not show up in his profile https://publiclab.org/profile/bsugar

It would be great if it did!

### Further considerations

Perhaps, to accommodate for the potential situation where someone might reject being named as co-author, or simply not want that content showing on their profile, or other such situations, can we consider giving co-authors the ability to untag themselves from content they are tagged on?

Let's discuss.

**Comment by jywarren** [comment]
I think the current answer for rejecting coauthorship would be just to remove the tag, though that may not be ideal. We could later discuss an email notification with a link to remove coauthorship credit if someone chooses. This could just remove the tag. But if it's all right with you, maybe open a separate issue from this one, since that's a whole other discussion and I think we could narrow down a solution for the main issue here!

The easiest way to list coauthored (if you're not primary author) notes would be to have a separate listing for them. This would avoid having to interleave your primary-author posts with ones where you're co-author (since we look them up in different ways). Would that be an all right first step?

**Comment by ebarry** [comment]
+1, all this sounds good!!

--

+1 336-269-1539 / @lizbarry <http://twitter.com/lizbarry> / lizbarry.net

**Comment by sagarpreet-chadha** [comment]
@jywarren sir , @ebarry mam...can i take this one ?

**Comment by sagarpreet-chadha** [comment]
<img width="1251" alt="screen shot 2017-11-17 at 6 43 17 pm" src="https://user-images.githubusercontent.com/14952645/32949066-735e0890-cbc7-11e7-9332-9f1676c2e2a2.png">
I was thinking of making a tab as shown in image . What do you think ?

**Comment by ebarry** [comment]
that looks great to me at least! What does @jywarren think?

--

+1 336-269-1539 / @lizbarry <http://twitter.com/lizbarry> / lizbarry.net



On Fri, Nov 17, 2017 at 8:17 AM, Sagarpreet Chadha <notifications@github.com

**Comment by jywarren** [comment]
I like it too - but that row of tabs is starting to wrap. Could we remove the words "Barnstars" and "Comments" and rely on the icons for those, to make more space? And perhaps we could just say "Coauthored" for short? 

This is a temporary space-making solution, as we'll be circling back to the profile page pretty soon to try to reorganize it for better information design, and this'll let us address this issue faster. Thank you!!!
