### ISSUE TITLE
Rich Profile tagging: use powertags to connect a person's usernames form other platforms

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1805]
### Please describe the problem (or idea)

As mentioned in https://github.com/publiclab/plots2/issues/1802, automated tweeting from our website would be improved if people with PublicLab.org accounts could specify what their usernames on twitter are. 

The ability to specify what your username on additional other platforms is as part of your PublicLab profile would help fill in the hard-to-track gaps of how people work across multiple areas of the ecosystem including github, various social media, or elsewhere. 

Can we look into how to set up a profile interface where it is easy to add in your usernames form other platforms?

**Comment by jywarren** [comment]
Hi, Liz - I'd recommend either changing this to:

1. `Profile tagging input design work for adding Twitter handle to PL profile` - a narrower case and a specific ask for design help in how this would be input OR
2. `Display Twitter link on profiles if profile tag "twitter:______" exists` -- leaving the input manual for the time being so we know what this will look like once an input interface is designed

I'm happy to change it to one of these if you like!

**Comment by ebarry** [comment]
ok well #1802 is really the one about Twitter, perhaps we could change that title? This one is about making it possible to add lots of other platforms as well

**Comment by jywarren** [comment]
Oh, i think #1802 is too broad to be a discrete solvable issue; so converting this one into a narrow enough issue that someone can pick it up would be a good step forward. Otherwise I worry this is another planning issue, and there's some redundancy with #1802. Does that make sense? 

If this is for repeating the Twitter-specific changes on other platforms, then we should probably make one for the discrete changes for Twitter first, then build some "repeat this, but for platform X" issues afterwards (these'll make good first-timers-only issues, as there'll be a really solid example to work from). How does that sound?

**Comment by jywarren** [comment]
Complete -- Solved adding to profile pages in #1816! 

But we should still make a discrete issue for `a UI for inputting social media usernames into your profile` -- perhaps based on a JavaScript `prompt()`
