### ISSUE TITLE
Find profiles by real person's name

### ISSUE THREAD

**Issue by shanlter** [publiclab/plots2#1823]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

I know some PL members' real name, but I don't know how to find their PL profile, and don't know how to @them...
For example I want to find "Katie Gradowski", I type the name in the searching box, no result. I type "Katie", 5 katies showed, I click their name to view their profile, but none of them is the Katie I want. 

This is not only Katie, try "Jeff Warren", "Liz Barry", it's all the same. I encountered this problem several times, I want to show my friends some of the members page, but I have trouble remembering their usernames, I try to search, the problem come.

> What did you expect to see that you didn't?

I type "Katie", the most popular/active Katie appeared.

### Please show us where to look
These are the Katies I don't want.

https://publiclab.org/profile/KatieJane
https://publiclab.org/profile/Katieins
https://publiclab.org/profile/Katiemdd
https://publiclab.org/profile/Katiefam
https://publiclab.org/profile/Katieins

### What's your PublicLab.org username?

shanlter

Thanks very much!!!!!

**Comment by jywarren** [comment]
Hi, this is a really good point. I can see two issues:

1. some people don't put their real name up -- Katie is actually one of them, although maybe it's an oversight? https://publiclab.org/profile/kgradow1/
2. we don't currently search user profile bios, but we could. Let's open an issue for that -- it'll have to wait until our big search upgrade, but it's definitely a good suggestion! 

We could also prompt people to input their real name in their bio... if they want?

**Comment by jywarren** [comment]
I added an issue for 2) here: #1824 though it may be a bit before the new search system is online and we can take action. Thanks again!

**Comment by shanlter** [comment]
Thanks for your revise! It looks much clear now.
I put my real name into my bio, make it easier for further searching.
Not only searching bio. I think there are little problem with the username searching. 
eg, try "Warren" in the searching box, several users recommend none if them is you; try "Liz", none user recommend result. If I ignore the recommend, just press search button, several research notes showed. Under the "Liz" searching, none of the articles are composed by Liz.
Unlike Katie, both of your username are those words.
I don't know if this is very difficult, but it will be very helpful to classify the
research note/wiki/user searching result (like github?)

Thanks!

**Comment by jywarren** [comment]
The new search system is almost ready; it's just not activated as we're dealing with some performance issues. If you know anyone who does Ruby on Rails or Solr search work, we could use the help! #1784 describes the problem. 

Also, a first-time contributor is also now working on #1824 to make the whole bio searchable! So thanks for helping articulate that improvement!

But yes, once Solr is running, we should be able to improve the username searching pretty dramatically. Right now, the line of code doing the search (without the help of the new Solr system yet) is here:

https://github.com/publiclab/plots2/blob/master/app/services/search_service.rb#L38

This could perhaps also be optimized a bit; it's sorted so that newer users get returned first, and may also need a `.where(status: 1)` addition so that we're only searching non-spam users. I'll add that as a first-timers-only issue.

**Comment by jywarren** [comment]
Great, I added an issue at #1829 to address this last suggestion too. Hopefully someone picks it up! If you can tweet it with #FirstTimersOnly people are likely to see it and someone may plug in. Thanks so much!

**Comment by jywarren** [comment]
I just searched for: "liz" "shan" "warren" and got profiles for us three as top results. The new search system is much better. I'm sure there are still ways to improve it -- a search for `katie` doesn't return kgradow1, but that's because she hasn't put her name on her account. 

I noticed `kgradow` also doesn't return `kgradow1` but typing the full username works. I'm not sure why, actually. But overall I'm going to close this issue as the original narrower question seems solved -- that of why Katie is not showing up. And other searches seem to be working well. Thank you! Please open a new one if you want to pursue another improvement, and thanks!
