### ISSUE TITLE
Logout not working

### ISSUE THREAD

**Issue by Gauravano** [publiclab/plots2#1853]
### Please describe the problem (or idea)
Logout not working, showing 404 every time

**Comment by jywarren** [comment]
Oh, good catch! Are you at all interested in submitting a fix? I believe
it's related to this line -- i think it should be `get` not `delete`. I'd
be happy to help you file the fix, and we'd really appreciate it!

https://github.com/publiclab/plots2/blob/f6fe2ea6273e30444bb2ccde131c0ae1bf6c8ea6/config/routes.rb#L37

**Comment by Gauravano** [comment]
Actually, there are is one modification possible in Logout from all devices too ...we can display successful logout message there too.What do you say?

**Comment by jywarren** [comment]
Good idea!

**Comment by Gauravano** [comment]
Thank you.So can I add this notice to pull #1855

**Comment by jywarren** [comment]
That would be super. Great idea!

**Comment by Gauravano** [comment]
hey @jywarren, I think this issue still persists, it worked fine in development when I changed routes.rb but in production, it's giving different results now.I have checked "Log out from all devices" too, its also not working and rendering an error page. What you say about re-opening this issue ?

**Comment by jywarren** [comment]
Hmm, too bad; yes, let's reopen!

On Jan 7, 2018 10:05 AM, "Gaurav Sachdeva" <notifications@github.com> wrote:

hey @jywarren <https://github.com/jywarren>, I think this issue still
persists, it worked fine in development when I changed routes.rb but in
production, it's giving different results now.I have checked "Log out from
all devices" too, its also not working and rendering an error page. What
you say about re-opening this issue ?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/issues/1853#issuecomment-355828730>,
or mute the thread

**Comment by Gauravano** [comment]
@jywarren I just found that logout is working properly it's just not visible to the user as the website is redirecting us to root after log out as usual and rendering the page from the cache so I believe its due to    #1892 .What you think about this jeff

**Comment by jywarren** [comment]
Ah, isn't this a client-side browser cache though? Perhaps we can add a
timestamp to the redirect URL such as `?_=123456` as we do elsewhere in the
code?

**Comment by Gauravano** [comment]
yes @jywarren you are right its due to client-side browser cache.Just making a commit.Thanks for helping.

**Comment by jywarren** [comment]
thank you!!!

**Comment by skilfullycurled** [comment]
Hey friends.

This might (might not) still be an issue.

I was logged in to the PL website with Firefox 65 (macOS) and when I tried to logout I was redirected and still logged in.  So then I tried to log out of all devices and was redirected to an error page: https://publiclab.org/logoutRemotely (There was an error. Are you sure you have the right address?)

That's when I realized that I had also been logged in using Chrome 72.0.3626.119 (macOS).  So again, I tried to logout and was redirected back to being logged in. I tried to log out of all devices and was taken to the same error page as above.

The good news is that now I am logged out of both browsers.

Could just be an edge case but even so, thought I'd report.

**Comment by gauravano** [comment]
Hey @skilfullycurled, thanks for bringing the case to notice. We have been through many changes in our authentication flow in last year and that may have resurfaced this error or any other like this.  

I have opened an issue - https://github.com/publiclab/plots2/issues/4907 just to be sure, that we are on track.

**Comment by skilfullycurled** [comment]
Cool.  Although on your end it might be indicative of something important, just wanted to say that on my end, in the many many years I've been using the site, this is the first time I've ever used two browsers at the same time so it's not particularly bothersome.  Sadly, the two browsers were open because I wanted to check if a different bug was browser related or not. Stay tuned on that.  : /
