### ISSUE TITLE
Add a new page for tagged content by a single author

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1854]
Let's add a new page, similar to the "tag" page like https://publiclab.org/tag/hydrogen-sulfide, but for just one author's work, so:

https://publiclab.org/tag/hydrogen-sulfide/author/warren ?

This'd require:

1. a `config/routes.rb` entry
2. a re-use of the `/app/views/tag/show.html.erb` template with a custom title
3. a new action in `/app/controllers/tag_controller.rb` for, maybe `def show_for_author` ? which uses the new `Tag.tagged_nodes_by_author()` method here
4. a functional test in `/test/functionals/tag_controller_test.rb` to show that the new `show_for_author` action works

This would be a bigger project, but would be pretty awesome to see. 

I'd be happy to help anyone through it -- @SidharthBansal ?

**Comment by SidharthBansal** [comment]
I will like to try this one out too!!!

**Comment by jywarren** [comment]
Awesome!

**Comment by SidharthBansal** [comment]
@jywarren I was browsing over the tags on the public lab websites. I found that we are able to search research articles with the custom tags but we are not able to search for the contributors related to them with custom tags.
For example, if I need to search for all balloon related notes, I will type publiclab.org/tag/balloon*
it shows 0 contributors but for balloon, there are 16 contributors.
see https://publiclab.org/tag/balloon
and https://publiclab.org/tag/balloon*
I think this issue is to be taken later on, in this power tags?

**Comment by jywarren** [comment]
Indeed, that's a really good point. But wildcard searches can be expensive
to the database. If we can't come up with an optimized way to run a search
for, say, "a*", we might give the database some trouble. Another option is
to just disable the Contributors tag and have a tooltip hint that says
"Contributors cannot be listed for wildcard tag searches" or something.

Great thinking ahead!

**Comment by SidharthBansal** [comment]
Yeah, the query like 'a*' will be very time-consuming. The second option is better.
