### ISSUE TITLE
User can't enter custom query on Search Page

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#1863]
On the search page https://publiclab.org/search there are two search fields.
In the lower field if a person types something and clicks on the search icon then it instead of finding the results gets redirected to the search page again.
Also, on pressing enter key, one item from the suggested searches get selected and corresponding search page is rendered. The user is unable to do a custom search. For example, if I typed in balloon, as I want to search for all balloon related notes. But on pressing enter, a page related to the one highlighted from the suggestions is rendered.
The upper search button is working fine.

**Comment by jywarren** [comment]
Did #1869 solve this? Hmm, probably not -- how is it related to #1868? Thank you!

**Comment by ankitbhardwaj78** [comment]
@jywarren can i solve this issue .I think this is due to inline form submit action is missing
https://github.com/publiclab/plots2/blob/c6b2d3460d1fb9da28ce5e1cc0944daf690f9415/app/views/searches/new.html.erb#L1-L6
As for header search we have submit action
https://github.com/publiclab/plots2/blob/c6b2d3460d1fb9da28ce5e1cc0944daf690f9415/app/assets/javascripts/searchform.js#L1-L9
I think same We have to do it for inline search bar.

**Comment by SidharthBansal** [comment]
@ankitbhardwaj78 try if you can

**Comment by jywarren** [comment]
:-)
