### ISSUE TITLE
Repetitive code in Users controller (lines 129-144)?

### ISSUE THREAD

**Issue by seafr** [publiclab/plots2#1908]
The code on lines 129-144 in the Users controller seems to be repetitive. Can I move it to a (private) method? Please note that I am new to this.

**Comment by jywarren** [comment]
That'd be great, thanks! Perhaps even in /app/models/user.rb?

On Dec 29, 2017 8:04 AM, "Sea" <notifications@github.com> wrote:

The code on lines 129-144 in the Users controller seems to be repetitive.
Can I move it to a (private) method? Please note that I am new to this.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/issues/1908>, or mute the thread

**Comment by seafr** [comment]
OK, in the model then.

**Comment by jywarren** [comment]
Awesome, thanks for your help!

**Comment by jywarren** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by seafr** [comment]
Hi @jywarren, plz check PR #1909 and get back to me. Unfortunately, it seems there is some problem with it :( The Travis CI build did not succeed.

**Comment by jywarren** [comment]
Merged the fix in #1909 -- thanks!!!
