### ISSUE TITLE
Showing a basic user as 'moderator' .

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/plots2#1918]
### Please describe the problem (or idea)

In [/people](https://publiclab.org/people) , basic user is shown as a 'moderator'  . 
Also do we have to show normal users the ban buttons ?

<img width="1152" alt="screen shot 2018-01-05 at 11 35 17 pm" src="https://user-images.githubusercontent.com/14952645/34622241-68f67b04-f272-11e7-9a0c-25c9ab87f949.png">

**Comment by jywarren** [comment]
Hmm, are you sure you're not a moderator? It's this line of code:

https://github.com/publiclab/plots2/blob/646deeb659cd62064792b4134155717d08a5b5a5/app/views/layouts/_header.html.erb#L126

Thanks!

**Comment by Diksha2008** [comment]
https://github.com/publiclab/plots2/blob/9e0f5e6ba58b72390cb7772c9ebbb088d672d4a5/app/views/users/list.html.erb#L8
https://github.com/publiclab/plots2/blob/9e0f5e6ba58b72390cb7772c9ebbb088d672d4a5/app/views/users/list.html.erb#L22
I think this is due to ' = ' instead of '==' on line 8 and 22
@jywarren May I open a PR to resolve this?

**Comment by sagarpreet-chadha** [comment]
Nice Catch @Diksha2008 !

**Comment by jywarren** [comment]
Oh, please do -- great catch!

**Comment by jywarren** [comment]
Was this resolved in #1990? Or was it the same "kind" of issue but not the exact same code fixes? Thanks, all! Feel free to close if it's resolved!
