### ISSUE TITLE
Redundant "Share your work" on the dashboard

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#1925]
### Please describe the problem (or idea)
There are 3 Share your work links to the same page on the dashboard. One inside the navbar's menu. Other on sidebar and one in the Activity Section
![image](https://user-images.githubusercontent.com/20972099/34681483-0a5ae772-f4c2-11e7-8abf-3c99d70573af.png)
> What did you expect to see that you didn't?
I don't know whether it is a feature or redundancy that needs to be removed.
### Please show us where to look
https://publiclab.org/dashboard

**Comment by jywarren** [comment]
I think we're going to be revisiting the Share your work button pretty soon
but if it's all right I think we'll leave this as is for now. Partly this
is because different people look in different places for things, depending
on their preferences and expectations. And sharing your work is something
we really want people to do!

**Comment by jywarren** [comment]
Thanks so much for thinking through this carefully, though!
