### ISSUE TITLE
Implement Style Guide

### ISSUE THREAD

**Issue by siaw23** [publiclab/plots2#1994]
I saw `rubocop` added in `development` group. I think it'll be a good idea to actually add it to to travis too so non-conforming PRs won't pass. In the mean time I'll go ahead and start the implementation first to put things in order. This will take some time. @jywarren

**Comment by jywarren** [comment]
Hi, @siaw23 -- thanks, this is great to see. I wanted to note that we want to be extra welcoming and helpful to people, so do you think there's a way for this to, rather than showing an angry red X alone, we could have rubocop make friendly suggestions of style, to help people along? This is kind of a stylistic request, but what do you think? Even just not making a super long list of issues all at once could help -- start with a few suggestions but don't show more than 2-3 initially. What do you think?

**Comment by siaw23** [comment]
well i think there are enough friendly messages like this

> And don’t be discouraged if you see errors – we’re here to help.

So instead we can add this info to the README instead. that's the first thing first-time contributors [should] read anyway. And `rubocop` errors are fairly straight-forward in my opinion. The README can also directly mention who to ask for extra help directly, that way if they are really lost they can mention someone.

**Comment by jywarren** [comment]
OK, -- can you show what it'll look like to people? Like, could you trigger
some errors on your PR to demonstrate?

On Sat, Jan 13, 2018 at 11:44 AM, Emmanuel Hayford <notifications@github.com

**Comment by siaw23** [comment]
now that's rubocop is not added to Travis nothing will show when there's an error. So even if this is merged, people can still create PRs like before, no errors until we add it to CI. The errors will only show locally which they can ignore if they want. Errors will appear on PRs after we add rubocop to Travis. @jywarren

**Comment by jywarren** [comment]
Hi, i see -- so, for now, you're proposing going through in #1993 and resolving the existing ones, then Rubocop would alert people for new ones? Let's do this in stages in any case, maybe section by section in different PRs, so that we don't end up with tough merges. 

Thanks!!

**Comment by siaw23** [comment]
Yeah so first stage is this PR. Second will be for me to correct remaining offences. Third will be to add small set of instruction to README. fourth will be to add it to Travis @jywarren
