### ISSUE TITLE
Proper Template missing

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#1998]
### Please describe the problem (or idea)
The URLs of the type https://publiclab.org/widget/kite don't show any header, footer etc.
![image](https://user-images.githubusercontent.com/20972099/34908914-0cc5c6bc-f8be-11e7-8e9e-4c125f92309d.png)

**Comment by jywarren** [comment]
Hi! This template is used for embedding on other sites, which is why it
lacks a header or footer. Thanks for the catch though!

On Jan 13, 2018 1:32 PM, "Sidharth Bansal" <notifications@github.com> wrote:

Please describe the problem (or idea)

The URLs of the type https://publiclab.org/widget/kite don't show any
header, footer etc.
[image: image]
<https://user-images.githubusercontent.com/20972099/34908914-0cc5c6bc-f8be-11e7-8e9e-4c125f92309d.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/issues/1998>, or mute the thread
