### ISSUE TITLE
Dashboard overwhelmed with just a few posts on a single topic

### ISSUE THREAD

**Issue by gretchengehrke** [publiclab/plots2#2076]
The current PL dashboard (http://publiclab.org/dashboard) can easily become overwhelmed with a single topic or a single person's username if just a few questions, comments, or posts are made. As many people (perhaps especially PL staff) seem to respond to or post several related items in a given website session, the dashboard is quite often flooded with information on one topic, leaving other topics invisible until someone else posts on them. 

Since @jywarren has explained that doing a dashboard or search view that is not reverse-chronological is very challenging, perhaps we could have "pinned topics" where each topic is still sorted reverse-chronologically, but at least three (or perhaps six, one for each core piece of dashboard real estate) topics are always visible.

**Comment by jywarren** [comment]
Awesome, good topic to open here. Let's break down the problem some:

* bursts or "collections" on a single topic push down other topics
* bursts by a single author could do the same
* we'd like to feature more diversity of topics and authors on the dashboard activity feed

Anything you'd add?

I think the next step is to collect and compare possible solutions. For one, what are some conventions from activity feeds you've seen around the web? One I see regularly is the GitHub activity feed ([link if you're logged in](https://github.com/)), which groups some things but isn't great for some of the same reasons our feed is not great:

![screen shot 2018-01-23 at 12 03 41 pm](https://user-images.githubusercontent.com/24359/35289493-8192db96-0035-11e8-9f9e-0ce5dcb5f5a0.png)

One thing we already do is to omit wiki edits by a single author that closely follow previous edits by that author. We can do a bit of that kind of "trimming" on different groupings too. 

So, some solutions might be:

1. group any nearby 5 posts that share a tag into a single item that says `5 posts on _air quality_ by 3 authors` or something like that? 
2. actually not display more than X pieces of content by a single author, hiding the additional ones. This could frustrate some authors but we could note this somewhere to explain, or have a "show all" that's not the default. 

With the "pinning" idea, would we then show a collection of recent topics, instead of a collection of posts on any topic? That's a cool idea, thinking outside the box. So in that model, the activity feed would be a list of recently trending topics, rather than a feed of all posts. I kind of like that!

Other ideas?

**Comment by jywarren** [comment]
I found this old issue that i'll merge into this one - https://github.com/publiclab/plots2/issues/370

**Comment by jywarren** [comment]
I'd originally said in that old post:

> This might rely upon profile tagging (#104), and would benefit from #64 as well.
> But it could be based purely on subscriptions, since people already make those based on topic/tag.
> This should not be on by default, and we might warn people "14 additional notes not tagged with balloon-mapping".

**Comment by gretchengehrke** [comment]
Ooh, I like the idea of showing recent work in a collection of topics,
showing one *and* saying "see 10 additional recent posts about turbidity"
too.

**Comment by ebarry** [comment]
+1 I like all these ideas. 

I have an idea to help make room for this: remove the righthand column with two tabs for "wiki" and "discussion lists". Instead, add these into the checkbox where you can choose to see research notes, questions, events, and comments:

<img width="192" alt="screen shot 2018-01-24 at 5 21 34 pm" src="https://user-images.githubusercontent.com/161439/35360237-1096717c-012b-11e8-98b6-41efc4681993.png">

Discussion lists aren't looking so good lately anyways: https://github.com/publiclab/plots2/issues/2101

**Comment by ebarry** [comment]
ok we're handling this last idea in another issue, let's return to the brainstorm around **how we could show recent work in a collection of topics**. Sorry for the disruption!

**Comment by ebarry** [comment]
Here's an update that makes some progress toward this, a new listing of the largest research areas on publiclab.org in the sidebar, as tags you can click to directly view all or follow: 
<img width="1080" alt="screen shot 2018-10-05 at 6 17 03 pm" src="https://user-images.githubusercontent.com/161439/46562705-77492a00-c8cb-11e8-9049-a0acfc0c5d94.png">

**Comment by jywarren** [comment]
We're resolving this in the new Dashboard design -- see https://github.com/publiclab/plots2/projects/10 and #5676 and https://publiclab.org/notes/warren/04-22-2019/user-interface-projects-update-and-dial-osc-project-recap

Mainly, we're moving to a topics list instead of a posts list, based around the Subscriptions system - like on https://publiclab.org/tags !
