### ISSUE TITLE
Add a "feature" to the signup page footer

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#208]
The signup page has some text at the bottom we want to change from time to time. Right now it features the Code of Conduct text and a notice about open sourcing your work (see screenshot, below the blue button):

http://publiclab.org/signup

![screen shot 2018-01-23 at 3 14 49 pm](https://user-images.githubusercontent.com/24359/35298443-3bf4d902-0050-11e8-8785-d0473316195d.png)

We could add a "feature" to the bottom where the existing text is, so it could be easily modified without needing to change code -- would that help get this solved?

The code for this is here: 

https://github.com/publiclab/plots2/blob/ceb7d05404b4619c7fa8cd8cae5e8215798cb02c/app/views/users/new.html.erb#L27-L35

We could replace this with a "feature" using these lines of code:

https://github.com/publiclab/plots2/blob/ceb7d05404b4619c7fa8cd8cae5e8215798cb02c/app/views/layouts/_footer.html.erb#L9-L11

although instead of `footer-notice` we could have it say `signup-notice`. 

Any help appreciated!

**Comment by steviepubliclab** [comment]
Interesting, getting back to this. Wondering if we could point people to the live call when they sign up?

**Comment by jywarren** [comment]
Great -- this is what the signup page currently looks like. We could add a "feature" to the bottom where the existing text is, so it could be easily modified without needing to change code -- would that help get this solved?

![screen shot 2018-01-23 at 3 14 49 pm](https://user-images.githubusercontent.com/24359/35298443-3bf4d902-0050-11e8-8785-d0473316195d.png)

If we wanted to move forward in this way, the code for this is here: 

https://github.com/publiclab/plots2/blob/ceb7d05404b4619c7fa8cd8cae5e8215798cb02c/app/views/users/new.html.erb#L27-L35

We could replace this with a "feature" using these lines of code:

https://github.com/publiclab/plots2/blob/ceb7d05404b4619c7fa8cd8cae5e8215798cb02c/app/views/layouts/_footer.html.erb#L9-L11

although instead of `footer-notice` we could have it say `signup-notice`.

**Comment by ebarry** [comment]
Great! Let's do add a footer so that we can begin 

The original issue of "add a note about possibly being contacted by admins/staff when people sign up" also came up in a different context this week where our research partners at UCD asked if they could contact people who have posted on the website. As staff, we need to let people know at signup that staff might contact them. So we still need to add this.

**Comment by jywarren** [comment]
I deleted my comment and copied it into the issue body, and tagged! 

If anyone wants to tackle this one, please jump in! Thanks!

**Comment by jywarren** [comment]
Made this into a first-timers-only issue at #2261 !!
