### ISSUE TITLE
bug in contributor notes by tag

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#2178]
### Please describe the problem

> What happened just before the problem occurred?

I am cataloguing all contributors in a research area, and just looked at all notes tagged wetlands. 
On the contributors tag, https://publiclab.org/contributors/tag/wetlands the people at the bottom are listed as having notes, but when you click on notes, there is unexpected behavior: 

![contributor-notes](https://user-images.githubusercontent.com/161439/35595195-cd5df408-05e3-11e8-9cc0-547c19ec9f1d.gif)

> What did you expect to see that you didn't?

I expected to see a display of notes about wetlands that that contributor wrote that is visually similar to the tag pages. 

### Please show us where to look

https://publiclab.org/contributors/tag/wetlands

**Comment by SidharthBansal** [comment]
@ebarry @jywarren may I take it and try to solve it?

**Comment by SidharthBansal** [comment]
Even the links which are working properly has multiple errors in them.
1.For eg, we are having a route of type /notes/author/authorname/note-id
like this one
![image](https://user-images.githubusercontent.com/20972099/35652158-7959ae62-0708-11e8-8dce-6af809c05358.png)
It is not rendering the contributions
2.The "1023 research notes and wiki edits starting almost 6 years ago" is in accordance with the tag "wetlands"
3.There are the different type of contributors to public lab for a tag. Those who have written notes, wikis or questions and tagged with a tag. Those who have written comments. Those who have answered questions or wiki edits and something like these. Tell me if I am wrong. 
So, even if we show the contributions on basis of tag they should have the possibility to be sorted by wiki edits, comments, etc. 
4. ![image](https://user-images.githubusercontent.com/20972099/35652418-8c467d2e-0709-11e8-96e9-7bb96ab65979.png)
We see the sidebar it shows Recent tags for @author even though there are no tags. That should not be displayed if there are no tags. There should be a message like "There are no recent tags by @author"
5.There are two horizontal lines on the sidebars instead of one that needs to be tackled too.
6.We can  compare the two images and see that the no of research notes and edits are not in the same line for one while they are inline for the other one
7.On the left sidebar, I saw the tags listed. It is showing the tags by the contributor. So, a user will be willing to click on them and want to see @authors contribution to that tag? But it is redirecting to the /tag/tagname. That is the general page for that tag. So, it is breaking the logic.

**Comment by SidharthBansal** [comment]
One more thing.
![image](https://user-images.githubusercontent.com/20972099/35653602-1ceecac0-070f-11e8-867d-7d39c895cd99.png)
this is contributors list for question:gsoc
it is showing all notes. Shouldn't it display wiki, questions, comments like this kind of stuff to know the exact kind of contribution? And should link to the exact portion of text, like for comment then to the comment section??

**Comment by ebarry** [comment]
I believe this entire issue can be closed because an entire new interface with new links has rolled out.
