### ISSUE TITLE
Hyperlink text 

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#2191]
### Please describe the problem (or idea)
![image](https://user-images.githubusercontent.com/20972099/35689820-5bff5186-079a-11e8-918f-89129996c1b5.png)
This the text next to the hyperlink button which is not needed as the functionality is present in the hyperlink button itself

### Please show us where to look
/wiki/:id
https://publiclab.org/wiki/authoring-help

**Comment by jywarren** [comment]
Hi, you know, I like the idea of simplifying here, but I actually also like the actual number appearing so you can see what the ID is on a quick glance. I sometimes copy paste that number! Maybe we could modify this PR so it shows `#1234` instead of `/n/1234`, though, so people can copy paste and use them as references as we do in Github, like #2192 -- what do you think?

**Comment by SidharthBansal** [comment]
Yeah, you are right. We may need it. Actually `/n/1234` made me ambiguous until I saw the code. So thought it will create much more ambiguity to the user of public lab so removed it.
I have changed it to `#1234` syntax. It will not create ambiguity. Please review my pr @jywarren 
Thanks
