### ISSUE TITLE
Research and dashboard urls inconsistencies

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#2301]
### Please describe the problem (or idea)
A user who is logged in can access both research and dashboard page but sees the same content on both pages.
A user who is not logged in sees different contents on both the pages.
A user who is not logged in is able to access the dashboard
> What did you expect to see that you didn't?
A user who is logged in should see the dashboard and a user not logged in should see the research page. In case of user who is logged in and want to see research page should be redirected to the dashboard page. For a user who is not logged in and tries to see the dashboard page should be redirected to the research page.

### Please show us where to look
publiclab.org/dashboard and publiclab.org/research

**Comment by jywarren** [comment]
Hi! This was actually originally by design -- the idea being that the dashboard is something newcomers should be able to preview at `/dashboard` even if not logged in-- and it'd say `This could be your dashboard if you sign up!`

But now that the front page of the site shows an activity feed, maybe this is not needed anymore. I'd like to ask for input from @publiclab/community-reps before accepting this change, though -- thank you!!! 

(Also note that any solution could reduce code duplication by having `def dashboard` run `self.research` in order to actually do the ActiveRecord queries.)

Thanks, all!

**Comment by SidharthBansal** [comment]
Yeah, I have read that line ```"This could be your dashboard if you sign up!"``` but was a little inclined to keep this with the urls which users nowadays have on the other websites
@jywarren I will make the required changes.

**Comment by jywarren** [comment]
Fixed! Thank you!!!
