### ISSUE TITLE
User can like his own research note

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#2383]
### Please describe the problem (or idea)
A person is able to like his own note eg https://publiclab.org/notes/bansal_sidharth2996/02-20-2018/gsoc-proposal-oauth-authentication?_=1519141316 I have liked on own note. 
From my opinion, every person likes his own work. So a person should not be able to like his own research note.

**Comment by SidharthBansal** [comment]
@jywarren @ebarry what do you say?

**Comment by jywarren** [comment]
haha, i do that myself actually, for various reasons, so maybe for now it's
not a bug :-P

you caught me! :-)

**Comment by SidharthBansal** [comment]
Actually I saw your posts liked by you, I catches you there too. 
I am closing this then.
I am having my college mid sems upcoming week so will not be able to do much. As soon as I get time I will do the pending works
Thanks

**Comment by jywarren** [comment]
Ok, good luck with your exams!!!

On Feb 22, 2018 10:08 PM, "Sidharth Bansal" <notifications@github.com>
wrote:

Actually I saw your posts liked by you, I catches you there too.
I am closing this then.
I am having my college mid sems upcoming week so will not be able to do
much. As soon as I get time I will do the pending works
Thanks

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/issues/2383#issuecomment-367896474>,
or mute the thread
