### ISSUE TITLE
emails are not being sent consistently

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#242]
on my own notes, on any notes (i should be subscribed to all) 
Not sure why, i used to get them.

**Comment by btbonval** [comment]
@ebarry Can you try a password reset request?

Don't actually reset your password, just confirm if you can an email.

We've been getting a lot of emails that password reset is broken, but I think it's because email is failing to go outbound sometimes.

**Comment by btbonval** [comment]
Also check your spam folder. <-- required by law to say this

**Comment by btbonval** [comment]
I've been seeing a lot of email traffic on the help list that reset passwords are not being received. I assume it is related to @ebarry 's report that comment emails are not coming.

**Comment by ebarry** [comment]
I have found many messages from do-not-reply@publiclab.org in my spam folder. As i adjusted my filters, gmail popped up this link to "Google's recommended email sender guidelines"
https://support.google.com/mail/answer/81126?hl=en#authentication

Are we following these?

I am waiting to see how long it takes new comments to show up in my inbox, if they do at all, and will report back. If everything begins working i will close this issue.

**Comment by btbonval** [comment]
I have checked my spam folder and found none even when there ought to be an
email in my inbox or spam folder or somewhere. I will keep an eye on my
spam folder for future incursions though. It's definitely not the only
problem.

**Comment by btbonval** [comment]
Ah there are some in my spam folder at this moment, so at least I am
getting some emails now. I'm not sure if we want to tackle the Bulk Sender
Guidelines in this ticket or create a new one. I believe these are two
distinct problems.

For now, I'll simply agree that yeah, we need to address those points. I'm
a little concerned about reverse DNS; that tends to be difficult to manage
when using VPS providers.

**Comment by ebarry** [comment]
All do-not-reply@publiclab.org are now arriving in my inbox. I don't feel like this issue is totally closed because I had to set up a gmail filter to achieve this result that formerly happened without any action needed on my part. But feel free to close this issue if you like.

**Comment by btbonval** [comment]
I added `do-not-reply@publiclab.org` to my contact list so it would not be
spam. I'm certainly back to a high volume. Also, we haven't heard from
anyone saying they are unable to reset their passwords due to no email sent
(which, btw, many had checked their spam folder at the time).

I don't like that this ticket's primary issue has mysteriously resolved
itself. I don't feel comfortable closing this unless Jeff or Kep or someone
can confirm they actually did something to fix this problem.

I guess the other problem can stay here to cuz whatever it's here.

**Comment by jywarren** [comment]
Hmm, wasn't the resolution just that they were going to the spam folder?

**Comment by btbonval** [comment]
Not in the past. When I finally stopped getting the emails, that was the first place I checked. When people emailed me saying they weren't getting their password reset links, they would confirm nothing in spam folder.

We have two problems being confounded.

**Comment by btbonval** [comment]
At some point I did start getting the emails again, but they were going straight to my spambox (which I found out yesterday).

**Comment by Nataliegurl** [comment]
Hmm, is there any way to pinpoint when they stopped and started?

**Comment by btbonval** [comment]
Unfortunately I have no good way to track when missing emails started and stopped due to the conflation of the spambox issue and the nature of the spambox deletion policies. Whenever the emails started coming back in again, they were getting spammed and deleted later, so I am missing a history to nail down a timeline.

This seems to be largely a non-issue now. I'm going to close the ticket, as I don't see missing obvious missing emails via the subscription to all research notes.
