### ISSUE TITLE
support site-wide notifications via the database

### ISSUE THREAD

**Issue by btbonval** [publiclab/plots2#243]
Have some area in the database which contains site-wide messages. If any are present, the messages should be displayed somewhere near the top of the page.

This should probably make use of https://github.com/publiclab/plots2/blob/master/public/assets/js/alerts.js

**Comment by jywarren** [comment]
I just implemented something like this, with template syntax `<%= feature('feature-title') %>` to display the contents of a "feature" which is a DrupalNode of type=feature. Admins only. Will also start the process of abstracting out branding or PL-related text so that other organizations or projects can use this codebase!

**Comment by jywarren** [comment]
And features listing at http://publiclab.org/features

this is going live shortly

**Comment by jywarren** [comment]
Adding a new Feature called "sitewide-alert" which appears at top of page. Default is empty as in other Features.

**Comment by jywarren** [comment]
You can now paste

````html
<div class="alert alert-success">Hello world!</div>
````

into a Feature called "sitewide-alert" and it'll show on every page. Yay!
