### ISSUE TITLE
header images are different heights

### ISSUE THREAD

**Issue by Be-ing** [publiclab/plots2#2597]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

The content on the [PublicLab homepage](https://publiclab.org/) moves as the header images are cycled because they are not all the same height.

> What did you expect to see that you didn't?

I expected the content below the header images to remain in place. Instead it moves up and down as I read it.

### Please show us where to look

https://publiclab.org/

### What's your PublicLab.org username?

none

> This can help us diagnose the issue: 

Scroll below the top image on the front page and wait.

### Browser, version, and operating system

Firefox 59.0.2 on Fedora 27

**Comment by waqargithub** [comment]
I am looking to work on my first open-source contribution. I think this would be a suitable fto candidate. If you all agree then I can take this one.

Waqar

**Comment by waqargithub** [comment]
I thought it might be an JavaScript/HTML/CSS matter it seems that the HTML/CSS is generated by the Ruby code below:

```
plots2/app/views/home/home.html.erb:

<% cache('feature_home-carousel', skip_digest: true) do %>
  <%= feature("home-carousel") %>
<% end %>
```

Using Chrome Developer tools I was able to track down the generated HTML (with inline CSS) and see that the image height ranges between 178 px to 216 px. Some possible remedies:

1. See if we can tweak the code that generates the HTML or CSS to clip the images.

2. The images could be resized/cropped to have the same height.

Waqar

**Comment by pdurbin** [comment]
@waqargithub thanks for opening this issue. I was about to create one myself because I find it very strange how the text on the Public Lab homepage moves up and down while you're trying to read it because of how the images at the top are different sizes. I made a little video (sped up quite a bit) to demonstrate the problem:

![publiclab](https://user-images.githubusercontent.com/21006/38768789-dbd2b51a-3fc6-11e8-82dc-c5ffc3a24622.gif)

(For the hackers, with this: `ffmpeg -i original.mov -filter:v "setpts=0.04*PTS" -loop 20 -pix_fmt rgb24 output.gif`)

It's an especially strange user experience when you scroll down and notice that the text is moving up and down while you're trying to read it. At first I didn't realize why but then I scrolled back up and saw that the images at the top of the page were the culprit.

I agree with option 2 for now. Let's just crop the images to be all the same height. There are only a handful of them.

**Comment by Gauravano** [comment]
hi @waqargithub @pdurbin, agree with you guys to fix the size of the image container. @publiclab/ community-reps what do you think about the idea? Thanks, @Be-ing for opening the issue.

**Comment by sukhbir-singh** [comment]
In my opinion, the most important thing here is to fix the height of div having class="slick-list draggable", which is presently changing its height according to the image.  

I did some google for this and finds an open source library called "better-simple-slideshow" useful here. You can see the [demo](http://leemark.github.io/better-simple-slideshow/) of this library.

Slideshow demo link: http://leemark.github.io/better-simple-slideshow/
Github link: https://github.com/leemark/better-simple-slideshow

**Comment by waqargithub** [comment]
I do think cropping or resizing the images is the simplest fix since it requires no change to code and there are only 4 images.

Changing the code to control the size of the div might be the more resilient fix since it would avoid any change in behavior if new images are added in the future.

I am seeing support for both ideas but it seems there is more support for resizing the div. I am checking for explicit agreement about which option to take.

Either way, I am happy to tackle this problem. If we go the route of changing code, is there an individual from the project I can work with for any questions?

Waqar

**Comment by patcon** [comment]
Seems we use the Slick carousel, which already has a way to turn this on-off during carousel instance initiative, using `adaptiveHeight`. Example here: http://kenwheeler.github.io/slick/

But the code for the carousel itself seems to be in the database as a ["feature"](https://github.com/publiclab/plots2/blob/master/doc/DATA_MODEL.md#features). I'm not totally familiar with the plots2 codebase, but maybe on the way to addressing this, we could move some of the carousel code into the codebase, so that it's possible to scrutinize and be adjusted by folks other than website admins? :)

But yeah, I think this is an easy fix (assuming `adaptiveHeight: false` helps choose a good minimum height), that can currently only be done by a PL admin.

**Comment by jywarren** [comment]
Great work here, many thanks! I found the options for the slideshow when
used together were a bit buggy, so disabled fixed height to get it working.
But maybe more fiddling could help. I agree though that just making all
images same height is an easy fix! If anyone wants to upload them here or
to http://publiclab.org/sandbox I can update the URLs, thanks a LOT!!

**Comment by waqargithub** [comment]
I can make the images the same height so that we'll have an immediate and simple fix. If we want to make a change to the code eventually then that option still could happen in the future.

**Comment by jywarren** [comment]
that sound fantastic, thank you!!

**Comment by waqargithub** [comment]
I have resized the 5 images so that they all have the same dimensions.

My original plan was to find them in code, modify them, and then submit them via a PR. 

I was not able to find the images in the code. I wondered if they are kept in a database and so simply downloaded them from the website. I have attached the cropped/resized images to this post. Please let me know if it is possible to submit them via a PR and if that is preferred.

Waqar

![oil-testing-matej_1798x641](https://user-images.githubusercontent.com/5306998/38959885-f5b62ee4-4327-11e8-9599-7fb3a2197279.jpg)
![img_20160709_181427_1798x641](https://user-images.githubusercontent.com/5306998/38959894-fc247ff6-4327-11e8-8582-6d676b1f590d.jpg)
![gowanus_1798x641](https://user-images.githubusercontent.com/5306998/38959903-053ca9ec-4328-11e8-8e08-0d024d5e040e.jpg)
![fanboat-narrow-2_1798x641](https://user-images.githubusercontent.com/5306998/38959912-0dce8a30-4328-11e8-9dab-37776859f553.jpg)
![beach_1798x641](https://user-images.githubusercontent.com/5306998/38959917-1287a87c-4328-11e8-8fea-0e3dc24982fe.jpg)

**Comment by waqargithub** [comment]
Sure, no problem. I have attached a new set of images resized to 1200 px wide. They are all 231 kB or less.

Waqar

![beach_1200x427](https://user-images.githubusercontent.com/5306998/39063452-cc5b503c-4490-11e8-8115-b5d792e857c0.jpg)

![fanboat-narrow-2_1200x427](https://user-images.githubusercontent.com/5306998/39063462-d4716b12-4490-11e8-9069-fb9941ffc059.jpg)

![gowanus_1200x427](https://user-images.githubusercontent.com/5306998/39063469-da9da820-4490-11e8-84b4-1cd6bc7960cb.jpg)

![img_20160709_181427_1200x427](https://user-images.githubusercontent.com/5306998/39063488-e2997bee-4490-11e8-8db5-0f6f9c5007a3.jpg)

![oil-testing-matej_1200x427](https://user-images.githubusercontent.com/5306998/39063500-e84f791c-4490-11e8-8448-2bb5ce12354f.jpg)

**Comment by jywarren** [comment]
Perfect! Uploaded and complete. Thanks everyone for your help with this!!!
