### ISSUE TITLE
Parsing of markdown (formatting) of answers and comments is broken

### ISSUE THREAD

**Issue by Fastie** [publiclab/plots2#2604]
Formatting of answers to questions and comments on answers ignores line breaks and paragraph breaks and does not display images or make urls hot.

https://publiclab.org/questions/nshapiro/03-27-2018/what-data-logger-will-work-with-my-portable-hcho-meter#answer-927-comment-19332

https://publiclab.org/questions/JLJ/04-09-2018/calculating-ndvi-using-pinoir-camera-and-blue-filter

### What's your PublicLab.org username?

cfastie

### Browser, version, and operating system

Chrome, windows

**Comment by jywarren** [comment]
Thanks Chris! This was due to the Rails 4.2 upgrade, which changed string
sanitizing unexpectedly. I'm working on a fix but struggling a bit. Update
soon!

On Apr 9, 2018 6:32 PM, "Fastie" <notifications@github.com> wrote:

Formatting of answers to questions and comments on answers ignores line
breaks and paragraph breaks and does not display images or make urls hot.

https://publiclab.org/questions/nshapiro/03-27-2018/what-data-logger-will-work-with-my-portable-hcho-meter#answer-927-comment-19332

https://publiclab.org/questions/JLJ/04-09-2018/calculating-ndvi-using-pinoir-camera-and-blue-filter
What's your PublicLab.org username?

cfastie
Browser, version, and operating system

Chrome, windows

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/issues/2604>, or mute the thread

**Comment by jywarren** [comment]
Very close now... lot more changes than I'd thought when i started the fix... but also adding tests to detect breakages in this set of functions in the future. We could use some code cleanup on comment/answer body rendering, but once we have the tests, this will be easier to do while knowing we haven't broken the overall behavior. I've added unit and functional tests.

**Comment by Fastie** [comment]
The tags displayed after research notes and questions no longer link to a search for that tag. Is that part of the same problem or is that a feature?

**Comment by jywarren** [comment]
Hi, Chris - are you seeing a "popup" when you click the tags? If not,
that's a bug. If yes, but you still can't get to the tags page, that's
probably an oversight, and a good catch. Either way, a little extra detail
will help us tackle that too -- should be a small tweak.

**Comment by Fastie** [comment]
The popup includes a link to the profile of the user who created the tag (not sure why anyone would want that), a link to "follow" the tag (don't want more emails), and a link to a list of users who have used the tag (fun, but not a great way to find related content).  There is no link to all the research notes tagged with that tag (the thneeds that everyone needs).

**Comment by Fastie** [comment]
Also, it seems that most of the users in the list of contributors to the tag have never posted anything with that tag.

**Comment by jywarren** [comment]
Hi Chris, could you open an issue for "explanation for contributors list" ?
There is recently improved logic in this and we ought to make an
explanation link on the contributors page.

As to the links, you're right there are a few missing/merged. I'll try to
submit a fix but if I don't get to it today could you open an issue for
that too? I think "# notes" is supposed to link there.
