### ISSUE TITLE
non urgent: inconsistencies on count of Likes VS list of Likers on notes/wikis

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#2656]
### Please describe the problem (or idea)

> What happened just before the problem occurred? 

The number of Likes seems to flickr upon page reloading. I observed it yesterday on publiclab.org/evaluation, but actually can't reproduce what i documented in this video today: 
https://publiclab.org/system/images/photos/000/024/696/original/like_count.mov

Perhaps you can see it on a wiki page like https://publiclab.org/balloon-mapping. Try reloading the page and watching the Like count, and then seeing how many names are listed when you click the expanded view.

**Comment by etalamante** [comment]
Hello, I'm starting as a contributor and I would like to work on this issue. Just give me a few days to analyze and solve it.

**Comment by jywarren** [comment]
Awesome, thanks so much!

**Comment by etalamante** [comment]
Excellent, I will check them. Thanks!

**Comment by etalamante** [comment]
I checked the code and I was able to replicate the likes count to flick.

What I discovered was that, there are 2 different ways to display the likes count:

- first is by render the json created on the [like](https://github.com/publiclab/plots2/blob/master/app/controllers/like_controller.rb) controller (line 14)
- the second is displaying the count of likers on the [like](https://github.com/publiclab/plots2/blob/master/app/views/like/_like.html.erb) view (lines 19 and 23)

They are both used and what they differ is in how they treat moderated users. The former includes moderated users, whereas the latest doesn't. And, regarding the names listed on the expanded view, they don't include moderated users, as they used the latest method. The app first uses the latest method and, when the pages loads, the former method is executed.

You can replicate the error by using 2 sample users (they could be "user" and "moderator")  to both like one of the posts, then the "moderator" changes the "user" status as "moderated" and then you would see the like count to flick on each reload. 

I have a solution for both situations, but I would like you to tell me how do you want to treat moderated users, by including their likes on the count or exclude them?

Once I get that answer, I would only need to write a test to replicate the bug and another one to test the solution, so that I can open a PR.

**Comment by jywarren** [comment]
Wow this is such a thorough investigation! Thanks!!

We don't want to show moderated users. But I have an idea to try and
simplify things.

Could we wire both queries through the same code so that they work
identically and we don't have to maintain two? What do you think?

**Comment by etalamante** [comment]
Yes, we could use the same method to get the like count on the view and implement that on the controller. I run the app and it worked. Both moderated and banned users will be excluded from the like count and the expanded view. Correct? 
I added two tests, one to replicate the bug an another to prove the method seen on the view works. If you don't have any problem with that, I will open the PR.
