### ISSUE TITLE
Comment previews are blank

### ISSUE THREAD

**Issue by dbeavers** [publiclab/plots2#273]
I wrote a note and published it.  I then came back and edited it.  Everything was fine until I then did a preview.  The text then disappeared.  The rest of the page looked fine, just the text block was empty.

**Comment by dbeavers** [comment]
Further:  After the above I opened the Github issue from the same browser tab.  When finished I realized that was a mistake and did a couple of backs to get to the note page that had not had the second publish, it still had not been published.  It appeared that I lost my edits until I selected edit again and the second set of edits were present.  This is unexpected behavior that is a bit disturbing at first.

**Comment by jywarren** [comment]
Hi dan - I'm not sure if its standard to expect a form to function properly on returning to it via the back button, but perhaps we could make this possible by having the page poll the last edited time from the server and prompting a refresh if it does not match?

**Comment by btbonval** [comment]
This is almost entirely handled by the browser.

I believe we've discussed supporting drafts with folks like @dwblair , where the content is periodically saved to the server. However, 1) I cannot find those tickets and 2) the browsers tend to manage this in their own way, so with limited programmer resources available, we shelved the draft idea.

**Comment by btbonval** [comment]
I see the problem is related to using the back button and publishing to a published note, but I think it is still related to the concept of saving drafts periodically to the server. If we support that, then this sort of back button behavior would likely be no problem, since publish would take on a new meaning.

**Comment by dbeavers** [comment]
Perhaps you got caught up in my second comment and did not fully appreciate my first one or I don't understand fully what yall are saying?  There was no back button pressed in the first scenario.  A day or two later I again opened the note to edit it, after it had been published, and  the symptoms appeared.

**Comment by btbonval** [comment]
Ah. "Then I came back" sounded immediate and as though the back button were
used. Thanks for the clarification.

**Comment by jywarren** [comment]
Well, either with back button or in returning or editing a page, polling
the server for last edit date could give UA an opportunity to refetch the
latest text, right?

**Comment by btbonval** [comment]
Technically the browser does that already. If the page has not updated, the
server should tell the browser so by sending a 304 not modified.

Since rails does not do that, and send 200 ok with contents, the browser
always assumes the page content is new.

Instead of sending a date, it would be better to use http built into the
browser by sending the appropriate http codes.

**Comment by dbeavers** [comment]
So, are either of you able to reproduce the first scenario?

**Comment by btbonval** [comment]
@dbeavers I have not tried to duplicate the problem yet.

When you say the text disappears, does it only disappear from the preview? Is the published note affected in any way?

Does the problem persist? By that I mean, if you edit the same note again today and click preview, will the text disappear?

If you're willing to share, could you link the note? On the off chance that the problem is specific to that note (or is not a generally reproducible problem), it might help for us know which note can reproduce the problem reliably.

**Comment by dbeavers** [comment]
http://publiclab.org/notes/liz/04-06-2015/5th-anniversary-call-for-memories is the note and my comment is the one I am talking about.  It still happens for me.  The published note is just fine.

**Comment by jywarren** [comment]
And just to be extra clear, its only the preview and not the raw markdown
that's affected, or did I misunderstand?

**Comment by dbeavers** [comment]
Not clear on "not the raw markdown".  The field is blank when previewed but fine when editing or published.

**Comment by jywarren** [comment]
Ah, it's a comment, not a post. Great, thanks. We should also treat the following as a separate issue:

> When finished I realized that was a mistake and did a couple of backs to get to the note page that had not had the second publish, it still had not been published. It appeared that I lost my edits until I selected edit again and the second set of edits were present. This is unexpected behavior that is a bit disturbing at first.

This is still related to a comment, right? But this one did occur after the back button had been pressed, a I understand.

**Comment by jywarren** [comment]
Confirmed; comment previewing of already-posted comments after clicking the "edit" button seems to be broken:

![image](https://cloud.githubusercontent.com/assets/24359/7235946/9e43817e-e75f-11e4-86bf-7f855e3c5a3e.png)

**Comment by jywarren** [comment]
````js
$('#c11515preview').toggle();$('#c11515text-input').toggle();$('#c11515edit .preview-btn').button('toggle');$E.preview('c11515preview',$('#c11515text-input').val())
````

causes "object is not a function" when clicking preview.

**Comment by jywarren** [comment]
Specifically it's part of `$E.preview()`

**Comment by dbeavers** [comment]
Yes, second issue is on a comment.
