### ISSUE TITLE
question:tag not showing up on question tag pages

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#2778]
Hi, 
I was searching for a question I had posted recently, it was one I knew I tagged "question:raingauge" but when I went to the tag page:  https://publiclab.org/questions/tag/raingauge, there were no questions there. I found my question, it does have that tag, but I couldn't get it to show up on the tag page until I tagged it with not just the "question:raingauge" but also just the tag "raingauge".   Can someone check and make sure that when we use the "question:**" tag that it also shows up on the tag page for it?

Thanks!
-Stevie

**Comment by Gauravano** [comment]
hmm, I tried the tag, if the tag on a question is named as `question:raingauge` then, for finding questions related to it https://publiclab.org/questions/tag/question:raingauge have to be used. The power tag here plays it's role by showing the questions related to question:raingauge instead of showing research notes by default. Note the difference in between these two https://publiclab.org/tag/question:raingauge and https://publiclab.org/tag/raingauge . Is the above issue resolved? Also, my explanation is based on knowledge of power tag  `question:____` I have from https://publiclab.org/wiki/power-tags . Thanks.

**Comment by jywarren** [comment]
Could we modify the behavior so that the page returns both results for `raingauge` and `question:raingauge`? I often feel like i need to type in both when i tag things. This could avoid that... 

Another way to do this would be to make any new tag `question:raingauge` also auto-generate a `raingauge` tag in the `tag_controller#create` method. This could also be run in a migration against all existing `question:_____` tags... what do you think?

**Comment by Gauravano** [comment]
Yes, we can solve it by both the ways. I am fine with both , with which way should I solve ? Thanks.

**Comment by jywarren** [comment]
I guess I prefer the second way - auto-generating the tags, and running that in a migration too (so 2 parts). Thank you, Gaurav!

**Comment by Gauravano** [comment]
Great, implementing the second one. Thanks.

**Comment by steviepubliclab** [comment]
Ah actually I'm looking at this right now and I prefer the first option.

**Comment by Gauravano** [comment]
Cool! I am fine with both ways. Thanks.

**Comment by steviepubliclab** [comment]
Sorry, just wanted to jump in there fast before you started! 
Here's an example of why I'm interested in option 1: I'm starting a new project page here:
https://publiclab.org/wiki/pensacola-stormwater-project

and if we add the tag "stormwater-pensascola" on all the questions related to that tag, then those questions also show up in the "updates" section on that page. To keep that section clean, I'm only adding "questions:pensacola-stormwater" to the questions on that topic. :) Soooo if the pages on the

https://publiclab.org/questions/tag/pensacola-stormwater captures "question:pensacola-stormwater" and those that are "question" and "pensacola-stormwater" then it won't change the update section on the project page :). Does that sound right? Make sense?

**Comment by Gauravano** [comment]
yes, it does sound right. Thanks for details :smile: !

**Comment by Gauravano** [comment]
hi @steviepubliclab , I have raised a PR for this issue in #2864. the new query system for tags will work something like this- if the tag present in nodes are "computer" or "question:computer" then, it will also search the other one. I guess it will serve the purpose. Thanks.

Here's new working demo:-

![output_tag](https://user-images.githubusercontent.com/20878070/41648644-1f649c6c-7497-11e8-8934-877b2b52a734.gif)
