### ISSUE TITLE
Bots vs Humans

### ISSUE THREAD

**Issue by siaw23** [publiclab/plots2#2793]
Until recently I didn't consider contributing to OS projects. But when I started I stumbled on Public Lab's Plots2 and found a Rails project with room for a lot of contribution. Initially I didn't want to really contribute to Plots2 because I found the README to be 'unfriendly' for newcomers, it was long and had steps like "optional (not recommended)". There were a couple of those steps. The README is very important for new comers to a new project. Making it concise and friendly and straight to the point is necessary to get in more people as possible. So I thought, if something is 1. options and 2. not recommended, why include it. They might confuse people new to coding, if not why the bloat?

That aside I saw Plots2 is adding more and more bots. Then again I thought, maybe this is not the right direction. Why bots, when contributors know they are bots anyway. How lazy are we to response and uniquely welcome anyone interested in contributing to our project, I thought. Then I saw [this blog](https://mikemcquaid.com/2018/06/05/robot-pedantry-human-empathy/) posting talking about bots and Open Source and *Empathy* so I thought I'd share we you, we get rid of some bots, especially those "welcoming" ones and get ourselves more involved with interacting with people just for the sake of empathy and to show we're ourselves showing a sign that we care about our project and what we're doing. 

The biggest projects on GitHub for example have at most 1 bot! Please check how many bots the Rails projects itself has, come back and compare how many bots are on Plots2. Then find another successful, big OS project and counts its bots, you'll almost always count 0 or at most 1. "Welcoming bots" are not welcoming at all and I would like your thoughts and opinions on this. Everyone @publiclab/reviewers @publiclab/soc @publiclab/community-reps

**Comment by jywarren** [comment]
Hi @siaw23 -- thanks! I think my initial thoughts are that I 100% agree with the point that real human welcoming is irreplaceable. There's no bot that can extend a hand out and make someone feel welcome the way a human can.

However, lots of systems -- from GitHub interface design to Travis tests -- are not very friendly. I do think it's worth exploring how we can reform systems like these to be friendlier, because they aren't doing enough to encourage newcomers, and that's a real thing!

Finally, I do think we're being a bit experimental vs. other (bigger) open source projects, but we are also more welcoming -- by a long shot -- than most other open source projects out there. I'm not saying more bots is the answer, or even that we shouldn't reduce bots to find a balance, but just that we are quite different than the "usual" out there, and if we find that bots help us be more welcoming, I don't have a problem with that!

That said, if we are relying a lot on bots to take up the real human welcoming tasks, we should definitely recommit to truly extending a welcoming supportive hand to people who show up to pitch in. 

Thanks so much for your considerate thoughts! 🙌 👍 ❤️

**Comment by pdurbin** [comment]
> I found the README to be 'unfriendly' for newcomers, it was long and had steps like "optional (not recommended)"

If I go back in time I can see what you mean at https://github.com/publiclab/plots2/blob/a526639c572e406e0f2d5c158f5e21b530e1631c/README.md#installation but thankfully this has been fixed. No more bloat. We could open an issue at https://github.com/LappleApple/feedmereadmes to get some feedback on the README in its current form. I got some good feedback on a project I work on at https://github.com/LappleApple/feedmereadmes/issues/26

https://mikemcquaid.com/2018/06/05/robot-pedantry-human-empathy/ was a good read. Thanks for linking to it.

@siaw23 what do you see as the definition of done for this issue? Should we enumerate and evaluate the bots?

By the way, if anyone reading this hasn't already seen https://media.libreplanet.org/u/libreplanet/m/sharing-strategies-for-welcoming-newcomers-into-floss-projects-first-timers-only-list-moderation-and-more/ by @jywarren and @ebarry I highly recommend it! The slides are at https://publiclab.org/notes/warren/03-22-2018/libreplanet-talk-sharing-strategies-for-welcoming-newcomers-into-floss-projects-first-timers-only-list-moderation-and-more and slide 41 is where there's some discussion of friendly bots.

**Comment by siaw23** [comment]
i wouldn't request for a change with bots if others don't agree or have thoughts. so let's close this for now :)
