### ISSUE TITLE
Auto-complete of search not working on 'post' page

### ISSUE THREAD

**Issue by Souravirus** [publiclab/plots2#2795]
### Please describe the problem (or idea)
The auto complete is not working on search input on https://publiclab.org/post page
``
We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.
``

**Comment by rohancl** [comment]
Hey, can I have a link to .html file that is being loaded on https://publiclab.org/post ?

**Comment by jywarren** [comment]
Should be at /app/views/editor/rich.html.erb -- hope that helps!!!

On Nov 15, 2018 5:09 PM, "Rohan Singh" <notifications@github.com> wrote:

Hey, can I have a link to .html file that is being loaded on
https://publiclab.org/post ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/issues/2795#issuecomment-439208311>,
or mute the thread

**Comment by rohancl** [comment]
Hey @jywarren , Can you tell me how you see that, It has been a problem for me to locate the files that are being loaded :/

**Comment by kevinzluo** [comment]
Hi @rohancl .
I believe you should first check config/routes.rb, which tells you which controller each link goes to. In this case on line 268 and 269 you can see that post goes to editor#post. 
Then you can go find the controller under app/controllers, and in this case it is editor. Within the controller you can see under post, unless some conditions are met, it will call rich, meaning rich.html.erb should be loaded.

This is what I have learned so far. Hopefully it is helpful, but some of it may be wrong.

**Comment by rohancl** [comment]
Got it, thanks @kevinzluo

**Comment by rohancl** [comment]
<h1>Problem in contributing</h1>
Hey @jywarren @kevinzluo ,
I have completed the task, but I still think I need some help here,

![bruh 3](https://user-images.githubusercontent.com/29266591/48590912-6e865200-e967-11e8-9505-684375d1bcdd.gif)

<h2>What I did</h2>
I checked the links, and found that the code in post.js which contains the code for auto- completion of the search bar isn't actually linked to the post page. (or to rich.html.erb)
And also that it is dependent on typeahead.jquery.js to function properly/
So, I checked for the typeahead.jquery.js (located in /public/lib/typeahead.js/dist/typeahead.jquery.js) <b>[NOTE: The /public/lib folder is present here, but not on this repository] </b>script tag in rich.html.erb
and I got the link

![bruh](https://user-images.githubusercontent.com/29266591/48590331-151d2380-e965-11e8-8559-d839f74cc093.png)

<b>1</b>: Now, I copied and pasted the code of post.js into the starting of typeahead.jquery.js (along with the pre existing code) 
<b>2</b>: The auto-completion was now working ...
<h2>The Problem</h2>
<b>There is no such file as /public/lib in this repository. So where do I commit my code ?</b>
<h2> What I tried doing, but failed</h2>
I did notice that the /public/lib folder is created only if you install plots locally on a machine and thus it's not on this repository, So I thought instead of editing typeahead.jquery.js, I could move post.js in /public folder and directly link it to rich.html.erb like this:

![bruh 4](https://user-images.githubusercontent.com/29266591/48592168-2e29d280-e96d-11e8-825b-d7fd058c204a.png)

I also did notice that post.js requires the typeahead.jquery.js file for proper function,

![bruh 3](https://user-images.githubusercontent.com/29266591/48592063-acd24000-e96c-11e8-8ebc-76f7f5d7e13f.jpg)
And, So I copied and pasted the code of typeahead.jquery.js into post.js and kept typeahead.jquery.js as it was earlier.
Then, I tried running the files of localhost , the post.js is linked to rich.html.erb as well but, The auto-completion didn't happen.
This is very strange and I'm a bit confused.
<b> If I put the same code in the typeahead.jquery.js file, it works.
But, If i Put the same code in another js file that I've linked, nothing happens</b>
Mentors, please explain in detail. Thanks ^.^

**Comment by rohancl** [comment]
@jywarren  Please help.

**Comment by Souravirus** [comment]
Hi @rohancl, the `public/lib` folder is used for installation of packages of yarn and since we don't want the main repository to contain such packages, we put public/lib in `.gitignore`. This is the reason why you don't see public/lib in the repository. Now the problem is that you want to connect typeahead.jquery.js to a file. You can do that by writing this line in app/assets/javascript/application.js `//=require typeahead.js/dist/typeahead.jquery.js`.
Thank you!!

**Comment by rohancl** [comment]
I could not understand this completely, can I edit typeahead.jquery.js anywhere on this repository ?

**Comment by rohancl** [comment]
so we are linking a js file inside a js file right ?

**Comment by rohancl** [comment]
That means I can bring typeahead.jquery.js into post.js by typing in: //=require typeahead.js/dist/typeahead.jquery.js . right ?

**Comment by Souravirus** [comment]
Yeah that's what you have to do

**Comment by rohancl** [comment]
I did but it's not working,
I have post.js in my public folder and I have imported it in rich.html.erb like this:
![posto](https://user-images.githubusercontent.com/29266591/48661654-89f27980-ea9b-11e8-87a6-cb2438cc16e4.png)

I checked reloading the post page, the post.js is linked (i tested it with an alert box)
Then, I pasted the require code you gave me in post.js 

![req](https://user-images.githubusercontent.com/29266591/48661655-8a8b1000-ea9b-11e8-99d8-79b10379aa2d.png)


reloaded the page, the dropdowns didn't come :/

**Comment by Souravirus** [comment]
I dont understand why you are keeping anything in public folder. I think it should be kept inside `app/assets/javascript` folder.

**Comment by rohancl** [comment]
that was because I could not link the file anywhere else i tried writing:
../app/assets/javascript/post.js
but it gave me a warning

![screenshot from 2018-11-17 19-24-16](https://user-images.githubusercontent.com/29266591/48661835-65e46780-ea9e-11e8-95da-013bfdbaa1b9.png)

I know I am probably doing something dumb, Please help @Souravirus

**Comment by rohancl** [comment]
Yeah sure, wait a moment....

**Comment by rohancl** [comment]
Oh sorry I forgot to commit the application.js part, but I have it updated in my localhost.
I've added the spaces too, still... not working

**Comment by Souravirus** [comment]
What's the error now?

**Comment by rohancl** [comment]
<h2>ERROR: I cannot link the post.js file</h2>

![bru](https://user-images.githubusercontent.com/29266591/48662430-f6737580-eaa7-11e8-9311-c1f93ebf05f8.png)
<h2>
Here are the addresses of my main files in plots2:</h2>
<b>
post.js: </b><i>app/assets/javascript/post.js</i>
<b><br>
rich.html.erb: </b><i>app/views/editor/rich.html.erb</i>
</b>
<h2>
 Updated code in post.js:
</h2>

![bru](https://user-images.githubusercontent.com/29266591/48662512-f6c04080-eaa8-11e8-9f7e-8e2b10fa9f02.png)
<h2>  Updated code in rich.html.erb: </h2>
<b>*look at the last line*</b>

![kiu](https://user-images.githubusercontent.com/29266591/48662523-1eafa400-eaa9-11e8-99a2-dc679593f95c.png)

**Comment by rohancl** [comment]
Also, along with the linking error in the inspect element tab, I am getting this too:

![newerr](https://user-images.githubusercontent.com/29266591/48662569-c3ca7c80-eaa9-11e8-8578-2d63665e5407.png)
 Tell me if it's a problem, because as far as I know, this is an outsource

**Comment by jywarren** [comment]
Aha! Cool you are making progress here.

The public url route will be /lib/... Instead of /app/assets/ which is the
internal system path.

Or lib is for yarn dependencies. Actually there is a JavaScript method that
rails supplies... Let me find it...

**Comment by jywarren** [comment]
Here:

<%= javascript_include_tag "post" %>

In this, the root will refer to anything in /app/assets/javascripts/

But I didn't think the post js file was related to auto completion.  So
maybe this isn't needed and you need to find why jQuery autocompletion is
not loaded in the rich editor?

I definitely see it in the first few lines of this file already -
https://github.com/publiclab/plots2/blob/master/app/views/editor/rich.html.erb

**Comment by rohancl** [comment]
Hey thanks for replying @jywarren 
SO, that means there is no need to link post.js into rich.html.erb ? 
and also that the js file with autocompletion is already linked :fearful:

**Comment by rohancl** [comment]
Hey @jywarren ,
If I have to contribute to the typeahead.jquery.js file in this repository. Is it possible to find it somewhere ?
thanks ^.^

**Comment by rohancl** [comment]
Hey @Souravirus  @jywarren , Is the file that has autocompletition code already linked to rich.html.erb ?

**Comment by rohancl** [comment]
@jywarren  Can i edit typeahead.jquery.js anywhere on this repository ?

**Comment by oorjitchowdhary** [comment]
Is this task already done or picked up by someone?
If not, I'd like to solve it

**Comment by jywarren** [comment]
@rohancl yes it is - see the top few lines of `rich.html.erb` -- you can see it included in there. 

@oorjitchowdhary -- maybe you could help @rohancl take the next step on this one?

**Comment by JonathanXu1** [comment]
I saw this task was free and claimed it. Can I work on it?

**Comment by Souravirus** [comment]
Yeah sure @JonathanXu1

**Comment by kevinzluo** [comment]
Hello. I am very confused currently. 
**I saw this task open this morning and claimed it.** 
Is there anyone else with this task claimed currently on GCI? Is it possible that it has been duplicated?

On a side note, I believe the issue is a result of the inclusion of typeahead.jquery.js, which is changing the properties of the search field, here:
https://github.com/publiclab/plots2/blob/ba053502ded9ec0163af90d3d7a4cb3eb2a4b74e/app/views/editor/rich.html.erb#L7.

When I check the documentation it seems to only be a "standalone UI view", so I do not think it is actually essential to the tags module which still works once I remove it.

![autocompleteonpost](https://user-images.githubusercontent.com/44309027/48992708-e8080800-f0fe-11e8-9e5f-beb64f83846a.gif)

If no one else has this task currently claimed on GCI, I will submit a PR tomorrow with more detail on my findings.

**Comment by Souravirus** [comment]
Hi @kevinzluo, this issue is currently available as it is abandoned by 2 students. So, you can surely submit a PR to address this issue. Thank you!!
