### ISSUE TITLE
Need to start mailman server process in order to fetch incoming mail

### ISSUE THREAD

**Issue by icarito** [publiclab/plots2#2878]
### Please describe the problem (or idea)

In #2669 we merged functionality for incoming email. We've configured this, but now we need to start an independent process that does the mail fetching. 

@namangupta01 mentioned this:

> We just have to write the configurations in https://github.com/publiclab/plots2/blob/master/script/mailman_server and then we can start the mailman server which is an incoming mail server which will automatically do the work for us.
We only have to write the proper configurations of the email id which will going to receive all the mails.

So now we need to add a container to `containers/docker-compose-*.yml` where we define by code what processes / containers run in staging and production.

@namangupta01  We'll appreciate your help in defining the command that needs to be run - similar to how it was done for Sidekiq (see docker-compose files)

Thanks in advance!

**Comment by jywarren** [comment]
I believe the command is `ruby script/mailman_server` -- right? 

Hi @icarito can you show an example of how it should be formatted? Would it look like this, but instead of `web` we'd call it `mailman`?

https://github.com/publiclab/plots2/blob/950539c8e7f89bfd5761616e6458adb804ae293b/containers/docker-compose-stable.yml#L18-L20

**Comment by jywarren** [comment]
Ah, @namangupta01  did this! 

https://github.com/publiclab/plots2/pull/2823/files
