### ISSUE TITLE
Use MySQL on development and production?

### ISSUE THREAD

**Issue by stefannibrasil** [publiclab/plots2#3170]
@milaaraujo and I were having some errors on travis even having our checks all green locally. We asked our coaches to help us and we were able to fix the error (#3134). We were doing full text search, to give more context.

The problem was that locally, we were using SQLite3 and travis uses maria db, so the query was not returning the same results.

Is it possible to have a unique and consistent database type for development and production? What do you think? We believe this may improve the future contributions for the project :)

we found some links that might be useful for this [here](https://stackoverflow.com/questions/29743444/rails-databases-why-use-same-dbms-for-development-and-production) and [here](https://medium.com/@amliving/rails-db-lesson-learned-e416e2f2549c).

**Comment by jywarren** [comment]
aha - sorry, i should've caught that! Hmm, so we've traditionally used
sqlite because it's such an easy install (by default already available on
Macs, I think?) but this has come up before, and I agree it's a frustrating
issue.

I wonder if we could think about how to remind ourselves about the database
differences - so when this does happen, there's some clue to what's
happening... i don't know, do you think there's an approach like that which
could work?

But i'm not set on either way, i just want to think through this carefully.

**Comment by stefannibrasil** [comment]
I added this to the Testing docs file #3483
