### ISSUE TITLE
Pagination is broken in home page

### ISSUE THREAD

**Issue by arteteco** [publiclab/plots2#3301]
Hi all,

That'show to reproduce the bug:

* go to https://publiclab.org
* Go at the pagination, at the bottom. It will by default have the 2 selected.
* click on any page number
* The results of the blog entries do not change, and you are still on page 2.

It is quite frustrating, and I frankly have no idea of why that is happening.

Tested with

Chromium Version 68.0.3440.75 (Developer Build) built on Debian 9.5, running on Debian 9.5 (64-bit)

Firefox ESR 52.9.0

Thanks!

**Comment by SidharthBansal** [comment]
Issue earlier reported in #2173

**Comment by SidharthBansal** [comment]
Thanks @arteteco for reporting the issue. We are trying to fix it as soon as possible.
Thanks for your patience and thanks for making an issue.

**Comment by aSquare14** [comment]
@SidharthBansal  I investigated this. This issue can be closed. I am opening a new issue with proper details.
Pagination doesn't work when not logged in. This is because to view the other pages, you need to be logged in. Remove Pagination in  https://publiclab.org/ when the user is not logged in.
After logging in, pagination works fine on the home page. 
P.S - This could be a good issue for GCI

**Comment by icarito** [comment]
Hi,
@kaametza ran into this issue today and reported it to me. Thanks for having it documented!

Just a note that even when logged in, pagination doesn't seem to work because the user gets redirected to the dashboard upon choosing any page in the pagination control. I guess removing the pagination control as suggested in #3360 is a way to do this, but I guess this is superseded by #6155 ?

**Comment by SidharthBansal** [comment]
I agree that it will be superseded by #6155. We can close it once #6155 is completed

**Comment by jywarren** [comment]
Thank you! Yes, it will be. Thank you!!!
