### ISSUE TITLE
Locale Deustch doesn't work in Footer

### ISSUE THREAD

**Issue by aSquare14** [publiclab/plots2#3348]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

Scrolled to the footer. Clicked on the Language Dropdown at Extreme Right. Selected Dutch as my preferred locale.

> What did you expect to see that you didn't?

I expected the page to be translated to dutch but it was still english. The Dutch locale doesn't work.

### Please show us where to look

https://publiclab.org/?_=1537367148

### What's your PublicLab.org username?
asquare14
> This can help us diagnose the issue: 

### Browser, version, and operating system
Tested on Chrome in Ubuntu 16.04
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****
We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.

**Comment by gauravano** [comment]
Hi @aSquare14, some months back, we decided to remove the German language from our website due to the number of cases of wrong translations. I guess the language button in footer was a leftover. Thanks for reporting the issue and if you want to solve it, you are most welcome. If you need any help, feel free to ask. Thanks!

**Comment by aSquare14** [comment]
@gauravano Thanks but I'd like to leave this for GCI candidates :) Will work on help-wanted or fto.

**Comment by gauravano** [comment]
That's great! I guess for making this issue a GCI candidate, the relevant line of code should be added. What do you think?

**Comment by aSquare14** [comment]
Yes. I am busy with my midsems + RGSoC till September end, so I can do it after 30 Sept . I also plan to work on a few issues after that. :smile:  Is that ok ? Also, if you're free, please feel free to improve this issue :yellow_heart:

**Comment by gauravano** [comment]
Actually, I am also in-between my sessional exams but don't worry I will improve this issue as soon as I get some time. All the best for you exams and thanks!

**Comment by SidharthBansal** [comment]
Hi I reported this error. But due to some reason @jywarren told that we need not to solve this issue.
Can @jywarren you explain the reason once again to @aSquare14 ?

Thanks folks

**Comment by jywarren** [comment]
Ah yes - so, the issue I believe is simply that there are almost no German
(Deutche) translations available. I'd like to explore ways to have
untranslated strings on the site appear with a small globe icon to prompt
people to attempt a translation:

https://github.com/publiclab/plots2/issues/3262

Also - this will only translate the website static text, not the content of
the site. So perhaps this issue could be converted to one where we try to
clarify the purpose of the locale dropdown so it better sets expectations!

**Comment by jywarren** [comment]
Sure, maybe we could just hide it for now?

There is a translation issue which we could begin to work on. One part
thatd make for lots of good starter issues is to start consolidating the
translation files into just one file... We could make one task per
translation!

On Sep 27, 2018 9:23 AM, "Gaurav Sachdeva" <notifications@github.com> wrote:

Hi @jywarren <https://github.com/jywarren> , great idea to use user-input.
Do you think we should remove the Language button from footer until we get
a little started on Language feature to avoid confusion? Thanks!

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/issues/3348#issuecomment-425090085>,
or mute the thread

**Comment by gauravano** [comment]
@jywarren do you mean -  we should restore previously removed translation files with lots of FTOs?

**Comment by jywarren** [comment]
Actually i think we could try some of the steps here:
https://github.com/publiclab/plots2/issues/3262

for one, we should move each language into one big file. but it'll take a
while, but we can do it as individual tasks, what do you think?

**Comment by gauravano** [comment]
Looking awesome! hopefully, it would be done soon :smiley: .

**Comment by jywarren** [comment]
OK so perhaps I will close this one now as we are seeing uptake on #3262 and #3515 !!!
