### ISSUE TITLE
Add FAQs page. Add link to same in footer.

### ISSUE THREAD

**Issue by aSquare14** [publiclab/plots2#3356]
### Please describe the problem (or idea)

It would be cool to have an FAQ page where some of the frequently asked questions about Public Labs could be listed.

### What's your PublicLab.org username?
asquare14
> This can help us diagnose the issue: 

### Browser, version, and operating system
Chrome. Ubuntu 16.04
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

**Comment by SidharthBansal** [comment]
I think that this task needs to be done by someone who knows a lot of public labs. Most probably @jywarren , @ebarry @icarito or @steviepubliclab . GCI candidates will not be much aware of Public Lab's stuff.
This task is creating a wiki page instead of a github document on publiclab.org/wiki/faqs, I guess.

Nice suggestion. I really love your suggestion.
Thanks

**Comment by jywarren** [comment]
Thanks, I'm going to close this now!! 👍
