### ISSUE TITLE
Image upload stalls when editing research notes

### ISSUE THREAD

**Issue by Fastie** [publiclab/plots2#336]
In the last 12 hours I have not been able to upload an image to a research note (a new one or old one) while editing the note. The progress bar progresses forever but never ends. Chrome in Windows.

**Comment by jywarren** [comment]
@icarito is this possibly ssl related?

**Comment by jywarren** [comment]
And Chris, do you see an error in the web developer JavaScript console?

**Comment by Fastie** [comment]
Yes. When I open the research note editor:
**Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.**
Then when I drag a photo into the editor:
**POST http://publiclab.org/images 500 (Internal Server Error)**

**Comment by icarito** [comment]
I'll test this.

On 08/11/15 12:15, Jeffrey Warren wrote:
> @icarito is this possibly ssl related?
> On Nov 8, 2015 11:16 AM, "Fastie" <notifications@github.com> wrote:
>
> > In the last 12 hours I have not been able to upload an image to a
> research
> > note (a new one or old one) while editing the note. The progress bar
> > progresses forever but never ends. Chrome in Windows.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/publiclab/plots2/issues/336>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/publiclab/plots2/issues/336#issuecomment-154842051>.
>

-- 
I+D SomosAzucar.Org
"icarito" #somosazucar en Freenode IRC
"Nadie libera a nadie, nadie se libera solo. Los seres humanos se liberan en comunión" - P. Freire

**Comment by icarito** [comment]
Thanks for reporting this. I've recently migrated the publiclab.org app
to run thru nginx webserver, in order to enable SSL.
This has caused this (i'm reading lots of these in the server logs:)

2015/11/08 17:02:36 [error] 25380#0: *225496 client intended to send too
large body: 1084429 bytes, client: 75.69.124.171, server: publiclab.org,
request: "POST /images HTTP/1.1", host: "publiclab.org", referrer:
"http://publiclab.org/post?tags=oil-testing-kit,oil-testing-kit-beta,spectrometer,fluorescence&template=oiltestkit"

I'll fix it promptly.
Regards,
Sebastian

On 08/11/15 12:27, Fastie wrote:
>
> Yes. When I open the research note editor:
> *Synchronous XMLHttpRequest on the main thread is deprecated because
> of its detrimental effects to the end user's experience. For more
> help, check http://xhr.spec.whatwg.org/.*
> Then when I drag a photo into the editor:
> *POST http://publiclab.org/images 500 (Internal Server Error)*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/publiclab/plots2/issues/336#issuecomment-154844166>.
>

-- 
I+D SomosAzucar.Org
"icarito" #somosazucar en Freenode IRC
"Nadie libera a nadie, nadie se libera solo. Los seres humanos se liberan en comunión" - P. Freire

**Comment by icarito** [comment]
Hello,
Thanks for reporting this. In transferring the files from user "warren"
to generic user "plots", I missed to change the owner the upload
directory (which I moved separately because it is massive). I've since
corrected the file ownership and confirmed the problem is solved, as
shown below:

https://publiclab.org/notes/warren/12-12-2010/front-illumination-ccds-used-digital-cameras-dont-perform-well-uv#c12874

Let me know if any other issues arise.

Regards,
Sebastian

On 08/11/15 13:12, Sebastian Silva wrote:
> Thanks for reporting this. I've recently migrated the publiclab.org
> app to run thru nginx webserver, in order to enable SSL.
> This has caused this (i'm reading lots of these in the server logs:)
>
> 2015/11/08 17:02:36 [error] 25380#0: *225496 client intended to send
> too large body: 1084429 bytes, client: 75.69.124.171, server:
> publiclab.org, request: "POST /images HTTP/1.1", host:
> "publiclab.org", referrer:
> "http://publiclab.org/post?tags=oil-testing-kit,oil-testing-kit-beta,spectrometer,fluorescence&template=oiltestkit"
>
> I'll fix it promptly.
> Regards,
> Sebastian
>
> On 08/11/15 12:27, Fastie wrote:
>>
>> Yes. When I open the research note editor:
>> *Synchronous XMLHttpRequest on the main thread is deprecated because
>> of its detrimental effects to the end user's experience. For more
>> help, check http://xhr.spec.whatwg.org/.*
>> Then when I drag a photo into the editor:
>> *POST http://publiclab.org/images 500 (Internal Server Error)*
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/publiclab/plots2/issues/336#issuecomment-154844166>.
>>
>
> -- 
> I+D SomosAzucar.Org
> "icarito" #somosazucar en Freenode IRC
> "Nadie libera a nadie, nadie se libera solo. Los seres humanos se liberan en comunión" - P. Freire

-- 
I+D SomosAzucar.Org
"icarito" #somosazucar en Freenode IRC
"Nadie libera a nadie, nadie se libera solo. Los seres humanos se liberan en comunión" - P. Freire

**Comment by Fastie** [comment]
Excellent. Images now upload normally.

Thanks Sebastion.

**Comment by jywarren** [comment]
Thanks to you both!!
