### ISSUE TITLE
[Typo and UI Fix] in first time sign in at Dashboard Screen

### ISSUE THREAD

**Issue by YashishDua** [publiclab/plots2#3366]
Pop up component error on the dashboard screen. [Text and its UI]
![screen shot 2018-09-20 at 10 54 18 pm](https://user-images.githubusercontent.com/20666950/45836624-ff0b3200-bd2a-11e8-87a6-c8f0b6a28709.png)

When a user signs up for Public Lab and is landed on the home screen, pop up is shown at the top which has two errors:
1. Typo in text
Existing Text: You have successfully signed in. Please change your password via a link sent to you via a mail
Updated Text: You have successfully signed in. Please change your password using the link sent to you via a mail
2. The popup component is not full sized as compared to its relatively bottom placed popup of the welcome message

https://publiclab.org/ ...

**Comment by bkocsis3** [comment]
I'm very new to this, but could I give it a try?

**Comment by YashishDua** [comment]
@bkocsis3 Yes, you can! It's for the first timers only.

**Comment by SidharthBansal** [comment]
@bkocsis3 go ahead.
Just remember that this issue has two parts. So solve them one by one.
Happy coding

**Comment by the-prolific-coder** [comment]
Can multiple people work on this issue? I'd like to try it too!

**Comment by namangupta01** [comment]
Hi @the-prolific-coder, this is not a big issue so it would be difficult for two people to work on it.
Please look for the other issues.

**Comment by bkocsis3** [comment]
Awesome, thanks!

**Comment by bkocsis3** [comment]
This is a very noob question, but how do I find the file pertaining to this issue?

**Comment by SidharthBansal** [comment]
https://github.com/publiclab/plots2/blob/cdef0bd7978836212c112f2295b4561d3f6a57f0/app/controllers/user_sessions_controller.rb#L53
This might help

**Comment by YashishDua** [comment]
@bkocsis3 is this Issue resolved?

**Comment by jywarren** [comment]
Hello @YashishDua, I see this is listed as a first-timers-only issue in your GCI mentor application. If you can read over some of these docs, you'll see that such issues follow a format to welcome someone else into the project, so if you're interested in being a mentor, please give this a try! We're happy to help and we're grateful for your involvement. You can read a bit more about this here:

A [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all) is simple, self-contained, and has specific step-by-step formatting, in order to be a great entry point for a new contributor. If you're familiar enough with this code, please consider [formatting a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled.

**Comment by YashishDua** [comment]
@jywarren I will update the form by tomorrow. Are you still accepting the forms?

**Comment by jywarren** [comment]
Hi, if you've already submitted and just need to update, that's fine! But
if the original submission was after the 15th, we cannot accept new ones
(just to say for folks who may ask). Thank you!

**Comment by gauravano** [comment]
#3489 doesn't solve the issue both parts and there's still more work required so I've opened a FTO at #4915
