### ISSUE TITLE
Success sign when Password match  with Confirmation password

### ISSUE THREAD

**Issue by avsingh999** [publiclab/plots2#3439]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

### Please describe the problem (or idea)
This is a feature request  in Sign up (https://publiclab.org/register) Page when we sign up and  fill details but No success  message sign when confirming password  field and password filed match and no error sign when not match

It should look like this

![pssword](https://user-images.githubusercontent.com/25536022/45979066-80383100-c06b-11e8-98d7-e99f4219700f.png)

### EDIT:
Let's do form validation for the whole sign-up form, so you need to check username, email, password, password_confirmation for their presence and their format. 

After that, if all the conditions are satisfied then user would be able to submit successfully otherwise sign-up button would just change the focus to error field. Any question?

**Comment by jywarren** [comment]
cool... is there a library that can help us do this?

**Comment by SidharthBansal** [comment]
@avsingh999 please tell the hint to the solution so that I can post it on the GCI dashboard. We need to help the folks by giving them hints to libraries, etc. They are very young.
I hope you will understand and post it soon.

**Comment by kevinzluo** [comment]
Hi. I don't yet see this on the GCI dashboard, but I would like to do it.

**Comment by SidharthBansal** [comment]
Go ahead. I have made an issue for this. Please claim that before anyone else claims it.
https://codein.withgoogle.com/dashboard/tasks/6593856700153856/

**Comment by SidharthBansal** [comment]
If you find more such issues labelled with gci tag but are not part of gci platform please tell us. We will be happy to add them there too.
Thanks

**Comment by HarimAhmed** [comment]
hahaaa @SidharthBansal claimed it b4 😂

**Comment by kevinzluo** [comment]
Haha.
I could not have claimed it anyway since my previous task has not been approved.

**Comment by oorjitchowdhary** [comment]
@publiclab/reviewers This task is done or not? Coz I can still find it in the task listings in GCI

**Comment by gauravano** [comment]
Do you see it open?

**Comment by oorjitchowdhary** [comment]
Yes

**Comment by HarshKhandeparkar** [comment]
If this can be fixed using JavaScript, I guess we can add onchange event listeners to each field and then do the logic based on that.

**Comment by gauravano** [comment]
The task on GCI dashboard is duplicate. This issue is currently worked on by @kevinzluo. It would be closed soon. Thanks for notifying,

**Comment by oorjitchowdhary** [comment]
Okay great. Happy to help. 😄

**Comment by CodeSarthak** [comment]
Hey @jywarren @SidharthBansal It is still present on GCI, it would be good if it is removed to avoid confusion. Thanks 👍

**Comment by SidharthBansal** [comment]
I also could not find any way to delete. I hope decreasing instance count to zero works.

**Comment by SidharthBansal** [comment]
@kevinzluo is working on this.

**Comment by SidharthBansal** [comment]
Published for 2020 GCI

**Comment by SidharthBansal** [comment]
@VladimirMikulic sorry for confusion. 
This issue is about password and password confirmation that should match each other. 
There will be 2 medium tasks for this issue
1. Form password JS validations
2. Modal password JS validations
In case they are already present on the website then please feel free to close #3439


The issue https://github.com/publiclab/plots2/issues/4268 can be broken into 4 hard issues:
1. JS validations / RoR validations for Signup modal. We need to check which one is applicable. We tried RoR last year but that didn't work. Also, they need a response from the server as ROR is backend architecture while JS is the frontend.
2. JS validations / RoR validations for Signup FORM. We need to check which one is applicable. 
3. JS validations / RoR validations for Login modal. We need to check which one is applicable. 
4. JS validations / RoR validations for Login Form. We need to check which one is applicable. 

I broke down into discrete tasks so that you can get more points for discrete functionalities.

**Comment by SidharthBansal** [comment]
Also, consider the layout structure of form and modal. Are they same piece of code? Then we have to use either JS/ROR (for both modal and form). Does this makes sense?

**Comment by VladimirMikulic** [comment]
@SidharthBansal I see that you are using the terms signup form and signup modal.
In the demo video is it the signup modal or form?
I understand modal as a popup and form as HTML form element ie. form that the user fills in that is in signup modal.

This PR, as you saw in the demo does form validation in the signup modal(it validates passwords as well as other inputs).

I hope we understand each other :smile: 
Thanks a lot.

**Comment by SidharthBansal** [comment]
I agree with modal and form definitions

**Comment by SidharthBansal** [comment]
That means you did both of them in the same pr? Great

**Comment by SidharthBansal** [comment]
Ques1: does that pr work for sign up modal?
Ques 2: does it work for signup form?
Ques 3: have you implemented password confirmation for both modal and form?

**Comment by VladimirMikulic** [comment]
@SidharthBansal my PR has all 3 quests done. 

You mentioned 4 JS/RoR concrete tasks. 

My PR covers the first two because it handles signup modal validation and signup form validation.

The only thing left to do here are login modal and login form validation. Login functionality is always handled on server, so RoR definitely.

**Comment by VladimirMikulic** [comment]
My PR also closes #4268. You can open a new issue for login modal and login form validation.

**Comment by SidharthBansal** [comment]
Sure. I think we should make it as a single task having x points as one pr
is required. What should be x?

**Comment by SidharthBansal** [comment]
I think it should be 10 points in total. So you can claim this task and the
other task and get points. Both are hard tasks.
I hope you are ok with it.
Thanks

**Comment by SidharthBansal** [comment]
Explicitly: 5 points for #3439 issue and 5 points for #4268
This will be a fair judgment. So, in total 10 points. Is it okay with you?

**Comment by VladimirMikulic** [comment]
@SidharthBansal perfectly OK. Thank you for acknowledging my work :+1:

**Comment by SidharthBansal** [comment]
In case you find anywhere anyone is gettung lesser points then contact
me(including you).
