### ISSUE TITLE
Increase consistence of nav bars

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#3454]
```We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.```
Instance count 1
### Please describe the problem (or idea)
On small screen devices we get inconsistent nav bars
![whatsapp image 2018-09-25 at 6 44 57 pm](https://user-images.githubusercontent.com/20972099/46017158-77d80880-c0f4-11e8-98cf-d92920cfe243.jpeg)

> What happened just before the problem occurred? Or what problem could this idea solve?

We need to make them look similar

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/ questions

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by SidharthBansal** [comment]
May be we can highlight the selected nav bar in rectangular form or any other way so that it will not create ambiguity to users

**Comment by jywarren** [comment]
Do you mean the black top navbar or the tabs? Sorry, not quite sure what
you're pointing at? Thanks!

**Comment by SidharthBansal** [comment]
Following nav bars
* Popular
* Recently asked
* Recently answered
etc.
They are not aligned properly
Also, I face problem in detecting which nav bar is selected right now. We can change the front end a little bit to enhance which button is selected.

**Comment by oorjitchowdhary** [comment]
Hi, @publiclab/reviewers .. I think the inconsistency was due to the redundant list and grid view buttons in the mobile view.. I just removed them through my PR #4201 .. I just viewed this page and this is how it looks without the list and grid buttons..

![screenshot 70](https://user-images.githubusercontent.com/39333058/49694545-4f6b9080-fbb2-11e8-9faa-4533c72d88c5.png)

For the problem in detecting which navbar is selected, I think we can either highlight that tab or perhaps **bold** the font of that tab..

Hope this helps!

**Comment by JonathanXu1** [comment]
Great job @oorjitchowdhary fixing the layout! Would you guys like it if I implemented a dropdown on mobile view for these buttons since they no longer have the same tab view when they overlap each other?
![image](https://user-images.githubusercontent.com/22998430/49712477-a5702080-fc12-11e8-953b-2e08dc10ab71.png)
vs
![image](https://user-images.githubusercontent.com/22998430/49712484-b02ab580-fc12-11e8-92d1-e63b4386b7bb.png)

**Comment by SidharthBansal** [comment]
Yeah sure create an issue and submit a patch

**Comment by JonathanXu1** [comment]
While testing out mobile dropdown, it seems like after a certain point, the buttons stop displaying text, most likely for better ui on mobile view.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22998430/49717108-efadcd80-fc23-11e8-9c40-99921766b015.gif)

However, at the apect ratio targeted from @oorjitchowdhary 's PR the text reappears. Perhaps the issue with tabs is a result of another issue of text reappearing at that aspect ratio?

**Comment by JonathanXu1** [comment]
@SidharthBansal I fixed the issue here: https://github.com/publiclab/plots2/pull/4248

**Comment by SidharthBansal** [comment]
Please wait. I am reviewing sorry I was not present for last hour.
Was busy with my lunch.

**Comment by VladimirMikulic** [comment]
This has been fixed in #4201 & #4248. Closing this.

**Comment by SidharthBansal** [comment]
Great you have power to close issues :-)
