### ISSUE TITLE
API method may have changed for location data? Map won't show data

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3478]
https://Publiclab.org/puerto-rico shows a map for which there are a few errors in loading data:

https://publiclab.org/api/srch/locations?srchString=18,-66 is the call; it shows a 404. I think @stefannibrasil and @milaaraujo changed the URLs so maybe that's the issue? 

The code for the request is here:

https://github.com/publiclab/plots2/blob/4610d1f646ef328e0c336ee0bf7aee7fe9102016/app/views/map/_leaflet.html.erb#L37

Thanks!

**Comment by stefannibrasil** [comment]
yep, [that changed!](https://publiclab.org/api/srch/taglocations?srchString=18,-66) it's called now `taglocations`.  Sorry for this!
if someone is willing to do this, it can be solved by changing it to:

` $.getJSON("/api/srch/taglocations?srchString="+s , function(data){ `

otherwise, I can fix it now, @jywarren

**Comment by jywarren** [comment]
This could be a great first-timers-only issue, but we are holding off on
making new ones for now, so fto-candidate will be fine! (we're getting a
bit inundated with newcomer requests and want to be sure we hold some back,
and that we don't get too overloaded to support people well)

Thanks!

**Comment by jywarren** [comment]
I'm closing this and moving it to https://github.com/publiclab/plots2/issues/3573 as a FTO. Thank you!!!
