### ISSUE TITLE
Search results: Change profile sorting to "recent" i.e. "by most recent note/wiki post"

### ISSUE THREAD

**Issue by milaaraujo** [publiclab/plots2#3501]
In the search [page](https://publiclab.org/search/profiles/example/), when we select the "profiles" tab it would be more interesting if the results were sorted by the most recent users first.

The `/api/srch/profiles` already has the parameter `sort_by`. One possible solution would be to change this [line]( https://github.com/publiclab/plots2/blob/master/app/views/search/profiles.html.erb#L10) so it calls the endpoint:
```
https://publiclab.org/search/profiles/#{profile.username}?sort_by=recent
```

**Comment by jywarren** [comment]
It looks like according to the docs here: https://github.com/publiclab/plots2/blob/master/doc/API.md#profiles

The current sorting is by user_id, which would be /roughly/ by creation date. 

I think Liz's observation reflects this as `philipsilva` is probably a very old profile!

A few things:

1. I'm editing this so that it makes clear that `recent` means `recently posted notes/wikis` -- so sorting by whoever's posted something on the site (not comments) most recently. 
2. When I actually try sorting by `recently posted notes/wikis`, `philipsilva` doesn't appear (https://publiclab.org/search/profiles/philip+silva?sort_by=recent) -- because Phil has never posted a note: https://publiclab.org/profile/philipsilva

So, while I think this is good, it would make the default sorting exclude people who've never posted a note. So I think we may want to explore first --

A. making `recent` reflect... comments also? Something else? Note that `philipsilva` has also not posted any comments, so that wouldn't help @ebarry's search
B. any other way to sort users that WOULD help @ebarry ?

**Comment by jywarren** [comment]
For example, @stefannibrasil @milaaraujo -- would it conceivably be helpful to add another sorting type to `user.rb` to sort by natural language score? This is done in node searching: 

https://github.com/publiclab/plots2/blob/0c0007fe7a64b9ee11aee33abaf6ee1eb2711195/app/models/node.rb#L47-L51

We could copy that into profile searching over here:

https://github.com/publiclab/plots2/blob/0c0007fe7a64b9ee11aee33abaf6ee1eb2711195/app/models/user.rb#L45-L47

Although we'd have to accept more parameters, as we do in `node.rb`:

```ruby
  def self.search(query:, order: :default, type: :natural, limit: 25)
```

Could this be a reasonable next step? I would kind of loosely guess that `philip silva` would have a good match score against `philipsilva` -- what do you think?

**Comment by stefannibrasil** [comment]
hello, all! back from my vacations! hum, that's true, thanks for the details!

hum, I think that we may need to break those into two separate endpoints. The way it's now is basically used for the autocompletion feature.

I can work on this. What do you think of leaving this endpoint (rename to usernames, for example, or something) for the autocompletion and create a new one only for the search, since they are supposed to be used in different contexts? That way would be easier to search for user tags for the search feature. Let me know what do you think! @ebarry @jywarren

**Comment by stefannibrasil** [comment]
that woudl also fix #3506

**Comment by jywarren** [comment]
Oh that makes a lot of sense. Thanks!

**Comment by stefannibrasil** [comment]
ok, @jywarren I'll work on this, then :+1:

**Comment by stefannibrasil** [comment]
hey everyone, I'm fixing this #3700 first then I'll focus on this one, hang on! xD

**Comment by stefannibrasil** [comment]
hi, everyone. I'm afraid I'm not gonna have the time for this.

@milaaraujo do you wanna move with this one? Thanks!

**Comment by jywarren** [comment]
Closing as we've wrapped our search project!
