### ISSUE TITLE
Update the Readme

### ISSUE THREAD

**Issue by Sandhya023** [publiclab/plots2#3537]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

I am working on this

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by SidharthBansal** [comment]
@Sandhya023 what are you working at??
I think you missed to tell what is the issue in the issue body.
Can you please tell us the issue before you start working on it.
Thanks

**Comment by jywarren** [comment]
Hello @Sandhya023, I see this is listed as a first-timers-only issue in your application. If you can read over some of these docs, you'll see that such issues follow a format to welcome someone else into the project, so if you're interested in being a mentor, please give this a try! We're happy to help and we're grateful for your involvement. You can read a bit more about this here:

A [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all) is simple, self-contained, and has specific step-by-step formatting, in order to be a great entry point for a new contributor. If you're familiar enough with this code, please consider [formatting a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled.
