### ISSUE TITLE
Stored XSS in comments section https://publiclab.org/questions

### ISSUE THREAD

**Issue by vsk4** [publiclab/plots2#3549]
### Please describe the problem (or idea)

 The comment section is vulnerable to  stored - XSS 

> What happened just before the problem occurred? Or what problem could this idea solve?

I tried to comment in [here](https://publiclab.org/questions/) and pasted simple XSS payload and uploaded the comment, after refreshing the page it got executed.
While taking the input for the comment, filtering of input does not happen so that XSS script is executed.

> What did you expect to see that you didn't?

Filtering of script and no pop up when a payload(testing script) is applied.
See the deadly effects of Stored XSS [here](https://resources.infosecinstitute.com/deadly-consequences-xss/#gref)

### Please show us where to look

click on this [link](https://publiclab.org/questions/apparao/09-29-2018/with-which-android-tablets-is-the-mobius-action-cam-compatible) to see the Stored -XSS
Screenshots :- 
![screen shot 2018-10-01 at 8 40 36 am](https://user-images.githubusercontent.com/23310407/46268022-ca328280-c555-11e8-8713-314c1ed59989.png)
![screen shot 2018-10-01 at 8 40 15 am](https://user-images.githubusercontent.com/23310407/46268023-ca328280-c555-11e8-83b1-354f2ab1b038.png)

https://publiclab.org/questions

### What's your PublicLab.org username?
herovsk4
> This can help us diagnose the issue: 

please have a look at this [link](https://www.owasp.org/index.php/Cross-site_Scripting_(XSS)) for more information on XSS.
Filter the input containing Script tags like <,>-,% and all other payload inputs. 

### Browser, version, and operating system
Safari, chrome and firefox

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
Hi! Thank you! I'm going to move your comment to our staging server so it doesn't impact real people posting on PublicLab.org:

https://publiclab.org/questions/apparao/09-29-2018/with-which-android-tablets-is-the-mobius-action-cam-compatible#c20756

It's now at: https://stable.publiclab.org/notes/bkleist/04-04-2017/uwec-air-quality-monitoring#c17379

The offending string was:

`"><img src=x onerror=prompt(133)>`

I'm going to make a test which demonstrates this, so it can be fixed in the template file; I wonder if it has to do with the hidden `raw` display, here:

https://github.com/publiclab/plots2/blob/6595ef39f25ca4f2d377cacfd92e86a7460214d6/app/views/notes/_comment.html.erb#L120-L121

**Comment by jywarren** [comment]
I think we should be filtering some parameters here: 

https://github.com/publiclab/plots2/blob/2fd9e45f198a84b351a3ae562ae826e9998fde94/app/helpers/application_helper.rb#L102-L107

here, would we filter out attributes like `onerror` and such? What's the best way to sanitize?

**Comment by jywarren** [comment]
OK! I've demonstrated the vulnerability in a unit test here: https://github.com/publiclab/plots2/pull/3553

I believe we can use the `sanitize()` method and whitelist a lot of attributes:

https://guides.rubyonrails.org/security.html#html-javascript-injection-countermeasures

Be sure we whitelist everything we really need, like `class`, `href`, `src`, and so forth! 

@vsk4 did you want to give this one a try? If so, try building on the branch in the PR  above -- that way if you succeed, you should be able to get that test to pass.

But first, you could experiment in a Rails console locally, by using variations of the `sanitize()` method to try to get it to reject the `onerror` attribute. Make sense? 

Thanks again!

**Comment by jywarren** [comment]
Great, so sanitize() can now go in comment.rb, here

https://github.com/publiclab/plots2/blob/f78d53e53647bfa91c09b84754ae40a44d468e48/app/models/comment.rb#L335

**Comment by vsk4** [comment]
@jywarren  can you be clear where should I insert sanitize()?

**Comment by jywarren** [comment]
I believe on the output (last line) of comment.rb's `render_body` method!

**Comment by jywarren** [comment]
So I tried this with a badly formatted comment but it removed the markdown formatting too. I think we may need to somehow go through the HTML and ensure it's properly nested... :-/

**Comment by jywarren** [comment]
And note that if we do use `sanitize` in the model, we'll have to call it like:

`ApplicationController.helpers.sanitize()` since it's not normally available in the models.

**Comment by jywarren** [comment]
And note that if we do use `sanitize` in the model, we'll have to call it like:

`ApplicationController.helpers.sanitize()` since it's not normally available in the models. 

Aha! The answer to closing unclosed tags is:

`Nokogiri::HTML::DocumentFragment.parse(html).to_html` (https://stackoverflow.com/questions/9933333/sanitize-html-and-close-incomplete-tags)

This is for a distinct issue and we should add it too, in `comment.rb`. I've created a test for this which is incomplete but could help us diagnose: https://github.com/publiclab/plots2/pull/3630

**Comment by jywarren** [comment]
Hello @vsk4, I see this is listed as a first-timers-only issue in your GCI mentor application. If you can read over some of these docs, you'll see that such issues follow a format to welcome someone else into the project, so if you're interested in being a mentor, please give this a try! We're happy to help and we're grateful for your involvement. You can read a bit more about this here:

A [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all) is simple, self-contained, and has specific step-by-step formatting, in order to be a great entry point for a new contributor. If you're familiar enough with this code, please consider [formatting a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. 

If you've already done this in another issue, that's fine, just either update your application form or respond to this comment with a link to your FTO issue and I'll update my data. Thanks a lot!

**Comment by vsk4** [comment]
Thank you @jywarren  as of now I am not interested to be as a mentor for GCI. Thank you for helping me out. I would love to contribute to the Public Lab community mostly in security issues 😃

**Comment by jywarren** [comment]
Thank you, we'd LOVE to have your help! 🎉

**Comment by jywarren** [comment]
thank you! We'd love your help :-)

**Comment by RuthNjeri** [comment]
Fixed in https://github.com/publiclab/plots2/pull/7282
