### ISSUE TITLE
Embeded content does not display in iframes from non-ssl sites

### ISSUE THREAD

**Issue by Fastie** [publiclab/plots2#355]
Embedded content (iframe) from gigapan.com and 360cities.net in research notes is not displaying. Those sites are http not https. Youtube and Photosynth are all https now, so they display okay.

I changed the url from http://360cities.net to //360cities.net and the content now displays. That trick did not work for the gigapan.com iframes.

The content displayed in the past, so something changed. Is this a permanent change? I can change all the urls for 360cities.net. Will this trick work indefinitely? Are gigapan embeds now not allowed?

**Comment by jywarren** [comment]
Hi, Chris - for some other sites, like alerts.skytruth.org, we had great
success reaching out to the developers to ask them to enable https -- I
sent a note with some of the following:

> Do you think it's possible to enable SSL on your site, so we could embed
content from "*https://*" instead of "*http://*"? It's not currently
possible to display embeds from your site on an https:// site. This affects
display anywhere your content have been embedded, not just on our site.
Thanks!

This is why all the other vendors have enabled https:// for embeds -- in
fact it is the browsers that will not display so-called "mixed content" in
iframes.

Thanks for finding and reporting!

**Comment by Fastie** [comment]
It sounds like the answer is that embeds from gigapan.com will not display at publiclab.org until gigapan.com makes a change. Is the required change easy for them to do, or does it require a major switch to putting their entire site behind ssl?

**Comment by jywarren** [comment]
They won't display anywhere on the internet that uses HTTPS, which is one
reason they should make the change as quickly as they can. This is one of
the reasons we made the switch ourselves.

Skytruth was able to do it in a few minutes, but it depends on their setup.
We took a couple weeks to do a complete conversion. But we also have very
little staff to do such projects, whereas gigapan presumably has plenty of
staff for this kind of thing.

**Comment by Fastie** [comment]
I'm afraid gigapan may not have any staff at all. Somebody is keeping the site live, but the home page has not changed in months, or maybe since the CEO quit two years ago. They have sold the hardware business, and there is no evidence that the website is going to survive as an ecommerce venture. Customer support is apparently non-existent, so I assume requests to change their site will receive no response. 

It was a really nice thing while it lasted.

**Comment by jywarren** [comment]
Oh, that's disappointing. 

Anyhow, I'm going to close this issue. There is one other way -- Chrome may be modifying their "mixed content warning" behavior, and I wonder if browsers would consider displaying a "accept insecure content" message/button in iframes from http. That'd be nice.
