### ISSUE TITLE
Remove body text from notes lists

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3598]
https://github.com/publiclab/plots2/blob/693f22683ef6c871e51fc6b4d7d09ccd6c6a7d48/app/views/notes/_notes.html.erb#L47

Let's remove this line!

**Comment by jywarren** [comment]
It'll simplify pages like this: https://publiclab.org/tag/mobius

where it'll then just show title and image, but not text, for those posts.

**Comment by sagarpreet-chadha** [comment]
@coopjc...Thank you for opening the Pull Request 😄 !!!
But please be careful in future to get the issue assigned to you before you send a PR because someone else may be working on it .

@Dhiraj240...we appreciate your help and would like you to make your first PR . Please have a look at other **first-timers-only** issue . If you don't find any - ping @publiclab/reviewers and one of us may open it for you 😃 .

Thank you :)
