### ISSUE TITLE
blog tab not working after page 5

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#3676]
I was exploring some older posts on the blog (www.publiclab.org/blog) when I noticed I couldn't tab back more than the 4 pages that show on the bottom of the blog. If you try to hit "next" once you're on page 4 nothing happens. 

![screen shot 2018-10-11 at 4 31 51 pm](https://user-images.githubusercontent.com/7490478/46832146-49ecf800-cd73-11e8-8b17-2c76342971cf.png)

@publiclab/mentors here's another bug that might be made into a good issue :)

**Comment by quinn-codes-synthesis** [comment]
Hi! Is it possible that there are not enough blog entries to populate a 5th page? I ask because when I try to navigate to https://publiclab.org/blog?page=5 I get "No results found; try searching for 'blog':"

**Comment by gauravano** [comment]
You are right @quinn-codes-synthesis, as seen from the above image too, the Next button is disabled after arriving at Page 4 as there is no 5th page. @steviepubliclab do you think, this issue can be closed now?

**Comment by steviepubliclab** [comment]
Oh no sorry, there are a lot more blog entries than that. Should go back about 3 years. (at least)

Best,
Stevie

**Comment by shubhangi-chauhan** [comment]
@steviepubliclab as you've already figured out, it's not due to number of blogs that the blog tab is not working after page 4*.

This is really because in file : 
[/plots2/app/controllers/tag_controller.rb](https://github.com/publiclab/plots2/blob/master/app/controllers/tag_controller.rb#L246#L247)

```
#code-snipet

  def blog
    nids = Tag.find_nodes_by_type(params[:id], 'note', 20).collect(&:nid)
    @notes = Node.paginate(page: params[:page], per_page: 6)

#code-snipet
```

You'd notice we're passing a limit of *20* blogs to the model, and there are *6* blogs on each of page 1, 2, 3 and remaining *2* on page 4, which make all of it.

I'm not sure why this has been implemented in such a way, I'd like @publiclab/mentors to explain it better. :star:

**Comment by shubhangi-chauhan** [comment]
Quoting @gauravano ,
> Anyways, @steviepubliclab @jywarren so we want to increase the nodes limit or display all the blog nodes?

**Comment by jywarren** [comment]
Let's increase the limit, but still show the same # per page. Make sense?
