### ISSUE TITLE
hyphenated tag pages

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#3677]
I'm noticing that we're having some overlap on tags, just by some people's nature of some using hyphens and others who remove spaces. For example there are tags "purple-air" and "purpleair" the material should be the same, we end up with two different tag pages, and different material on each tag page. Is there anyway to make those two things go to the same result? go to the same tag page?

https://publiclab.org/tag/purple-air
https://publiclab.org/tag/purpleair

@publiclab/mentors this one is probably a little more complicated, but I'd love to talk about it with someone!

**Comment by steviepubliclab** [comment]
It might also be interesting to force one system here, for example if someone tries to post hyphenated tags, the hyphens are removed when it's posted and replaced with a tag with hyphen. We could make it capitalize the word after the hyphen for example someone trying to tag "purple-air" could end up with "PurpleAir"

**Comment by jywarren** [comment]
Thanks Stevie! We can do two things here:

1. we can make one the "parent" of the other tag, so if you have a preferred please mention it and we can do this (although it's done in the database directly... we could imagine adding a button to "make a parent" as a break-out feature)
2. we can also be sure there is a wiki page for both, but one redirecting with `redirect:purpleair` (for example) so that both show the same wiki page content at the top of the tag page.

Thanks again!

**Comment by jywarren** [comment]
Ok, so would we be good to have tag parenting get more user interface or
would we like to perhaps have some other system developed like, if no
content is found, redirect to a non-hyphenated close alternative?

I don't think it'd be able to figure out how to add in hyphens because it
wouldn't know enough English to figure that out, like, if
maneatingcabbage would
become man-eating-cabbage or maneating-cabbage.


We could also make a button to "add redirects" if that makes creating
redirect pages a bit faster.

+1 for any of these ideas? 1 and 3 are easier and more maintainable than 2.

**Comment by jywarren** [comment]
I think what Liz was saying, and I see her point, is that we already have a pretty strong convention for using hyphens ("kabob-case"), so this might disrupt a lot of existing pages. But let's think through it -- if we can't /add/ hyphens, we can only remove them, then:

* `purple-air` would be auto-redirected to `purpleair` which would work for this instance

But my concern with this is that that we have a lot of existing redirects in both directions, but mostly **towards** hyphens, as Liz pointed out: https://publiclab.org/wiki/airquality for example, redirects to https://publiclab.org/wiki/air-quality, and many more like that. 

@shubhangi-chauhan is right (thank you!!!!) that we can strip out the hyphens. 

I think we could potentially make all hyphenated tags **automatically** have all non-hyphenated versions as alias tags, AND create a wiki page redirecting back to the hyphenated page, so if we create a tag like `sand-storm` it would automatically generate `sandstorm` and redirect the `/wiki/sandstorm` wiki page to `/wiki/sand-storm`. We could run this on all existing hyphenated tags too, although we'd have to check for exceptions like `purpleair`. But because of the `man-eating-cabbage` problem, we can't do the reverse (insert hyphens) because the system wouldn't know where to put the hyphens. 

What do you think? There are a couple features we'd have to implement here, but it could be broken up into smaller parts.

**Comment by steviepubliclab** [comment]
Hi again, 
Is there any way to do a search on Public Lab URLs for text that is the same regardless of the hiphons, that could point out where we run into trouble with redirects.

**Comment by jywarren** [comment]
Would it be helpful to just output all wiki page URLs in alphabetical
order? We could do that and review it?

**Comment by steviepubliclab** [comment]
Interesting, do you have an estimate on about how many wikis there are right now?

**Comment by ebarry** [comment]
I would love to see an alphebetized list of wikis! Last time i paged
through to count, there were about 1000 pages.

**Comment by jywarren** [comment]
https://publiclab.org/stats says 1269, wow!

**Comment by jywarren** [comment]
OK - so here's the alphabetized list: https://publiclab.org/wiki?sort=title

**Comment by jywarren** [comment]
I guess we can add a column to show the URL here too if that would be
helpful!

**Comment by jywarren** [comment]
Created an issue for a first-timer:
https://github.com/publiclab/plots2/issues/3744

**Comment by ebarry** [comment]
Awesome!!!!

**Comment by jywarren** [comment]
Also added an interface for adding tag parents (admin only) here: https://github.com/publiclab/plots2/pull/3749

barebones though and not published yet!

**Comment by jywarren** [comment]
Alphabetizing of URLs is also here now as of today: https://publiclab.org/wiki

**Comment by jywarren** [comment]
Add tag parent now exists but is buggy. Updates soon!

**Comment by jywarren** [comment]
OK tag parenting has a button only shown to admins now. it's not that tidy looking but it works:

![image](https://user-images.githubusercontent.com/24359/47587893-5ad06880-d932-11e8-9652-7f680b2aab0f.png)

There is one final bug but it should be running by Monday. 👍

**Comment by gauravano** [comment]
Hi @jywarren, please update the issue progress. Thanks!

**Comment by jywarren** [comment]
I think the only remaining thing we could look into would be from [this comment](https://github.com/publiclab/plots2/issues/3677#issuecomment-431881996), the essence of which would be:

* [ ] decide to, and implement, auto-generating redirects from any `kabob-cased` tag to its hyphen-free alternative `kabob-cased` version, for all wiki pages. 

Although now that I think of it, we could also explore @steviepubliclab's idea [in this comment](https://github.com/publiclab/plots2/issues/3677#issuecomment-432246848) to see if we can get the search function to essentially ignore hyphens, or to add an unhyphenated version to the search terms automatically, or something like that -- i'd be happy to break out a new issue with that if folks are interested.

**Comment by gauravano** [comment]
@jywarren I think @steviepubliclab's [idea](https://github.com/publiclab/plots2/issues/3677#issuecomment-432246848) is nice and seems possible. Where do you think we should implement it- at https://publiclab.org/search/ maybe? 

Thanks!

**Comment by ebarry** [comment]
I agree that @steviepubliclab 's idea is nice and straightforward. Not sure where it should be implemented.

**Comment by jywarren** [comment]
OK, i'll open a new issue for that and close this one, leaving aside the auto-redirect generation idea. Thanks!

**Comment by jywarren** [comment]
moved to https://github.com/publiclab/plots2/issues/4823
