### ISSUE TITLE
Remove the list and grid view button in the mobile view

### ISSUE THREAD

**Issue by rohan2599** [publiclab/plots2#3733]
### Please describe the problem (or idea)
The list and grid view button in the mobile view needs to be removed as it is not working and is just an additional problem whichs needs to be eliminated in the page where tags are being added .
> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?
![capt](https://user-images.githubusercontent.com/31514059/47298396-4724b980-d635-11e8-9ca7-aa6833ebf1eb.PNG)

### Please show us where to look
https://publiclab.org/tag/code

### What's your PublicLab.org username?
201651044
> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by SidharthBansal** [comment]
This task is published on GCI dashboard. Thanks all.

**Comment by DTalone** [comment]
#3954 
to delete list and grid view button you have to delete this code <div class="btn-group visible-desktop" style="float:right;" id="note-format" data-toggle="buttons-radio"> <a onClick="toggle_format('grid')" id="grid-format" class="btn btn-default btn-sm active" href="#"><i style="font-size:14px;" class="fa fa-th-large"></i></a> <a onClick="toggle_format('list')" id="list-format" class="btn btn-default btn-sm" href="#"><i style="font-size:14px;" class="fa fa-list"></i></a></div>
The problem shows that grid and list button is useless, because i will prefer list than grid so you have to remove that and just use list then i think you have to  make a column for all recent questions because i think it will make the web good
My Publiclab : farisaziz22
Chrome, windows 10

**Comment by SidharthBansal** [comment]
Hi, some people prefer list view while others prefer grid view.
On the mobile we want only list view.
On desktop we want both views.

**Comment by oorjitchowdhary** [comment]
> This task is published on GCI dashboard. Thanks all.

Is this issue already solved?

**Comment by oorjitchowdhary** [comment]
@SidharthBansal @rohan2599

**Comment by oorjitchowdhary** [comment]
> > This task is published on GCI dashboard. Thanks all.
> 
> Is this issue already solved?

@publiclab/reviewers ??
