### ISSUE TITLE
Sending an answer inserts answer text into other textareas on the page

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3836]
I entered an answer and posted it on this page: https://publiclab.org/questions/warren/10-29-2018/help-us-refine-the-search-interface-at-publiclab-org

My answer was posted, but strangely, its comment box also contained my original answer text, and the text also remained in the answer posting textarea:

![screen shot 2018-10-29 at 6 22 11 pm](https://user-images.githubusercontent.com/24359/47684102-13531200-dba8-11e8-858d-204e605ea404.png)

I would guess there's something going wrong with the `id`s of these textareas that is causing the content to be inserted incorrectly:

https://github.com/publiclab/plots2/blob/46235a78887702e29817e0c74c83e9c639608e81/app/views/questions/_answers.html.erb#L9-L14

Notice how the answer posting form re-uses the comment form. Perhaps there is a collision of unique IDs between these.

**Comment by SidharthBansal** [comment]
Published on GCI dashboard

**Comment by oorjitchowdhary** [comment]
I can't find this task on the gci dashboard.. is it already solved?

**Comment by oorjitchowdhary** [comment]
@SidharthBansal @jywarren

**Comment by gauravano** [comment]
Hey @jywarren @handlerug while reviewing PR created by @handlerug , i was trying to replicate the error and found that this error is not due to unique id problem or so, but somewhat related to comment template. Like, when I created a test question on the website and added tag as `comment-template:ui-feedback-template`. All text areas got this template.

Information about comment templates - https://publiclab.org/comment-templates

Test question - https://publiclab.org/questions/gauravano/11-26-2018/test-question

Thanks!

**Comment by handlerug** [comment]
It's problem with response from the server. When user submits comment, server returns filled answer template with new comment form prefilled with answer text. So I added special flag to disable auto-filling and now it's working fine.

I will do some extra checks today and will try to solve it, thanks! :+1:

**Comment by jywarren** [comment]
Awesome!!!

**Comment by handlerug** [comment]
It's problem inside new comment view, so I fixed it already. Can you check it again @jywarren @gauravano?

**Comment by gauravano** [comment]
@jywarren don't you think the issue you mentioned was due to the tag `comment-template:ui-feedback-template` in https://publiclab.org/questions/warren/10-29-2018/help-us-refine-the-search-interface-at-publiclab-org. See https://publiclab.org/comment-templates for more details. If you think the issue you faced was due to tag and it's the natural function of tag, then it's possibility that we might have intruded in comment-template tag's working by merging PR #4049 . Thanks!

**Comment by jywarren** [comment]
Hmm, it's worth watching this carefully. I don't think the original issue was related to the comment template feature. So i think this is OK. But let's keep an eye out. I also haven't seen the `local_assigns` usage that the solution in #4049 has, so maybe i'm not quite sure what's going on. Let's watch the production server to be sure comment-templates still work, as in https://publiclab.org/questions/warren/10-29-2018/help-us-refine-the-search-interface-at-publiclab-org

@handlerug i'm going to be publishing new code in about an hour. Would you be able to test and ensure both features are working? Thanks!

**Comment by handlerug** [comment]
I think comment templates will be broken because I ever didn't know about this feature and my fix removes any text from comment form inside answer view. I will check it in two hours, can I add more commits to my pull request? Thanks!

**Comment by jywarren** [comment]
Ah - well you can open a new PR with additional changes! No worries --
thanks for following up!

>
