### ISSUE TITLE
Replace phantom.js with selenium driver

### ISSUE THREAD

**Issue by Radhikadua123** [publiclab/plots2#3869]
phantomjs was deprecated in past. We should remove phantomjs use and switch to better solution. Rails itself has moved away from it to Selenium Chrome webdriver.

**Comment by gauravano** [comment]
@jywarren what do you think about this transition?

**Comment by jywarren** [comment]
Could it relate at all to system testing, which is opened another issue
about, which seems to be able to render screenshots of the app from a test?
Just thinking ahead to upcoming rails features. We have a lot of errors
recently with JavaScript integrations and our js plots2 tests are not very
good (partly because we have to keep HTML fixtures up to date which is not
very maintainable).

Even if system tests doesn't pan out, if selenium has a good rails
integration I'd love to consider it. Can we look at some examples?

**Comment by jywarren** [comment]
I believe this is complete now in our new test setup - using chromedriver! https://github.com/publiclab/plots2/blob/main/.github/workflows/tests.yml#L89
