### ISSUE TITLE
use grids via "insert_extras()" in all types of comments

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3978]
When using inline shortcodes like `[notes:balloon-mapping]` in wiki or note body text, they get converted using the `insert_extras()` method, like on these lines:

https://github.com/publiclab/plots2/search?utf8=%E2%9C%93&q=insert_extras&type=

See how it works in the sandbox: https://publiclab.org/wiki/sandbox-2

But this doesn't happen in comments -- see this example:

https://publiclab.org/notes/imvec/11-10-2018/community-microscope-laser-cut-file#c21267

It also doesn't work in wiki comments, question comments... yet some of those seem to have the `insert_extras()` code, as per the search results above. 

Let's figure this out!

**Comment by conkytom** [comment]
Hello @jywarren, I'd like to try and solve this one.  Thanks!

**Comment by jywarren** [comment]
oh that would be tremendous, thanks!

**Comment by conkytom** [comment]
Just submitted PR 4013 that I think solves the problem.  

I had some questions about other behavior I came across while trying to figure this out, that I have not seen issues for.  If they aren't expected behavior I'd be happy to take a look at them:

1. Inline shortcode for notes includes results in questions as well. Example: if there are notes tagged with "tag_topic" and questions tagged with "tag_topic" putting `[notes:tag_topic]` in a form will display all notes and questions in the resulting table.  I would have assumed it should only return notes with that tag.
2. Inline shortcode for questions only returns questions if the tag is formatted with "question:" before the tag.  Example: Question A is tagged with `tag_topic` and Question B is tagged with `question:tag_topic`.  Putting `[questions:tag_topic]` in a form will only return a table with Question B.  Possibly related to the first question.

**Comment by jywarren** [comment]
For 1) i think that must've been a request from community at some point, so we'd best leave it. 

for 2, I think that does give us some ability to ensure that questions show up on the appropriate grids, even if they have a lot of extra topic tags. I think we can leave these for now, but maybe your 1) and 2) could go onto this page by way of documentation? https://publiclab.org/wiki/advanced-grids

Thanks!!!
