### ISSUE TITLE
Publishing wiki edits redirects to URL "data:,"

### ISSUE THREAD

**Issue by shapironick** [publiclab/plots2#399]
##What happened just before the problem occurred
I clicked "publish" on a wiki edit and it sent me to "data:," as the complete URL  (no https:// or www. or publicly.org) I was editing the DIY Indoor Air Quality Remediation Kit page

##Relevant URLs

data:,

##PublicLab.org username
nshapiro
(to help reproduce the issue)

##Browser, version, and operating system
on safari Version 9.0.3 (11601.4.4)
OS  Mac 10.11.3 (15D21)
For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by jywarren** [comment]
Thanks for reporting, Nick! We'll try to smush this bug promptly.

**Comment by jywarren** [comment]
Whoa, this is a mysterious one. Did it happen only once? Can you try again? Does it happen only on that page, or on others too? 

I was able to edit and save a revision to that wiki page, so I want to figure out what was different. You didn't happen to use tab-enter to click on the button, right, like instead of a mouse?

**Comment by jywarren** [comment]
Or tab-space i mean

**Comment by shapironick** [comment]
Strange! It did happen 2 or 3 times. I won't be able to do that again on that same computer as it is now 1000 miles away. But I'll try it again tonight. 

I don't think I was holding any other keys down when I clicked. 

Sorry if this was a red herring!


Sent on the move

**Comment by jywarren** [comment]
Yes, please do and tell me what you see! Thanks, Nick.

**Comment by shapironick** [comment]
![screen shot 2016-03-08 at 8 28 28 pm](https://cloud.githubusercontent.com/assets/7503343/13622418/98230ed4-e56c-11e5-880a-a90385214823.png)

it happened again when I just tried it. Screenshot above. 

on OSX 10.11.2 (15C50)
Safari Version 9.0.2 (11601.3.9)

**Comment by jywarren** [comment]
Hi, Nick - there were a lot of changes to the editor image upload form a day or two after you saw this bug. Have you seen it again since? I'm hoping it was just one of the issues that was fixed. If you don't see it, or haven't, can you close this issue and we can assume it's been resolved by the new fixes? Thanks so much for reporting!

**Comment by jywarren** [comment]
Closing, please re-open if you see the issue again!
