### ISSUE TITLE
Make additions / changes to I did this button

### ISSUE THREAD

**Issue by shubhscoder** [publiclab/plots2#4012]
### Please describe the problem (or idea)

In public lab store the products page has the following:
1. The cost of the product.
2. A small description about the product.
3. And links to posts on the website related to the use of that product.

Proposed additions:
1. A reviews section : Where the users who have bought the product could share their reviews with potential customers.
2. A question and answer section : Where the users could get their doubts regarding the products cleared by someone who has already used it.

**Comment by jywarren** [comment]
Hi, this is an interesting idea! We can't actually make many changes to the store because it's not part of our open source project, it's actually run over at https://shopify.com
However, I think you might look at the `I did this` button and how that works on activities:

https://publiclab.org/w/activities
https://publiclab.org/notes/bronwen/05-07-2018/microscope-webcam-conversion

Would you be able to suggest some improvements for that process? I'd love to see, for example, the `I did this` button open up a form for a comment, so that you can reply with a comment to say you did it! It could pop open a section with the comment form in there and a prompt like "upload a photo to illustrate your comment"?

**Comment by shubhscoder** [comment]
Yeah. So now we redirect it to a new page, to fill the form, that is I think kind off inefficient. How about using a bootstrap modal? We would have the required form in that modal no there is no need of redirection to a new page. We could use the same existing design and just adjust it properly in the modal? I am attaching a small image of how the modal would look like. 
![modal_demo](https://user-images.githubusercontent.com/18489285/48857904-0bba0e00-ede0-11e8-9ee1-25572e5cdcdd.png)

**Comment by shubhscoder** [comment]
Also on this page:
https://publiclab.org/notes/warren/10-24-2018/add-a-high-quality-webcam-to-your-community-microscope-kit
There are two buttons "I made this" and "I did this" , both of them open up the same form I guess. So why do we have two buttons?

**Comment by jywarren** [comment]
ah, that is odd, but I think it may be because it's labeled as both a
"build" and an "activity".

I think a modal /could/ work, but it's still going to be hard to implement
it within the store code.

Can we change this issue to be about making it easier to post an "i did
this" by allowing people to fill out a specially formatted comment form
when they click "I did this"?

**Comment by jywarren** [comment]
Hm, that is an interesting idea! Perhaps open an issue to brainstorm?

**Comment by jywarren** [comment]
Also, we are looking to improve new member outreach in this issue as well,
so please chime in with ideas!
https://github.com/publiclab/plots2/issues/3924

**Comment by jywarren** [comment]
OK, i've rebuilt a new issue from some of these ideas. I hope this makes sense! Check it out!

https://github.com/publiclab/plots2/issues/4093
