### ISSUE TITLE
Link Login Modal to Try out the activity on the sidebar.

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4171]
We are creating a login/signup modal, next step is to link to various pages. In this issue we will be linking it to Try out the activity on the sidebar.
https://publiclab.org/questions/LaPa/12-03-2015/how-do-i-set-a-costum-white-balance-of-the-noir-modulo-cam
![image](https://user-images.githubusercontent.com/20972099/49639053-f542c200-fa2f-11e8-893c-2a87f9de4aa7.png)

**Comment by oorjitchowdhary** [comment]
@SidharthBansal could you please create a task for #3755 too..

**Comment by SidharthBansal** [comment]
Yeah I created these issues because each separate parts needs to be checked
completely before merge.
Even though the number of lines is small, but proper rendering action needs
to be checked. Like whether the user is getting redirected to same place or
not. Is the user experience good with modal on this page etc...
We don't want redundancy. We are trying to give a better user interface.

**Comment by oorjitchowdhary** [comment]
Absolutely.. I totally agree..

On Dec 7, 2018, at 3:02 PM, Sidharth Bansal <notifications@github.com<mailto:notifications@github.com>> wrote:

Yeah I created these issues because each separate parts needs to be checked
completely before merge.
Even though the number of lines is small, but proper rendering action needs
to be checked. Like whether the user is getting redirected to same place or
not. Is the user experience good with modal on this page etc...
We don't want redundancy. We are trying to give a better user interface.

**Comment by oorjitchowdhary** [comment]
@publiclab/mentors I think we can start working on these issues right?

**Comment by SidharthBansal** [comment]
@kevinzluo I forget to tag you and tell that atmost 5 these linking tasks can be performed by a single student(5prs) and 5 first timer issues with the first timers only template can be created by you all GCI students. So total of 10 tasks. As they are similar, they have upper bound of 10.
