### ISSUE TITLE
Create signup modal

### ISSUE THREAD

**Issue by JonathanXu1** [publiclab/plots2#4173]
As an extension of #4133 , and similar to the issue of #2866 , we will need to create a modal that pops up when the user clicks the "signup" button in the navbar:
![image](https://user-images.githubusercontent.com/22998430/49650759-5603d780-f9fb-11e8-81bf-e22f121e200f.png)

A modal should pop up, with the contents of this page: https://publiclab.org/signup
Here's the modal for logging in: 
![image](https://user-images.githubusercontent.com/22998430/49650836-88153980-f9fb-11e8-9818-75a808d9530a.png)

I've made the login modal so if I'm not working on this task you can ask me for help :)

**Comment by SidharthBansal** [comment]
Sorry for the misunderstanding.
You need to enlarge the existing modal so that it will have sign up form also.
Check the sign up form for codechef.com
May be that will help us.
You need not to create second modal.

Also, please claim the suggest changes issue on the GCI dashboard I will give you rewards.

**Comment by JonathanXu1** [comment]
Alright, I'll add the signup to the modal. While I'm working on that, I've claimed the suggest changes issue and submitted that.

**Comment by SidharthBansal** [comment]
Approved it!
Can you claim it again?

**Comment by JonathanXu1** [comment]
Nope, not anymore :) I'm trying to add the signup form in a new modal like such:

![image](https://user-images.githubusercontent.com/22998430/49659302-ee0cbb80-fa11-11e8-8be7-c961056cdda9.png)
However I'm getting the error: 
![image](https://user-images.githubusercontent.com/22998430/49659317-f82eba00-fa11-11e8-9132-c4812da8fc80.png)

Not sure if you meant this way of adding the signup.

**Comment by SidharthBansal** [comment]
I was looking forward for this design
![image](https://user-images.githubusercontent.com/20972099/49659891-3ad0b080-fa6b-11e8-8d91-4c39182efedf.png)
![image](https://user-images.githubusercontent.com/20972099/49659907-445a1880-fa6b-11e8-801a-eaff68bd9f6e.png)
In the form of a modal, a line in between dividing the sign up and login
Like
Sign up                                                        |                         Login
Social media Icons                                      |                Social media Icons
Sign up Form Button                                   |                 Login form button

You created the right portion in the pr. Now let's make the right portion and integrate both stuff together.
We require Social Media Icons on both sides because an end user don't know that backend logic for login and sign up for social media icons is same.

**Comment by JonathanXu1** [comment]
Mhmm, the design would be pretty easy for that, but I'm having trouble including the form component. It only works if I'm on the signup page because of line 2: 

<%= form_for @user, :url => {:controller => 'users', :action => @action}, :html => {:class => "row"} do f| %>

If I can get it to work anywhere outside the signup page I can add signup functionality to the modal.

**Comment by SidharthBansal** [comment]
Can we complete #4133 first OR are you willing to push changes to that PR?

**Comment by jywarren** [comment]
OK, I'm sort of thinking let's get this working really well with the modal for login, and treat sign up as a separate task/issue. The reason is that i thought about this a lot and there is just more content on the signup form: https://publiclab.org/signup (in incognito mode or not logged in). So, let's get the login working smoothly before we take on this 2-column version which seems almost like a separate issue. I hope that sounds reasonable. 

I was thinking more about Sidharth's concern that the "Log in with Email" button appearing on the same line looks strange... i do think some people who have been logging into the site for a long time with username + password may find it confusing. I think i was wrong about it... so shall we revert back to how it was in an earlier version? 

![image](https://user-images.githubusercontent.com/24359/49662341-8490ab00-fa19-11e8-9550-ac47f6ee420d.png)

**Comment by jywarren** [comment]
I apologize for the confusion about the email button -- and Sidharth's idea of OR happening with a horizontal line does still make sense too:

![image](https://user-images.githubusercontent.com/24359/49662464-e05b3400-fa19-11e8-8d24-3124edd41a6c.png)

**Comment by jywarren** [comment]
Thanks everyone for this quite complex set of inter-related issues!

**Comment by JonathanXu1** [comment]
Personally, I think the signup should not be placed in a modal as there is much text, information and content that would make it very difficult to read in a modal. Also, since it is a one-time event, a page would not affect the ui much afterwards. That's just my opinion; you probably have reasons to include it as a modal.

**Comment by JonathanXu1** [comment]
@jywarren @SidharthBansal can I apply the changes to the design of the login modal and push just the login modal as a solution for #4133 ?

**Comment by jywarren** [comment]
Hmm, @SidharthBansal what do you think? Signup is quite a bit more complex, maybe it needs more thought esp. for narrow smartphone screens. We could break this issue in two and solve the first part completely?

**Comment by SidharthBansal** [comment]
We can first merge the login modal then we can work on the sign-up.
I will suggest that we should create a modal for signup. Redirecting for the signup to a page and we are popping the login template does not makes sense to me. Sorry @JonathanXu1 
I know that signup form is lengthy. 

I am reviewing some other websites to see their UI.

**Comment by SidharthBansal** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22998430/49662365-9a05d500-fa19-11e8-823f-21c75559fc6f.gif)
in the gif shared @JonathanXu1 you can minimize the the sign up modal by removing the sidebar.

**Comment by SidharthBansal** [comment]
Also, we don't need OR ``Login with email`` on signup page. Please remove it

**Comment by oorjitchowdhary** [comment]
@JonathanXu1 Ping me if you need any help..

**Comment by oorjitchowdhary** [comment]
@JonathanXu1 you're working on this or this issue is left to solve by anyone?

**Comment by JonathanXu1** [comment]
Yep, I'm currently setting up the signup modal as it was before in my previous PR before I removed it. I'll let you know if there's anything I'll help with. Good luck!

**Comment by oorjitchowdhary** [comment]
Okay great

**Comment by JonathanXu1** [comment]
@oorjitchowdhary could you help me figure out a way to render the form template in directories outside of /signup?
https://github.com/publiclab/plots2/issues/4173#issuecomment-445283901

@SidharthBansal @jywarren Is this task up on GCI yet?

**Comment by SidharthBansal** [comment]
you need to check it. If it is not we will create one. It is non beginner task. So, don't worry :smile:

**Comment by SidharthBansal** [comment]
@oorjitchowdhary if you will be doing the collaborative task with @JonathanXu1 in resolving then both of you will get rewards :-) I am very generous in giving points.

**Comment by oorjitchowdhary** [comment]
@JonathanXu1 We can do that

**Comment by SidharthBansal** [comment]
Moved to#4196 then #4203 then to #4209.
Now we are on the integration part.
