### ISSUE TITLE
Weekly Community Check-In #2 - "Everybody Struggles"!

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4369]
Hi everybody :smiley: !

We all at Public Lab :balloon: - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal :dart:. You are also welcome to share fun-fact :smile: , new ideas :bulb: , your learning goals :ballot_box_with_check: . 

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. :100: 

If you're new here, welcome, and please comment a _Hello message_ below, we would love to work with you. If you're looking for new issues, please try some of our [first-timers-only issues](https://code.publiclab.org/#r=all). 
 
We're SO EXCITED to have your help!

**Is there anything, you would like to share with us from past week's work? What is your plan for this week?** 

If you have not planned yet, just leave a Hello! so that we know that you are in sync with us :arrows_clockwise: and doing well!

The coming weeks will be absolutely full of code :computer: , tasks :spiral_notepad:, fun :tada: and excitement :smiley:!!

As always, if you're waiting for a review, or if you're stuck, please request help here OR leave a comment with @publiclab/mentors @publiclab/reviewers for some input. 🙌 

## This week's theme

This week we are having outreachy theme `Everybody Struggles`. So if you are struggling on any issue or have struggled on any issue then feel free to comment below here. We are not going to judge you on it. We want to showcase that BEST THINGS TAKES TIME AND LABOUR. 

Have a GREAT week :tada:  !

Thank you !

/cc 
@kunalvaswani123 @thesparks @faithngetich @DakshGondaliya  @mohitRJranjan @milaaraujo @kevinzluo 
@stefannibrasil @gauravano @ViditChitkara @tech4GT @mridulnagpal @namangupta01 @sagarpreet-chadha @Souravirus @jywarren @MayankKashyap @siaw23 @ryzokuken @ccpandhare @icarito @steviepubliclab @ebarry @jywarren, @sagarpreet-chadha, @icarito, @JonathanXu1, @uzorjchibuzor, @eli6, @kevinzluo, @ValentinaTironi, @rexagod, @sashadev-sky, @IshaGupta18, @milaaraujo, @dinaelhanan, @cesswairimu, @dependabot[bot], @oorjitchowdhary, @okonek, @wanzulfikri, @mohitRJranjan @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @vishalka98 @publiclab/reviewers @Divy123 @pomyo @bhavayAnand9 @ovipa017-xamk @Mridul97 @avsingh999 @Rishabh570 @subhahu123 @aSquare14  @Radhikadua123 @faithngetich @quinn-codes-synthesis @amychan331 @mardelvalle @narnt @hydro-m @love-opensource @romanrodriguez @shubhangi-chauhan

Feel free to mention names of those contributors in comment below who have been missed.

**Comment by SidharthBansal** [comment]
Here is @jywarren's struggle from https://github.com/publiclab/plots2/issues/4327#issuecomment-449565239.

>This past week I have been continuing to try to remove the old DrupalUsers code in https://github.com/publiclab/plots2/pull/2857, and no matter how many errors I solve, another dozen or more appear -- it can be pretty frustrating! Never-ending, even. I'm getting closer though! Each time I open the Travis logs and hunt through for clues. We'll get there eventually, and hopefully this will dramatically simplify a lot of our users code by finally getting rid of the duplicated code of having 2 user models. 

As he is busy. I am pasting it from his comment.

**Comment by IshaGupta18** [comment]
Hey everyone! First of all thank you so much @SidharthBansal for the appreciation. It means a lot to me and you have been putting a ton of effort to get the functionality right. I have recently started here and enjoy it a lot. Right now, I am working on the multiple tag subscription feature and I hope to finish it soon. 
My semester is about to start very soon, however I would love to keep working here and learn a lot more stuff! Thank you all very much!

**Comment by sagarpreet-chadha** [comment]
Hi 😄 !

I was trying to get the **spinner**  work in Leaflet.blurred 🗺  library today and i got stuck 🙈  at one point : 

#### How do i install different versions of same package in package.json  ?

_What i tried before reaching to a solution :_ 

* The issue here is that **leaflet-spinner** has peer dependencies of **leaflet@0.7.3 .**

* Peer dependencies are not installed automatically after **npm 3** !

* I have tried **npm i npm-install-peers** but this is not working .

* Had faced same problem while integrating with mapknitter but there we use Bower which has concept of **Resolutions** to install multiple versions of same package .

* Finally tried installing 2 versions of leaflet : one using npm name and another using git url , which also is not working 😥  .

* Finally used **cdn links** to install the package and now it seems to work smoothly 😃 😌 !

### Thank you 🎅 🎄 🤶 🎆  !

**Comment by jywarren** [comment]
Hi, all! I am traveling this week and doing my best to keep up with the fast pace. So one additional struggle is being sure that, even in a limited amount of time, I look carefully at big project plans like those of @milaaraujo (on the API and especially latitude/longitude storage in the Node model! #4292) and @cesswairimu (on the community stats project, 📊 📈  #4302). I don't want to misread or miss something that will cause trouble later!

Also wanting to mention @edieblu who continues to make progress on the Dashboard redesign, and has shared some great progress -- please check it out and offer your feedback to help improve our dashboard! https://publiclab.org/notes/edie_blues/12-13-2018/public-lab-dashboard-new-design-ideas#c21559

Thanks, everyone!!!

**Comment by cesswairimu** [comment]
Hi everyone :wave: ,
A couple of struggles on my side especially on the ui, styling and basic layout. 

-  One specific thing that I struggled with was date-picker positioning..sounds pretty simple but it was a pain to get it to appear where I wanted, asked for help from the community though the suggestions I got did not solve it I had to make some comprises.

- Another major struggle was a brakeman issue `User controlled method execution` it looked critical to ignore. I tried to tweak it a couple of times  and much much later solved it by making the method a private method :tada: .

Thanks all for the support :smiley: !!

**Comment by jywarren** [comment]
Just a note also that this week many people are on holiday or vacation. Please be patient and activity will pick up a bit as people return over the next week or so!

**Comment by Dhiraj240** [comment]
Hello everyone,
 I have not been active since 3 months and i only worked on reviewing PRs.Although i solved few issues in ```plots-2``` My main focus in this week will be to take up the new issues and work on pending issues too.Now my performance from this week will be consistent to get some edge in other projects. especially on solving issues.

**Comment by SidharthBansal** [comment]
Nice to see you again Dhiraj. As Jeff wrote, this week will be low
intensity week as most of the people are travelling across globe and having
vacations.
I am available to help you all as much as I can.
Dhiraj it will be great to complete the existing tasks taken by you before
taking new ones.

**Comment by geekychaser** [comment]
Hello everyone,
This week I am working on some ```/tags``` related issues and some UI related problems and will try to complete them as soon as possible and will try to form some more issues.
Special thanks to @SidharthBansal @oorjitchowdhary for lots of support and helping out to make things more clear

**Comment by SidharthBansal** [comment]
Who is willing to do next week checkins? We do this process in rotations so that each one will get an opportunity to do checkins. You need to just create a similar issue on Monday like this and close previous weeks issue.
Thanks

**Comment by cesswairimu** [comment]
@SidharthBansal I would love to do next week's checkins

**Comment by SidharthBansal** [comment]
This will be great!!!
Thanks Cess.

**Comment by SidharthBansal** [comment]
There are over 500+ help wanted issues. Please try to solve as many as you
want. We want them to be decreased asap.
Thanks

**Comment by gauravano** [comment]
I struggled a lot while completing my first PR with Public Lab. Why because I got scared from the huge codebase, I tried to go through the whole repo at once, but was it really the right way? I think No. Because, I was not a superhero that I would just read the project and all features understood, it took time for me in getting familiar. I started with small issues, focussed only on that part which is relative to a particular issue like see only those routes, models, controllers, tests required at that time.

So, start small but with each subsequent issue try to up your game and remember to utilize practices you learnt from last PR experiences.

The case may be different if the contributor is experienced in RoR. I was just at beginner level when I started.

 @codeIriss this might help. Thanks!

**Comment by SidharthBansal** [comment]
Thanks for sharing your experience. We all faced the same problem. You are
correct we should explore piece by piece.

**Comment by Souravirus** [comment]
Hi everyone, hope everyone is enjoying their holidays. I am currently working on upgrading to bootstrap4 in #3937 and hoping to complete by the next week. 
Thank you!!

**Comment by CoderJolly** [comment]
> Who is willing to do next week checkins? We do this process in rotations so that each one will get an opportunity to do checkins. You need to just create a similar issue on Monday like this and close previous weeks issue.
> Thanks

I am willing

**Comment by gauravano** [comment]
Hi @CoderJolly, for next check-In @cesswairimu has already shown interest but you could surely do the check-In for next to next week. How does it sound?

**Comment by SidharthBansal** [comment]
@cesswairimu please link it to the new weekly check in after forming it.
Don't forget to close this issue.
Thanks in advance.

**Comment by sashadev-sky** [comment]
Hi all! I am traveling this week and won’t be back online until after nye, but I look forward to continue contributing in 2019. Happy new year!

**Comment by dinaelhanan** [comment]
Hey everyone! I struggled a lot at first, with this being a codebase bigger than any I have every worked with, especially since I've never written a line of ruby before working on plots2, but I am started to feel more at ease because of the great help from the community, and taking a deep breath! I am working on a few small tasks and closing up loose ends with the login modals, and hope to continue with this. Thanks to everyone that helped me out!

**Comment by shubhscoder** [comment]
Hello everyone! According to my experience the initial setup of the project was the most difficult part of my first PR. So, in order to facilitate a newcomer, we should automate the process of setup. I had opened a issue regarding the same #3259 but later forgot about it. I think some basic shell scripting is required or we can write a python script to automate the process. Anyone with any experience in this, please provide some guidance regarding the same. Thank you so much!

**Comment by CoderJolly** [comment]
> Hi @CoderJolly, for next check-In @cesswairimu has already shown interest but you could surely do the check-In for next to next week. How does it sound?

Sure, feel free to mention as now I am free from my exams

**Comment by cesswairimu** [comment]
Moved to #4476 Thanks everyone
