### ISSUE TITLE
Enhance the profile page

### ISSUE THREAD

**Issue by oorjitchowdhary** [publiclab/plots2#4423]
### Please describe the problem (or idea)
The current `user profile page` looks very unorganized and broken.
I think we can design it and make it look much better.

> What happened just before the problem occurred? Or what problem could this idea solve?

![screenshot 133](https://user-images.githubusercontent.com/39333058/50477264-913d6900-09f1-11e9-8982-85ec14bad05a.png)

How about a small image grid for the `activities`, `questions` and `answers`.
Also, we can reduce the `share your location` map size and I think fit it below the username as a horizontal tab rather than a big square.

> What did you expect to see that you didn't?

Similar to this but with good images rather than coloured bg.
![yuwkl](https://user-images.githubusercontent.com/39333058/50477245-7cf96c00-09f1-11e9-884c-24a04450a40b.png)

### Please show us where to look

https://publiclab.org/profile/ `your_profile` (when logged in)

### What's your PublicLab.org username?

oorjit_chowdhary

### Browser, version, and operating system
Chrome, Windows 10

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by SidharthBansal** [comment]
Nice idea. Can you please explain your design in detail?
Please share link or video of the website where it is live. That will be great.

**Comment by oorjitchowdhary** [comment]
I haven't seen it on any live website yet...
I just came through this idea.

Here are some grid images that we can add...

For answers
![answer icon](https://user-images.githubusercontent.com/39333058/50479945-2135df80-09ff-11e9-98ea-912a0f83d79b.png)

For questions
![faq-icon](https://user-images.githubusercontent.com/39333058/50479949-2430d000-09ff-11e9-9615-2aa0676f378c.png)

These three for activities.. We can decide which one for `activity posted` and `activity attempted`
![activity icon](https://user-images.githubusercontent.com/39333058/50479950-25fa9380-09ff-11e9-858f-e8fcc4d9d97f.jpg)
![activity attempt icon](https://user-images.githubusercontent.com/39333058/50479954-298e1a80-09ff-11e9-9e2c-3eaa90b6af6b.png)
![activity](https://user-images.githubusercontent.com/39333058/50479955-2bf07480-09ff-11e9-8697-68c6dd92b916.jpg)

**Comment by gauravano** [comment]
@publiclab/community-reps your thoughts are required. Thanks!

**Comment by oorjitchowdhary** [comment]
So currently in the profile page, we have a lot of empty space and the center shows 4 things
`x questions`, `x activities posted`, `x activities attempted` and `x answers posted`...
The current UI is very plain and simply shows it as text in 2 lines. (see the pic)

What we could do is, we can make these into 4 quadrants through a 2x2 image grid

**Comment by arungoel123456** [comment]
@oorjitchowdhary  Can I work on this issue

**Comment by SidharthBansal** [comment]
Yes

**Comment by arungoel123456** [comment]
Thanks @SidharthBansal .... I am working on this

**Comment by arungoel123456** [comment]
@jywarren , @SidharthBansal   can u please suggest some changes?

**Comment by arungoel123456** [comment]
@IshaGupta18  yes

**Comment by IshaGupta18** [comment]
Then I would encourage you to start with some first-timer-only issues that are created especially to welcome new comers to the community. You can find them at:

https://github.com/publiclab/plots2/issues?q=is%3Aopen+is%3Aissue+label%3Afirst-timers-only


Once you are a bit more familiar with the codebase, you can take up bigger issues! Looking forward to your work here at publiclab!

**Comment by arungoel123456** [comment]
@IshaGupta18  I am almost completed with editing . So let me do it and complete this issue .

**Comment by IshaGupta18** [comment]
Okay that's great! I just wanted you to feel welcomed!

**Comment by arungoel123456** [comment]
I have just made a pr . Mentors please review

**Comment by jywarren** [comment]
Hi @arungoel123456 - thank you for your PR at https://github.com/publiclab/plots2/pull/4734 -- however I wanted to echo @IshaGupta18 and say that for a PR it may be best to go through the process of completing a small change and getting familiar with both the codebase and the workflow. 

But also - let's keep sharing and brainstorming ideas for the profile page! I think there's a lot of design, discussion, refinement that'd have to happen before we're quite ready for code. 

I started doing a bit of an analysis of the profile page here: https://docs.google.com/presentation/d/1TCZoTfuhamRVrUak8aDgqJAwSgyhRtZg2Pgacl2_4zc/edit#slide=id.g4b41dd6a91_0_0

![image](https://user-images.githubusercontent.com/24359/52078755-fbea4300-2561-11e9-9c59-5e7fe26b3909.png)

Just trying to analyze how it's currently laid out and how we might reorganize it. I think it's good to look at other examples of profile pages too, like the GitHub one or profile pages on other sites. What do you think?

**Comment by IshaGupta18** [comment]
Yes this would be lovely @jywarren . Would you like if I design a few wireframes for the profile page UI? Would that be okay? Also, I want you to know that I am facing a bit of an issue with my system's Ruby, so I'll fix it and get back to coding work ASAP. Thanks a lot.

**Comment by arungoel123456** [comment]
@jywarren so should I modify the profile page according to the design u have sent ?

**Comment by IshaGupta18** [comment]
Thank you @jywarren. @arungoel123456 the design sent by @jywarren is just a mock up. This is a big planning and design issue and requires some brainstorming before the design can be finalised and implemented.

**Comment by jywarren** [comment]
Hey this is awesome! 

To be honest I was thinking of removing the activity graph because on most peoples' profiles it's pretty empty. Writing a post on PL.org is not quite like making a commit, so this is reasonable. Although we could also consider adding comments to the graph; maybe that'd improve it. Still, I think it may be more important to think about what topics people are engaging on rather than their activity "grid". Maybe this opens up more space in the design? 

I like how the map is up high. Could you paste in a map graphic to sort of see what that'd look like? 

Also, maybe `rss feed` could be just the RSS icon and could appear in line with the social icons...

And the "stats" line could be moved to the circular "tabs" at the bottom -- like `Research notes (23)` `Wikis (41)` and such. What do you think? 

Finally, how might we display a bit more information about the tags/topics people have engaged on, rather than their profile tags (which honestly are more for utility use right now, so we might even just display them below the bio -- there shouldn't be too many of them anyways.)

One last thought - the Bio (About) area could get pushed down with too much content, so maybe we should show the first 300 or so px of height, but cut it off (using CSS only), and show an "expand" or "read more" link to show the rest. 

This is very cool! @edieblu @ebarry take a look!

**Comment by IshaGupta18** [comment]
Thanks a lot! I think all the suggestions here are wonderful. I could implement all of them in a new mockup and even I feel that the grid takes up too much space and isn't very much required. 
I was going to put icons and stats along with the titles in bubbles so that would okay.

About the tags, I really like the ides. Actually, I am weaving one of my GSoC proposals around tags only so I would love to add a feature related to it, I think we can brainstorm on it a bit more, on how to use tags in which the user has engaged on their profile page to make it more personalised for them.

And we could make the about box an accordion for more information. I was also thinking of putting a place holder like 'tell us a bit about yourself' for people who have an empty bio.

How does this sound?

**Comment by jywarren** [comment]
This all sounds great!!!!

**Comment by edieblu** [comment]
Hey @IshaGupta18 really cool design! 👍 

I would definitely add the "tell us about yourself" prompt for those that haven't added the bio yet as you suggested. I think this would encourage users to flesh out their profiles - which is important for getting them more engaged overall :) 

Not sure if linking to GitHub or Instagram makes sense, however, I really do like the icons under the user image. Maybe we could instead feature some of the user-selected best content - for example, a research note that they are most proud of, or a link to a project that they manage.

As far as I know, the plan for the user profile is to link to stuff on Public Lab (and not to link outside to other pages that much). 

There seems to be a lot of interest around displaying projects especially (that's why my suggestion above about featuring one project that the user selected).

I really like the round shape for the activity feed (and the user icon). I agree with @jywarren that you could just add a number of posts next to it. 

The only issue that I see is that, proportionally, I don't know if all of these things would fit on one (laptop page) - especially if we work with fonts 16px and up :) 

In any case, good job! 👍 You got this :)

**Comment by IshaGupta18** [comment]
Thanks a lot @edieblu ! I added the social icons because I saw them on some profile but I think it would be okay to remove them and add something more useful in their place like you said.

To tackle the proportionality issue, I think we would be able to reduce some space after the removal of the grid and try some other adjustments.

Would this be okay?

**Comment by IshaGupta18** [comment]
Okay so here's the updated mock up, we can implement that tag customisation thing in the page, now that we have some room

![image](https://user-images.githubusercontent.com/40794215/52322917-0cd30280-2a01-11e9-837c-443448c99001.png)


I think this looks more organzied and cleaner. What do you think @jywarren ?

**Comment by jywarren** [comment]
OK, apologies, circling back here! We have a few threads all interconnecting and I wanted to see if we could try to incorporate them in one thread. Please check out https://publiclab.org/notes/lekhidugtal/03-13-2019/ui-wireframe-for-profile-page too -- let's discuss a bit there!

**Comment by gauravano** [comment]
Also, I just closed a PR https://github.com/publiclab/plots2/pull/4734 which was raised against this issue. Closed because of inactivity. @arungoel123456 you can help us in makeover if interested. Thanks!

**Comment by jywarren** [comment]
With our new profile pages, i'm going to close this up! Thanks, all!!!
