### ISSUE TITLE
'Add one now' redirects to dashboard when user is logged in

### ISSUE THREAD

**Issue by geekychaser** [publiclab/plots2#4463]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

![test](https://user-images.githubusercontent.com/24489162/50546968-22614980-0c57-11e9-8538-6025eb4b381b.gif)

so the issue is Add one now takes us to dashboard rather than to the create a wiki page with that tag name

> What did you expect to see that you didn't?

https://publiclab.org/tag/event

### What's your PublicLab.org username?

geekychaser

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by geekychaser** [comment]
@gauravano please correct me if i am wrong

**Comment by kevinzluo** [comment]
Hi @geekychaser . I believe this is because your are a first time poster. On PL.org, you need to have at least 1 post approved by moderators before you can create a wiki page. The `Add one now` button tries to create a new wiki page. Because you haven't had a post approved yet, you are redirected to the dashboard and should be given this message:
![image](https://user-images.githubusercontent.com/44309027/50549051-fa082980-0c1b-11e9-852a-f831118a3da6.png)

However, I don't seem to see it on your dashboard which might be an issue.

**Comment by shubhscoder** [comment]
@geekychaser have you posted a question or any other content before editing ? I think you first need to post a question.

**Comment by kevinzluo** [comment]
@geekychaser Maybe it hasn't been approved yet? Your account says 0 questions posted. https://publiclab.org/profile/rbothra1998

**Comment by geekychaser** [comment]
@kevinzluo oh sorry , it hasn't been approved.

**Comment by kevinzluo** [comment]
Maybe that is the issue. In that case, we should raise an issue saying that the user should be told to wait for their post to be approved when they try to create a page but have already posted! Would you like to make it @geekychaser ?

**Comment by geekychaser** [comment]
@kevinzluo okay , i will create the issue

**Comment by geekychaser** [comment]
@kevinzluo i am facing this issue on local server 
![image](https://user-images.githubusercontent.com/24489162/50549534-a847b980-0c84-11e9-8c5f-ceefb5ea69b2.png)


when i am logged in and try to click on Add one now this occurs..?

are you facing the same problem or there is problem in my system..?

Thank you

**Comment by kevinzluo** [comment]
Interesting. I am getting that issue too.

**Comment by geekychaser** [comment]
shall i make one?

**Comment by kevinzluo** [comment]
Sure! It appears someone hard coded the id into the url.

**Comment by geekychaser** [comment]
@kevinzluo this flash message appears and after `click` it redirects to a page describing the requirements
![image](https://user-images.githubusercontent.com/24489162/50549687-4c326480-0c87-11e9-81d1-0917a6bad9d9.png)


is this fine?

**Comment by gauravano** [comment]
Hi @geekychaser @shubhscoder @kevinzluo sorry for replying late on this one.

The error you getting in this https://github.com/publiclab/plots2/issues/4463#issuecomment-450574459 is due to missing node, that node actually act as a template for new wiki. The link at `Add one now` is https://publiclab.org/wiki/new?title=event&n=14552 . the node is present in production database so showing error when run on local server. 

I think, this solves all the confusion. 

A new issue can be made from here, such that when a user tries to make a new wiki and if there work is in moderation then show a different alert.

**Comment by gauravano** [comment]
I have opened the issue at #4504. If any of you can edit it further and add links then it would be really helpful. Thanks!

**Comment by gauravano** [comment]
If you guys think any concern is missed, feel free to reopen this issue. Thanks all of you!
