### ISSUE TITLE
Tags most used in a period

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#4539]
Tags most used in this period linking with #4140

**Comment by cesswairimu** [comment]
Hi, @gauravano  @SidharthBansal @sagarpreet-chadha @jywarren 

I am conflicted on which time I should use to determine the period here. Should I use the NodeTag `date` attribute or the Node `created` to determine the `tag date`

Also I was thinking of having this on the /range page with displaying the most used 5 tags within that range represented like so :point_down:
![pie](https://user-images.githubusercontent.com/17081074/52727548-8735f080-2fc6-11e9-99d9-c74c88ecb1d5.png)
Thoughts? Thanks.

**Comment by jywarren** [comment]
Hmm, intersting question! Let's try using the Node `created` because it represents the date of the content itself, not the labeling of that content. 

I like the graph - it's very nice looking! But i wonder if it kind of implies a "maximum" value since it's a circle. I hate to be boring but in this case perhaps a simple bar graph is most appropriate. We can brainstorm some other ways to do more interesting visualizations in another place though! Thanks for keeping it creative!!!

**Comment by cesswairimu** [comment]
Thanks @jywarren
