### ISSUE TITLE
Implement Access token modal like Link social modal 

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#4542]
![link_social_modal](https://user-images.githubusercontent.com/20878070/50729380-9b343a00-115e-11e9-837b-f36b4287f636.png)

This is social media linking modal which is integrated using simple HTML - https://github.com/publiclab/plots2/blob/master/app/views/users/profile.html.erb#L206-L223 

![access_token_modal](https://user-images.githubusercontent.com/20878070/50729430-5ceb4a80-115f-11e9-961d-fd3bcdf0bdce.png)
This is access token modal which is integrated using JavaScript - https://github.com/publiclab/plots2/blob/master/app/views/users/_token.html.erb which is complicated as token modal can be implemented similar to the social modal.

Make the token modal appear without using the JavaScript code present in file _token.html.erb and implement it just like social media modal i.e., normal bootstrap modal called on button press.

Thanks!

**Comment by trompj** [comment]
Hi @gauravano, I am going to try and work on this! It is my first open-source work so may have to bear with me a minute, but I will give it a shot. :)

**Comment by trompj** [comment]
Hi @gauravano, I am going to try and work on this for a bit and see if I can get it. It's my first project outside of basic coursework so bear with me!

**Comment by trompj** [comment]
So I was able to get everything ported to HTML, although from what I can tell we still have to use Javascript for the copy to clipboard functionality, which I am also having issues getting functional after the port over to HTML. Otherwise, everything is working well. I am going to keep looking into the clipboard issue but this is what I have so far.

<button id="accessTokenButton" data-toggle="modal" data-target="#btn-token" class="btn btn-default btn-block">My Access Token</button>
    <div class="modal fade" id="btn-token" tabindex="-1" role="dialog" aria-labelledby="accessModal" aria-hidden="true">
      <div class="modal-dialog" role="document" id="token-popup">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" id="close-btn" data-dismiss="modal">x</button>
            <h4 class="modal-title" id="accessModal">My Access Token</h4>
          </div>
          <div class="modal-body">
          <p><span id="accessTokenForm" class="token form-control text-center"></span></p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" id="copy-btn">Copy</button>
          </div>
        </div>
      </div>
    </div>


Script to add user.token to screen and copy that to clipboard (although the clipboard functionality does not work as of right now....
<script type="text/javascript">
  $('#accessTokenButton').on('click',function() {
    let token = '<%= @user.token %>';
    $('.token').text(token);

    $('#copy-btn').on('click', copyToken);


  });

  function copyToken(){
    var temp = $('<input>');
    $("body").append(temp);
    temp.val($('#token-popup .token').text()).select();
    document.execCommand('copy');
    temp.remove();
    $('#token-popup #copy-btn').text('Copied').attr('disabled', 'true');
  };

</script>

**Comment by trompj** [comment]
So I was able to get everything ported to HTML, although from what I can tell we still have to use Javascript for the copy to clipboard functionality, which I am also having issues getting functional after the port over to HTML. Otherwise, everything is working well. I am going to keep looking into the clipboard issue but this is what I have so far.

`<button id="accessTokenButton" data-toggle="modal" data-target="#btn-token" class="btn btn-default btn-block">My Access Token</button>`
    `<div class="modal fade" id="btn-token" tabindex="-1" role="dialog" aria-labelledby="accessModal" aria-hidden="true">`
     `<div class="modal-dialog" role="document" id="token-popup">`        
`<div class="modal-content">`
          `<div class="modal-header">`
            `<button type="button" class="close" id="close-btn" data-dismiss="modal">x</button>`
            `<h4 class="modal-title" id="accessModal">My Access Token</h4>`
          `</div>`
          `<div class="modal-body">`
          `<p><span id="accessTokenForm" class="token form-control text-center"></span></p>`
          `</div>`
          `<div class="modal-footer">`
            `<button type="button" class="btn btn-default" id="copy-btn">Copy</button>`
          `</div>`
        `</div>`
      `</div>`
    `</div>`


Script to add user.token to screen and copy that to clipboard (although the clipboard functionality does not work as of right now....
`<script` type="text/javascript">
$('#accessTokenButton').on('click',function() {
    let token = '<%= @user.token %>';
    $('.token').text(token);

    $('#copy-btn').on('click', copyToken);


  });

  function copyToken(){
    var temp = $('<input>');
    $("body").append(temp);
    temp.val($('#token-popup .token').text()).select();
    document.execCommand('copy');
    temp.remove();
    $('#token-popup #copy-btn').text('Copied').attr('disabled', 'true');
  };

</script>

**Comment by trompj** [comment]
So I was able to get most everything ported to HTML, although from what I can tell we still have to use Javascript for the copy to clipboard functionality, which I am also having issues getting functional after the port over to HTML. Otherwise, everything is working well. I am going to keep looking into the clipboard issue but this is what I have so far. I am waiting to initiate changes until the clipboard issue is taken care of.

`<button id="accessTokenButton" data-toggle="modal" data-target="#btn-token" class="btn btn-default btn-block">My Access Token</button>`
    `<div class="modal fade" id="btn-token" tabindex="-1" role="dialog" aria-labelledby="accessModal" aria-hidden="true">`
     `<div class="modal-dialog" role="document" id="token-popup">`        
`<div class="modal-content">`
          `<div class="modal-header">`
            `<button type="button" class="close" id="close-btn" data-dismiss="modal">x</button>`
            `<h4 class="modal-title" id="accessModal">My Access Token</h4>`
          `</div>`
          `<div class="modal-body">`
          `<p><span id="accessTokenForm" class="token form-control text-center"></span></p>`
          `</div>`
          `<div class="modal-footer">`
            `<button type="button" class="btn btn-default" id="copy-btn">Copy</button>`
          `</div>`
        `</div>`
      `</div>`
    `</div>`


Script to add user.token to screen and copy that to clipboard (although the clipboard functionality does not work as of right now....
`<script` type="text/javascript">
$('#accessTokenButton').on('click',function() {
    let token = '<%= @user.token %>';
    $('.token').text(token);

    $('#copy-btn').on('click', copyToken);


  });

  function copyToken(){
    var temp = $('<input>');
    $("body").append(temp);
    temp.val($('#token-popup .token').text()).select();
    document.execCommand('copy');
    temp.remove();
    $('#token-popup #copy-btn').text('Copied').attr('disabled', 'true');
  };

</script>

**Comment by trompj** [comment]
@gauravano In order to copy to clipboard via the button, the JavaScript is a necessity in some shape or form. I adjusted the code to allow removal of all other JavaScript in the file though. Would you prefer to try and have the copy function in the profile file and remove the token file completely or just leave the copy function by itself in the token file?

**Comment by trompj** [comment]
I went ahead and moved all the scripting to the profile.html.erb file. I can make additional changes as needed! I know there was some css I wanted to look at for mobile devices that needed some updating. I am going to go ahead and make a pull request and commit for now.

**Comment by gauravano** [comment]
Welcome to Public Lab @trompj and happy to see your energy. As you have opened your PR, we can have further discussion there only. 

Reviewing your PR now.Thanks!
