### ISSUE TITLE
Weekly Community Check-In #4 - "Thinking about our Audience (Platform users)"

### ISSUE THREAD

**Issue by CoderJolly** [publiclab/plots2#4548]
Hi everyone 👋 !

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. Let's start a Community Check-In from this week onwards, where every community member would share something about their work from the past week and about their current week's goal 🎯. You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️ .

If you're new here, welcome 🎈 , and please comment a Hello message below, we love to work with you. If you're looking for new issues, please try some of our first-timers-only issues.

We're SO EXCITED to have your help!

Is there anything, you would like to share with us from past week's work? What is your plan for this week?

If you have not planned yet, just leave a Hello! so that we know that you are in sync with us 🔃 and doing well!

As always, if you're waiting for a review, or if you're stuck, please request help here OR leave a comment with @publiclab/mentors @publiclab/reviewers for some input. 🙌

### **This Week's Theme** 🎉 🎈 🎉

This week being the first week of 2019, we are following Outreachy theme `Thinking About Our Audience` where people who are reading our blog/posts can follow up, users who are using our code are able to use it efficiently and smoothly. So, share ideas
* How can we make the user experience better at Public Lab
* Spend some time with a feature and explore the scope of enhancement 
* Are we keeping up with the advancement if not, share ideas which are required to make a shift to keep-up the trend 

If anybody is struggling or stuck on any issue, then feel free to comment down below. You may share some new skills that you have acquired in the starting of the year or some new resources that can enrich the community experience.

cc

@tsparksh @faithngetich @DakshGondaliya @mohitRJranjan @milaaraujo @kevinzluo
@stefannibrasil @gauravano @ViditChitkara @tech4GT @mridulnagpal @namangupta01 @sagarpreet-chadha @Souravirus @jywarren @MayankKashyap @siaw23 @ryzokuken @ccpandhare @icarito @steviepubliclab @ebarry @jywarren, @sagarpreet-chadha, @icarito, @JonathanXu1, @uzorjchibuzor, @eli6, @kevinzluo, @ValentinaTironi, @rexagod, @sashadev-sky, @IshaGupta18, @milaaraujo, @dinaelhanan, @cesswairimu, @dependabot[bot], @oorjitchowdhary, @okonek, @wanzulfikri, @mohitRJranjan @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @vishalka98 @publiclab/reviewers @Divy123 @pomyo @bhavayAnand9 @ovipa017-xamk @Mridul97 @avsingh999 @Rishabh570 @subhahu123 @aSquare14 @Radhikadua123 @quinn-codes-synthesis @amychan331 @mardelvalle @narnt @hydro-m @love-opensource @romanrodriguez @shubhangi-chauhan @Dhiraj240 @geekychaser @codeIriss

**Summer of Code**
@jywarren has started a brainstorming post for the ideas page for Summer of Code 2019 -It would be best get some ideas into discussion from the fellow community member before time. People have been brainstorming already - let's do it together!
https://publiclab.org/notes/warren/01-02-2019/brainstorming-for-summer-of-code-2019

**Software Contributors Survey**
@ebarry reminded us about a survey that was conducted the year before and we are willing to hear it from you again. The idea discussed in 2017 is here: https://publiclab.org/questions/warren/10-25-2017/help-with-a-standard-mini-evaluation-for-assessing-software-outreach-efforts

Here's the survey as sent out on December 14, 2017: #1890 so, it would great to run the survey this time too.

**Comment by SidharthBansal** [comment]
Great Harman.
Hello everyone,
These people did previous checkins Gaurav, Sidharth, Cess and Harman. Who
will be doing the next checkins please tell. We do this in rotations. New
folks aspiring for GSoC'19 are requested to show their interest in these
checkins. Thanks .

This winter is GIGANTIC. Results for GCI are tomorrow. Most of the students
are curious to know about the result. The competition was too immense this
time. We had a tough time and long discussions forming your results.
For those who will win the contest it is great. For those who will not it
means you are awesome and you require little more hard work for such
programs. All GCI students are further encouraged to participate in next
year GCI, GSoC, RGSoC, and many more programs. We will love to have your
contributions. Best of luck for them and tomorrow's result.

This week we will be looking forward to complete the milestone `Login &
OAuth Sequence`. Let's hope to complete them as soon as possible. So that
we can catch up the new milestoned. I will thank all the collaborators for
sticking onto this issue. We are almost done with it(already completed 125+
issues/prs this dec, jan). But still many small issues(35+) are left. We
are trying hard to complete them asap.
Some subscription work is also going on the notes page with help of Isha.

**Comment by Dsxv** [comment]
Hi Everyone ! I am new here . I joined public Labs a few days ago and I've been loving it so far because everyone is so friendly that it feels unreal and the one thing I regret the most is that why haven't I found it earlier , currently I am understanding the codebase of plots2(I have made a few noob PRs ! )  and hoping to learn and contribute to PublicLab.Editor ( because its cool ! ) . 

 I am aiming for gsoc2019 with public labs and I would really like if someone can guide me through it , I still haven't made the list of ideas but I guess that will filter out while I work with everyone ! 
Thanks for having me in this community and I look forward to work with everyone !

**Comment by SidharthBansal** [comment]
You can start your journey by doing some ftos.

**Comment by CoderJolly** [comment]
> Hi, everyone! so lovely to see you all as usual!
> 
> I'm going to write in a bit more soon, but wanted to note that @rexagod is working on formatting a first-timers-only issue over at [publiclab/PublicLab.Editor#202](https://github.com/publiclab/PublicLab.Editor/issues/202) and could perhaps use some input and support in getting it finalized as a fullly formatted FTO. Would anyone who's done this before be willing to help them out? Thank you so much!

Well, I haven't done this before bt would be willing to help if possible

**Comment by SidharthBansal** [comment]
Congrats https://codein.withgoogle.com/winners/#winners.

**Comment by jywarren** [comment]
Hooray!!!! 🎉🎉🎉🎉

Thank you everyone for participating in GCI!

**Comment by gauravano** [comment]
Congratulations to all the Google Code-In winners and finalists :tada: :sparkles: :heart: 

![gci_result](https://user-images.githubusercontent.com/20878070/50781800-4b738100-12cc-11e9-8810-c3d48aa3174a.png)

**Comment by gauravano** [comment]
@kevinzluo @oorjitchowdhary @ValentinaTironi @JonathanXu1 @okonek @tsparksh @dinaelhanan  @CodeSarthak @mohitRJranjan

**Comment by geekychaser** [comment]
Congratulations to all 😍

**Comment by sagarpreet-chadha** [comment]
Wow !!! Thank you for evryone for participating in Google Code In :heart_decoration: !

**Comment by shubhscoder** [comment]
Congratulations everyone! Keep up the good work ! Also make sure that you all guide your juniors into this, create awareness among them regarding open source contributions, regarding google code in,etc. Thank you!

**Comment by oorjitchowdhary** [comment]
Hi everyone... Finally the `much-awaited` results are out! Congratulations to @kevinzluo and the Finalists of course @JonathanXu1 @okonek @ValentinaTironi Great work all! 🎉 😄 

7 weeks of code, excitement, and surprises.. It was an amazing journey! 
This is my first GCI and I'm really really happy for all! 

A **big big** THANK YOU to all the mentors @SidharthBansal @jywarren @gauravano @sagarpreet-chadha and others... Thank you for the guidance and your inclination towards this. 

A bunch of new things learned you people...

##### Congratulations to all the winners and finalists! 
and
### Cheers to our wonderful community -- `Public Lab` 🎈

**Comment by jywarren** [comment]
❤️❤️❤️ I just posted a big THANK YOU here: https://publiclab.org/notes/warren/01-07-2019/congrats-to-google-code-in-2018-participants

**Comment by gauravano** [comment]
To **ALL Google Code-In Participants**. I want to congratulate all of you :tada: , because, just by participating and dedicating your time in GCI, you have contributed to Open Source World :globe_with_meridians: . Some of you might have raised your first PR, some might have contributed first-time for an organization, and what not, but I guess, everyone learnt something new. 

The Open Source world is huge and full of opportunities, it's full of learning steps and it's up to you how much you explore. There are many Open Source programs which you can explore - GSoC, RGSoC, Outreachy, etc. As you have got familiar with FOSS, you can start preparing for these programs(if eligible). We at Public Lab participates in many of these programs, so have resourceful alumni available, so feel free to contact for suggestions, advice, etc. 

By means of FOSS, developers give back to the communities which build something meaningful for society, for their work, so we hope as you have learned from GCI, you would help us in coordinating GCI this year by becoming mentors and you can participate too(if eligible).  

I really loved every bit of collaborating with you all and yes learnt so much. Thanks for making this winter full of code. 

@kevinzluo @oorjitchowdhary @ValentinaTironi @JonathanXu1 @okonek @tsparksh @dinaelhanan @CodeSarthak @mohitRJranjan.

All the best for your future endeavors and would love to collaborate with you all again. 

Thank you all :heart: 
Gaurav  

P.S: Some Open source program like Outreachy don't allow GSoC students(if I remember correctly), so plan accordingly in which program, you want to participate in which order :)

**Comment by jywarren** [comment]
Hi, everyone - I just wanted to say, I am humbled by the care and power of our community. Years ago, I started coding in open source projects, and it seemed (not everywhere, but overall) a very lonely place - one where people were not likely to help each other get started -- so I'm so excited to be part of a community (and a movement) to change this, and to set a different tone and culture. 

You've all helped to make this possible, through your mutual support, and I feel so lucky to be working with you all. THANK YOU!

**Comment by gauravano** [comment]
Hi everyone, due to bug in Google Code-In website, @tsparksh's name was skipped at time of result decalaration. But, Google OSS team have updated the site and here's updated result

![img_20190108_035450](https://user-images.githubusercontent.com/20878070/50797730-cb650f80-12fb-11e9-802a-abc8fb0cdec7.jpg)

Congratulations to @tsparksh for being one of the finalist. 

Thanks!

**Comment by jywarren** [comment]
Hi, all - wanted to follow up with a pragmatic note -- @rexagod has implemented this PR which is really nice: https://github.com/publiclab/PublicLab.Editor/pull/206#issuecomment-451759446

It adds `grunt build` to the Travis file, so that Travis fails if `grunt build` has an error. This can help us to catch errors in the dependencies which `grunt build` uses to build! Many of you have noticed @dependabot opening issues on many of our repos. Sometimes we have to manually test if the new dependency is not included in the code, but just used to /generate/ the code. With this change, we can now rely on Travis tests to tell us if @dependabot -added updates break the `grunt build` task. Very useful! I suggest we adopt this change in `image-sequencer` and other JS libraries. Someone want to open some PRs? 😄 🎉

**Comment by jywarren** [comment]
Hi, all -I also started some code cleanup, and @shubhscoder has gotten excited about test coverage-- awesome! We've been kind of "stuck" at 91% coverage for a LONG time, and there are a few areas which need better testing: https://coveralls.io/github/publiclab/plots2

One is our controllers -- functional tests cover controllers, and we could be testing more of our controller code for sure! 

I wanted to highlight this PR I opened, which starts to remove some old code which I thought we didn't need anymore. https://github.com/publiclab/plots2/pull/4575

However, it turns out we do use this old-style error message system! We should refactor to use the standard Rails-based error reporting. I left some tips in my PR - would anyone like to try taking this on? It should positively affect our test coverage and simplify our code!

**Comment by jywarren** [comment]
Hello everyone! I wanted to note another big thing -- after 1 year of community outreach, Image Sequencer now has over 43 contributors and some real community momentum. I've opened a new issue to ask people to join a reviewers group for just that project -- @publiclab/is-reviewers -- in this issue:

https://github.com/publiclab/image-sequencer/issues/656

Hooray for a growing community! 🎉

**Comment by gauravano** [comment]
Anyone interested in opening next week's check-in? Thanks!

**Comment by Rishabh570** [comment]
Hi @gauravano, I would like to open it...do I need to copy the issue description?

**Comment by gauravano** [comment]
Hi @Rishabh570, great! You can copy the issue description and make some nice edits. You can add your own progress to issue body. You can add some interesting question/theme for the week.

Thanks!

**Comment by dinaelhanan** [comment]
Hey everyone! This week and this next, I'm kind of really busy (more culminating assignments, they end in 2 weeks though! + a hackathon) so I will probably be MIA, but I'm hoping to: 
- [ ] help out a lot more in image sequencer, since I've got more experience in JS than I do in Ruby, so I'm looking forward to that!
- [ ] explore and be more active on the public lab platform

Those are my two goals for the next week/weeks. Hope everyone has a great one!

**Comment by gauravano** [comment]
Hey @dinaelhanan! Nice to hear from you. All the best for your assignments and hackathon :smiley: . Thanks!

**Comment by Rishabh570** [comment]
@jywarren @gauravano @SidharthBansal I've just opened new weekly check-in, #4607 :)

**Comment by gauravano** [comment]
Closing this one as new check-In at #4607. Thanks!
