### ISSUE TITLE
database.yml missing from recently updated master branch

### ISSUE THREAD

**Issue by franktank** [publiclab/plots2#455]
### What happened just before the problem occurred
Pulled master branch, dependencies with database.yml no longer working (ex. rspec, rails console...)

database.yml doesn't exist but there is .yml.cloud9, .yml.example, etc

### PublicLab.org username
franktank

(to help reproduce the issue)

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by jywarren** [comment]
Hi, Franky - the database.yml file should not be version tracked, as it
specifies the local database setup. If we tracked it, there'd be a git
conflict every time we git pulled to the production server, since the
git-tracked version would not match the local setup and username/passwords.
You will need to copy one of the example files to make your own; i
recommend the sqlite one.

**Comment by franktank** [comment]
Okay excellent, thanks!
