### ISSUE TITLE
Consider how to show clusters of people “active over past 6 months”

### ISSUE THREAD

**Issue by milaaraujo** [publiclab/plots2#4560]
Hey @jywarren, could you make it clearer what you're thinking about this?

**Comment by jywarren** [comment]
I think this may need some input from @ebarry and
possibly @sagarpreet-chadha -- the idea is to brainstorm if there is a way
to highlight which regions of the world are seeing lots of activity. If we
feel the API can efficiently provide data for longer periods of time (and
we understand the limits if lots of people begin to post) perhaps this
could be achieved simply through the /people page but showing many many
people on the map. If that's the case, then this could in theory be
addressed through optimization, rather than through a unique API endpoint.
But I wanted to hear from others as to the possibilities and options here.
Thanks!

**Comment by mardelvalle** [comment]
I am going to jump in with a suggestion. If there is a concern about how many people from certain regions if the site becomes larger maybe instead of showing the differential based on the number of individuals it could be shown as percent of currently active users? For example, if there are 2000 active users in the past six months and 200 was from one region it could be indicated with 10%. Maybe on hover it could show the actual number of people.

**Comment by ebarry** [comment]
Cool idea @mardelvalle!
How do we decide regional boundaries? Maybe just continents to begin with?

**Comment by ebarry** [comment]
Just for context, a long time ago, we imagined overlaying a grid on the map on /people, and shading squares based on number of contributors: https://github.com/publiclab/plots2/issues/1070#issue-193899340

<img width="625" alt="screen shot 2019-01-10 at 10 38 24 am" src="https://user-images.githubusercontent.com/161439/50979144-e2eef480-14c3-11e9-98b3-c919ceb717b3.png">

I am not attached to this idea at all, just sharing prior thoughts. I really like where you all are going regarding showing "clusters of active people"

**Comment by sagarpreet-chadha** [comment]
Hi everyone ,
If i am getting this right , i would like to see the most active people (which would be calculated via an algorithm using their last 6 months contributions) with RED marker on /people map (instead of current normal black marker) .
Again just an idea , Liz may have something more interesting in her mind :)
Thanks !

**Comment by ebarry** [comment]
That sounds great @sagarpreet-chadha ! Do you like this idea?

**Comment by sagarpreet-chadha** [comment]
If we want rough idea of regions with most active contributors , then it seems like a good option .
If we want exact maths , then it more sense as to yours and @mardelvalle suggestions above . Thank you :)

**Comment by jywarren** [comment]
Hi, I think perhaps we should look to examples on other sites for how we'd
like this to be represented. Can folks try sharing some screenshots? Thank
you!

**Comment by milaaraujo** [comment]
Hey @jywarren, have you thought about adding a "last activity" column in the user table? Looking at the API code, several times we have to use a `join (:revisions)` only to get this information...

**Comment by milaaraujo** [comment]
I guess so! But it is just a suggestion, we can think about it in the future. :)

**Comment by milaaraujo** [comment]
From Jeff: 
>Let's say: optimization (#4561) will make this much easier, and we could set the default # of people to display much higher on /people.

**Comment by jywarren** [comment]
We'll close this out for now! I believe this is solved in the LEL people layer but we'll see as it grows!
