### ISSUE TITLE
Content Based Tag Filtering for Personalised Tag Recommendation System

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#4592]
This would be an addition to the User model, in https://github.com/publiclab/plots2/tree/master/app/models/user.rb

This would return a descending list of most-used tags, looking at a user's posts and tallying all the tags used on all their posts. This would start with just their notes + questions, but might later expand to:

* wiki edits
* comments on notes with tags
* tags created by the user

This may be a great source of suggested tags to subscribe to for @SidharthBansal and others working on increasing tag subscriptions.

**Comment by ebarry** [comment]
ooooo great idea!

**Comment by SidharthBansal** [comment]
This is a great idea. I will like to work on it once all the assigned Dec & Jan's pending work gets completed.
We will require to be thorough in details here before implementing it. Don't want to hurry up on this. This seems to be a medium project in itself.

**Comment by IshaGupta18** [comment]
Hey I love this idea, I was kind of thinking about a more personalised user experience (one way through tags) for my Gsoc proposal, so I would love to delve into this for the same, would that be okay @SidharthBansal if I consider this as one of the ideas?

**Comment by SidharthBansal** [comment]
This project greatly depends on the depth with which we can look at the issue.
As per the issue description I think it is relatively small issue compared to GSoC project. In case we are looking for flask integration so that the recommendation system can be built then it can be considered for GSoC else it cannot be as per my judgement. 
You can start working on this if you want. Also @jywarren please guide us whether we require MVC function and tests OR do we require dimension of ml to be included in this project?
Sorry, Jeff I changed the name. I actually thought the hyper parameters may change over time so we need ml techniques instead of mvc logic code. So, changed the title. Sorry in case I did wrong. What do you suggest ??

**Comment by IshaGupta18** [comment]
Yes I get it, if we really take this issue in depth only then it can be considered as a GSoC project, I was thinking of other things along with something about personalized tags for the same, that's why I asked you. Like if I can expand on the idea of a personlized feed ( I haven't thought about it in depth, I have some vague ideas) and include this as one of the features, will this be good?

**Comment by SidharthBansal** [comment]
Isha, we need to hold on this until Jeff comments. Integrating flask for ml
for many workflows is a HUGE step. It will be much bigger task then you
think.
We need the data preprocessing, data cleaning and a lot other things on the
tag before applying the recommendations. Also, there is tremendous other
things to be explored. So let's wait.
Simpler approach as Jeff indicated is using Js local storage or cache etc
inside the model and doing some db optimisations. It is simple approach.
Will require lesser time and energy but has limitations in future as the Js
storage has limited storage capability etc.
Let's wait for Jeff's reply.

**Comment by jywarren** [comment]
Hi all, i'm closing this as I think we are OK on this for now!
