### ISSUE TITLE
Refactor _answer.html.erb

### ISSUE THREAD

**Issue by dave-light** [publiclab/plots2#4595]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### The problem

Line 62 in _answer.html.erb is considerably long. We need to break it into shorter lines for readability.
```
<a href="<% if current_user %>'/answer_like/likes/<%= answer.id %>'<% else %>'#'<% end %>" data-remote ="true" tooltip-title="Helpful? Like it" class="btn btn-default btn-sm btn-like" id="answer-like-button-<%= answer.id %>" <% unless current_user %> popover-content="You must be logged in to Like the answer" <% end %> ><span id="answer-like-star-<%= answer.id %>" class="fa fa-star<% if current_user && !answer.liked_by(current_user.uid) %>-o<% end %>"></span><span id="answer-like-count-<%= answer.id %>"><%= answer.likers.length %></span> Likes</a>
```

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step solution

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Refactor** line 62, instead of one long line break it into smaller lines instead. 

**code link** - https://github.com/publiclab/plots2/blob/master/app/views/questions/_answer.html.erb

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by gauravano** [comment]
Hi @jywarren there are many places in our codebase where the length of line makes it look complex and difficult to read. Would you like to recommend the optimal length?

Thanks!

**Comment by jywarren** [comment]
I've read that 80 characters is a good # to aim for, and i think in coding
maybe even less... what's the max character width of GitHub's UI?

**Comment by dave-light** [comment]
Quick thought, instead of doing this myself, should I edit the issue and make it an FTO? It's perfect for someone who hasn't yet contributed.

**Comment by gauravano** [comment]
Yes, sure @dave-light! you can refer to FTO template from here - https://github.com/publiclab/plots2/issues/4440 and mention me or @publiclab/plots2-reviewers for getting it labelled.

 Thanks!

**Comment by gauravano** [comment]
Hi @dave-light, here's the markdown for FTO:

`Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Add**  fa fa-icon for store

**code link** - https://github.com/publiclab/plots2/blob/master/app/views/layouts/_header.html.erb#L70

now add this line of code `<i class="fa fa-shopping-cart" style="color: white" aria-hidden="true"></i>` 
inside `<a>` tag

![image](https://user-images.githubusercontent.com/24489162/50535836-09cc3300-0b74-11e9-81e3-823ac026937d.png)





- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)


### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)
`
Thanks!

**Comment by dave-light** [comment]
@gauravano thanks for the FTO markdown code, i've updated the issue. Please add FTO tag :-)

**Comment by vladdypwnz** [comment]
Greetings! 
First time contributor in your codebase.
Could I start with this issue ?

**Comment by gauravano** [comment]
Hi @vladdypwnz,  Welcome to Public Lab and you can start with this issue! Thanks!
