### ISSUE TITLE
Search typeahead two words or more bug

### ISSUE THREAD

**Issue by annhchen** [publiclab/plots2#4601]
Typing two words or more (i.e. "wetlands mapping") only pulls up "users" with typeahead. "Wiki" and "tags" keywords do not show up. See attached image.

Similarly, typing in two words concatenated "oiltesting" also pulls up weird typeahead results.

<img width="1328" alt="screen shot 2019-01-11 at 3 20 49 pm" src="https://user-images.githubusercontent.com/1396091/51058245-26299000-15b6-11e9-94a4-5c7ff8144b34.png">
<img width="1328" alt="screen shot 2019-01-11 at 3 19 38 pm" src="https://user-images.githubusercontent.com/1396091/51058256-2f1a6180-15b6-11e9-83c5-f08d7a9e16af.png">
<img width="1328" alt="screen shot 2019-01-11 at 3 20 57 pm" src="https://user-images.githubusercontent.com/1396091/51058262-32155200-15b6-11e9-9abd-95064eb34f2b.png">

**Comment by ebarry** [comment]
Tagging in @milaaraujo who knows this system best <3 <3 <3

**Comment by milaaraujo** [comment]
Right now I'm working on the UI/API improvements for geographic features project, but after I finish it I can work on this one. I just don't know when it will be! So if anyone is interested, go ahead and I can help with any question about the current code.

**Comment by ebarry** [comment]
Is there a way to temporarily disable typeahead? It is so unpredictable and unexplainable that at this point I do not think it's appropriate to have running on the live site.

**Comment by milaaraujo** [comment]
So, we have two problems here: how the results are returned (only users) and the set of results (weird typeahead results).

1 - It is not a problem that happens only when we search two words, for example:
![screenshot from 2019-01-17 08-34-51](https://user-images.githubusercontent.com/4355017/51333874-7e87e400-1a33-11e9-800c-43888e53087d.png) It happens because we use this [dependency](https://github.com/bassjobsen/Bootstrap-3-Typeahead) to for our navbar and search typeahead results. Part of the problem was documented by Steffani here (#3517).

2 -  The results are not "wrong", this is not a "bug". For exemple, "oiltesting" returns -https://publiclab.org/notes/stevie/03-05-2015/gulf-coast-build-your-own-spectrometer-event - because in the post body we have:

>Spectrometers can be useful in examining everything from the make up of your beer, to **oil testing** and food grade sampling.

So this is the way the full search works... We can stop using the full search and the results would be more predictable, I guess. What do you think, @jywarren?

**Comment by jywarren** [comment]
Just closing this up as I believe it is being addressed through a combination of UI and search functionality changes in https://github.com/publiclab/plots2/issues/5708. Thanks!
