### ISSUE TITLE
Banned Accounts and probable API bug

### ISSUE THREAD

**Issue by rexagod** [publiclab/plots2#4609]
Quoting the gitter chatroom, I mentioned

> Plots2 currently returns a "banned" message for https://publiclab.org/profile/rexagod
> Same results in case of https://publiclab.org/profile/dsxv007 and https://publiclab.org/profile/geekychaser
> However this doesn't happen in case of mods and admin. https://publiclab.org/profile/gauravano https://publiclab.org/profile/warren
> Hope I'm not vague. But I think this might be something that's worth looking into.

Edit: As of now, @gauravano has unbanned all of us.

Also another concern of mine was that @jywarren's profile wasn't returned in the output payload, is this a bug?

**Comment by jywarren** [comment]
Maybe connection to #4522 ...

**Comment by gauravano** [comment]
Yes, all the issues #4522 #4569 and this one all are interconnected and same. This one just highlights on the API issue too.

The issue is some users are not able to login via any way. When they try login/signup form alert is shown that user is banned. And, when those same user try OAuth, a alert comes up saying "Signed In" but in reality they were'nt signed in which is found while having a Gitter chat with @rexagod.

This is case with only some of the users and somewhat related to drupal_user deprecation maybe. 

cc @jywarren

**Comment by jywarren** [comment]
Hi, thanks - can you clarify what you mean by `@jywarren's profile wasn't returned in the output payload, is this a bug?`?

**Comment by vladdypwnz** [comment]
Hey there, newcomer to the codebase. Just added a commit(#4615) for first-timers-only and managed to host and run public lab locally. When I try to login in with any of the following usernames indicated in the installation process(user, moderator, admin), I get the `User 'user' is banned` message.   

Maybe this helps pinpoint the problem further ?
Hope it helps.

**Comment by rexagod** [comment]
I was fiddling with the API for some reason when I noticed that your profile didn't come up here [`https://publiclab.org/api/srch/profiles?query=warren`](https://publiclab.org/api/srch/profiles?query=warren), but it does here, [`https://publiclab.org/api/srch/profiles?query=jywarren`](https://publiclab.org/api/srch/profiles?query=jywarren). Note that this didn't occur for any other user I tested it on, and their payloads were an exact match of their `/profile/_` names. While this may not seem that big of a problem at first, it can actually hinder the auto-recommend system (At.js) of the Editor, at least for @jywarren's mentions.

**Comment by jywarren** [comment]
Hi, all! I believe I've found that after the `DrupalUsers` upgrade, we aren't explicitly setting status in the seeds file. I've made a change here: https://github.com/publiclab/plots2/pull/4625

You should be able to run `rake db:seed` to add these, though you may need to clear your database first. Thanks, i hope this helps!

**Comment by jywarren** [comment]
Can folks check back in here with whether this worked? Thanks!

**Comment by rexagod** [comment]
It's working @jywarren. Thanks!

**Comment by vladdypwnz** [comment]
Hey, I'm getting the following error after running `rake db:seed`.

`ActiveRecord::RecordInvalid: Validation failed: Email has already been taken, Username has already been taken, That username is already taken. If this is your username, you can simply log in to this site.
`

Any ideas?

**Comment by jywarren** [comment]
Ah, I think you may need to flush your database as they wouldve been
already created the first time. Is there maybe a simple command to flush?

On Jan 16, 2019 10:43 AM, "Vlad" <notifications@github.com> wrote:

Hey, I'm getting the following error after running rake db:seed.

ActiveRecord::RecordInvalid: Validation failed: Email has already been
taken, Username has already been taken, That username is already taken. If
this is your username, you can simply log in to this site.

Any ideas?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/issues/4609#issuecomment-454825764>,
or mute the thread

**Comment by vladdypwnz** [comment]
I dumped and created my db again but the rake db:seed didn't worked for me. In any case, I can now login with user "user".
