### ISSUE TITLE
Subscription Prompt next to Topics on Dashboard

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4644]
![image](https://user-images.githubusercontent.com/20972099/51338782-c13bd180-1ab0-11e9-89d0-c442e82bfb52.png)

Tthis isn't like a normal view here, the view is being rendered through cache, from an entry in the database, here are the links:
https://github.com/publiclab/plots2/blob/9f7cfc47ded41ed3a7370c66a9c4f7af9704af59/app/views/sidebar/_dashboard.html.erb#L38-L41

https://github.com/publiclab/plots2/blob/9f7cfc47ded41ed3a7370c66a9c4f7af9704af59/app/helpers/application_helper.rb#L57-L64

So the view is rendered from the database's entry. Does this make sense?

@jywarren can you help us how we can know the tags passed in this section? We need to pass them in the Subscription button.

**Comment by SidharthBansal** [comment]
Part of #4131

**Comment by jywarren** [comment]
Hmm, I think we may need to hold on this for the time being, as I can't think of a way to do this efficiently esp if the tags are updated later.

**Comment by jywarren** [comment]
OK, my comment from #3932 could potentially help us prompt subscriptions for tags from another source, adding a new prompt below instead of replacing this section. 

The idea is to identify tags people have been active on, but aren't subscribed to -- something like
`user.active_topics(limit)` -- which could return a max of `limit` tags for:

1. tags user is not subscribed to
2. which occur a lot on nodes they've posted
3. which occur a lot on nodes on which they've commented
4. we could limit this using time if we wanted to optimize! Or cache it.

Then we'd have a list of likely candidates to prompt them to subscribe to.
This is an unrelated project but could be swapped in for this one (since I
agree with your comment above).

Then we could use `user.active_topics` to prompt users in places like the
dashboard or tags page, with something like "You've been posting a lot on
[air-quality]. Click here to follow that topic."

**Comment by SidharthBansal** [comment]
@jywarren it will be really helpful if you can tell some good resources for
cache management and how we do this in plots2 as I have never worked at
plots2 with cache. I think it will be just a model function in tags model.
It is interesting idea. You suggested me this in August but I was never
able to find time on this due to gci. Will do this first.

**Comment by SidharthBansal** [comment]
I think 
``
  def self.related(tag_name)
    Rails.cache.fetch('related-tags/' + tag_name, expires_in: 1.weeks) do
      nids = NodeTag.joins(:tag)
                     .where(Tag.table_name => { name: tag_name })
                     .select(:nid)

      Tag.joins(:node_tag)
         .where(NodeTag.table_name => { nid: nids })
         .where.not(name: tag_name)
         .group(:tid)
         .order('COUNT(term_data.tid) DESC')
         .limit(5)
    end
  end
``
can help me using cache.

**Comment by jywarren** [comment]
This is actually a really great resource! https://guides.rubyonrails.org/caching_with_rails.html

**Comment by SidharthBansal** [comment]
Okay thanks I will try.

**Comment by SidharthBansal** [comment]
I read this two years ago. Will do a revision.

**Comment by jywarren** [comment]
We'll merge this into the new dashboard design which has plentiful subscription prompts! #6072 Thanks!!!
