### ISSUE TITLE
give authors of "seeks responses" posts ability to approve responses to their post

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#4645]
A number of our post types invite "responses" -- esp. useful for classroom assignments, where students can post a response to complete an assignment: https://publiclab.org/wiki/requesting-responses

https://github.com/publiclab/plots2/issues/375 is where we originally implemented this.

To smooth this experience, we could give the original author permission to moderate responses. This could include:

* [ ] auto-approving responses but letting orig. author mark them as spam
* [ ] displaying unapproved responses (greyed out) on the orig. post and allowing orig. author to approve
* [ ] including orig. author in moderation email notifications

This is lower priority but pretty neat. Maybe we could build on it to expand out the idea of moderation on a per-tag basis, to help better split up and share the work of moderation.

**Comment by dave-light** [comment]
Hi @jywarren @gauravano I'm interested in working on this. 

Perhaps allowing the original author (and moderators of course) to approve responses would be most effective in my humble opinion. The original poster may not be very active in approving responses but I suppose this is better than auto approving responses and hoping the original author will mark it as spam.

Correct me if I am wrong but it sounds like there's quite a problem with spam. If the issue was small then auto approving could make sense. It would avoid a helpful response going unapproved, to the expense of the community. Posts could be auto approved unless detected as spam (I'm preparing a GSoC proposal addressing this example).
