### ISSUE TITLE
Add testing for MapModule's proper construction

### ISSUE THREAD

**Issue by rexagod** [publiclab/plots2#4717]
Aims to identify issue #4714 if it happens again. I think we can check to see if the [code below](https://github.com/publiclab/PublicLab.Editor/blob/master/src/modules/PublicLab.MapModule.js#L28) throws an error or not.

```js
     _module.blurredLocation.panMapToGeocodedLocation("placenameInput") ;
```

Reference - https://github.com/publiclab/plots2/issues/4714#issuecomment-458284117

**Comment by rexagod** [comment]
https://github.com/publiclab/PublicLab.Editor/blob/master/src/modules/PublicLab.MapModule.js#L28

**Comment by rexagod** [comment]
@jywarren Can we proceed with this?

**Comment by sagarpreet-chadha** [comment]
Hi @rexagod !

`panMapToGeocodedLocation` this function of LBL uses Google API .

The error in #4714 was due to script not being loaded .

- I guess we can write a test to confirm that the script is being loaded or not before the actual loading of the page content , that would make us more confident that this will not happen again  

See this comment here (i changed the code where we were loading script earlier) : 
https://github.com/publiclab/plots2/pull/4608#discussion_r248002791

- Also , in LBL if we can write some` if condition` in the `panMapToGeocodedLocation` function when it uses the google API's function --- to check if that function exists or not ! 

What do you think ? Would you like to work with me on this one ?
Thanks 😄 !

**Comment by jywarren** [comment]
Ah yes actually I like the idea of testing if the API exists before loading
it, that'd have stopped this bug from cascading to other issues. Great idea!

I wonder though if the test @rexagod proposes would catch issues like
yesterday's, where the issue was in the deployment setup? Maybe still
worthwhile but let's try to imagine exactly what scenarios it'd catch!

**Comment by jywarren** [comment]
So i like the first approach mainly because it allows us to stop the error
from cascading and disrupting other functionality on the site, which i
think is good practice -- it's pragmatic and quick to implement with only 1
line of code.

For the second, I think the issue may still be that this won't come up in
tests to be caught at all, since it was an issue with deployment, not code
-- we could, perhaps, try to implement a system test (new feature in Rails
5.1+) to actually boot the whole site + javascript, and monitor for errors
on various pages that way, which would be interesting, although a bit
heavy: https://github.com/publiclab/plots2/issues/3683
