### ISSUE TITLE
Online Location For API Developer Documentation

### ISSUE THREAD

**Issue by skilfullycurled** [publiclab/plots2#4750]
Hi,

Is there a place online where the [developer documentation](https://github.com/publiclab/plots2/tree/master/doc/app) (the one that gets generated with the classes, methods, modules, etc.) is located?  

If not, feature request: Have an online location where the developer documentation is located such as https://code.publiclab.org/docs...?

I downloaded the repo and it works just fine locally but it'd be nice to have it in a central place online.

Thanks!

**Comment by jywarren** [comment]
Yes, there's a link at https://publiclab.org/api, with docs and a web
interface! Is that what you're looking for?

**Comment by skilfullycurled** [comment]
I don't think it is, but I saw that and it's _awesome_ by way!  That's the real deal right there.

I'm talking about the stuff that can be found in [here}(https://github.com/publiclab/plots2/tree/master/doc/app) which yields a document like this:

<img width="262" alt="screen shot 2019-02-02 at 10 51 46 am" src="https://user-images.githubusercontent.com/950291/52166265-0bd86300-26d9-11e9-8480-c2d633bd0d46.png">

**Comment by jywarren** [comment]
Ah yes, be aware that hasn't been regenerated in a while!

**Comment by skilfullycurled** [comment]
Okay, so if I'm understanding the implication, there isn't an online location, then, and probably won't be due to the need to constantly regenerate the docs?

**Comment by jywarren** [comment]
Do you mean online differently than at
https://github.com/publiclab/plots2/tree/master/doc/app ? the docs would
publish at publiclab.org if we moved them into the public folder, would
that be helpful? Ah, i see, because GitHub doesn't actually render the
HTML, right?

I think there was an issue re-generating them in the most recent release of
Rails and we just haven't figured it out yet.

Looking into it, seems like they removed the `rake doc:app` command in
Rails 5:
https://stackoverflow.com/questions/38691498/rake-docapp-is-not-working-in-rails-5-api

bah! But their reasoning is sound - this doesn't really generate docs that
are that useful, and people did not (like us) keep generating it --
https://github.com/rails/rails/commit/cd7cc5254b090ccbb84dcee4408a5acede25ef2a

We've slowly begun to use the tests to demonstrate usage, although that's
not the same thing as full documentation (although it never goes out of
date). There's a data model diagram in the README that's kept up to date.
And as we incorporate CodeClimate recommendations, our code is becoming
simpler and containing fewer methods per file, which contributes to
readability.

**Comment by skilfullycurled** [comment]
Actually, those tests are great.  I mean, the best documentation is the type where you get to see the functions, the params, and then an example of that function.  Never having had to do unit testing, I hadn't considered that as a side effect of good tests!  I'll think on what a good sentence might be and where it could fit in the wiki to express their utility in seeing how the functions work.

Thanks, Jeff!

**Comment by jywarren** [comment]
We can do better on tests being documentation. 

You might like this -- one time i got really into this idea while coding a pixel-based dungeon adventure game platform (its a really good idea 😂), and I wrote a set of tests that actually narrate a scene in the dungeon:

http://pxlqst.com/test

https://github.com/jywarren/pxlqst

There's a lot going on in this project https://github.com/jywarren/pxlqst#map-editor

lol

**Comment by skilfullycurled** [comment]
@jywarren, I love it.  It's the unit test equivalent of the [Vim Adventures](https://vim-adventures.com/) game.  How much do I need to contribute to the crowdfunding campaign for you to name it, "Return to Dork".
