### ISSUE TITLE
Dynamic incremental solution for graphs.

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#4754]
The new graph on stats page has a function https://github.com/publiclab/plots2/blob/master/app/views/stats/index.html.erb#L247-L264 we want to update this so the increment `x += 604800000;` is changed to get the next value from the array  `months`.

**Comment by rexagod** [comment]
## Dynamic incremental solution for graphs
### Current (static) incremental function
````js
function generateDayWiseTimeSeries(s, count) {
      var values = [
       <%= @graph_notes.values.collect {|ind| ind[1]} %>,
       <%= @graph_wikis.values.collect {|ind| ind[1]} %>,
       <%= @graph_comments.values.collect {|ind| ind[1]} %>,
      ];
       var i = 0;
var months = <%= @graph_notes.values.collect {|ind| ind[0]} %>
      var series = [];
      var x = new Date(months[0]).getTime();
      while (i < count) {
        series.push([x, values[s][i]]);
        x += 604800000;
        i++;
      }
      return series;
    }
````
### Proposed changes
- **A getWeek function down on Date object's prototype chain that returns current week (or in your case, modified week relative to the value given to it (months[n])). We can use that to refer to different weeks that will automatically get updated depending on their respective dates rather than a static increase of 604800000.**
````js
Date.prototype.getWeek = function(){
  var d = new Date(Date.UTC(this.getFullYear(), this.getMonth(), this.getDate()));
  var dayNum = d.getUTCDay() || 7;
  d.setUTCDate(d.getUTCDate() + 4 - dayNum);
  var yearStart = new Date(Date.UTC(d.getUTCFullYear(),0,1));
  return Math.ceil((((d - yearStart) / 86400000) + 1)/7)
};
````
- **Since we want the week number _relative_ to the month[n] passed to it, we can instantiate the Date object to months[n], and get back the week number accordingly, that is, `new Date(months[n]).getWeekNumber()`**
### Final function (after prototype chaining getWeek to the Date object)
````js
function generateDayWiseTimeSeries(s, count) {
      var values = [
        <%= @graph_notes.values.collect {|ind| ind[1]} %>,
        <%= @graph_wikis.values.collect {|ind| ind[1]} %>,
        <%= @graph_wikis.values.collect {|ind| ind[1]} %>,
      ];

      var i=0;
      var months = <%= @graph_notes.values.collect {|ind| ind[0]} %>
      var series = [];
      var x = new Date(months[0]).getWeekNumber();
      while (i < count) {
        series.push([x, values[s][i]]); //note that x is no longer a thirteen digit decimal
        x++;
        i++;
      }
      return series;
}
````

> so I was wondering if there is a way to just push each of the values to the series array and do away with this increment code x += 604800000;

I think this should do it, Cess.

**Comment by cesswairimu** [comment]
Thanks @rexagod on it
