### ISSUE TITLE
Tests failing for new sqlite database

### ISSUE THREAD

**Issue by ananyo2012** [publiclab/plots2#478]
### What happened just before the problem occurred
When running `rake test` with the new sqlite database I am getting these errors.
https://gist.github.com/ananyo2012/12240a1a59c0cc5287b138ebdf6e8f6e

These were not failing in our previous mysql database.Also a **test.sqlite** file is created when running tests. So it must must be added to .gitignore so that it doesn't get accidentally committed with other changes.

**Comment by jywarren** [comment]
Hmm, rake test shouldn't use the development database at all, since it
generates a new test.db on its own.  Can you post the errors?

Thanks for reporting!

**Comment by jywarren** [comment]
Oh sorry I see you posted the errors. I'll try to get to them soon.

**Comment by ananyo2012** [comment]
@jywarren Sorry for the confusion. I meant the sqlite database that is used now. Should I make a commit add the test.sqlite in .gitignore?

**Comment by jywarren** [comment]
Hi, @ananyo2012 - sorry, i've been in meetings last week and just catching up now. Yes, please do add the test database to the .gitignore, thank you!  But as for your tests, I'm switching to an sqlite db and testing that now.

**Comment by jywarren** [comment]
OK, i see there's a constraint that sqlite is more strict about than mysql:

    SQLite3::ConstraintException: NOT NULL constraint failed: comments.thread

I'm removing that constraint as we don't use the thread column.

**Comment by jywarren** [comment]
Thanks, I had been running all tests on mysql, and overlooked this. Very good catch, many thanks. Just jumping in here, I also see: 

    NoMethodError: undefined method `to_datetime' for 1459721088:Bignum

I think I've fixed this in a local copy, but am chasing some more test failures. 

And finally: 

    SQLite3::SQLException: cannot start a transaction within a transaction: begin transaction

I'm wondering if during tests, or even in development, we can disable nested transactions, so we could maybe put the transaction in an `if Rails.env == 'production'` conditional? Will try this, and have to think through if that'd break anything.

**Comment by jywarren** [comment]
Sqlite is also case sensitive by default. It can be [made non-case sensitive](http://stackoverflow.com/questions/973541/how-to-set-sqlite3-to-be-case-insensitive-when-string-comparing) if need be, using `COLLATE NOCASE` as in:

    SELECT * FROM ... WHERE name = 'someone' COLLATE NOCASE

But since we only use this in development and test, but not production, I think we should just make our test usernames match. We might want to consider downcasing all usernames during save, and in a migration? Not sure what another solution would be.

**Comment by jywarren** [comment]
I'm kind of guessing on the nested transactions, that the nesting is happening during testing because tests are run in transactions? So we could disable the transactions *only* for tests, if that works... have to think about it more and try it out. Tests shouldn't have issues with concurrency; I assume they're run serially. 

Will have to work on this a bit tomorrow, sorry!

**Comment by jywarren** [comment]
Getting close on this fix, sorry its taking me a while!

**Comment by jywarren** [comment]
OK, got it. See #483 - will merge this tomorrow.

**Comment by ananyo2012** [comment]
@jywarren Ok great! Great fix Jeff! Now we will have tests passing in sqlite database too.
