### ISSUE TITLE
New changes in install_cloudnine.sh

### ISSUE THREAD

**Issue by ananyo2012** [publiclab/plots2#479]
### What happened just before the problem occurred

Now that there is no development.db database in the master branch of the repository the cloud9 deployment no longer works properly. A new user won't be able to see the the deployment running as there is no development.db file. 

We need to change the **database.yml.cloud9** file and also copy and rename the **development.sqlite.example** file to **development.sqlite**. Should I get this issue fixed?

**Comment by jywarren** [comment]
Yes please! Very good catch, thank you. Please submit a PR with `database.yml.cloud9` changed to point at `development.sqlite` instead of `development.db`

But please do not change `development.sqlite.example` -- new instructions in the README tell users to make a copy themselves named `development.sqlite` -- because if we version track that database, it'll keep getting included in submitted pull requests. The actual used database file should be outside version tracking.

**Comment by jywarren** [comment]
And yes, also we should include a line in `install_cloudnine.sh` as follows:

`cp development.sqlite.example development.sqlite`

Thanks!

**Comment by ananyo2012** [comment]
@jywarren Yes I was going to make the same changes. I will make a PR soon with the changes mentioned.

**Comment by jywarren** [comment]
Great, thanks!!!

**Comment by ananyo2012** [comment]
@jywarren Please review the PR. I have made the cloud9 fixes. I have also added test.sqlite file in gitignore.

**Comment by jywarren** [comment]
Merged, thanks!
