### ISSUE TITLE
Weekly Community Check-In #11 - "Funny/Awesome moment" 

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#4879]
Hi everyone  :wave: !

We all at Public Lab  :balloon: - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. The goal of our Community Check-In is for every community member to share something about their work from the past week and about their current week's goal :dart: . You are also welcome to share fun-fact :smile:  , new ideas  :bulb: , your learning goals :ballot_box_with_check:  .

If you're new here, welcome :balloon:, and please comment a Hello message below, we love to work with you. If you're looking for new issues, please try some of our first-timers-only issues.

We're SO EXCITED to have your help!

Is there anything, you would like to share with us from last week's work? What is your plan for this week?

If you have not planned yet, just leave a Hello! so that we know that you are in sync with us :arrows_clockwise:   and doing well!

As always, if you're waiting for a review, or if you're stuck, you can request help here, leave a comment on your issue with @publiclab/reviewers mentioned, or ask the community in our [Gitter](https://gitter.im/publiclab/publiclab) chatroom :open_hands: .

### Gitter
Gitter is an active chatroom in our community and we'll be sending weekly reminders about check-ins there. Be sure to sign up there for these updates or just to join the conversation :pager: .

### This Week's Theme

There are many funny and awesome moments in everyone's developer journey, like when you were finally successful in solving a  bug(which gave you headache for few hours) or maybe when you developed something coool and was really proud of. I bet everyone would be having something(some moments) to share, so go on and share your developer journey funny/awesome/memorable moments. And, don't worry no one's judging, so feel free to share.
  
Since open source is all about community and helping others, let's find some issues which might be good for someone else who is contributing or just beginning and help them solve it. Let’s expand our community as much as we can! :tada: 

### Summer of Code
@jywarren has started a brainstorming post for the ideas page for Summer of Code 2019 -It would be best to get some ideas into the discussion from the fellow community member before time. People have been brainstorming already - let's do it together!
https://publiclab.org/notes/warren/01-02-2019/brainstorming-for-summer-of-code-2019
And this is the official idea’s page:
https://publiclab.org/wiki/gsoc-ideas 

### Software Contributors Survey
This survey is conducted on a yearly basis to improve our experience.
https://goo.gl/forms/4VVMO8dOijRj6BUA3
The form will remain open until early March, but don't wait to respond! This one’s for us!

### MapKnitter

Some great planning and discussions are going on in our MapKnitter repo, do check them out! We are welcoming new contributors there as well, so anyone is welcome to chime in!

cc
@mohitRJranjan @milaaraujo @kevinzluo @Rishabh570 @sashadev-sky @geekychaser @shubhscoder
@sidntrivedi012 @SidharthBansal @cesswairimu @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @Ishagupta18 @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1, @uzorjchibuzor, @eli6, @rexagod, @dinaelhanan, @dependabot[bot], @oorjitchowdhary, @wanzulfikri, @mohitRJranjan @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999  @romanrodriguez @Dhiraj240 @codeIriss @rishabhc32 @chirag-singhal @Saurabh19126848_twitter @IgorWilbert @dhruvgupta167 @vrk99 @pdurbin @dave-light @HarshKhandeparkar @aashna27 @Harshithpabbati @marieram @swiatek7 @kaunair

Thanks and keep contributing! Contributing to Public Lab means contributing to the Environment.    

People who did the check-ins-
Gaurav Sachdeva (@gauravano )
Sidharth Bansal (@SidharthBansal)
Cess (@cesswairimu )
Harman Jolly (@CoderJolly )
Rishabh Rawat (@Rishabh570 )
Sasha Boginsky (@sashadev-sky)
Rishabh Kr Bothra (@geekychaser)
Shubham Sangamnerkar (@shubhscoder)
Siddhant N Trivedi(@sidntrivedi012)
Isha Gupta (@Ishagupta18)
Gaurav Sachdeva (@gauravano)
Have a great week everyone :balloon: :tada: :sparkler:

**Comment by gauravano** [comment]
Mentioning some new contributors @marieram @swiatek7 @kaunair @sidntrivedi012 (mention limit exceeded in above comment)

**Comment by gauravano** [comment]
Hi everyone!

I have many moments to share :p but let's start with one related to Public Lab only. 

It happened while I was starting with the Public Lab (Oct 18, 2017). I was working on an issue and trying many things on localhost. After doing some work on the issue, I tried to post a question on the localhost for trying my changes. The changes didn't work, wanna guess why?

the production website publiclab.org was also open when I was working so I posted the test question on the production website(:man_facepalming: ). I guess I got troubled due to the similar interface of localhost and production website. 

there is more to it, you know moderation of new-comers' posts take place at PL. Yes, I got banned from the website(lol). :fearful: I read the moderation email and emailed moderators group with the apology.

Thank you @ebarry for unbanning me :laughing: 

**This week's goal**
I have exams going on right now, so will be spending very less time. I would be back by Thurs evening or Friday. 

Happy a great week everyone :+1:

**Comment by Yugandhartripathi** [comment]
Hi everyone!

I will share with you all a recent story that happened roughly a month ago, 

It was the day I got the invite to publiclab organisation and I was super pumped to contribute more and more but soon after I realised that, I need better understanding of Ruby and Rails so I decided to take a step back and started with the [Ruby on Rails book by Michael Hartl](https://www.railstutorial.org/book) after completing 10 or 11 chapters I had a site with full auth,user index and profiles ready and I was proud of my progress so I decided to show it to my friends the next day.
As we all know rails has a lot of magic in it, some of the dark magic showed up that day and out of nowhere I started getting the error that your ruby version is 2.6.0 but in gemfile it is mentioned 2.5.1. I won't go into detail regarding hours of stackoverflow and github issue threads I wandered that day just that it took me a full reinstall of ruby to fix that. I still don't know why rvm use or changing version in gemfile didn't work.
I guess we will never know because a magician(rails) never reveals the tricks right?

## This week's Goals/To-do
I have a hackathon finale coming up this weekend, will spend most of my time prepping for that.

So that was me and my adventures in the magical world.
Hope you all have a great week. :+1:

**Comment by gauravano** [comment]
Our efforts and contributions have been appreciated at Texas Barnraising. Thank you @Zengirl2 :blush: :heart: :100: 

![tx_barn](https://user-images.githubusercontent.com/20878070/53346411-fe5f7300-393c-11e9-9c83-e158e12c84f4.png)

Tweet here:  https://twitter.com/zengirl2/status/1099475378517745665

**Comment by ebarry** [comment]
Yes thanks for posting leslie's tweet about the coding community!
If you are a Twitter user may I please encourage you  to respond to the
post and say hi and maybe even a "You're Welcome!"

Thanks all

**Comment by Zengirl2** [comment]
@gauravano Jeff gave a lightning talk about the success of the Welcome Page and I was like whoa, back up to the slide with everyone's pic so I can tweet. I'm really excited by this because it's really hard to find beginner open-source projects that are welcoming. You all have proven that it works and the searches are getting better and better on the site, as well as all the other improvements. Keep doing you! :fireworks: :star2: :trophy:

**Comment by niravasher** [comment]
Hey everyone
Its been a month I started contributing to open source. At first I thought it to be very difficult and quite big but soon realized that it is very interesting and lively.
I was going through many organizations at first and after looking at the projects built by them, I got amazed by the technologies people are making. I was just like I couldn't ever think like this before. I love the way people be creative and find out what catches the human brain and convert it to technology using hardware or software.
This literally makes Satya Nadella's statement "Believe in making the impossible, improbable" hit straight to my heart.
The most exciting part is to meet so many new genius minds work together creating products, solving issues and building this multi billion dollar industry.
Yes it is a bit difficult and requires hard work but it gives pleasure after it is completely done. This new world has opened lot of new doors for me, given me a lot of ideas, kept me motivated and helped me in every way possible. I am looking at life ahead with a completely new perspective.
A big shout out to all the contributors. I wish all of them good luck.
Thanks

**Comment by gauravano** [comment]
Hey @Yugandhartripathi, you're always welcome to open new issue regarding installation problem and we also have some hints [here](https://github.com/publiclab/plots2/issues/3840). Thanks!

**Comment by cesswairimu** [comment]
Hey all,

I once reused a poster when writing a blog post on the website without reading its copyrights Liz emailed me and I freaked out thought the owner might sue me or something :smile: changed the image immediately and now I am always cautious when reusing images from the internet 

#### Week goals
* Finish consolidating range and stats page
* Figure out a way to have the new graphs expandable on zoom out
Nice week :balloon:

**Comment by Dsxv** [comment]
Hi everyone ! I ended up showing after a month actually and I am sorry for that T.T. because of exams ( still going on )  , assignments and lot of attendance !
 But well nothing to worry now as all the college work is under control for this sem :D .
I started contributing a month back and @SidharthBansal  and @gauravano  were always there to help me ( I am very grateful for that ) !
I once again look forward to working with all of you ! 
Target : Looking forward to work up on issues relating to  leaflet-environmental-layers , plots2 !   
Thank you for having me be a part of this community !

**Comment by jywarren** [comment]
Hi, all! 

Love the topic this week. My funniest moment was probably... I was on vacation once, and took a boat trip for a few days. On the first day, I got a cell signal from the shore 📶 ⛵️, and got a bunch of emails downloaded. Suddenly I saw one said "oh no, the website is down, what do we do? Jeff's on vacation!" -- and as I started to type back, i lost signal. 📵 😱 ... but really i was on vacation and shouldn't have worried. Offline time is offline! 🏖 🌴 😴 🍸 

Loved your story @cesswairimu ! But don't be afraid, that's why we are creating open source content so that people can reuse without asking. Gotta change the world bit by bit! 🙌 

Also - just reporting back on the Outreachy topic from last week's check-in - we have been accepted to Outreachy! You can read more here and I'll be posting a welcome soon: https://www.outreachy.org/communities/cfp/public-lab/

We've also been accepted to Google Summer of Code! https://opensource.googleblog.com/2019/02/gsoc-2019-organizations.html

It's going to be a great summer!!! 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Comment by shubhscoder** [comment]
Very nice checkin @gauravano ! Congratulations everyone, PublicLabs has again made it to GSOC ! Great achievement. Looking forward for an exciting summer ahead :stuck_out_tongue_closed_eyes:!
This week I would work on #4493 and try to get it merged as soon as possible. Thank you!

**Comment by sashadev-sky** [comment]
Hi everyone,

This week I have been working on allowing multiple image selection for the leaflet.DistortableImage library, which will eventually be integrated into mapknitter. 

I don't have any funny stories off the top of my head but, for me, every time I start to understand how to use a new library is an awesome moment for me. Just started getting more involved with the Leaflet library this week and at first was pretty lost. Now getting down some working code.  👍

Thank you!

**Comment by SidharthBansal** [comment]
Congratulations everyone, PublicLabs has again made it to GSOC !

**Comment by sashadev-sky** [comment]
@gauravano do you think it would be helpful to delete the people that are mentioned in the list of people who have opened a check in already? to make room for new people added?

**Comment by sashadev-sky** [comment]
Also who would like to open next weeks check-in! 🚀

**Comment by uzorjchibuzor** [comment]
I can open checkin. What do I need to do?

**Comment by gauravano** [comment]
> @gauravano do you think it would be helpful to delete the people that are mentioned in the list of people who have opened a check in already? to make room for new people added?

Yes, let's clear it in the next check-in. Thanks @sashadev-sky!

**Comment by gauravano** [comment]
> I can open checkin. What do I need to do?

Hey @uzorjchibuzor thanks for volunteering. You have to open new community check-in by Monday evening. You can refer this doc - https://github.com/publiclab/plots2/blob/master/doc/CHECKINS.md for help. If you have any questions, feel free to ask here. Thanks!

**Comment by sashadev-sky** [comment]
@gauravano I had a minute so I cleared it now. @uzorjchibuzor please take note to open the next check in based on the updated list of mentions (just updated a minute ago). Thank you!

**Comment by gauravano** [comment]
Hey @uzorjchibuzor, you haven't opened any Check-In as I can see in issues. Are you still interested?

**Comment by Harshithpabbati** [comment]
@uzorjchibuzor if you aren't interested in it.Then i like to take it up 😁

**Comment by sashadev-sky** [comment]
@gauravano I totally misaccounted how the mentions work! Removing our names from the first list is not useful.. now we will not be mentioned. Reverting that back asap. 

@Harshithpabbati open it tonight if @uzorjchibuzor doesn't? I think maybe he could be experiencing wifi connectivity issues.

**Comment by sashadev-sky** [comment]
@gauravano I totally misaccounted how the mentions work! Removing our names from the first list is not useful.. now we will not be mentioned. Reverting that back asap. 

@Harshithpabbati open it tonight if @uzorjchibuzor doesn't? I think maybe he could be experiencing wifi connectivity issues.

**Comment by sashadev-sky** [comment]
@gauravano I totally misaccounted how the mentions work! Removing our names from the first list is not useful.. now we will not be mentioned. Reverting that back asap. 

@Harshithpabbati open it tonight if @uzorjchibuzor doesn't? I think maybe he could be experiencing wifi connectivity issues.

**Comment by sashadev-sky** [comment]
@gauravano @Harshithpabbati ok good to go. New plan: I think we can just put the names that don't highlight in a separate comment like @gauravano did here.

**Comment by gauravano** [comment]
I think we would be notified in the new issue. If we don't get notified, I will add our names back. How does this sound?

**Comment by sashadev-sky** [comment]
@gauravano I already put it back! I'm not sure we would though... maybe remove just your own name and test it out?

**Comment by niravasher** [comment]
Hello, good evening from Mumbai

**Comment by gauravano** [comment]
Good evening Nirav!

**Comment by Harshithpabbati** [comment]
Hello
I opened a new check-in https://github.com/publiclab/plots2/issues/4917 . Thanks!!

**Comment by gauravano** [comment]
Thanks @Harshithpabbati
