### ISSUE TITLE
wiki edits can be displayed twice on dashboard following specific Activity menu sequence

### ISSUE THREAD

**Issue by Fastie** [publiclab/plots2#514]
Recent wiki edits are displayed in the right panel but also mixed in with notes and comments, etc in the left panel.

**Comment by jywarren** [comment]
I was able to reproduce this after several check/uncheck cycles of the dashboard's Activity feed menu, at a small window size, followed by resizing the window to be large enough for a sidebar. 

This occurs at https://publiclab.org/dashboard

The relevant code is in this file: https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/dashboard.js#L3-L57

The expected behavior is that wiki content is shown in the main feed except when there's room for it to appear in a sidebar (above ~992px I believe), at which point it's displayed there instead.

**Comment by jywarren** [comment]
Also helpful would be to check if they were displayed upon initial /dashboard pageload by someone who's never visited the dashboard before (a completely clean browser, say, an incognito tab).

**Comment by jywarren** [comment]
I've done some debugging on this and believe I've fixed it -- but we'll have to test out on varying sized screens and devices to be sure. I'll publish tomorrow with other followup fixes and give a heads up, but provisionally closing for now. Please re-open if you see the issue persist and thanks for reporting!
