### ISSUE TITLE
Follow button not showing the user is subscribed on the /subscriptions page

### ISSUE THREAD

**Issue by Souravirus** [publiclab/plots2#5485]
Reported on #5182 
The subscribe button is actually working in the backend but it's not being shown to the user. Also, the user count is not increased after clicking the follow button. 

The page is [this](https://publiclab.org/tags#) and here is the screenshot.
![image](https://user-images.githubusercontent.com/17192149/56131857-421e4280-5fa6-11e9-8abd-a738c6de25a2.png)

**Comment by divyabaid16** [comment]
If this issue is open to be worked upon, I would like to give it a try. Thanks!

**Comment by gautamig54** [comment]
The user count is increased on refreshing the page. Also, we can add a toggle button for following or unfollowing a tag. Currently, the "follow" button also changes to "following" when the page is refreshed.

**Comment by gautamig54** [comment]
@divyabaid16 Can we divide the issue?
I can create a toggle button for following or unfollowing a tag and you can work upon the incrementing the user count without needing to refresh the tag.

**Comment by divyabaid16** [comment]
Sure!!

**Comment by gautamig54** [comment]
Should the user be allowed to delete their subscription from the tags page directly? 
There is a separate page for managing subscriptions which provides the user an option to unsubscribe a particular tag. 
Considering this, If a user follows a certain tags and wishes to unfollow it, we can direct the user directly to the "Manage Subscriptions" page rather than the tag specific page. 
What do you think @Souravirus  @divyabaid16 ?

**Comment by Souravirus** [comment]
Yeah that would also be great. Thank you for working on it.

**Comment by gautamig54** [comment]
I have written a code for changing the text from "follow" to "following" when clicked. But, it only works once. I will have to refresh the page again for the click to work again. It can be because the query is set to work only for one action. What do you think about this @divyabaid16?

**Comment by divyabaid16** [comment]
@gautamig54 I guess you will need to make changes in routes.rb 
Also, I would like to give one more suggestions, if we could auto refresh the page during certain interval of time like suppose 5 mins so that all the update in the page can be visible and there will be no need to refresh the page in certain inrerval.

**Comment by divyabaid16** [comment]
> Should the user be allowed to delete their subscription from the tags page directly?
> There is a separate page for managing subscriptions which provides the user an option to unsubscribe a particular tag.
> Considering this, If a user follows a certain tags and wishes to unfollow it, we can direct the user directly to the "Manage Subscriptions" page rather than the tag specific page.
> What do you think @Souravirus @divyabaid16 ?

@gautamig54 Regarding this, a new layout of tags page was proposed by @jywarren in issue #5090 
In this, the user can unsubscribe directly.

**Comment by Utiwari1999** [comment]
@Souravirus I want to work on this issue.

**Comment by coder-cracker** [comment]
@Souravirus I also want to work on this issue.

**Comment by Souravirus** [comment]
Hi @Utiwari1999, sorry for the late reply. Yeah you can surely work on this. Thank you!!

**Comment by jywarren** [comment]
I believe this is resolved in the new design, thank you!!!
