### ISSUE TITLE
Add ellipsis to tag if the tag length exceeds certain limit of charcters

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#5610]
## Description
![Screenshot from 2019-04-24 19-49-01](https://user-images.githubusercontent.com/26685258/56666718-05e79200-66ca-11e9-9a8c-497e2f34c4f5.png)

Tha tags with large no of characters can be limited with certain amount of characters so it does not cause overflow in horizontal direction.

Thanks !!!

**Comment by CleverFool77** [comment]
@publiclab/plots2-reviewers What's your opinion regarding this.
I'm interested in working in this.
Thanks !!

**Comment by sashadev-sky** [comment]
@CleverFool77 hi! Please see my comment on your other similar issue, #5609. 

I think imposing a limit on tags would be a little more complex to think about, though, so I am edging on just going with the ellipsis here as you mention and not implementing my suggestion for #5609. 

What do you think? Feel free to put one reply for both comments here so that our conversation isn't split between two pages

**Comment by CleverFool77** [comment]
I've @sashadev-sky , I haven't tried it yet but there is a css property which can help limit the overflow of characters with ellipsis. I was thinking of using that for now.
I think this property could be the solution .
Though I'll explore and seee more.
I'm having exams right now, so it might take sometime to work upon this.
Thanks !!

**Comment by sashadev-sky** [comment]
@CleverFool77 ok cool, I think the overflow css property is a good place to start, and then consider for the other issue also implementing a limit on length in the first place or opening an issue for it would be a good idea. Does that sound good?

**Comment by CleverFool77** [comment]
As the PR is merged , So I'll close this Issue.
Thanks !!!
