### ISSUE TITLE
Fix the profile icon with bootstrap4 class

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#5693]
## Description
Due to recent bootstrap4 upgrade, the profile icon class of bootstrap3 is not working anymore.
It would be great to have it back to circle like we earlier it.
We can use `rounded-circle` class of bootstrap4 instead of `img-circle` in bootstrap3.

Thanks !!!

**Comment by jywarren** [comment]
yes! awesome.

**Comment by skilfullycurled** [comment]
@CleverFool77, this would make a perfect FTO.  Would you like me to create an official FTO with the header?  I think I found the [place](https://github.com/publiclab/plots2/blob/fe2ffd6d71b9c5fc7c4ff09bb9d770ce30f4fe78/app/views/layouts/_header.html.erb#L96) you were talking about so I could give the instructions.  Or, I could put it here and then edit the top comment.

**Comment by CleverFool77** [comment]
Hi @skilfullycurled
Its not about finding the place. We have so many first timer only. But there should be a step after first timers only.
That's why I specified the change, but I wanted candidate to find the file and line themselves and do the change. By not giving the file directly, they can search through the codebase and get more familiar with it. This could a step after some people are done with first timer only issues but haven't found other issues to work on.

**Comment by skilfullycurled** [comment]
@CleverFool77, sorry, I think I was unclear in my comment.  Oh internet.  : )

I edited my former comment to remove the change.

Please take the following as clarification of my own comments.  My experience is that sometimes being really specific and writing a lot can come off as argumentative and that's not what I'm trying to do at all.  With regard to the length, I write a lot either way ; )

As to me finding the place, I only meant that having found it, I would be happy to help create the FTO with the template.  I figured you might be busy doing higher level things so I was offering to do the lower level part so you could get to working on other more complicated things.  : ) 

I also think I may be misunderstanding what in FTO is.  I wasn't thinking that the FTO was simply to locate the file, rather, that the steps in the FTO template would have been to go to that location and make this change using our workflow.  

My only mental model is from my own [experience](https://github.com/publiclab/plots2/issues/5412) in which I was given both the code and the place to find it.   My impression was that they were supposed to be this easy so that one could focus on the workflow, and not the change itself.  

I think this would make a perfect FTO, and I'll leave you to handle as you see fit.  If it's not an FTO, then I'm happy to make the change.  I've been looking for tiny change to make so that I could add to Liz's tutorial.  Currently, there isn't any tutorial with photos for what to do during the PR process.

**Comment by skilfullycurled** [comment]
In a related story, I do have a suggestion for the FTO:

From my own experience, even though I know how MVC works, finding a template in the PLOTS code base is a pretty big hunt. There are 30+ folders of views, and you have to have general knowledge of a templating language and how partials work and then jump from view to view.  That could be frustrating for an FTO.  I have some ideas in a range of difficulties for how to balance your desire for a person to engage with the code, and ease the burden of doing so in the views.  

Easy: point them to the file where the change will be made but not the line. 
Medium: point them to the folder where they have to find the right file.
Medium Hard : point them to the line in a parent file where the partial is imported and then they figure out which file they need to go to.
Difficult:  point them to a parent file and show them what the line which imports a partial will look like (not the exact line), then have them find the line in the parent, and figure out which partial to go to.

Just some thoughts.  Again, it's your FTO and you're more experienced than I so now I'll leave it to you!

**Comment by CleverFool77** [comment]
I read your comments. :smile: 
Let's see if someone solves it in here as `fto-candicate` label without files.
If not, then I'll update the location and make it a first-timers only.
Thanks for expressing your opinion with such patience.
I got to know a lot.
Thanks !!!

**Comment by CleverFool77** [comment]
Closing as opened this one https://github.com/publiclab/plots2/issues/5804
