### ISSUE TITLE
Fix Flag Mailto Text (Potential FTO)

### ISSUE THREAD

**Issue by skilfullycurled** [publiclab/plots2#5873]
I think this will make a good FTO but I could use some feedback on this first.

The [mailto flagging text](https://github.com/publiclab/plots2/blob/964be1f16ae2546efa47fab5ffcc0eceb679c993/app/views/comments/_comments.html.erb#L33) uses string concatenation which then creates an email which includes the pluses.
```
<a rel="tooltip" title="Flag as spam" class="btn btn-sm btn-outline-secondary btn-flag-spam-<%= comment.id %>" href="mailto:moderators@publiclab.org?subject=Reporting+spam+on+Public+Lab&body=Hi,+I+found+this+comment+that+looks+like+spam+or+needs+to+be+moderated:+https://publiclab.org/<%= comment.parent.path %>#c<%= comment.cid %>+by+https://publiclab.org/profile/<% if comment.author %><%= comment.author.name %><% end %>+Thanks!">
```
So either it needs to be rewritten with spaces or %20's or put inside template tags either as a variable which is interpolated or using mail_to?  If it's the former, should it be spaces and the browser converts the %20's or should the %20's be added ahead of time?  If it's the latter, would variables and string interpolation or using [mail_to](https://stackoverflow.com/a/51617135/6023530) be better?

**Related:** _I also think that the text should be changed. Should I make that a separate issue that is resolved first and then create an FTO, or create this FTO, have that discussion elsewhere, and then we can make another FTO : ) ?_

**Comment by jywarren** [comment]
Hi! If we can agree on some new text, that sounds great. Also, maybe you can demonstrate that a different encoding works properly? I think we had set this up so that mails triggered in development pop up in a new window using some testing gem trickery... but it's been a while! I think if we use spaces, there was some problem with that. But what you could do is create a few links with such `mailto:` lines in a wiki page and test them out. I think it just took too many steps to iterate through testing this for it ever to be fixed but we definitely want to fix it, so thanks!

I agree it can be a good FTO because ultimately there ought to be basically a single line fix. I'll add the standard "this could be a good FTO text below from my saved replies in case it's helpful!

****

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

**Comment by skilfullycurled** [comment]
Sounds like a good plan @jywarren.  Probably because it is, indeed, a plan.

> Hi! If we can agree on some new text, that sounds great. 

We can discuss in another issue but here's where I'm headed.  Right now the tool tip reads `Flag as spam' and the email text , _"looks like spam or needs to be moderated"_  I wonder if the tool tip should be generalized to `Flag  for moderation` and if the text might include a numbered list of potential reasons (spam, violation, website error, other, etc.) and ask the flag-er to indicate one of them. 

> Maybe you can demonstrate that a different encoding works properly?

Sure, I'll just do a few on my local installation and give some screenshots of the results.

**Comment by jywarren** [comment]
Hi, i believe this has been merged into the Flag-as-spam system built in this past summer's new Spam Dashboard in #7885 -- closing! Thanks!
