### ISSUE TITLE
Add 'all time' option for stats

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#5904]
I have also encountered this error when attempting to guestimate the start date for our website so that i could view data "For All Time". 

I'm wondering if it's really a bug or perhaps maybe it could be worked around by people not having to guess when we started logging data for our website? 

If it's the latter, here's an idea: 
On the "Choose a Start Date" interface, could we add the exact start date of our website as a "quick pick" OR perhaps make an option to choose "for all time" as the period of inquiry?

_Originally posted by @ebarry in https://github.com/publiclab/plots2/issues/5490#issuecomment-497454355_

**Comment by cesswairimu** [comment]
I tried  ` For all time` option

```
 def all_time_stats
      params[:start] = Date.new(2012,9,27).to_time
      params[:end] = Time.now
  end
```
but this was failing on unstable of course because of https://github.com/publiclab/plots2/issues/5490 (Forgot about this for a minute) so this means the "quick pick" option won't work too.

### Suggestions for this implementation.
- Have an section for 'all time data' the  that can be collapsed with all counts for the various objects possibly using `.all`  ...But with this won't be able to display the graphs because we depend on `start_date` and `end_date` to plot the graphs within the range selected. 

Mentioning @ebarry @skilfullycurled  you guys might have ideas on how to implement this 

_Feel free to add suggestions for a possible implementation_
Thanks.

**Comment by skilfullycurled** [comment]
@cesswairimu, yeah, both #5490 and the stats overload issue (#5524) will play into this.  The latter has a good chance of breaking the site.  They are purging the database of "some" (8.4GB) of rsession data so that might help a bit on the overload but I'm not sure considering there is one place where there are ~350,000.  

Anyway.

Some ideas if you don't mind hacky temporary code:

1) Exclude users for the entire year of 2013.  This seems to be the problem year both in terms of some possibly corrupt data and the ~350,000 users.

2) What would it take resource wise to create a highly customized cache which could either:

     - Use the set of unique users from all published content in 2013.  So, get all of the content for that year, and then take the set of all unique users who created it.
     - Exclude the problem dates (4/23/13 was it?) and also users who have never logged in.  And if that doesn't whittle down the users to something manageable, we can add "never published anything as well" (which would essentially be like the above I think).

Then, when we get the whole thing sorted out, you can delete those qualifiers.  That way you could at least check off the basic functionality in this issue for the time being because I think the other two issues will take some sorting out.

Is it possible to merge two issues on Github?  I think it might be worth joining #5490 and #5524 in the same conversation and do some planning and break down the tasks.  Or maybe we can create a single issue such as "Stats Page Query Bugs" (or whatever).  We're hoping to mitigate #5524 by removing spam users (see approach [here](https://github.com/publiclab/plots2/issues/5450#issuecomment-500591813)) but that will require some planning because I'm not sure what the best practices will be for emailing that many users at once (how do we break them up into groups?).

**Comment by cesswairimu** [comment]
Wow! Thanks.  I will try the suggested methods @skilfullycurled and see what will work best. Also creating a planning issue for all the related tickets.:+1:

**Comment by skilfullycurled** [comment]
Glad you like them @cesswairimu !  Actually, I didn't realize the first date was 9/27/12.  You could just start at 2014 and do what you did in the other visualization (can't recall the verbiage but it was something to the effect, "tracking started since XXXX) 

Also, thanks for opening the new issue.  I didn't mean to imply that you should do the work of opening it, I just thought you might have the permissions to merge them (if they can be).  Anyway, still, much appreciated!

**Comment by cesswairimu** [comment]
Hahaha maybe not. I picked 9/27/12 because it  was the first commit date. It might not be when the first record was created then but def not earlier than that
