### ISSUE TITLE
Weekly community Check-In #26 (Bash Aliases)

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/plots2#5943]
Hi everybody :smiley: !

We all at Public Lab :balloon:  - learn, grow, work, brainstorm ideas, contribute together so why not share about our _weekly goals and the awesome work_ we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal :dart: . You are also welcome to share fun-fact :smile: , new ideas :bulb: , your learning goals :ballot_box_with_check: .

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. :100:

If you're new here, welcome, and please comment a _Hello_ below, we would love to work with you. If you're looking for new issues, please try some of our [first-timers-only](https://code.publiclab.org/#r=all) issues.

We're SO EXCITED to have your help!

**Is there anything, you would like to share with us from past week's work? What is your plan for this week?**

If you have not planned yet, just leave a Hello! :wave: so that we know that you are in sync with us :arrows_clockwise: and doing well!

The coming weeks will be full of code :computer: , tasks :spiral_notepad:, fun :tada: and excitement :smiley:!!

As always, if you're waiting for a review, or if you're stuck, please request help here OR leave a comment with @publiclab/mentors @publiclab/reviewers for some input. :raised_hands:

#### Gitter

Gitter is an active chatroom in our community and we'll be sending weekly reminders about check-ins there. Be sure to sign up [there](https://gitter.im/publiclab/publiclab) for these updates or just to join the conversation. You can also join us through http://publiclab.org/chat :speech_balloon:.

**This Week's Theme:**

**Bash Aliases**: Bash aliases provide my greatest productivity boost. They also have become a reflection for myself for how my workflow has increased in sophistication over time and new knowledge I have gained. 

This week, tell us an interesting bash alias you use. If you don't use any or have a good one to share, try looking one up and sharing that! Everyone is encouraged to discover and start using a new alias this week either through online research or from someone else's post here. 

For those not familiar with them: 
- open your bash profile (found at `~/.bash_profile`) in your code editor
- add an alias and save. Here is a simple ex. that demonstrates the correct syntax: `alias be="bundle exec"`
- reload your current terminal session with `source ~/.bash_profile`
- the alias will now be available

You can find our list of previous check-ins [here](https://github.com/publiclab/plots2/issues/5627) 

## Note to Summer of Code interns:

Hi, we request all the SoC students to include the below-mentioned points in their check-in comment:
- FTOs created in the previous week
- Progress for your project
- Upcoming week's goals 
- PR reviewed by you in the previous week
- Work completed last week.
- What things you did collaboratively last week? This is really important we want team spirit.
It is like a weekly scrum. Be flexible. 
- Feel free to tell us about your absence too, if you're taking a break.
- Issue/PR you're struggling with (if any)

With FTOs and PR reviews, we are seeking to develop a much more friendly and collaborative platform. We want you all will involve people in your project. You all will develop skills like leadership along the way.

Thank you!

**Comment by sashadev-sky** [comment]
@milaaraujo @kevinzluo @Rishabh570 @sashadev-sky @shubhscoder @sidntrivedi012 @SidharthBansal @cesswairimu @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @IshaGupta18 @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1, @uzorjchibuzor, @eli6, @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @Mridul97 @avsingh999 @romanrodriguez @Dhiraj240 @codeIriss @IgorWilbert @pdurbin @HarshKhandeparkar @aashna27

**Comment by sashadev-sky** [comment]
@mohitRJranjan @milaaraujo @kevinzluo @Rishabh570 @sashadev-sky @shubhscoder @sidntrivedi012 @SidharthBansal @cesswairimu @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @IshaGupta18 @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1, @uzorjchibuzor, @eli6, @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary, @wanzulfikri, @mohitRJranjan @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @romanrodriguez @Dhiraj240 @codeIriss @rishabhc32 @chirag-singhal @IgorWilbert @vrk99 @pdurbin @HarshKhandeparkar @niravasher @marieram @publiclab/reviewers @publiclab/is-reviewers @publiclab/community-reps @divyabaid16

**Comment by sashadev-sky** [comment]
@publiclab/community-reps @subhahu123 @An0u @Jaya738 @mgroovyank @shreyateeza @TANGL3SIT3S @nazeem1988 @karunagoyalk @Nirvikalpa108 @cassianoblonski @EngrEric @Anjalizi @GettyOrawo @coderbeetle @corbettbw @govindjeevan @gautamig54 @daddyjab @emestabillo @letnewKid @srujana121 @jazdao @ChinwenduSilvia @aggarwal19 @Jenniline @madelinejones @helenatxu @richa031 @fabsar @kuja24 @megha070 @Aarabhi2017 @Manvi07 @siddhishree @Julius26 @VinneyJ @sonali9696 @rarrunategu1 @coreytegeler @labseven @milomacphail @CleverFool77 @ananyaarun @ananya @publiclab-mimi @shubhi2000

**Comment by sashadev-sky** [comment]
@Priyak5 @techchic @ananya @hc-barker @edwd42 @PritiShaw @themonster2015 @supriya-kotturu @AnthoniaOkafor @scheleon @mahmodHammad @santushk @jillpena @stoic-plus @starkblaze01 @aSquare14 @vaarigupta @alonpeer @madeofhuman @ibnjunaid @aashna27 @harshithpabbati @mmmelissa @rarrunategu1 @UNnamed66 @GauravJ3 @Greg-Tarr @Sanscripter @hodbadger @alaxalves @becomingajunior @monsij @vrk99 @pdurbin @HarshKhandeparkar @aashna27 @harshithpabbati @CleverFool77 @niravasher @gautamig54 @jesus-montano @michelelong @cryptoclidus

**Comment by sashadev-sky** [comment]
note @alaxalves will be opening next weeks!

**Comment by aSquare14** [comment]
@sashadev-sky  Great topic for the cheeckin ! Bash is highly underrated I feel and an amazing tool :)
One bash alias I use is ```alias ports=netstat -t```
Hoping everyone has a great week ahead !

**Comment by kaustubh-nair** [comment]
HI all! And nice topic @sashadev-sky ! :smiley: 
I use a lot of aliases while working, mostly for rails and git
Here are some of them
```
alias c="clear"
alias lg="ls -a | grep"
alias rdm="rails db:migrate"
alias rg="rails generate"
alias rr="rails routes"
alias rdc='rails db:create'
alias rc='rails console'
alias rds='rails db:seed'
```

I also wrote some really cool functions for git, which I use a lot. 
$1 and $2 denote the first and second arguments in shell script
So if you type 'gp beta master', it will push to 'beta' remote and 'master' branch

```
gc(){
  git add .
  git commit -m "$1"
}
gp(){
  git push $1 $2
}
gpo(){
  git push origin $1
}
gpu(){
  git push upstream $1
}
# And similar for pulling
```

I also highly recommend using zsh instead of bash. It's a lot faster, and has amazing auto completion. Once you switch you will never look back :smile: 

### Summer of code update for Mapknitter Rails upgrade

This week I've been helping fix the asset issues that have arisen due to the yarn switch. We'll hopefully fix all of these this week and get Rails 4 deployed to the main site!
We were stuck on setting up the database for Rails 5 last week, but the errors turned out to be because to some manual overrides that were done previously for the `mysql_adapter` ( thanks @sashadev-sky ). 
Since then, we've fixed all the tests and got the build passing for Rails 5 https://github.com/publiclab/mapknitter/pull/685 :tada: :tada: 
There's still a lot of deprecation warnings to fix, which we'll address after finishing setting up Rails 4!
Thanks!

**Comment by HarshKhandeparkar** [comment]
Hi, I don't set any bash aliases as such but I have some scripts which boost the productivity a lot.
- https://github.com/HarshKhandeparkar/bashinthebin
- https://github.com/HarshKhandeparkar/gitshot
- https://github.com/harshithpabbati/Update-is (for deploying image sequencer beta)

**Comment by alaxalves** [comment]
Hey guys, to be honest I am not a big fan of setting aliases on my bash, because I like remembering the entire command :smile: :smile: :smile:. But I have set some useful functions on my bash to integrate it better with git commands. Here they go:

``` bash
function git_branch_name() {
        git branch 2>/dev/null | grep -e '^*' | sed -E 's/^\* (.+)$/(\1)/'
}

function show_colored_git_branch_in_prompt() {
        PS1="\[\033[01;32m\]\u@\h:\[\033[01;34m\]\w\[\033[31m\]\$(git_branch_name)\[\033[m\]$ "
}

show_colored_git_branch_in_prompt
```
With those two functions you can quickly identify if it is a git versioned repo, and easily know where you at haha, it will prompt out something like this:
![image](https://user-images.githubusercontent.com/19597045/60119772-9dfb0980-9755-11e9-9de2-b0d4aab57102.png)

Now about my GSoC project progress, here we go:
Mostly of my last week work can be found at https://github.com/publiclab/mapknitter/pull/685
**Progress**
Currently me and @kaustubh-nair are pretty in advance with our work, thanks to @IgorWilbert's suggestion I have "skipped" a version and went straight ahead to Rails 5.2.3 version(latest stable rails).

**Upcoming goals**
I plan to fix the deprecation warnings that are still left, change folder names to the newest rails conventions, investigate the simplecov integration and fix some assets related bugs along with @kaustubh-nair. Also I'd like to start testing with Rails 6.0.0-rc1 version, but only after Rails 5.2.3 gets merged to `development` branch.

**Work completed last week**

- Removed deprecated method invokations, such as atr_acessible.
- Locked every version of our gems, to latest possible.
- Fixed broken CI pipelines(Unit tests and docker building).
- Fixed the MySQL adapter integration, (had a huge help of @sashadev-sky).
- Started using strong_params.
- Started making model associations "weak".
- Included abstracted classes for ApplicationMailer and ApplicationRecord.
- Using required_relative in favor of plain require.

** What things I did collaboratively last week?**
I have been working mostly with @kaustubh-nair and @sashadev-sky only. Me and Kaustubh have been organizing our work pretty nicely, there's never been a mismatch or conflict.

**Comment by gauravano** [comment]
Hi everyone, 

Nice theme @sashadev-sky! 

I don't use aliases. Because I can't remember them and using complete command help me picture the effect better. 

### Plots2:
I am going through plots2 old issues/PRs, pushing some to completion, and closing some of them. 

### Goals:
1. Notification system PR review 
2. Plots2 issue template setup
3. Image management project update

have a great week  :100:

**Comment by sashadev-sky** [comment]
Just implemented @alaxalves script! 🚀 

I use an alias for grabbing the name of the branch i'm on:

`alias me='git rev-parse --abbrev-ref HEAD'`

Which allows me to do `$ git push origin $me` to quickly push up my work from a branch

This week my goal is to complete the progress update UI for the exporting system!

**Comment by jywarren** [comment]
Hi all! It was great talking to folks on the Code Open Call today (https://pad.publiclab.org/p/opencall) and we took lots of notes. 


@IshaGupta18 I tried making a diagram of your app flow - take a look and try making your own!

![image](https://user-images.githubusercontent.com/24359/60133228-fbe61c00-976a-11e9-8abe-cc37e8ac4908.png)

This is a good exercise for everyone! You can try starting on page 2 of thsi doc, but please copy the slide so you don't mess up others' work: https://docs.google.com/presentation/d/1aquQKyih8vvtD7U-AI0NlbAcgT-BVu9G8hloYg-c-QI/edit#slide=id.g1b2a1e1ee8_0_82

I also wrote a good bit about managing variable scope and overwriting values in @ananyaarun's issue here - good for others to read too! There are different strategies for this but it's super important as code becomes more complex: https://github.com/publiclab/leaflet-environmental-layers/pull/207

**Comment by pdurbin** [comment]
I type `git status` so much that I shorten it to `gits` with this Bash alias:

    alias gits='git status'

Speaking of aliases, git itself supports them. I have a lot in my .gitconfig at https://github.com/pdurbin but I only use a couple of them regularly.

I shorten `git checkout` to `git co`.

I also like being able to specify an alternative email address after I've cloned a git repo. For example, if I want to make commits using my work email address, I `cd` into the repo and type `git harvard`.

Here's the `.gitconfig` file:

```
[user]
	name  = Philip Durbin
	email = philipdurbin@gmail.com
[alias]
	co      = checkout
	harvard = config user.email philip_durbin@harvard.edu
```

**Comment by divyabaid16** [comment]
Hi everyone!

Great theme @sashadev-sky :tada: 

Well, I just use Bash Alias to clear my terminal xD
```alias c='clear'``` and not for other things. For me writing the complete command is much easier. 

And I guess, I just missed my previous week's check-in so I will write about my work for the past 2 weeks.

FTO's created:
https://github.com/publiclab/mapknitter/issues/739
https://github.com/publiclab/mapknitter/issues/722
https://github.com/publiclab/mapknitter/issues/723
https://github.com/publiclab/mapknitter/issues/673

PR's created (open):
https://github.com/publiclab/mapknitter/pull/738
https://github.com/publiclab/mapknitter/pull/693

PR's merged:
https://github.com/publiclab/mapknitter/pull/735
https://github.com/publiclab/mapknitter/pull/721
https://github.com/publiclab/mapknitter/pull/717
https://github.com/publiclab/mapknitter/pull/692
https://github.com/publiclab/mapknitter/pull/689

Goals for this week:
* Get started with the image version control. Here, the details of all the edits must be available to the user and can select any version as the version to be displayed on the map. 
* Get completed with multiple image export
* Find and work on other bugs.

Have a great week ahead everyone.
Thanks! :)

**Comment by jywarren** [comment]
Hi, everyone! I wrote up a post about "how to get help effectively"! It's based on some advice I put into the GSoC evals. I think it's worth a read, and would love feedback! 

https://publiclab.org/notes/warren/06-27-2019/getting-help-in-a-coding-project

![Screen Shot 2019-06-27 at 5 50 53 PM](https://user-images.githubusercontent.com/24359/60303336-215a5d80-9904-11e9-9ad1-2cdbaed21e7f.png)

**Comment by SidharthBansal** [comment]
I hope you all are going good. I am right now busy with some personal stuff. Will be back after a month.
I hope all of you enjoyed phase 1 with PL community.

**Comment by alaxalves** [comment]
> Hi, everyone! I wrote up a post about "how to get help effectively"! It's based on some advice I put into the GSoC evals. I think it's worth a read, and would love feedback!
> 
> https://publiclab.org/notes/warren/06-27-2019/getting-help-in-a-coding-project
> 
> ![Screen Shot 2019-06-27 at 5 50 53 PM](https://user-images.githubusercontent.com/24359/60303336-215a5d80-9904-11e9-9ad1-2cdbaed21e7f.png)

Those are very good tips, despite of being kinda boring, being pretty descriptive on issues and PRs are very necessary. BTW a good practice I took from @sashadev-sky is using this section of github to review PR and such:
![image](https://user-images.githubusercontent.com/19597045/60386288-65b33e00-9a69-11e9-9a00-f78fb2d36afe.png)
Very useful to exactly express what we want.

**Comment by gauravano** [comment]
Hey @alaxalves, you would be opening check-in for this week, right?

**Comment by alaxalves** [comment]
@gauravano I'm working on it rn. I'll send the link here and on Gitter when I'm done :D
