### ISSUE TITLE
Add the extra white spaces in tags after `# people discussing`

### ISSUE THREAD

**Issue by newbazz** [publiclab/plots2#6059]
### Description
Add extra space after #people discussing inwiki image as per new style guide -  
<img width="497" alt="59403744-8e78d980-8dc1-11e9-8590-79db2b0c62ac" src="https://user-images.githubusercontent.com/26685258/61811889-1988cd00-ae60-11e9-9d5a-2a8f5979f70a.png">

**Comment by newbazz** [comment]
Related to https://github.com/publiclab/plots2/issues/6055

**Comment by CleverFool77** [comment]
Hi @newbazz Instead of removing extra spaces, we are supposed to add extra spaces, as per new design draft.
So you should add more space, something like this - It has extra image 
<img width="497" alt="59403744-8e78d980-8dc1-11e9-8590-79db2b0c62ac" src="https://user-images.githubusercontent.com/26685258/61811532-4a1c3700-ae5f-11e9-8882-5a58820362a1.png">

**Comment by CleverFool77** [comment]
@newbazz I have edited your issue and title.
Thanks !!

**Comment by newbazz** [comment]
![image](https://user-images.githubusercontent.com/25884863/61814813-83a47080-ae66-11e9-8f03-7a23a995ecda.png)

I have updated to this

**Comment by newbazz** [comment]
@CleverFool77 can you review when free

**Comment by CleverFool77** [comment]
@newbazz I gave my review in your PR.
Thanks !!!
