### ISSUE TITLE
expand co-authorship features with right-to-edit 

### ISSUE THREAD

**Issue by klie1** [publiclab/plots2#606]
### What happened just before the problem occurred

- I'm already logged in

- I click on "Edit" in the drop down box of the [specific note that I want to edit](https://publiclab.org/notes/Shannon/07-06-2016/public-lab-code-of-conduct)

- I get a pop up that says “Please be aware that you are editing someone else/“ 

![screen shot 2016-07-06 at 2 13 57 pm](https://cloud.githubusercontent.com/assets/20325934/16631670/d260aa6c-4385-11e6-9ef9-dcc4756e699d.png)

- Then it kicks me back to the [login screen](https://publiclab.org/login)

But, at the same time, I'm actually still logged in (which you can see in the drop down box).
![screen shot 2016-07-06 at 2 25 08 pm](https://cloud.githubusercontent.com/assets/20325934/16631655/be805a74-4385-11e6-8b82-8d0fe2c09e8b.png)

- If I log back in though at this point, it does the same thing / process repeats

### Relevant URLs

https://publiclab.org/notes/Shannon/07-06-2016/public-lab-code-of-conduct
https://publiclab.org/login

### PublicLab.org username

@klie

(to help reproduce the issue)

### Browser, version, and operating system

I've tried it on two browsers:
Firefox 47.0
Google Chrome Version 51.0.2704.103 (64-bit)

OS:
Mac OS X El Capitan 10.11.5

**Comment by jywarren** [comment]
This is because coauthoring is a very primitive system at the moment -- it really just affects the author credit line. I think you were able to edit because you're an admin, not because you're a co-author. But we can and should improve this system and we could check for co-author status both when clicking the edit button (no pop-up) and when viewing the edit page and thirdly when saving (coauthors should be notified). 

We need to break this out into several issues with code refs and suggestions and mark as "help wanted" or maybe it'd make some good "first timers only" material as the individual steps are pretty simple.

**Comment by jywarren** [comment]
Closing and redirecting to a new issue #761.
