### ISSUE TITLE
Listing of recent likes

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#610]
In #309, we see that spam users are liking things in order to get link visibility. We can ban them, and #309 will make their usernames disappear from page like listings, but there is no master listing of likes, organized by time, so that we can occasionally skim it for spammers. Like spam is accumulating. 

A page at `/likes` listing all recent likes would be great, also showing a `ban` button for admins. 

Ban button example can be found here: https://github.com/publiclab/plots2/blob/master/app/views/admin/users.html.erb#L28

Likes have a model called `node_selections` and an index method could go here: https://github.com/publiclab/plots2/blob/master/app/controllers/like_controller.rb

**Comment by neliojrr** [comment]
I would like to do it. =)

**Comment by jywarren** [comment]
We'd love your help on this. Thanks a lot!

**Comment by ebarry** [comment]
Perhaps related to this is the error in how many likes a page has. Shown on https://publiclab.org/wiki/plots-staff, there's a count of 6 likes: 

![screen shot 2017-01-19 at 1 03 07 pm](https://cloud.githubusercontent.com/assets/161439/22119026/ec9707ac-de47-11e6-9827-fea10b6514bb.png)
but only three usernames (assuming it's because spammers were banned and their usernames removed from display): 

![screen shot 2017-01-19 at 1 03 14 pm](https://cloud.githubusercontent.com/assets/161439/22119039/fe08854c-de47-11e6-845c-63cddccec320.png)

**Comment by jywarren** [comment]
No, i believe that is unrelated, but is related to #607 -- thanks!

@neliojrr -- just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by Diksha2008** [comment]
@jywarren I would like to give it a try!

**Comment by Diksha2008** [comment]
@jywarren I hope I can work on this?

**Comment by jywarren** [comment]
Yes please, that'd be great!

On Wed, Oct 18, 2017 at 11:39 AM, Diksha Manchanda <notifications@github.com
