### ISSUE TITLE
Login flow issues - explore and address with system tests

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6141]
I noted that when logging in, if I don't have the correct username, I'm sometimes redirected to the /research page or to the front page (/) instead of back to the login page. Sometimes I see a notice that says something like `You must be logged out to see that page`. 

I also note #4691 and https://github.com/publiclab/plots2/issues/5198 as potential login flow issues. 

I'd like to suggest we create system tests to try to reproduce these scenarios, which can be quite complex, and that we try to expand our system tests to cover many of these flows and resolve them. 

cc @SidharthBansal as you've done so much great work on login flow, and now our new system tests make automatically testing and protecting these flows much easier!

**Comment by SidharthBansal** [comment]
Hi, I am having trouble setting up an environment to test system tests. Can you please tell me a guide which you followed for writing them at plots2?
I read through official guidelines and many guidelines from google search but they are not working. It will be really convenient and fast if I will iterate over the same guide which @jywarren followed.

**Comment by jywarren** [comment]
I've actually not run them locally - I have relied on the Travis
environment to run them. I know that's a bit odd but it makes for a very
standardized test environment.

**Comment by SidharthBansal** [comment]
Oh. I thought you have set up the local environment for localhost:3000 using some gems. So, I was checking on your prs and trying to run them locally.
If they are not set, then let's try to set it up first locally so that everyone can run the tests locally. Are you in favour of it OR do you want that collaborators will run them with Travis. I personally prefer local because of time optimization. Also, Travis fails randomly many times.
My second questions are we aiming to write Tests for all the login sequences at MK/SWB/plots2 OR we are aiming at only the above issues? I will suggest let's focus on the above issues first and then create a separate issue for each repository for System Tests. Then system tests can be broken down into sub projects like login, oauth, notification overhaul, tagging and much more. If you have already created that issue then I will be happy to explore it once you give its link.
My third question is are we planning to do system tests for MK/SWB, editor and other js repos? I will suggest let's stick to plots2 first and then go into other repositories. There will be many tests, so let's plan for a feasible amount of work.
Suggestions : 
1. Breaking of system tests in GCI 2019 project as this is huge and requires a lot of prs.
2. Having a careful attitude before merging pr. All the tests should be submitted in the pr itself. We follow this but we have to be strict with tests. There can be multiple flows in the same pr. So, all the tests should be written in the pr. I observed people writing a single test where 3-4 or more tests were required. 
3. We need to optimize on the testing techniques. As software testing principles, tests should be minimalistic covering all the flows for the project. Minimalistic because a large number of tests contribute to many bugs at later phases of the project. 
2 and 3 are conflicting things and should be seen once we can formalize on testing approaches at PL.

**Comment by jywarren** [comment]
> I will suggest let's focus on the above issues first

Agreed! We don't have to make a system test for every single scenario, partially because it'd be time-intensive for running them. But let's start with some that'll be particularly helpful. 

And yeah, plots2 first -- although MapKnitter now has system tests too. Again, they are not the most efficient tests, so let's reserve them for critical functions. 

We can provide more support for people writing tests. System tests and screenshot tests are pretty fun, but not everyone knows how to do them. And agreed on optimization too!

**Comment by SidharthBansal** [comment]
@Uzay-G @VladimirMikulic i think you both are writing tests for this too

**Comment by Uzay-G** [comment]
No problem. I will make some of these :+1:

**Comment by SidharthBansal** [comment]
Why not all?
Do as much as possible. No hurry

**Comment by SidharthBansal** [comment]
@Uzay-G are you initiating a pr for this?

**Comment by Uzay-G** [comment]
Hey @SidharthBansal I am having an issue here. The system tests I am coming up with can all be done with normal functional tests. What should I do?

**Comment by SidharthBansal** [comment]
Functional tests if they are not present. Don't go into system tests until
user interface is needed.

**Comment by Uzay-G** [comment]
Most of the complex issues with login/signup have already been addresseSd recently with functional tests. I have been searching for any useful additions but am stumped. Are there any issues in particular you have in mind that have not been treated?

Thanks for your help :+1:. I have been investigating areas that could be improved on but plots2's testing is very careful and precise.

**Comment by SidharthBansal** [comment]
Let's move to #5198 then
