### ISSUE TITLE
"Responses to this note:" does not display in sidebar

### ISSUE THREAD

**Issue by Fastie** [publiclab/plots2#635]
### What happened just before the problem occurred
Another note is a response to this note, but no message is displayed to that effect.

### Relevant URLs
There is a response note to this note:
https://publiclab.org/notes/cfastie/12-21-2014/holiday-beverage-whodunit
This note is a response to the above note:
https://publiclab.org/notes/cfastie/12-24-2014/potent-potable-puzzle

The response note ***does*** display the message that it is a response to the first note. But if you find the first note (the whodunit puzzle) you can't find the second note (the answer to the puzzle). 

### PublicLab.org username
cfastie
(to help reproduce the issue)

### Browser, version, and operating system
Chrome, Windows

**Comment by ananyo2012** [comment]
@Fastie The `seeks:responses` tag was somehow removed. I added it back. Please check now. Currently this tag is used to collect any responses to a research note.

**Comment by jywarren** [comment]
Hi, I think actually the issue is not the seeks:responses tag, but the following line:

https://github.com/publiclab/plots2/commit/9ced93988d6329b2044bfcaa72c5dbd43815ee8b#diff-77c36730d14905eeed787a672e334dacL45

Previously the condition was `<% responses = @node.responses if @node %>` and then `<% if @node && responses.length > 0 %>`, not a `node.has_power_tag()` at all. I must've miscopied that during an edit. We should write a test each for responses and recipients of responses.

Although with so many tests now, perhaps for efficiency we could just make a method on `node.has_responses` that returns a boolean, and unit test that instead of running a whole functional test. Unit tests are simpler and faster to run.

**Comment by ananyo2012** [comment]
Ok sorry the issue was referring to the title text of the response for "Responses to this note:". I was thinking of the response not showing in the notes page.

**Comment by jywarren** [comment]
we should test for both! :-)

**Comment by jywarren** [comment]
Fixed this but haven't written the tests yet. I'll close in any case.

**Comment by jywarren** [comment]
Hmm, the fix did not resolve the issue -- we should do the unit test for `node.responses`.

**Comment by Fastie** [comment]
This series of notes: https://publiclab.org/tag/eos_m
all have response:xxxxx powertags, but only one of them (https://publiclab.org/notes/cfastie/02-25-2016/kapvolution) displays the related notes in the sidebar.
I can't see any obvious reason why that note should be different, but there must be one.
That one note is the oldest of the four, and it is a response to a much older note.
