### ISSUE TITLE
Refactor JS functions add_tag() and create add_comment() for pure JS API

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6411]
We have a JavaScript function to add tags, here:

https://github.com/publiclab/plots2/blob/86ea8ba5efafad0fcb0befadb399c5a84e0bf786/app/assets/javascripts/tagging.js#L1-L13

However, it uses the on-page HTML tag form to do this. We should be able to do this directly using AJAX without using an HTML form. 

Secondly, we should implement the same functionality for an `add_comment('Comment body here')` function, similarly AJAX based.

Our functional tests show how these should be possible to run directly, instead of via the HTML page:

https://github.com/publiclab/plots2/blob/86ea8ba5efafad0fcb0befadb399c5a84e0bf786/test/functional/comment_controller_test.rb#L43-L53

https://github.com/publiclab/plots2/blob/86ea8ba5efafad0fcb0befadb399c5a84e0bf786/test/functional/tag_controller_test.rb#L9-L12

We should create a system test to confirm that these javascript functions actually work! You can run javascript in a system test like this:

https://github.com/publiclab/plots2/blob/86ea8ba5efafad0fcb0befadb399c5a84e0bf786/test/system/search_test.rb#L26-L27

**Comment by nstjean** [comment]
I'll try this out!

**Comment by nstjean** [comment]
So to check in, what we are doing for that tag form is accepting whatever value is sent in and instead of loading it into the HTML form and submitting the form it is instead sending a POST request via AJAX, right?

`$.ajax({
      async: false,
      type: 'POST',
      url: $('#tagform').attr('action'),
      data: "name+" + tagname
    })`

The URL of the POST request I either have to grab from the form (as above), or I'd have to have some way to pass the node ID value into the function.
