### ISSUE TITLE
hashtags being read strangely on previews shown on tag pages: 

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#6517]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

When visiting https://publiclab.org/tag/community, i saw this which appears strange: 
<img width="461" alt="Screen Shot 2019-10-22 at 12 22 01 PM" src="https://user-images.githubusercontent.com/161439/67307929-45e7d000-f4c7-11e9-9508-a1dbc38bd620.png">

When i clicked through to the wiki: https://publiclab.org/wiki/community , i see this which is fine: 
<img width="1199" alt="Screen Shot 2019-10-22 at 12 24 55 PM" src="https://user-images.githubusercontent.com/161439/67307936-497b5700-f4c7-11e9-8633-b5fdb22bbbd9.png">

> What did you expect to see that you didn't?

I expected the word "community" to appear in regular font in the preview, or at least not missspelled perhaps because of some unicode issue :)

### Please show us where to look

https://publiclab.org/tag/community
https://publiclab.org/wiki/community

**Comment by publiclab-mimi** [comment]
I see this as well, both on Safari and on Chrome, but only for the tag page related to community.

**Comment by jywarren** [comment]
This is a tough one. Some vocal users had requested the ability to use "MathJax" equations, which is a way to write out scientific expressions, and these are typically presented between ` characters. This has been used on the site on a number of posts. 

But the ` character is used in Markdown (which drives formatting on our site) to indicate a quoted text, and is commonly used for tags, because it puts them in a nice box like this:

`community`

this is achieved with the syntax \`community\`, but on our site, MathJax also tries to turn it into an expression. 

I'm not sure what the solution is, but perhaps the easiest fix is to just avoid any special formatting for initial sentences on wiki pages -- this has been our solution for related issues both Liz and Stevie have discussed. But we can discuss adding a special feature to strip out HTML formatting on tag page cards if that's of interest?

**Comment by ebarry** [comment]
Thanks for the explanation all -- i have added the tag `won't fix` and suggest we close this is favor of manually editing wiki pages when it is a priority to fix the text preview shown on the tag page of the same name.
