### ISSUE TITLE
Planning issue: Hide profile bio content unless users have had some content approved

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#6584]
**Please describe the desired behavior:**

This is a planning issue to review the issue of spammy bio content in profile pages. 

**Problem:** many users create spam profiles with live links to illegal and harmful activities, links which may live on for years on our infrastructure. There is currently no "Gate" on creating profiles with bio content that instantly goes live. 

**Proposal:** to allow new profile creation, but to not display any profile bio content (including links, pictures) unless users have been approved for something. 

**How would this work?**

New people could still create a profile page, but the bio content would be hidden until they had some kind of post approved (comment, note, or question) and until that first approval, we could display a message in the place of the bio content explaining the status. 

Needs to further explore how to hold custom profile images in a queue, although it would be a little more complex as those are used around the site not just on the profile page. 

**Background**

While the presence of spammy profiles had long been regarded as irrelevant to the health of our website and safe to ignore, our position is this is now changing. Why? Because of the growing awareness of illegal and harmful activities which our infrastructure is hosting and allowing to be live on the internet. 

**Additional context**

A significant amount of work on detecting and screening for spam profiles has been undertaken here: https://github.com/publiclab/plots2/issues/5450

**Comment by jywarren** [comment]
Here is the code displaying bio content! 

https://github.com/publiclab/plots2/blob/4d6bcd4dc35ec3bc291330dd715973651cea4697/app/views/users/profile.html.erb#L62

We can wrap it in a conditional, but what exactly do we check:

1. that the user has at least one post that is published: `Node.where(status: 1, uid: profile_user.id)` (i think?)
2. OR, that the user has at least one comment that is published: `Comment.where(status: 1, uid: profile_user.id)` (i think?)

Does that make sense, Liz? That step is easy and would make a great FTO.  

The profile image... we can maybe just hide it on the profile page, because, i guess, it wouldn't appear anywhere else since the person would have to be approved to post or comment, right? 

Images are shown on these two lines; we can use the same conditional:

https://github.com/publiclab/plots2/blob/4d6bcd4dc35ec3bc291330dd715973651cea4697/app/views/users/profile.html.erb#L44-L48

This could become a second FTO!

Support on being an FTO: 

****

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

**Comment by ebarry** [comment]
These two approaches sound really great!
