### ISSUE TITLE
Contributor count on tag pages not reflecting number of contributors 

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#6675]
I was looking for the number of posts and contributors to this tag (https://publiclab.org/tag/oil-and-gas) and saw that the number was listed here as Zero: 
<img width="1155" alt="Screen Shot 2019-11-04 at 11 59 38 AM" src="https://user-images.githubusercontent.com/7490478/68140986-b72d7700-fefa-11e9-8fb5-d078f501daf3.png">

But there are actually 73 contributors and 38 posts. This can be found here https://publiclab.org/contributors/oil-and-gas: 
<img width="887" alt="Screen Shot 2019-11-04 at 12 00 54 PM" src="https://user-images.githubusercontent.com/7490478/68141072-dd531700-fefa-11e9-9df2-f453fc46a486.png">

**Comment by ebarry** [comment]
great catch!

**Comment by jywarren** [comment]
So, here are the queries used for the `0 posts by 0 contributors | 0 followers` area: 

https://github.com/publiclab/plots2/blob/8128a3053f9a145599ed58db27cf2d2ad50ca500/app/views/tag/show.html.erb#L57-L61

Here's somewhere they seem to be counting correctly, in the lower right of the main image:

https://github.com/publiclab/plots2/blob/8128a3053f9a145599ed58db27cf2d2ad50ca500/app/views/tag/show/_header.html.erb#L18

Is it possible that `tag.name` is not correct? 

Yes! This relates to the error on 

https://github.com/publiclab/plots2/blob/8128a3053f9a145599ed58db27cf2d2ad50ca500/app/views/tag/show.html.erb#L28

This has the same error! https://github.com/publiclab/plots2/issues/6592

We should be able to solve both by replacing `tag.name` with `params[:id]` for these lines. 

****

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

**Comment by nicoleiocana** [comment]
I would also like to piggy-back off of @jywarren to mention that the entire show.html.erb code should be refactored to include the instance variable @title since the tag_controller.rb file has `@title = params[:id]`. Since we should be practicing DRY, it is redundant to have `params[:id]` in the show.html.erb file when it was passed along as the @title instance variable from the tag_controller.rb.

**Comment by jywarren** [comment]
Hi, ah, i see - so @title is used to set the HTML document title field, so
I am a little hesitant about using it for this logic just as it's currently
named for a different purpose -- it could cause some confusion. If we'd
like to independently use a new instance variable like @tagname, that could
work, but it may not save us much code. Thanks a lot!

**Comment by nicoleiocana** [comment]
You are very welcome. I totally agree with you...... trust me. But since this isn't my code, I didn't want to edit out their usage of certain definitions; I was just using what they gave me. I'll submit this PR using @title, then, if someone wants to refactor the code to redefine @title to mean something else, I'll just let them have that responsibility. =)
