### ISSUE TITLE
Add redis installations for linux

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#6744]
We just updated redis installation guidelines on Readme on this pr https://github.com/publiclab/plots2/pull/6398 for MacOs thanks to @mathyoudawson . It would be good to update the same for Linux

--------------------------------------------------
This could be edited to become a fto or a gci issue

**Comment by nicoleiocana** [comment]
I wouldn't mind adding in the code for linux-based systems. Since there is no separate section for linux, I was just thinking of adding linux underneath the already provided macOS option. See pic below:

![redis](https://user-images.githubusercontent.com/44947175/68521041-e1ac6680-0251-11ea-8bc6-572d7eb6fc93.PNG)

Lemme know what you think.

**Comment by cesswairimu** [comment]
That's great @nicoleiocana, you can go ahead and add that. Thanks a lot
