### ISSUE TITLE
Incorrect number of research notes listed on tag page 

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#6855]
Hello,
I was looking at this tag page and found that the dropdown displays an incorrect number of research notes for this tag. On this page: https://publiclab.org/tag/Climate-change it lists there are four research notes, but I'm only seeing three:

<img width="1121" alt="Screen Shot 2019-11-26 at 12 19 00 PM" src="https://user-images.githubusercontent.com/7490478/69656775-2a805f80-1047-11ea-8b0f-458a0831916b.png">

**Comment by steviepubliclab** [comment]
I found a similar issue on this site https://publiclab.org/tag/Disaster-response that is listed having 18 research notes but I only count 14

**Comment by steviepubliclab** [comment]
Looks like it might count questions?

**Comment by steviepubliclab** [comment]
Sorry, not that's not it based on the first one.

**Comment by moskeyombus** [comment]
Based on what I'm seeing in the code, the difference in counts vs. visible tags in each page is due to a difference between the calculation used to determine the visible count on the page, and the actual results returned in the query.

For both the "X posts by X contributors" section at the top of the table and the count in the "by Type dropdown", the `Tag.find_nodes_by_type` method is called to determine the count:

https://github.com/publiclab/plots2/blob/master/app/controllers/tag_controller.rb#L79
^^^ this line sets the count in the "by Type" dropdown

https://github.com/publiclab/plots2/blob/master/app/views/tag/show.html.erb#L58
^^^ this line sets the count in the "X posts by X contributors" copy.

I propose we remove both of these method calls and instead, set a `@tags_count` variable in the `tag#show` method that is referenced in the views.  This ensures consistency between the result count in the view and the actual result count.  It also will increase response times, currently the database gets hit for each query producing the count, setting a variable once on the backend should eliminate some redundancy.

Will open a PR for this :)

**Comment by jywarren** [comment]
That sounds fantastic! Please link us to the PR once you do -- many thanks!

**Comment by steviepubliclab** [comment]
Hi, I noticed the number here did change, but they're still a little confusing to me. Can you share what was done here?

**Comment by moskeyombus** [comment]
I haven't been able to make any meaningful progress here.  Ultimately, the issue is far more complex than I originally thought.  There is a massive block of logic in the `tags#show` method that will apply filters and load a set of tags based on what you're viewing.  There is an entirely separate block of code that determines the counts in the 'by Type' dropdowns (`Tag.find_nodes_by_type`).

The logic in these 2 places is fundamentally different in multiple ways, it appears to be sheer luck that the counts ever match.  All I can really do here is recommend a full refactor of all the code I've mentioned in my comments into a single source of truth so that anywhere in the app you're querying for tags (either to display a list or just to get a count), you're using this service.  This is the only way to ensure counts in the view match the actual queries that run when you load a page the retrieves a full list of the tags.  Sorry I can't be more help here, this is a little too big of a task for me to take on at the moment.

**Comment by steviepubliclab** [comment]
oh wow! ok thank you for figuring that out and for trying! I'll leave this open incase anyone feels like they can take it on, or has new ideas on it.

**Comment by ckchu8** [comment]
I was able to find and reproduce the problem. The show action in the controller and the find_nodes_by_type method in the model look for term_data parents differently. I can't do a full refactor, but I can clean it up a little. Can I take this issue?

**Comment by steviepubliclab** [comment]
Go for it!! Thank you

**Comment by ckchu8** [comment]
Great thank you! 😄 I think I have a PR ready for review!

**Comment by jywarren** [comment]
It looks like @ckchu8 has submitted a fix at https://github.com/publiclab/plots2/pull/7476 with tests! 

Sorry for responding slowly but we're very excited for this fix. 

The confirmation for whether it's a valid fix is that the number shown should match a manual count of the posts displayed in the paginated list below. I believe this is confirmed here:

https://github.com/publiclab/plots2/pull/7476#issuecomment-585842037

Awesome work!

**Comment by jywarren** [comment]
Just confirming that on the live site, we now see:

* https://publiclab.org/tag/Climate-change in all variations counts properly
* https://publiclab.org/contributors/Disaster-response same!
