### ISSUE TITLE
new system test fails due to probably timing issue

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6904]
https://github.com/publiclab/plots2/blob/3c0273364cb9b2a22169bea32af6f11aad3ade91/test/system/tag_test.rb#L27-L46

These lines seem to fail - esp `assert_selector('.tags-list .card-body h5', text: 'roses')`, in what I think is just a timing failure - that we should wait longer for it to complete, as it's an AJAX request. 

I've seen a failure for this on https://github.com/publiclab/plots2/pull/6758 (which I restarted) and on https://github.com/publiclab/plots2/pull/6858#issuecomment-561337577 (which resolved on restart, but the error output is there):

```
 FAIL["test_adding_a_tag_via_javascript_with_url_only", #<Minitest::Reporters::Suite:0x00007fc289832e00 @name="TagTest">, 116.16007206999996]
 test_adding_a_tag_via_javascript_with_url_only#TagTest (116.16s)
        expected to find css ".tags-list .card-body h5" but there were no matches
        test/system/tag_test.rb:44:in `block in <class:TagTest>'
[Screenshot]: tmp/screenshots/test_viewing_the_dropdown_menu.png
[Screenshot]: tmp/screenshots/test_viewing_the_dropdown_menu.png
[Screenshot]: tmp/screenshots/test_viewing_the_settings_page.png
  43/43: [=================================] 100% Time: 00:03:05, Time: 00:03:05
```

We could lengthen `  Capybara.default_max_wait_time = 60` but there are other subtle ways to fix timings. Oddly, one is to add an `assert_select` as it is supposed to naturally keep looking for up to 60 seconds for stuff to appear on the page when looking for specific CSS/HTML with that method. Here, that doesn't seem to be working.

Referencing some previous timing-related issues which don't seem so helpful, but maybe:

https://github.com/publiclab/plots2/issues/5683 and #6179 (maybe?)

This is an odd one! I wonder what's going on, @nstjean !? Stumped!

**Comment by nstjean** [comment]
Hmmm, I'm not sure! I'll google and see if I can find any other tricks to getting it to process faster.

**Comment by nstjean** [comment]
One thing I'm finding is that some people have implemented a method wait_for_ajax which checks and waits while there are Ajax calls still completing.
https://medium.com/doctolib/hunting-flaky-tests-2-waiting-for-ajax-bd76d79d9ee9

The other option is addressing the `addTag` function specifically.

When a tag gets added via the form in `'adding a tag via javascript'` the tag is automatically added to the page in the ajax success call:
https://github.com/publiclab/plots2/blob/68245096cf4bac7635bc7c7a3f9c8b2663b56a59/app/assets/javascripts/submit_form_ajax.js#L11-L19
https://github.com/publiclab/plots2/blob/68245096cf4bac7635bc7c7a3f9c8b2663b56a59/app/assets/javascripts/tagging.js#L43-L64

But that doesn't happen when tag is added via url in `'adding a tag via javascript with url only'`, since there's no form object to trigger on success. I could pull out the code for adding the tag to the page into a separate function to trigger? That way we won't have to wait and refresh the page, it will just show up automatically like in the `'adding a tag via javascript'` test.

So two possible options: change the testing, or change the function itself.

**Comment by jywarren** [comment]
pulling out into a separate function sounds good, as it'd be a bit more modular as well. Let's do that! Thank you!
