### ISSUE TITLE
Getting Started "Page doesn't exist"

### ISSUE THREAD

**Issue by emilyashley** [publiclab/plots2#7144]
The `Community > Get Started` link in the navbar lead to a dead page. I then followed the link to "report a bug on github" so this is just a quick draft issue so I don't forget to follow back on this and do appropriate issue template etc. Did a quick search of issues and didn't see one open.

 <img width="748" alt="Screen Shot 2020-01-07 at 7 59 31 PM" src="https://user-images.githubusercontent.com/15912063/71944110-5b949980-3188-11ea-9da8-9f9325182430.png">

(P.s. Maybe I should also open an issue to make the "Report a bug on Github" button link start an issue with the bug report template? ie. `&template=--bug-report.md`)

**Comment by jywarren** [comment]
Wow, good catch! 

That's node 539 and it definitely did exist in March 2019, here:

https://web.archive.org/web/20190330072516/https://publiclab.org/wiki/getting-started

I'm looking in the database to see if the record still exists.

**Comment by jywarren** [comment]
Got it in Sentry. The error is wrong actually; it's a record not found but not for the page, which is fine, it's for this `revision.author` call:

https://github.com/publiclab/plots2/blob/07ac150285bee0eddf089ed7a5544369b3a7cf48/app/models/revision.rb#L73

Let's switch it to `find_by_id` instead of `find` -- but should we write a test for this? it's related to our long-term interest in developing an ability to delete users, because if we delete a user, this could happen here or elsewhere. But I don't know if we need to put tests for invalid data in here... it's a judgement call.
