### ISSUE TITLE
Redirect to profile page of user on username search

### ISSUE THREAD

**Issue by lalithr95** [publiclab/plots2#743]
### What happened just before the problem occurred

When I search for lalithr95 in search text field it displays autocomplete of usernames which match /lalithr95/ Clicking on any of the autocomplete suggestion should redirect to profile page of user.

Currently this doesn't happen. This is could be an interesting issue to get started with codebase.
<img width="1051" alt="username" src="https://cloud.githubusercontent.com/assets/4562611/18035805/f67eb5d2-6d2a-11e6-8ad8-bcb1a4466cb6.png">

Fix could be to add an anchor `<a href="/profile/lalithr95">Lalithr95</a>` in autocomplete.

### PublicLab.org username
Lalithr95
(to help reproduce the issue)

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by david-days** [comment]
@lalithr95 ,

@jywarren and I were just discussing this particular behavior on another thread.  This is due to my implementation of the typeahead script, and we can change this behavior for the general typeahead for all typeahead results (go to URL if exists).

@jywarren , would you like to change the behavior across the board, switch to bootstrap-typeahead, or something in between?

**Comment by jywarren** [comment]
I'm going to mark this as closed, as we're already working on typeahead changes that'll resolve it. But thanks, Lalith!
