### ISSUE TITLE
Unsubscribe button does'nt work

### ISSUE THREAD

**Issue by sssash18** [publiclab/plots2#7508]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
Unsubscribe button in dropdown does not actually unsubscribes a user
**Current Behaviour**
![Untitled_ Feb 16, 2020 12_23 AM](https://user-images.githubusercontent.com/57896905/74593588-c58b4300-5052-11ea-865c-79996875ab01.gif)

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by NitinBhasneria** [comment]
@sssash18 are you working on this?

**Comment by sssash18** [comment]
@NitinBhasneria if you want , you can work on it.Thanks

**Comment by NitinBhasneria** [comment]
Ok will be working on it.

**Comment by NitinBhasneria** [comment]
https://github.com/publiclab/plots2/blob/8d2efcb96e9643a74957d5cdde208f21d01360fb/app/views/tag/show/_user_controls.html.erb#L9-L12
this is the code @nstjean @cesswairimu do you find any error in this?

**Comment by cesswairimu** [comment]
Yeah..I think the problem here is its doing a `GET` instead of a `delete` try adding `data-method="delete"`

**Comment by NitinBhasneria** [comment]
@cesswairimu actually I have already tried adding data-method="delete" but nothing happened

**Comment by cesswairimu** [comment]
oh :thinking: ,maybe we can try rails link...using `<%= link_to method: :delete  %>`?

**Comment by NitinBhasneria** [comment]
No, @cesswairimu It is working same with this... as <a ....

**Comment by cesswairimu** [comment]
okay, I will take a closer look at it later and let you know if any success

**Comment by Shreets** [comment]
Hello, 
I am Outreachy Applicant and I would like to claim this issue.
Thanks

**Comment by Shreets** [comment]
Hi @cesswairimu,
I figured that this issue should be solved with addition of `data-method="delete"` to the following tag

https://github.com/publiclab/plots2/blob/8d2efcb96e9643a74957d5cdde208f21d01360fb/app/views/tag/show/_user_controls.html.erb#L11

However, what is stopping this from working is use of `e.stopPropagation()` as follows in the code:

https://github.com/publiclab/plots2/blob/8d2efcb96e9643a74957d5cdde208f21d01360fb/app/views/tag/show/_user_controls.html.erb#L51-L53

Apparently, jquery-ujs stops event propagation in its data-method attribute due to this `e.stopPropagation()` 

This code had been added as part of this PR: https://github.com/publiclab/plots2/pull/5995 

What this code does is, It stops the dropdown menu from closing when space outside the listed links(within dropdown menu) are clicked on

![publiclab_original](https://user-images.githubusercontent.com/54280935/96261137-c1e3fd80-0fdf-11eb-8252-1f1632469d49.gif)

This is how the drop down menu behaves when the stopPropagation is removed i.e the drop down menu closes when space outside the listed links are clicked.

![publiclab_test](https://user-images.githubusercontent.com/54280935/96261337-0a9bb680-0fe0-11eb-9514-3873972d5975.gif)

One way to go about this could be to remove `stopPropagation` libe above and apply padding to the hyperlinks so that it responds to click when the div surrounding it is clicked. This will solve the problem to some extent. The dropdown wont close as long as we click withing the hyperlinks.

![hyperlinks](https://user-images.githubusercontent.com/54280935/96264459-ec37ba00-0fe3-11eb-9416-220ed8837f36.png)

Could you please suggest how I should go about this?

Thanks!
