### ISSUE TITLE
popover stays on screen after clicking spam

### ISSUE THREAD

**Issue by keshavsethi** [publiclab/plots2#7543]
In some tag link like  https://publiclab.org/questions/tag/air-quality
on clicking on spam button a popover appears which stays there even after clicking. It gets removed only after scrolling as shown 
![Screenshot from 2020-02-20 01-58-29](https://user-images.githubusercontent.com/36025262/74873332-0225aa00-5385-11ea-9c6f-824741f6fb3f.png)
 
Thanks

**Comment by diogobest** [comment]
I have a question, is this popover necessary? What should be the behavior of it? The popover should appear after the user hover the mouse over the spam button?

I've observed the popover is not hiding after the menu disappears or after scrolling. It goes to the top of the page and stays there until the user clicks on some link on the page or the spam button again.

I'm not sure yet, but I think the trigger or the jquery used to show or pop the item are causing the problem. I'll update when I find the problem.

**Comment by allprogrammers** [comment]
Hello, I would like to work on this.

**Comment by sakshi-2412** [comment]
Hey! I would like to work on this issue

**Comment by sakshi-2412** [comment]
I tried to understand the function of this popover, and I think the expected behaviour is that after hovering over the spam button, `dashboard/flag_list` should be rendered as a popover which gives two options - report the question via mail or become a moderator. Is this so?

Attaching code snippet below -
https://github.com/publiclab/plots2/blob/36780424bf48bbf338564e8c9c69ee6c750f6822/app/views/questions/_new_question.html.erb#L84

I am still not sure what "sample" means!
@TildaDares can you please help me with the same?😅Thanks!

**Comment by TildaDares** [comment]
Hi @sakshi-2412, [Boostrap's docs](https://getbootstrap.com/docs/4.0/components/popovers/#:~:text=template,the%20.popover%20class.) says that this is what a data-template should look like
`<div class="popover" role="tooltip"><div class="arrow"></div><h3 class="popover-header"></h3><div class="popover-body"></div></div>`. 
So whatever content we want to place in `.popover-body` should be in `data-content` which means the partial rendering should be done in `data-content` and not `data-template`. I hope that helps

**Comment by sakshi-2412** [comment]
Thanks! I'll start working on this then😄

**Comment by sakshi-2412** [comment]
Hey @TildaDares  I think this bug is related to bootstrap, a popover within a dropdown doesn't work the way we want it to. I tried out a few combinations of the same ( https://codepen.io/ash_24/pen/PoJMMbE ), but didn't get the expected results. 
So, I changed the popover to a multi-level dropdown with some custom styling. Does it look fine?

https://user-images.githubusercontent.com/85152262/150691858-5358b24e-11fb-471e-b336-ddc7635a4822.mp4

**Comment by TildaDares** [comment]
That looks fine @sakshi-2412

**Comment by sakshi-2412** [comment]
Okay thanks! I'll open a PR soon✨

**Comment by govindgoel** [comment]
@sakshi-2412 can you please test it once that it works well with i18n translation for the text. Also, one more question is there an option to unflag the post after marking it as spam as of now ?

**Comment by sakshi-2412** [comment]
Hey @govindgoel .. No, margin between the buttons is removed🤔 ( we check the same by clicking "Switch On Translation" right? )
![image](https://user-images.githubusercontent.com/85152262/151034394-8518583b-f8e3-4da0-bef2-a489f097dcf1.png)

Also, there is no option to unflag the post as "Flag post to moderators" button redirects you to a mail that can be sent to the moderators.

**Comment by govindgoel** [comment]
> Hey @govindgoel .. No, margin between the buttons is removedthinking ( we check the same by clicking "Switch On Translation" right? ) ![image](https://user-images.githubusercontent.com/85152262/151034394-8518583b-f8e3-4da0-bef2-a489f097dcf1.png)
> 
> Also, there is no option to unflag the post as "Flag post to moderators" button redirects you to a mail that can be sent to the moderators.

Okay yeah, it will redirect to mail, yeah you can check by switching language. You can maybe leave for now and we can test this later on . Thanks.
