### ISSUE TITLE
Social icons alignment is not proper in sidebar

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#7608]
**Please describe the desired behavior.**
In the current beahviour the questions sidebar social links alignment is not proper. The twitter icon is not placed on the same vertical level as other social icons.

**Additional context (optional)**

![image](https://user-images.githubusercontent.com/33183263/77518775-5b14c080-6ea4-11ea-9290-2c7159333d46.png)

**Comment by Tlazypanda** [comment]
@VladimirMikulic  can you kindly approve? Thanks :v:

**Comment by VladimirMikulic** [comment]
@Tlazypanda consistency is very important. Approved!

**Comment by Medlineme4** [comment]
I would like to try

**Comment by VladimirMikulic** [comment]
Hi @Medlineme4. 
Welcome to Public Lab :balloon: 

I am glad that you are interested in solving this issue, but as you can see @Tlazypanda has already provided a PR for it.
Since you are a newcomer, it would be good to solve a few FTO(first-timers-only) issues to get familiar with the codebase.

Finally, don't forget to say "Hi" to our community on [Gitter](https://gitter.im/publiclab/publiclab) and if you have any question feel free to ask me :)

**Comment by cesswairimu** [comment]
Mmmh I am not sure if this is okay since its a huge UI change...tagging @emilyashley @ebarry @steviepubliclab @jywarren to hear their thoughts thanks

**Comment by Medlineme4** [comment]
How do I try one when all FTO gives a red mark when posted/ answered

Sent from Yahoo Mail on Android 
 
  On Mon, Mar 9, 2020 at 8:53 PM, Cess<notifications@github.com> wrote:   
Mmmh I am not sure if this is okay since its a huge UI change...tagging @emilyashley @ebarry @steviepubliclab @jywarren to hear their thoughts thanks

**Comment by Medlineme4** [comment]
I tried giving an answer to a FTO but  it always shows a red mark X

Sent from Yahoo Mail on Android 
 
  On Mon, Mar 9, 2020 at 8:53 PM, Cess<notifications@github.com> wrote:   
Mmmh I am not sure if this is okay since its a huge UI change...tagging @emilyashley @ebarry @steviepubliclab @jywarren to hear their thoughts thanks

**Comment by cesswairimu** [comment]
Sorry about that, could you please link me to the fto you are talking about @Medlineme4, I am glad to help. Thanks

**Comment by Medlineme4** [comment]
#7558: change function t() to translation in specific lines
#7598: update_form.html.erb
For #7558, I had to go for another issue with same title but I still had a red mark

Sent from Yahoo Mail on Android 
 
  On Mon, Mar 9, 2020 at 9:09 PM, Cess<notifications@github.com> wrote:   
Sorry about that, could you please link me to the fto you are talking about @Medlineme4, I am glad to help. Thanks
