### ISSUE TITLE
Signup button gets disabled permanently after errors

### ISSUE THREAD

**Issue by sssash18** [publiclab/plots2#7618]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
The signup button gets disabled permanently after we try to signup when some error occurs.

> What did you expect to see that you didn't?
it must not be disabled permanently
**Current Behaviour**
![Untitled_ Mar 8, 2020 10_45 PM](https://user-images.githubusercontent.com/57896905/76280171-f9a2fe00-62b6-11ea-86d6-2ab21c8050aa.gif)

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by shreyaa-s** [comment]
Hey @nstjean @jywarren  , can I please get assigned to this one? Thanks!

**Comment by shreyaa-s** [comment]
@nstjean @jywarren @SidharthBansal @VladimirMikulic @cesswairimu @sagarpreet-chadha @crisner @ebarry Hey,
I went through the code and have thought of two ways that we could use to sort this out:
1. We check for form validation at every key up and enable the the submit button only when it's validated but I'm not sure if that would be the optimal user experience.
2. Another thing that we could do is that when the user clicks on the submit button we could check for form validity and if it's valid we could send him directly to the next page or display an error if it's not valid rather than enabling/disabling the button.

I feel that the second method is the better approach out of the two. Could you please tell me what could be the other possible ways to tackle this? Or which method you think is the most appropriate. Any input is highly appreciated. 
Thanks!

PS - I still need your green signal to go ahead on this one.

**Comment by VladimirMikulic** [comment]
The second option defeats the purpose of the interactive form. That's why it was made that way.

**Comment by shreyaa-s** [comment]
So I've been looking into the issue and turns out it was misunderstood. The submit button enables only when all the inputs pass the validation check except for the last, ie. `spamaway` check. The button disables with the wrong input in `spamaway` but it's due to the reloading of the page and more importantly the user gets registered since all other validation checks have passed irrespective of the last check though it displays an error for the same.

Here's a video depicting the same:
![signup](https://user-images.githubusercontent.com/55884943/77323911-fd656480-6d3b-11ea-9075-83d977b457c1.gif)

Please guide me further on this issue.
Thanks!

**Comment by VladimirMikulic** [comment]
@shreyaa-s correct. That's kind of bug here. It would be great if the interactive form would validate `spam` form as well. If all data in the form is valid (username, email, password, confirmPassword & spam form) -> enable the submit button. Otherwise, keep the submit button disabled.

Hopefully, this clears your doubts.

**Comment by shreyaa-s** [comment]
@VladimirMikulic how can I access the error messages if any error is encountered during signup, such as username/email is taken?

**Comment by VladimirMikulic** [comment]
What do you mean by 'accessing error messages'? You don't access error message, instead, you render your own.

**Comment by shreyaa-s** [comment]
What I meant to say was, we check the database to see if email is taken, How can I access the result of this query? Or could you please direct me to the concerned files?

**Comment by shreyaa-s** [comment]
```javascript
$.get("/api/srch/profiles?query=" + username, function (data) {
      if (data.items) {
        $.map(data.items, function (userData) {
          if (userData.doc_title === username) {
            obj.updateUI(self, false, "Username already exists");
          } else {
            obj.updateUI(self, true);
          }
        });
      } else {
        obj.updateUI(self, true);
      }
    });```
this ajax request returns data variable. In data variable, items variable is an empty string and because of that my validation becomes true even if I have registered with that username on my local machine. Is that how it's supposed to act in local environment? Could you please help me with the same? Thanks!

**Comment by shreyaa-s** [comment]
`error_messages = objects.sum do |object|
              object.errors.full_messages.map do |msg|
                content_tag(:li, msg)
              end
            end.join.html_safe`
I found this where the error messages are converted into li tags. I want to access these error messages in formValidation. So how can I use this? I can use the include javascript function to find specific strings but its not a good practice. Please guide me through this.

**Comment by VladimirMikulic** [comment]
We check if username is available by sending reuest to the API. This is client-side validation.

**Comment by shreyaa-s** [comment]
@VladimirMikulic I know this is client-side validation. I wanted to know if the API returns an empty string in local development. Because I'm getting an empty string for a username which I've already registered.

**Comment by VladimirMikulic** [comment]
Yes, it does.
