### ISSUE TITLE
space between navbar and donation bar

### ISSUE THREAD

**Issue by shreyaa-s** [publiclab/plots2#7794]
### Please describe the problem (or idea)
While testing the editor for issues related to the responsiveness of the editor I encountered additional space between the two bars.
 Screenshots depicting the same:
![Screenshot_20200402_134401](https://user-images.githubusercontent.com/55884943/78238257-00114800-74fa-11ea-93ba-4f835a315ec7.png)

![Screenshot_20200402_134454](https://user-images.githubusercontent.com/55884943/78238272-04d5fc00-74fa-11ea-9728-854141928113.png)

****

Thank you!

**Comment by jywarren** [comment]
This is due to code in a Feature, documented here: https://github.com/publiclab/plots2/blob/master/doc/DATA_MODEL.md#features

cc @ebarry @steviepubliclab that this needs to be tweaked - the issue I believe is the length of text in the message not having been tested out at different screen sizes. Thanks!

**Comment by jywarren** [comment]
OK, they have turned off that ribbon and are taking note that content added there needs to be tested on different screen sizes. thanks!!!
