### ISSUE TITLE
bucket-monitor not showing up in search results

### ISSUE THREAD

**Issue by kgradow1** [publiclab/plots2#7973]
### Please describe the problem (or idea)

Hi all, I am the Community Tech Fellow working on the bucket monitor project for Public Lab.  Nice to meet you all!   I'm having a problem where the wiki post related to this project are appearing in search results under the bucket-monitor tag or under a general text search for "bucket monitor."  

> What happened just before the problem occurred? Or what problem could this idea solve?

The wiki page is available here:

https://publiclab.org/wiki/bucket-monitor

The wiki is tagged under bucket-monitor, air-quality, air-sensor, and method, but it does not appear under the search results for any of these tags, or under a general text search.  It looks like it is hidden behind the "type" search feature -- it appears when I specifically filter for wiki pages -- but it should be appearing in the general search results like other wiki pages. 

To complicate things, there is also an archival page -- Bucket 2020 Relaunch and Update -- which no longer has content but now *is* showing up in the text-based search.  We migrated all the content from this page to try to fix the problem, since this page was not showing up in initial search results.   This page should be deleted and should not be appearing in search. 

https://publiclab.org/wiki/bucket-2020-relaunch-and-update?fbclid=IwAR1uli63AhVqBJSXU3kqLzXuKI9-LaqhVGbM1HeztwIBkb87cNhaWU8Xjn8

> What did you expect to see that you didn't?

I would like the updated wiki page -- publiclab/wiki/bucket-monitor -- to appear in tag search and open text search

### Please show us where to look

https://publiclab.org/wiki/bucket-monitor

### What's your PublicLab.org username?

> This can help us diagnose the issue: kgradow1

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by ebarry** [comment]
Thanks for documenting this so thoroughly Katie! We appreciate your major contribution on this!
I see a few possible issues in here: 

1. The wiki https://publiclab.org/wiki/bucket-monitor is not appearing in search results under the bucket-monitor tag. Two related points on this: 

- the top of the tag page https://publiclab.org/tag/bucket-monitor is essentially the wiki page (lead image, and text); clicking "learn more" goes to the wiki page. So these pages are inextricably linked, more deeply than that the wiki page is just another type of content with this tag. 
- After many years, last year the "type" dropdown menu replaced the "tab view" on tag pages. Previously each type of content had a tab dedicated to it and allowing for navigation. Here's a screencap from an older page on publiclab.org which still has tabs (it's going to be replaced by the end of the summer): 
![tabs](https://user-images.githubusercontent.com/161439/83652873-1b93e000-a589-11ea-8679-a1bc108105b9.gif) Notice a common issue with this type of display -- sometimes tag navigation brings you to a page where there's not a clear way to get back to the tag page; the "by type" dropdown did resolve this issue. 
@joyofsoy has expressed that returning to tabs on tag pages, and adding counts of content of each type visible in each tab would be an improvement over the current "by type" dropdown menu. A possible next step on this would be to mock up how tag pages could look with tabs while following the Style Guide https://publiclab.org/notes/warren/05-07-2019/introducing-a-draft-style-guide-for-public-lab. 

**I believe the above steps may result in meeting your stated expectations that "the updated wiki page -- publiclab/wiki/bucket-monitor -- to appear in tag search."** I'd like to hear back from you on this. 

2. Regarding open text search, i'm guessing you might mean by typing "bucket monitor" and either choosing "search all content" or clicking the button "🔍" to go to https://publiclab.org/search?q=bucket%20monitor. If so, this is the search provided by Google to nonprofits to show results on their site without ads, and if Google's crawlers and algorithms have given an old and now deleted page a high page rank, it's just going to take time for their bots to sort out. We can help by adding more links around our site and more widely around the internet to https://publiclab.org/wiki/bucket-monitor.
<img width="1167" alt="Screen Shot 2020-06-03 at 11 07 38 AM" src="https://user-images.githubusercontent.com/161439/83654026-898cd700-a58a-11ea-9025-dbfae64906f6.png">

**I would like to hear back from you with any more thoughts on how https://publiclab/wiki/bucket-monitor appears in open text search on our site.** 

Thank you Katie!

**Comment by emilyashley** [comment]
Yes, thanks Katie! Reading thru this now :)

**Comment by jywarren** [comment]
Hi all, just skimmed this and checked, and https://publiclab.org/search?q=bucket-monitor (and `bucket monitor` -- https://publiclab.org/search?q=bucket%20monitor) do both now return https://publiclab.org/wiki/bucket-monitor, so I think what's happened is that there is a delay between the creation of a new page and when Google scans our site for new pages and lists them in the search results. 

![image](https://user-images.githubusercontent.com/24359/84448396-95c30500-ac18-11ea-8cf2-61cdcb388400.png)

I agree totally with Liz's note that the "By Type" dropdown on tag pages can be revised, and +1 resuming that process. But just in case it may be a red herring in this case, I wonder if Katie by "It looks like it is hidden behind the "type" search feature -- it appears when I specifically filter for wiki pages" means that it does appear when you do a wiki page search, using this dropdown:

![image](https://user-images.githubusercontent.com/24359/84448601-20a3ff80-ac19-11ea-997a-f93525742a1f.png)

The reason it would appear there immediately but not in the general search function is that the per-type search function in this screenshot is a direct database search, so it will be listed immediately, while the general search is a Google-based search which depends on Google crawling our site repeatedly, so there is a lag time. Hope that may help diagnose here.

****

As for tag searching, both `bucket-monitor` and `bucket monitor` both return tag search results as well, this may have only recently started working smoothly due to a very obscure bug Liz and I found recently. 

![image](https://user-images.githubusercontent.com/24359/84448491-d589ec80-ac18-11ea-925c-e387ae549c1e.png)

In any case i hope this means everything is good now! Thanks!

**Comment by jywarren** [comment]
Oh, and if you'd like, we can redirect https://publiclab.org/wiki/bucket-2020-relaunch-and-update to https://publiclab.org/wiki/bucket-monitor ?

**Comment by ebarry** [comment]
This may be resolved now? @kgradow1 can you check on the behavior?

**Comment by kgradow1** [comment]
It's working perfectly now, thank you!

Jeff, I don't think we need to redirect that page.  There's no reason for
anyone to find it unless they're looking for it.

Thank you everyone!

**Comment by jywarren** [comment]
Thanks! Closing!!
