### ISSUE TITLE
Paginate not used in following and followers

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#8115]
### Please describe the problem (or idea)
While checking the pagination codes, came across this anomaly where `paginate` was used in the users_controller (methods following and followers) but the `will_paginate` code was not present in` show_follow` html file.

This leads to only load the first 24 followers/following for the users and not showing any pagination for the rest.

 For example - warren follows liz but https://publiclab.org/people/liz/followers doesn't display warren. 

### Please show us where to look

https://publiclab.org/people/liz/followers
https://publiclab.org/people/liz/following

**Comment by Tlazypanda** [comment]
@ebarry @jywarren can you confirm this behaviour? :sweat_smile: sorry for stalking xD i wasn't sure whose profile to look for proof  :joy:

**Comment by ebarry** [comment]
wow deep catch @Tlazypanda ! I haven't seen this format of page in a looooong time. Glad you've chased it down and are starting to sort it out! 
Good spotting of the missing pagination code.
Adding this would be helpful!

I'll ask another question as well tho, because these pages are not standard with our style guide—What would it be like to remove this custom display of followers and following that lacks interactivity and instead use the same table as the "People who are following" table on the /contributors pages? For example, the farthest right hand table on https://publiclab.org/contributors/water-quality. 

What do you think?

**Comment by Tlazypanda** [comment]
Yes, I think we should move to this styling as well to have consistency across our pages :v: Thanks @ebarry for the research and the suggestion :heart: What do you think? @jywarren :sweat_smile:

**Comment by jywarren** [comment]
Agree! Sorry for slow reply here, but this sounds great, thank you for the catch @Tlazypanda 

As to the restyling, I think that could work too but perhaps that splits this into 2 issues? Thank you!

**Comment by Tlazypanda** [comment]
@jywarren @ebarry Just a heads up created an issue for the design part of it here #8270 

We can keep this one open for later implementing the pagination task :v:

**Comment by RuthNjeri** [comment]
Hi @cesswairimu, if this is still valid, can you assign it to me?

**Comment by cesswairimu** [comment]
Hi @RuthNjeri, looks like @renugasaraswathy fixed this one too while updating the designs https://github.com/publiclab/plots2/pull/8372 :tada: This can be seen at https://publiclab.org/people/liz/followers

**Comment by RuthNjeri** [comment]
oh alright @cesswairimu, I'll keep looking..if you happen to find one that I could work on that's not a First-time issue, feel free to tag me.

**Comment by cesswairimu** [comment]
Maybe we can discuss on ways to improve this further maybe order the page, maybe order the list  in asc or maybe load  15 or 20 per page in a new issue?

**Comment by RuthNjeri** [comment]
Thanks, I'll join the discussion in the new issue

**Comment by cesswairimu** [comment]
Created a follow-up here https://github.com/publiclab/plots2/issues/8542. Closing this, thanks all
