### ISSUE TITLE
Slow response time in posting comments

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#8170]
Just trying to document this more fully -- it's quite slow to post a comment, and I wanted to try to figure out why:

https://publiclab.org/notes/cess/07-20-2020/mega-workshop-2-by-rails-girls-kenya

I just posted this, and it took so long i had to stop recording the gif! But it posted just after i clicked stop:

![editor2](https://user-images.githubusercontent.com/24359/87966940-079a3400-ca8c-11ea-834d-776d2e16159c.gif)

@Tlazypanda i think i mentioned this before, i wonder if we could look at why this is? Could it be synchronous use of mailer scripts? Something else?

Thank you!! We can check it out on Skylight as well...

**Comment by Tlazypanda** [comment]
@jywarren Sure, I will definitely check this out can you please merge the skylight pr #8103  so that I can check it out by pushing on unstable? Since it's a bit difficult to inspect if the performance is improving or not otherwise 😅 Thanks ✌️

**Comment by Tlazypanda** [comment]
@jywarren on researching this endpoint I figured there are some places where:- 

- uids were extracted from users and then again passed to other functions where users are found using those ids. So instead of this better solution will be to directly pass user to avoid the query to find user using uid. (#8173 )
- n+1 queries in some templates which need to be eagerly loaded (need to eliminate these) For this we can add [bullet](https://github.com/flyerhzm/bullet) gem to development setup to detect n+1 queries (todo: add it as a part of CI to make sure we don't add any code that promotes n+1 queries)

Thanks :v:

**Comment by jywarren** [comment]
Amazing. Thanks for the swift response. Will check out that PR and i left a clarifying Q on the older one about skylight! Thanks!
