### ISSUE TITLE
quick thought -- collapsible sections of Activity Grids

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#835]
Just jotting an idea here that Activity Grids could get quite long. Imagine the /water-quality page will contain all activities that are also housing in Coqui grids, Riffle Grids, Secchi grids, etc!

Perhaps rows of activities that are the same category could be "collapsed" somehow into a simple label listing the Activity Category.

**Comment by david-days** [comment]
An alternative to collapsing (or maybe as a container for collapsible rows) is using the tabbed navigation that comes with bootstrap.  The [dynamic search page](http://publiclab.org/search/dynamic) uses this: The full HTML (dynamic via jQuery, in this case) is still within the page, but the groups are separated out by tabbed panels.

It doesn't always work as the best form of navigation, since you are placing high-level meta groupings at the start.  OTOH, if you have basic categories that can help shorten the lists, it's not a bad place to start.  Then you can use collapsible rows or panels for more detail.

**Comment by jywarren** [comment]
There's also a grid pagination issue being worked on by a new contributor:
https://github.com/publiclab/plots2/issues/793

I tend to think that we should go ahead with that, which in combination
with grid sortability, should be pretty good. Maybe we could eventually add
the ability to filter -- like, if you click on "easy" it starts showing
only easy activities.

**Comment by jywarren** [comment]
I'd like to defer to #793 for now, and follow up with more after we see how that works. Thanks!
