### ISSUE TITLE
spam comments bypassing moderators 

### ISSUE THREAD

**Issue by bronwen9** [publiclab/plots2#8434]
Comments from unapproved posters land on pages without 1) appearing on the moderation queue or 2) appearing as a new/unmoderated comment on the dashboard (am assuming because technically they're not approved or live on the site. 

The comments do show up with the approve/spam button once you navigate onto the page, but there isn't anything to alert moderators to their presence unless they happen to open the post. Users don't appear in "active user" lists.

I haven't deleted the posts on this page here (these should only be visible to moderators):

https://publiclab.org/questions/mimiss/09-16-2020/for-the-bucket-monitor-how-many-tedlar-bags-do-you-need-per-sampling

Screen shot
![image](https://user-images.githubusercontent.com/8331717/94474505-bef1ac00-019b-11eb-82bc-e06ecfc89b25.png)

Is there a way to ensure that the alerts to moderators for first time posters **include** posts that are made in the comments? I have observed most of these limbo posts to be spam, but wonder if we are also missing some "real" first time posters this way.

**Comment by ebarry** [comment]
Thank you SO MUCH for reporting this @bronwen9 !!!!!

**Comment by jywarren** [comment]
Hi @bronwen9 - thanks, and good to hear from you. The comment you mentioned is listed at https://publiclab.org/spam2/comments in the new comment moderation system created by @keshavsethi, so that part of the issue I believe is resolved. 

![image](https://user-images.githubusercontent.com/24359/94580430-e9993e80-0247-11eb-902f-60efea36231c.png)

![image](https://user-images.githubusercontent.com/24359/94580449-f1f17980-0247-11eb-9f33-eb3a2691f016.png)

For your idea -- 

> Is there a way to ensure that the alerts to moderators for first time posters include posts that are made in the comments? I have observed most of these limbo posts to be spam, but wonder if we are also missing some "real" first time posters this way.

Tracing our comment moderation system, I believe comments by first timers are `status = 4` which means an email notification is sent. Is that the kind of alert you're looking for, and is it possible to check if it was sent and received correctly?

(code for ref below)

https://github.com/publiclab/plots2/blob/e92aa27622e1e0b09e180d8d1670089002f0fb13/app/models/node.rb#L651-L655

https://github.com/publiclab/plots2/blob/e92aa27622e1e0b09e180d8d1670089002f0fb13/app/models/comment.rb#L140-L142

I think this resolves the issue but please re-open if anything looks wrong or there are gaps here, or if you have other ideas to add. Thanks a lot!

**Comment by ebarry** [comment]
I think we have not communicated with our moderators that they should be using /spam2, or when /spam2 might replace /spam. 
@bronwen9 please do check for email notification on this even though this issue is closed, if you don't see the email, please re-open this issue.
