### ISSUE TITLE
numbered list items separated by newlines begin over again at 1

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#844]
### What happened just before the problem occurred

The how-to steps on @shapironick https://publiclab.org/notes/nshapiro/09-26-2016/build-a-plant-based-air-purifier used a numbered list, but the numbering was wrong --> each numbered step had an image following the text, after which the numbering would begin again at 1. 

As an admin, i went in and added parentheses around each number, like this: 

(1.)
(2.)
(3.)

If we are going to be making good activities, having illustrated steps shouldn't mess up the numbering. What should we do?
### Relevant URLs

https://publiclab.org/notes/nshapiro/09-26-2016/build-a-plant-based-air-purifier

**Comment by jywarren** [comment]
That's actually standard Markdown behavior -- I've never really liked it.
But it's in the spec: http://spec.commonmark.org/0.25/#list-items

But maybe the solution could be: I think each step should be a header
anyways, because then it gets a link. We could scaffold this with a
template to sidestep the numbering lists thing. So:

### Step 1: dot your Is

### Step 2: cross your Ts

**Comment by jywarren** [comment]
issue moved to here: https://github.com/publiclab/PublicLab.Editor/issues/59
