### ISSUE TITLE
Welcome Outreachy Aspirants Winter 2020 

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#8448]
# :tada: Welcome Outreachy applicants for Winter program :tada:

We are so excited to have you here :heart: . This is a discussion issue for all of you. Please say hello in a comment below, so we get to know you. Ask any questions that you might have here and we will be sure to answer them as soon as possible. If you would like to checkout our large community you can find us on gitter https://gitter.im/publiclab/publiclab and also we do weekly check-ins where folks say what they are working on and ask for help if blocked. You can find the link to the latest check-in here #5627 

## First Step :computer: 
We suggest you make a first contribution. We have issues with the `first-timer-only` label which are specifically tailored for a first time contributor. You can find them here https://code.publiclab.org/ along with the guidelines on how to start contributing. Please be sure to check if someone is already working on an issue before you take it up. Kindly leave a comment on the issue to let other people know you are working on an issue. If you can't find any issues that are available, please feel free to leave a comment below and we will find you one asap. 
After you solve the first issue you can browse through our  "help-wanted" issues. Feel free to tag @publiclab/mentors if you need more context for you to solve an issue.

## Outreachy Winter Projects :memo: 

We have 2 projects for this round.

1,Comment Editor Overhaul Project:
- Github: https://github.com/publiclab/PublicLab.Editor/issues/630
- Outreachy: https://www.outreachy.org/outreachy-december-2020-internship-round/communities/public-lab/#comment-editor-overhaul-project

2. New Dashboard Implementation Project: Bootstrap 4 and Rails :
- Github:  https://github.com/publiclab/plots2/issues/8513
- Outreachy: https://www.outreachy.org/outreachy-december-2020-internship-round/communities/public-lab/new-dashboard-implementation-project-bootstrap-4-a/cfp/

## Call for Proposals :page_with_curl: 
We request applicants to post their proposals on the PublicLab website. [Here](https://publiclab.org/notes/cess/10-02-2020/call-for-proposals-outreachy-winter-2020) is a link to call of proposals to the PL website, which also has a template for drafting the template, sample proposals for past interns and helpful pointers while drafting the proposals.
Kindly submit early and post the link here or on gitter so that contributors and mentors can give feedback and help you improve on your proposal before you submit it on the Outreachy website.

#### These tips are general tips.
Are you tensed? overwhelmed?  No need to worry!!! We all are there to help you at each stage of the way. Feel free to reach out in case of anything :relaxed:

**Comment by ebarry** [comment]
Welcome Outreachy applicants! We're excited that you're here. Do you have any questions?

**Comment by FrankieMFerreira** [comment]
Hello! I just want to thank you all for your contribution towards making this an open and friendly community!

**Comment by jywarren** [comment]
Hi everyone! I'm so excited to meet you all! My name is Jeff, he/him/his, and I'm in Rhode Island, on the US east coast. I like cooking and woodworking 🍜 🛠️  and helping newcomers get situated with our community!

I've been mentoring with Outreachy since 2017, and it's always been a wonderful experience! Several Outreachy alums are with us as regular contributors still, and a lot of awesome work has been done through Outreachy projects. We're here to help, so please ask if you have any questions! And, if you'd like a `first-timers-only` issue to work on, and one isn't available, we can make one for you!

We are really looking forward to this round of Outreachy! Thank you for coming!

**Comment by ana-vela** [comment]
Hello! I'm looking forward to making contributions to PublicLab! What a welcoming environment so far!

**Comment by Oghenebrume50** [comment]
Hello Everyone and awesome mentors :slightly_smiling_face: , I am looking forward to contributing and doing amazing work with Public lab during the course of this internship and afterwards

**Comment by Annysah** [comment]
Hello, I'm Anisat Akinbani and I must it feels so welcoming to be here. I would love to be a part of the Public Lab project and really looking forward to making contributions!!.

**Comment by jywarren** [comment]
Welcome all! And not to put her on the spot but Cess is an Outreachy alum! 🔥

**Comment by urvashigupta7** [comment]
I started my Opensource journey with PublicLab. This was the first org I contributed to. Thankyou all for being so welcoming always. Looking forward to make more contributions ❤️🎉

**Comment by Tlazypanda** [comment]
Hello everyone :wave: It's so great to have you all here! :tada: Here are some common queries answered in the previous Outreachy season for your reference:- 

https://github.com/publiclab/plots2/issues/7617#issuecomment-601110786 Thank you all! :v:

**Comment by nibble0101** [comment]
Hi. My name is Joseph, an outreachy applicant. Interested in contributing to this project.

**Comment by GabriellaAmah** [comment]
Hello everyone, My name is Gabriella and i am an Outreachy applicant. i look forward to working with the maintainers and contributors of this project.

**Comment by Iamhafsah** [comment]
Hi all. I'm Hafsah, an Outreachy applicant. I m so excited to be here, and I look forward to contributing to this project.

**Comment by Shreets** [comment]
Hello everyone, I am Shreeti- an Outreachy applicant and I am super psyched to be starting my open source contribution with Public Lab. Can't wait to work with and learn from this community and the mentors. Cheers!

**Comment by RuthNjeri** [comment]
Hi, PublicLab team and Outreachy applicants!
I'm Ruth Waiganjo, an Outreachy applicant, I'm looking forward to learning and collaborating with you all :)

**Comment by RuthNjeri** [comment]
Hi, @cesswairimu I'm trying to figure out which issue to pick up, most issues have been already assigned.. are there issues you could point me to? I'm okay if it's not a `first-timer-only` issue

**Comment by cesswairimu** [comment]
Hi @RuthNjeri , sure, let me find one for you.

**Comment by cesswairimu** [comment]
@RuthNjeri  checkout this one https://github.com/publiclab/plots2/issues/6685 and leave a comment there if you would be interested to work on it

**Comment by Cadreia** [comment]
Hi @cesswairimu , I'm an Outreachy Applicant and would like to work on an issue. Please can you create one and assign it to me? It's my first contribution.

**Comment by cesswairimu** [comment]
Hi @Cadreia, let me find you one

**Comment by cesswairimu** [comment]
@Cadreia here you go https://github.com/publiclab/plots2/issues/8496

**Comment by cesswairimu** [comment]
There is this open issue if anyone else is looking for one https://github.com/publiclab/plots2/issues/8497

**Comment by kofosu2289** [comment]
Hello everyone, I am an Outreach applicant and am very excited to begin my contributions to this organization. Everyone seems to be so welcoming!

**Comment by jywarren** [comment]
Made a new one in https://github.com/publiclab/plots2/issues/8501 if anyone is looking for one!

**Comment by jywarren** [comment]
I believe https://github.com/publiclab/plots2/issues/3440 and https://github.com/publiclab/plots2/issues/6598 are still available too! Please mention you're part of Outreachy when you claim them. And... if it's a pretty old issue, there is always a chance it's already complete or obsolete, so just be aware in case you get confused! Always feel free to ask if you get stuck :-) 🤝 🙌 🎉 

Thanks, folks!

**Comment by damiecode** [comment]
Hello Everyone, My name is Damilola and I look forward to working with you.

**Comment by GabriellaAmah** [comment]
@jywarren seems like the  all issue you put up has been taken. Please could you provide another

**Comment by jywarren** [comment]
Hi @GabriellaAmah I've just made #8510 for you! And #8511 and #8512 are both now open as well. Thanks, all!

**Comment by jywarren** [comment]
Great job @RuthNjeri for creating your own issue and welcoming/supporting someone else! https://github.com/publiclab/plots2/pull/8502

Folks who've completed their first contribution are welcome to try this out :-)

We also have some "candidates" that may make for good `first-timers-only` issues -- see https://github.com/publiclab/plots2/labels/fto-candidate -- and we often mark those with this following text so that they could be used to welcome someone new!

****

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

**Comment by sagarpreet-chadha** [comment]
Hi everyone! Very happy to meet you all!
My name is Sagarpreet, he/him/his, and I am from Bangalore, India. I like travelling, playing football and coding :) 

I've been mentoring with Outreachy from a long time now, and I always learn new exciting things each time from the interns!
Very excited for this round of Outreachy! The projects this time are also challenging yet fun to solve 😄 🚀 Thank you all for coming! 💯

**Comment by Asu1996** [comment]
Hello! I am Asutosh from India. I am an Outreachy Applicant and look forward to contributing here. Thank you.

**Comment by Emmahchinonso** [comment]
hi, i'm chinonso an outreachy applicant from nigeria, please how do i go about setting up my local environment..

**Comment by Cadreia** [comment]
Hello, @Emmahchinonso the information you'll need for that is found in the repository's README file. You can find it at https://github.com/publiclab/plots2/blob/main/README.md

**Comment by tawahpeggy** [comment]
Hi All, My name is Tawah Peggy Che. I recently completed the coursework for a BEng in Computer Software Engineering and will like to get in to open source not just to boost my career and gain experience but also to contribute to free and open-source projects. since my initial application for outreachy was approved I looked through current Outreachy projects and the Public Lab   Project #2 ( New Dashboard Implementation Project: Bootstrap 4 and Rails)   from this organization really seemed interesting to me and I would like to contribute to it so I can add value to this great initiative in my own little way. I am new to opensource and I look forward to learning from you all.

**Comment by jywarren** [comment]
Hello folks who've just joined! I've made a new first-timers-only issue -- please claim it by leaving a comment at https://github.com/publiclab/plots2/issues/8531

@Emmahchinonso - the easiest way to begin is to try using GitPod, which has a preset standard environment. It's a web-based system but very good - i use it myself quite a bit to work on this project. You can find a link near the top of the README, as @Cadreia linked to!

https://github.com/publiclab/plots2/blob/main/README.md

**Comment by jywarren** [comment]
Folks who've completed a first-timers-only issue - if you're interested, there may be some interesting tasks related to creating our new blog template -- you can read more at the very bottom of https://github.com/publiclab/plots2/issues/5352#issuecomment-706647406! We'd love help, and if you're looking for a new challenge, that's a great spot to start!

**Comment by Emmahchinonso** [comment]
@jywarren i have gotten gitpod running, please what next

**Comment by shubhangikori** [comment]
Hello everyone, I am Shubhangi Kori. I am an outreachy applicant. And looking forward to contributing to the project.

**Comment by shallom-dot** [comment]
Hello everyone,I'm Roseline, an outreachy applicant. I'm really excited to be here. Thankyou for being so welcoming.

**Comment by RuthNjeri** [comment]
Hi everyone, if you are still looking for a first-time issue you can comment on this issue https://github.com/publiclab/plots2/issues/8516 to get assigned.

**Comment by Janetsomehow** [comment]
Hi everyone i am an outreachy applicant

**Comment by diorshelton** [comment]
Hey everyone! I'm an Outreachy applicant searching for a first-time issues. I'm looking forward to contributing as well as learning. 🙂

**Comment by fiona-byte** [comment]
Hello everyone, I'm Chiamaka and I'm an Outreachy applicant. I'd love to be part of the Public Lab project and I'm looking forward to making contributions.

**Comment by jywarren** [comment]
@Emmahchinonso that's great you've gotten GitPod running! Now you can try completing a `first-timers-only` issue -- we are creating them as fast as we can, but they're listed at https://code.publiclab.org !

**Comment by Cadreia** [comment]
Sure! I'd love to. Just so I'm clear, am I creating an entirely new issue from #8490?

**Comment by jywarren** [comment]
Hi - yes, you can make a new one, copying in the essential info and
creating the welcoming step-by-step format, and then I'm happy to label it
and close the old issue! Thank you!

**Comment by jywarren** [comment]
I've just made a new first-timers-only issue at https://github.com/publiclab/plots2/issues/8561 - please leave a comment there to claim it! Thank you!

**Comment by jywarren** [comment]
And another here! https://github.com/publiclab/plots2/issues/8563

**Comment by tawahpeggy** [comment]
any first timers issue for me? i havent been able to lay hands on any.

**Comment by cesswairimu** [comment]
@tawahpeggy  you can claim this one  https://github.com/publiclab/plots2/issues/8572

**Comment by KarenEfereyan** [comment]
Good day everyone. My name is Karen. Im an outreachy applicant. Im looking forward to working with bright minds like you all. Im on the lookout for first timer issues. Kindly tag me to any available one.

**Comment by KarenEfereyan** [comment]
> Hi everyone! Very happy to meet you all!
> My name is Sagarpreet, he/him/his, and I am from Bangalore, India. I like travelling, playing football and coding :)
> 
> I've been mentoring with Outreachy from a long time now, and I always learn new exciting things each time from the interns!
> Very excited for this round of Outreachy! The projects this time are also challenging yet fun to solve 😄 🚀 Thank you all for coming! 💯

I love the sound of that. 🤣🤣

**Comment by KarenEfereyan** [comment]
@cesswairimu I can't find any first time issue. Can you create one for me?

**Comment by asadkhalid305** [comment]
Hello everyone!

My name is Asad and I am a professional JavaScript developer. 

It's good to see so welcoming environment here especially for people who are interested to start contributing in open source. Though, I am one of those who really want to contribute so thus I am looking forward for issues to start working on. 

Kindly tag me on some issues I can start working on since I found all existing one reserved already. 

Looking forward to learn and contribute with all of you amazing people!

**Comment by Kennygrace** [comment]
Hi everyone, I'm Kennygrace,  I'm happy to be here, looking to learn and contribute to this community

**Comment by ebarry** [comment]
Here's an issue that has code links and is high priority: https://github.com/publiclab/plots2/issues/8490

**Comment by saitgulmez** [comment]
Hi, 
I'm Mehmet,  an applicant of Outreachy Dec 2020 internship program. I'm interested in open source projects and would like to join to this community.

**Comment by edward-hong** [comment]
Hi I'm Edward an applicant of Outreachy. This projects intrigues me and seems very first-timer friendly. I look forward to working with all of you!

**Comment by IjayAbby** [comment]
Hello Everyone I feel honored by the welcome wishes from the mentors and community at Public Lab. I am Ijay an Outreachy applicant would love @cesswairimu & @jywarren   to kindly tag me to any available first timer issues to work on.

**Comment by cesswairimu** [comment]
@IjayAbby  here you go https://github.com/publiclab/plots2/issues/8615

**Comment by cesswairimu** [comment]
Hello everyone, its great to have you all here and  hope everything is going on well. If you still haven't got a first-timer issue to work on please let us know and we will try to find you one. The application deadline is 2 weeks away, this would be a good time to start drafting a [proposal](https://publiclab.org/notes/cess/10-02-2020/call-for-proposals-outreachy-winter-2020) to give mentors a chance to give feedback and improve your proposal before you post the final draft on the Outreachy website. 
Thanks all

**Comment by Sagarpreet** [comment]
Agreed with @cesswairimu , it is good time to start writing your draft proposals and share with us sooner to get better reviews and then you will have plenty of time to incorporate the changes if any in your proposals 😄

**Comment by RuthNjeri** [comment]
Hi everyone!
Thanks for the reminder @cesswairimu and @sagarpreet-chadha 

It's this week's focus in the weekly [check-in](https://github.com/publiclab/plots2/issues/8619)

**Comment by AnneThor** [comment]
Hello! My name is Anne and I'm an outreachy applicant looking for a first time issue, is there anything out there for me? :)

**Comment by tawahpeggy** [comment]
Hello @AnneThor  this is a first timer issue: https://github.com/publiclab/plots2/issues/8625 check if its still available and you can work on it if its okay by @jywarren. incase you encounter any problems you can ping me.

**Comment by jywarren** [comment]
Hi Anne - I've just created one at https://github.com/publiclab/plots2/issues/8639 if you leave a comment there you can claim it!

**Comment by saitgulmez** [comment]
Hi
 i'm Mehmet, an applicant of Outreachy and i really get stuck to find an
issue to deal with. Could you please assign me any issue that i can do?

Thanks in advance

**Comment by tawahpeggy** [comment]
Hi Mehmet Sait Gülmez welcome to publiclab. be patient and watchful a
mentor will soon open a first timers only issue for
you. @jywarren @cesswairimu

**Comment by cesswairimu** [comment]
@saitgulmez you can checkout this one https://github.com/publiclab/plots2/issues/8652

**Comment by saitgulmez** [comment]
Hi,
I'll definitely check it. At first, i tried to compile github sources codes
on Ubuntu 18.04 but i got some problems with gem,ruby and so on. Now i'll
do build source codes on windows 10  (Even i'm using Ubuntu more than 10
years and get used to it). Thank you.

**Comment by cesswairimu** [comment]
Hi @saitgulmez, its much easier to develop with Linux. If you would like to give Ubuntu installations another try we could help, there is a thread [here](https://github.com/publiclab/plots2/issues/3840) that has almost all the issues encountered when installing and their solutions if you have a new error you can post it there or on the chat. If you are doing first-time installation [this](https://github.com/cesswairimu/GirlsGetGeeky/blob/master/Installations/linux.md) works great. Either way, whichever OS works for you is okay. Thanks

**Comment by nk183** [comment]
Hello! I'm looking for a first time issue, is there anything out there for me?

**Comment by KarenEfereyan** [comment]
> 
> 
> Hello! I'm looking for a first time issue, is there anything out there for me?

We should be able to find something for you. @jywarren @cesswairimu any new timer issues up for grabs?

**Comment by RuthNjeri** [comment]
There's a first timer issue available if anyone is looking for one.. 
https://github.com/publiclab/plots2/issues/8690

**Comment by jywarren** [comment]
Hi all! Just a reminder!

Please be sure to file your proposal on the Outreachy website as well as [on our PublicLab.org page](https://publiclab.org/notes/cess/10-02-2020/call-for-proposals-outreachy-winter-2020). You can use a lot of the same text. See Outreachy's text below!

====

In order to be eligible to be selected as an Outreachy intern, each applicant must:

1. Fill out an initial application at https://www.outreachy.org/eligibility/
2. Record a contribution to your project on the Outreachy site.
3. Complete a final application for your project.

The deadline for final applications is Oct. 31, 2020 at 4pm UTC. Applicants will not be able to create a final application after the deadline. Applicants can edit their final application until the deadline.

Applicants who submit a final application will be able to continue recording and editing their contributions to your project. They can record contributions until the intern announcement on Nov. 23, 2020 at 4pm UTC. Applicants who have not submitted a final application will not be able to record or edit their contributions.

It's very important that you encourage the applicant(s) you want to accept for your project to complete their final application before the final application deadline. If you do not see the applicant you want to select on this list, contact them ASAP and tell them to record a contribution and submit a final application at this URL (which only works for eligible applicants, not mentors):

https://www.outreachy.org/outreachy-december-2020-internship-round/communities/public-lab/comment-editor-overhaul-project/contributions/

**Comment by cesswairimu** [comment]
Thank you everyone for applying with PublicLab. We had great proposals from all you and had a huge spike on contributions last month all thanks to you,  we got two slots but we would have loved to take in more..For those who did not get selected, please know that we are extremely grateful for your work with us to date and that we welcome you to continue being part of this community. Thank you for understanding and we hope you’ll apply again :heart:

**Comment by cesswairimu** [comment]
Thanks everyone once more for applying with us and Congrats @RuthNjeri  and @noi5e :tada: :tada:

**Comment by harshdhonchak** [comment]
Hello! I'm looking for a first time issue, is there anything out there for me?

**Comment by cesswairimu** [comment]
Hello @harshdhonchak, I have reserved one for you here https://github.com/publiclab/plots2/issues/8910 thanks
