### ISSUE TITLE
Turn editor tests back on after getting them to pass (Outreachy related)

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#8858]
To finish moving off Travis and into GitHub Actions in https://github.com/publiclab/plots2/pull/8795/, I turned off all 4 tests in `/test/system/editor_test.rb`

Here's the commit:

https://github.com/publiclab/plots2/pull/8795/commits/8bbbaf8baa061428b0ae7d221ae5831cff06cd76

We just need to turn them back on and figure out why they aren't passing; here are the errors:

```
[Screenshot]: tmp/screenshots/failures_test_check_markdown_editor_features_are_functional.png
ERROR["test_check_markdown_editor_features_are_functional", #<Minitest::Reporters::Suite:0x00007f34518414d0 @name="EditorTest">, 90.52515762799999]
 test_check_markdown_editor_features_are_functional#EditorTest (90.53s)
Minitest::UnexpectedError:         Capybara::ElementNotFound: Unable to find css "a[data-original-title='Edit this wiki page.']"
            test/system/editor_test.rb:66:in `block in <class:EditorTest>'

[Screenshot]: tmp/screenshots/failures_test_check_rich_editor_features_are_functional.png
ERROR["test_check_rich_editor_features_are_functional", #<Minitest::Reporters::Suite:0x00007f345b370b40 @name="EditorTest">, 153.1470894050001]
 test_check_rich_editor_features_are_functional#EditorTest (153.15s)
Minitest::UnexpectedError:         Capybara::ElementNotFound: Unable to find css "a[data-original-title='Try the beta inline Rich Wiki editor.'"
            test/system/editor_test.rb:42:in `block in <class:EditorTest>'

[Screenshot]: tmp/screenshots/failures_test_check_that_markdown_wiki_editor_functions_correctly.png
ERROR["test_check_that_markdown_wiki_editor_functions_correctly", #<Minitest::Reporters::Suite:0x00007f345ad811a8 @name="EditorTest">, 215.64896502800002]
 test_check_that_markdown_wiki_editor_functions_correctly#EditorTest (215.65s)
Minitest::UnexpectedError:         Capybara::ElementNotFound: Unable to find css "a[data-original-title='Edit this wiki page.'"
            test/system/editor_test.rb:32:in `block in <class:EditorTest>'

=[Screenshot]: tmp/screenshots/failures_test_check_that_rich_wiki_editor_functions_correctly.png
ERROR["test_check_that_rich_wiki_editor_functions_correctly", #<Minitest::Reporters::Suite:0x00007f345b28f118 @name="EditorTest">, 278.21773055100016]
 test_check_that_rich_wiki_editor_functions_correctly#EditorTest (278.22s)
Minitest::UnexpectedError:         Capybara::ElementNotFound: Unable to find css "a[data-original-title='Try the beta inline Rich Wiki editor.'"
            test/system/editor_test.rb:18:in `block in <class:EditorTest>'
```

**Comment by jywarren** [comment]
Hi @Uzay-G - i hope you're well - i've turned off these tests as i couldn't get them to work in Github Actions... do you have any ideas or suggestions as to why we aren't seeing them working? I remember you added them originally. I've moved the file to:

https://github.com/publiclab/plots2/blob/6e0d55f3d4f542a2a28c139abdc9964ec42c0d98/test/system/editor_test.rb#L15-L80

Thank you!

**Comment by noi5e** [comment]
It looks like the views at wiki#show and wiki#edit have changed a lot since this test was written. Here's the screenshot from the test:

![failures_test_check_markdown_editor_features_are_functional](https://user-images.githubusercontent.com/4361605/103693587-637b4b00-4f4e-11eb-8ead-94def7fdba09.png)

The pencil's selector is now `#edit-btn`, not `a[data-original-title='Edit this wiki page.']`.

**Comment by cesswairimu** [comment]
As I mentioned, I was checking into these and found  that this text
https://github.com/publiclab/plots2/blob/f82a11c17404bae7b4307313b6890ca3169e8c90/test/system/editor_test.rb#L17
is no longer rendered on that page...causing a couple of these to fail...also a lot of names, divs and ids have changed as  @noi5e  mentioned above 
Also a couple of these scenarios are tested here https://github.com/publiclab/plots2/blame/main/test/system/post_test.rb

**Comment by noi5e** [comment]
This may or may not be related, but I was asking in the meeting today... Is it even possible to access the legacy editor through `/wiki/edit` or `/wiki/new` (or even anywhere else on the site?)

- [/wiki/new on stable](https://user-images.githubusercontent.com/4361605/105083617-07362200-5a4a-11eb-84d5-bb09974dd639.png)
- [/wiki/edit on stable](https://user-images.githubusercontent.com/4361605/105083494-d5bd5680-5a49-11eb-9e49-e7bfb7793d47.png)
- [/post on stable](https://user-images.githubusercontent.com/4361605/105083904-70b63080-5a4a-11eb-8cc4-bc238c6a25cb.png)
- [/questions/new on stable](https://user-images.githubusercontent.com/4361605/105083959-83306a00-5a4a-11eb-98d0-cfd80b5a1dd9.png)

All of these appear to be using the rich-text editor (I think?). I can't find a link or other way to access the legacy editor in these pages... @jywarren Do you see the same things when you visit these pages? We were talking in the meeting about maybe admins or senior user accounts might still have access to the legacy editor. 

This does affect Comment Editor work at #8775, because scripts like `editor.js` and `dragdrop.js` are required in some pages that use the legacy editor... But if we're going to clean up controllers and views, maybe I don't have to worry about these contexts.

I also acknowledge that I may not actually know what the phrase "_legacy editor_" refers to... Like, maybe I've never even seen one live!

`/features/new` seems to still be live [here](https://stable.publiclab.org/features/new), and it's using a pretty bare-bones editor (which still has rich-text buttons and things): 
<img width="1440" alt="Screen Shot 2021-01-19 at 11 40 14 AM" src="https://user-images.githubusercontent.com/4361605/105084542-5597f080-5a4b-11eb-8f9f-dc67c9e43196.png">

Does this count as a legacy editor?

**Comment by jywarren** [comment]
Agreed though let's remove what's redundant and trim the rest, if possible!

**Comment by cesswairimu** [comment]
Wonderful! that totally explains it Jeff

**Comment by ebarry** [comment]
the one bit i'm sure of is that `/features/new` is fine as is. it's just a special editor where site admins can write html and stuff for special places.

**Comment by jywarren** [comment]
Thanks for investigating this one Cess! Great job!

**Comment by jywarren** [comment]
@noi5e did Cess's comments in the chatroom clarify things? I think sharing screenshots of both states will help disambiguate, if not. 

What do you think of leaving these tests off? Or, of how they might be redundant with tests you're writing?

**Comment by noi5e** [comment]
@jywarren I have greater clarity about legacy vs rich text editor now! 

I don't think system editor rich-text editor will affect my work much. It seems like the rich-text editor is using separate JavaScripts? I'm more trying to catch instances of the legacy editor.

Regarding this issue: yes, we can leave the tests off, if it makes sense. I agree, it seems like these tests just became inaccurate after being unused, and now just need to be rewritten with different selectors (doesn't seem like a lot of work TBH)

**Comment by jywarren** [comment]
OK. Let's close this and if there are opportunities to rebuild those tests that's fine as well. Thanks, all!

**Comment by cesswairimu** [comment]
Thanks Jeff, should I create an issue to add a link to the beta editor or we are good for now?
