### ISSUE TITLE
Intermittent database failures in MySQL on Github Actions

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#8868]
probably worth trying to search for this issue in relation to github actions, or maybe in the mysql github action:

```
/home/runner/work/plots2/plots2/vendor/bundle/ruby/2.6.0/gems/ffi-1.13.1/lib/ffi/library.rb:112: [BUG] Illegal instruction at 0x00007fb387d3a6d0
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0057 p:---- s:0287 e:000286 CFUNC  :open
c:0056 p:0022 s:0281 e:000280 BLOCK  /home/runner/work/plots2/plots2/vendor/bundle/ruby/2.6.0/gems/ffi-1.13.1/lib/ffi/library.rb:112 [FINISH]
c:0055 p:---- s:0272 e:000271 CFUNC  :each
c:0054 p:0113 s:0268 e:000267 BLOCK  /home/runner/work/plots2/plots2/vendor/bundle/ruby/2.6.0/gems/ffi-1.13.1/lib/ffi/library.rb:109 [FINISH]
```

_Originally posted by @jywarren in https://github.com/publiclab/plots2/issues/8860#issuecomment-747706371_

**Comment by noi5e** [comment]
Got this error on my most recent PR at #8860:
<img width="1024" alt="Screen-Shot-2020-12-17-at-1 00 05-PM" src="https://user-images.githubusercontent.com/4361605/102547002-5bc23800-406d-11eb-9538-8cdc8c6c3afa.png">

Restarted the tests 3 times and it worked on the third... However it might be concerning because of the high-frequency. @jywarren mentioned that @RuthNjeri may have also run into this problem.

I googled the bug a bit but haven't come up with anything. Search results [here](https://www.google.com/search?safe=off&sxsrf=ALeKk01ChZwqhqgdTC4Gq5DI1pUhCnjgKg%3A1608241295953&source=hp&ei=j9DbX9yyN8e40PEPqN-F0Ac&q=%2Fbundle%2Fruby%2F2.6.0%2Fgems%2Fffi-1.13.1%2Flib%2Fffi%2Flibrary.rb%3A112%3A+%5BBUG%5D+Illegal+instruction&oq=%2Fbundle%2Fruby%2F2.6.0%2Fgems%2Fffi-1.13.1%2Flib%2Fffi%2Flibrary.rb%3A112%3A+%5BBUG%5D+Illegal+instruction&gs_lcp=CgZwc3ktYWIQA1CcAVicAWCSBGgAcAB4AIABU4gBU5IBATGYAQCgAQKgAQGqAQdnd3Mtd2l6&sclient=psy-ab&ved=0ahUKEwictp_Z_dXtAhVHHDQIHahvAXoQ4dUDCAg&uact=5)

**Comment by jywarren** [comment]
OK, thanks @noi5e i will prioritize this on Tuesday!

**Comment by jywarren** [comment]
OK, and clarifying, we're using the built-in MySQL service that comes with the Github Actions containers... here are some resources:

* https://github.com/actions/virtual-environments - the repo for Actions stuff like the mysql service
* https://firefart.at/post/using-mysql-service-with-github-actions/ (includes example for possible switch back to MariaDB)

**Comment by jywarren** [comment]
Trying MariaDB here: https://github.com/publiclab/plots2/pull/8874

**Comment by jywarren** [comment]
Looks like this may actually have to do with the sassc gem -- https://github.com/ffi/ffi/issues/739

Indeed, our trace is more fully: https://gist.github.com/jywarren/a78bae4dc2af226d3d95d0bda625fb09

noting we're on sassc 2.2.1, not 2.2.0... still...

Seems like this error: https://github.com/sass/sassc-ruby/issues/146#issuecomment-527103083

**Comment by jywarren** [comment]
OK - will try these two options before `bundle install`:

* `RUN gem install sassc -- --disable-march-tune-native`
* `bundle config force_ruby_platform true`

**Comment by jywarren** [comment]
The solution was `upgrading sassc-ruby to v2.4.0` !!! Awesome #8889
