### ISSUE TITLE
Weekly Community Check-In #88 - Tools, Tips, & Tricks

### ISSUE THREAD

**Issue by RuthNjeri** [publiclab/plots2#8931]
Hello and Happy New Year! 🎉 

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## How do you choose your tools? And What are some of the Tips and Tricks You have

Sometime before the holidays began, there was a discussion in the Outreachy chat on the criteria to use when choosing which tools or gems to use. It could be useful when picking out a gem or setting up your working environment. Some tips shared were;

1. Asking more experienced people what tools to use and understanding what people's decision-making process is. 
2. Looking at the number of stars on the Github or the number of downloads a package has.
3. Looking at the issues on the Github page and if they have not been responded to, or has a lot of unreviewed PRs, it could mean that the project has been abandoned.
4. Checking the most recent commit and how many contributors are there.
5. Carrying out a community discussion and swapping suggestions

I'd like us to have our weekly check-in focus on the fifth point, where we share various tips and tricks that you think have been useful to you.

I'll start 😄  

I use Visual Studio Code as my main editor. It has a lot of useful extensions that I use when coding. There's an extension that color codes opening and closing brackets, which is very useful when debugging Javascript code.
<img width="685" alt="Screenshot 2021-01-04 at 15 56 39" src="https://user-images.githubusercontent.com/7622875/103537687-eac0b400-4ea5-11eb-89ef-150224a42268.png">

I also like how I can see the last person who wrote a specific code and I can even navigate to the Pull Request that contained that code to read more about it.  It has been useful in learning more about the code.

<img width="709" alt="Screenshot 2021-01-04 at 15 59 12" src="https://user-images.githubusercontent.com/7622875/103537709-f613df80-4ea5-11eb-8ce5-471890d171da.png">

What are some of the Tools, Tips and Tricks you use?

## This week's focus Issues

These are issues that are of high priority and requests from our
large community that use the software. 

1. https://github.com/publiclab/plots2/issues/8864
2. https://github.com/publiclab/plots2/issues/8858
3. https://github.com/publiclab/plots2/issues/8177
4. https://github.com/publiclab/plots2/issues/7798

We will very much appreciate any help on these issues. Any contributor who is looking for issues to work on please consider taking a look at these.
We will add a thank you message here in next week's check-in if you contribute to any of these. Thanks in advance 😄

### Thank you note to focus issues contributors

A huge thank you to all the contributors who spent some time to learn more about us, review code, pick up an issue, raise an issue and even create pull requests to fix an issue in 2020.

We hope that you will continue contributing any way you can this year 🤗 

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by cesswairimu** [comment]
Happy new year everyone :tada: :tada:
I use a terminal called terminator,it has this split screen feature that is really great esp for folks using command-line editors, you could have you server running on one side and have your editor on the other.
![Screenshot from 2021-01-05 11-31-38](https://user-images.githubusercontent.com/17081074/103624739-0205ad00-4f4b-11eb-846b-f06de515bc68.png)
 Its also great if you want to monitor multiple process like rails server, redis and sidekiq at the same time, you could split and have them running on the same window

Great theme @RuthNjeri and thanks for opening this

**Comment by Uzay-G** [comment]
I use [neovim](https://neovim.org) as my editor. I find it really nice because it's very lightweight and yet very extendable while running in the terminal.

![image](https://user-images.githubusercontent.com/52892257/103634005-c963d480-4f46-11eb-8b3c-df513558f83d.png)

I'm thinking about getting a better setup for handling my terminal windows as @cesswairimu has, but I haven't worked on it yet.

It's also interesting to think about what **languages** you use as tools for the projects you're working on. I've spent a lot of time discussing what stack I should use for a given project with friends and mentors because if you realize you've made a bad decision a rewrite will lose you a lot of time.

For now, though, my main choices have been Ruby and Python but I am learning Haskell and Rust as other intriguing languages I want to use.

**Comment by noi5e** [comment]
Wow, really impressed that @cesswairimu and @Uzay-G use command-line editors, I've always been intimidated by those... That's inspiring me to learn.

I use VSCode like @RuthNjeri, and I like it a lot! It's interfacing with Git is really useful... I can click a button to stage/unstage changes, and handle merge conflicts in the editor. I think it saves a lot of time vs typing in the command line.

<img width="1012" alt="Screen Shot 2021-01-05 at 5 10 52 PM" src="https://user-images.githubusercontent.com/4361605/103716996-37c18a80-4f79-11eb-8fc1-fc07febde131.png">

**Comment by Sagarpreet** [comment]
Hey @RuthNjeri , @cesswairimu , @noi5e (and everyone 😄 )
Happy new year 🎉 
Can you ping the PR's that you are working on or are up for review here? My notifications are messed up right now. Thanks 💯

**Comment by cesswairimu** [comment]
Hey all :wave:  lets keep this great theme for another week to give other folks time to share their tools.

A big welcome to new contributors 
  @gucci-ninja, @slaterp,  @nikole24, @frappelatte28, @TharindaDilshan, @Manasa2850, @gauravahlawat81, @wambugucoder, @salitaba, @EricJB77, @jctan :tada:  linking them to our current check-in ( we do check-ins each week ,its a place to say hi, ask for help if you are stuck etc and we normally have a theme that we discuss...you can checkout some past check-ins [here](https://github.com/publiclab/plots2/issues/5627) ), feel free to share  some tools, tips and tricks that you use to make your development easier, just say hi or just browse through.

If anyone would like to open next week's check-in please leave a comment.
Thanks all and great week ahead everyone :balloon:

**Comment by jywarren** [comment]
Wow, color-coding brackets is really useful @RuthNjeri!

Hmm, well i use vim, i guess i like it because i can use it to edit files on remote servers and my fingers know a consistent set of commands... 

I have gradually added color coding and such to help me see things, i keep my vim color settings (and other settings) here: https://github.com/jywarren/init

and it has this embarrassingly named vim plugin called NERDTree which lets you have tabs in vim. It's honestly really ridiculous because vim is so basic that adding tabs is almost silly, but it preserves copy/paste across the tabs, which is nice... although of course it wouldn't be an issue if I used a non-terminal editor 😂 😭 

I guess i've just gotten kind of set in my ways. I like using really cheap computers (my main one is a chromebook) and so just relying on terminal programs is nice for compatibility. And, i like making it full screen so i'm less likely to get distracted by a browser tab or something! 

One thing i really like about vim is the ability to copy paste from mid-line, but across multiple lines (which i think is possible in some editors on Macs using option-drag):

![image](https://user-images.githubusercontent.com/24359/104335679-9c24a280-54c1-11eb-842e-120c65e74250.png)

That said, i love the built-in way to see who made the last change on a line of code that @RuthNjeri showed, and I can't do that in vim!!!

**Comment by RuthNjeri** [comment]
> Hey @RuthNjeri , @cesswairimu , @noi5e (and everyone 😄 )
> Happy new year 🎉
> Can you ping the PR's that you are working on or are up for review here? My notifications are messed up right now. Thanks 💯

I'm just rereading this message now 😅 , I think you were able to fix the notifications? Or can I tag you in a comment if I need any reviews in future PRs?

**Comment by noi5e** [comment]
I've got to check out vim!!! I missed that message too, @Sagarpreet thanks for checking out some of my PRs in the meantime.

Just going to drop the link to my planning issue here #8775. I've been updating it every day for the past week, and I usually leave a link to my open PRs there too. (none open right now, but maybe later today)

**Comment by cesswairimu** [comment]
This was a great discussion...thanks all :heart: 

Moved to https://github.com/publiclab/plots2/issues/9077
