### ISSUE TITLE
Weekly Community Check-In #91 - Breaking Down Tasks

### ISSUE THREAD

**Issue by RuthNjeri** [publiclab/plots2#9158]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## How do you break down your tasks?

Hi Everyone! Happy Monday 🎉 

At Public Lab, we huge advocates for bite-sized pull requests.  It is not only easier to understand what is happening in a small Pull Request, it helps reduce the risk of introducing bugs within the application.

What are some of the metrics you use to determine if a PR is huge? The number of file changes? The Scope of the work?
What do you do to break down tasks? Frontend vs Backend? 

Say hi or tell us more in the comments below 😄 

Meaning of bite-sized
> small or short enough to be easy to understand, remember, or deal with at one time

## This week's focus Issues

These are issues that are of high priority and requests from our
large community that use the software.  Continued from last week's Checkin

#8864 (Test Failures Caused by Revision Fixtures with the Same NID)

We will very much appreciate any help on these [issues](https://github.com/publiclab/plots2/labels/high-priority). Any contributor who is looking for issues to work on please consider taking a look at these.
We will add a thank you message here in next week's check-in if you contribute to any of these. Thanks in advance 😄

### Thank you note to focus issues contributors

Thank you @StreakSharn, @StellaWanja, @Nagsenwaghmare, @Manasa2850, @joshuaretallick, @BenUnyolo for picking up new issues and working on them in the last week. We appreciate the time you are taking to help us improve [PublicLab](https://publiclab.org/). ❤️ 

A huge shout out to our reviewers as well @jywarren, @cesswairimu, @Sagarpreet 🥇 

A big thank you to @noi5e for creating a large number of FTOs as well 🥇 

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by cesswairimu** [comment]
Thanks @RuthNjeri 🎉

**Comment by noi5e** [comment]
Thanks @RuthNjeri! I appreciate this topic. I've been trying to do my best to keep my PRs nice and small, I know I've been guilty of doing some big ones in the past.

Part of it was just learning to be more comfortable with Git workflow. Once I understood what a `git rebase` was, I saw that I didn't have to solve everything in one PR... Instead, if I get stuck in one PR, I can open a second PR to fix the first one. Once that gets merged, I can `git rebase main` in the first PR to get my fix from the second PR. Things like that make me really grateful for Git! I wonder how people even programmed without it.

**Comment by jywarren** [comment]
I'm always amazed at how relatively easily Git resolves conflicts, @noi5e -- its kind of magic!

In breaking down my own work, my guide is to think of the amount of time it takes to "get in the zone" or really more like "get back into the mental state it requires to take the next step" -- because i tend to switch quickly between tasks a lot, like a magpie, and if it takes a long while to get back into the state of mind required, then i have to do that over and over and it wastes time and tires me out.

So i try to leave notes that allow me to quickly jump back into a mental context -- which are usually similar to what it takes to help someone ELSE find their way into what i was doing, as a bonus! Some tasks seem to take ten minutes or more to recover my state of mind with all the relevant info, and so I try to work in smaller pieces than that where possible. This, i hope, tends to make code I write more newcomer friendly as well, because you can orient yourself to some degree -- enough to be useful -- without having to know more than your immediate surroundings; not the whole forest, so to speak. So that's what I aim for! That's also why i leave comments to myself as notes as i work on a longer process, so I know where to pick back up. 

Great theme, Ruth!!!

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/plots2/issues/9205 thanks all

**Comment by ebarry** [comment]
I like this "magpie" Jeff concept
