### ISSUE TITLE
"Suggest a new title" feature to make friendly suggestions of more descriptive titles

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#919]
This would need some UI design work, but the idea is that it'd be a comment which could actually have a button on it that says something like:

> [Jeff]() is suggesting an alternative title, "How to fix a Time Machine Kit". To accept this as a new title to your post, `click here`. 

Then that button would directly replace your title. Curious what people think of this idea -- it'd likely need both a new controller action in the [notes controller](https://github.com/publiclab/plots2/tree/master/app/controllers/notes_controller.rb), and some well-thought-through UI design leading into the comment display template: https://github.com/publiclab/plots2/blob/master/app/views/comments/_comments.html.erb

**Comment by ebarry** [comment]
Seems like I see this idea from multiple perspectives, one of them is that this is essentially a type of in-line commenting that helps us help each other granularly improve our communication. 

At first though, reading this does kind of rub me the wrong way because i do love personal / idiosyncratic expression ... but i then i kind of come around to this idea for helping each other clarify our phrasing. I think we're here using the publiclab.org platform and sister platforms to collaborate not only on developing methods but also to collaborate on communicating so more people can get involved.

**Comment by ebarry** [comment]
Hi @pdhixenbaugh here's the issue about helping to improve titles that we mentioned on the open call earlier today!

**Comment by ViditChitkara** [comment]
@jywarren, @ebarry I want to work on it if it is available!

**Comment by ViditChitkara** [comment]
@jywarren I have an idea about this feature. 
Just like including inline power tags in the body we could use another syntax For eg:- {Changed title}. We could then use regex to detect this and embed a partial just like question grids, activity grids, etc.
Your thoughts??

**Comment by ViditChitkara** [comment]
Submitting a pr for this!!

**Comment by ViditChitkara** [comment]
Yes, this would be in the comment. Currently I have used ( {New Title} ) curly braces instead which could be easily changed according to the design we finalise.

**Comment by jywarren** [comment]
@pdhixenbaugh @ebarry this was just completed! :-) 🎈
