### ISSUE TITLE
Weekly Community Check-In #92 - Let's talk BurnOut

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#9205]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Let's talk BurnOut

BurnOut is an issue that affects a lot of people in the tech industry..This week share things you do to make avoid burn out, have you ever experienced burnout? tell us about it and what you did or normally do to get over it.

## This week's focus Issues

These are issues that are of high priority and requests from our
large community that use the software. 

https://github.com/publiclab/plots2/labels/high-priority

We will very much appreciate any help on these issues. Any contributor who is looking for issues to work on please consider taking a look at these.
We will add a thank you message here in next week's check-in if you contribute to any of these. Thanks in advance 😄

### Thank yous 

🥇🥇 Thanks so much @noi5e @RuthNjeri for many ftos created in the past week 🥇🥇
 🥇Thanks a lot @Manasa2850 @noi5e @RuthNjeri @jywarren @Sagarpreet for the reviews and feedback in the past week  🥇 🥇 

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by RuthNjeri** [comment]
Thanks for this @cesswairimu!

I know burnout could happen in different ways, I am not sure how to describe it. One thing I do to avoid it is ensuring that I do not overexert myself in work. Sometimes I catch myself when I want to do some extra work and tell myself to just leave it for tomorrow because work never ends. Other times, I try my best to avoid working 'after' hours because it could easily become a habit.

**Comment by noi5e** [comment]
Yeah, thanks for posting this @cesswairimu! It's a really important topic.

I like to track my time using the [Pomodoro technique](https://en.wikipedia.org/wiki/Pomodoro_Technique). Tracking and budgeting my time helps me feel less anxious about getting things done... I can look at a goal and say to myself, _"Oh, that will take around 3 days"_, which somehow takes a lot of the stress out of work. Otherwise, big tasks would feel impossible, and I might over-exert myself to compensate.

Another thing I like about Pomodoro technique is that the breaks are built into your work. Like, you set a timer for 25 minutes, then take a break for 5 (in theory, I actually skip breaks sometimes). But it helps to have a timer go **ding!** to remind me to stand up, drink water, bathroom break, re-focus my eyes, etc. It also helps to go to the park in the middle of the day and sit in the sun for 30 minutes. Nature is great! 🌞 

Is it just me or is it kind of hard to do 8 hours of work on a screen? 😅  I agree with what @RuthNjeri  says, I often feel tempted to work late into the night up until 1AM. But after a few months of doing this, I see that's actually counter-productive, because I wake up late the next day and feel rushed about getting work done. It's better to get good sleep.

**Comment by jywarren** [comment]
OMG i should really try pomodoro just for the "stand up take a break" thing. Tuesday I didn't move my body at all! It was not a good feeling. 

One thing I've really learned during the past year is that I have waves of energy and also lethargy, and that i have to learn to be attuned to my body and mind and to go with it when i feel it, but not force it when I don't, if I can help it. So, sometimes i've been laying out a plan for the day in recent months, but then i feel drawn into a specific task or project, and i've learned to follow that instinct rather than stick to the plan, and it's led me to some good inspirations and work sessions. the 9-5 is really not so natural!

**Comment by cesswairimu** [comment]
Thanks everyone for sharing.
This sneaks up on me every now and then, I do not have a well laid out plan of avoiding it yet...I have this not so good habit-- when I get started on a task I just don't know when to stop esp if I am in the "zone". Working from home has made it worse because when previously leaving the office would mean I am done from the day..now I just lose track of time... I will  give Pomodoro a try too...and an idea came from that I will have an alarm that notifies me when my office hours are done. Thanks again everyone

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/plots2/issues/9229. Thanks all
