### ISSUE TITLE
Activity timestamp errors related to new dashboard

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#9215]
Hi, @RuthNjeri i'm seeing this interesting error while testing out fixes for the "owmloading" bug on the latest main branch - i tried entering the tags `lat:32,lon:-90` into the tag input form and it turned grey but didn't add the tags. I checked the logs and saw this:

```
Completed 500 Internal Server Error in 76ms (ActiveRecord: 62.1ms)


undefined method `activity_timestamp=' for #<Tag:0x00007f921d32ece8> excluded from capture: Not configured to send/capture in environment 'development'
  
NoMethodError (undefined method `activity_timestamp=' for #<Tag:0x00007f921d32ece8>):
```

Not sure -- i think we have to run a migration and we haven't yet? That column seems not to exist yet. Any thoughts on this? Maybe it's as simple as editing the `schema.rb.example` file to ensure that the latest migration is run in the database?

**Comment by RuthNjeri** [comment]
Hi @jywarren I am trying to test this on the stable site https://stable.publiclab.org/  and everything seems to be working as expected(the tags bumping up a topic card when a new post is added...)

Are you testing this out locally? Your suggestion to add it in the schema.rb.example makes sense because in the installation steps outlined in the README we have this statement

`Run cp db/schema.rb.example db/schema.rb to make a copy of db/schema.rb.example in db/schema.rb.`
I've created the fix to add the columns in the `schema.rb.example` here https://github.com/publiclab/plots2/pull/9216

**Comment by jywarren** [comment]
I saw this in GitPod, so i'm not sure... i am remembering that there are 2 processes -- one from a fresh empty database where we just build it with `rake db:setup` and `rake db:seed` (i think) and another where it's a pre-existing database and we run `rake db:migrate`. So the migration you wrote is fine for a live existing database but in GitPod it's trying to instantiate one all at once from the schema.rb.example file and "start fresh". I think you should be able to just duplicate your `schema.rb` file, rename it to `schema.rb.example` and add those changes; we can review them to make sure it only affects the lines for the appropriate table. How does that sound?

Thanks, Ruth, and sorry I didn't catch this, it's been a while since we had a db change!!
