### ISSUE TITLE
Text overflows in editor (rich mode)

### ISSUE THREAD

**Issue by eightballocto** [publiclab/plots2#9476]
### Problem

When using the editor's Rich mode (i.e. wysiwyg) the text does not wrap around inside of the text area, but instead overflows and causes visual bugs.

![image](https://user-images.githubusercontent.com/58581962/114086397-305f9500-9878-11eb-8cba-32ddc0cca649.png)

### Where to find this bug

https://publiclab.org/post

### How to reproduce

Use the editor's "Rich" mode and type in a long string of characters (no new lines)

**Comment by aliciapaz** [comment]
Hi @eightballocto! 

I managed to fix it in the browser with this line of code: 

`word-break: break-all` 

![image](https://user-images.githubusercontent.com/67963195/114212659-14b7c580-9930-11eb-84db-1dd70e94604e.png)

However, I don't know exactly where to put it, since adding it to the class` .wk-wysiwyg `in wiki.css (where it is already)  didn't work.

Any ideas please? 😸

**Comment by eightballocto** [comment]
Actually, I noticed that in `wiki.css` this rule *doesn't* exist, and I added it. I've submitted a PR [here](https://github.com/publiclab/plots2/pull/9483)
