### ISSUE TITLE
When replying to a newly posted comment, the last comment text appears in the new "reply" comment form

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#9500]
This is on the non-React version so it may simply be solved by adopting the React version, but we'd have to test that it doesn't occur there. 

See how i just posted this comment and when i try to reply to the new comment, i see this in the textarea:

![image](https://user-images.githubusercontent.com/24359/114584241-750c7700-9c50-11eb-888d-64603e8e9cbc.png)

**Comment by Priyaraj17** [comment]
I can take a look into this.

**Comment by waridrox** [comment]
I was able to partially fix this on local env, but I'm not sure if it will work for sure on production env as well. That's because I also observed with/without the changes made, after replying to the comment once, a new reply comment box is generated with the previous contents again.


https://user-images.githubusercontent.com/58583793/114784451-e5261480-9d98-11eb-849b-f7dbc89b7c4e.mp4


Can someone pls confirm if the same behaviour of multiple replies is observed on the production env as well or is it just specific to local env...thanks.

**Comment by waridrox** [comment]
Ok, so I tried reproducing the error on the official website at https://publiclab.org and the error is persistent there 😅 where after the first comment reply, the second one keeps generating with the contents of the previous reply...


https://user-images.githubusercontent.com/58583793/116222612-618eff00-a76c-11eb-8836-a8dbdd3747f1.mp4
