### ISSUE TITLE
Isolated case: alert bar isn't being generated by the 'parent:foo' powertag on one wiki page

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#9562]
Here's a cute bug! 🐛

### The problem

First reported by @steviepubliclab : 

The powertag `parent:foo` is able to be added to wiki page https://publiclab.org/wiki/fellowship-teams, but it fails to generate the alert bar at the top of the page that links to the parent page. The parent page https://publiclab.org/wiki/fellows does not show that it possesses any subpages, which is also incorrect. 

I want to mention that this problem seems limited to the /fellowship-teams page, because here's a working example of a chain of parented wikis: https://publiclab.org/wiki/website-basics. This page displays its subpages and the alert bar is present and working properly, which is true for all the pages in this chain. 

> What did you expect to see that you didn't?

I expected to see a bar on /fellowship-teams like the bar that appears on https://publiclab.org/wiki/website-basics -- In hot pink, i've circled the bar and also the powertag in the right sidebar that generates it. 
<img width="1085" alt="Screen Shot 2021-04-26 at 10 08 18 AM" src="https://user-images.githubusercontent.com/161439/116096721-835a8a00-a677-11eb-856f-391166f567dd.png">

I also expected to see that the parent page /fellows lists /fellowship-teams as a subpage in the right sidebar. 

### Please show us where to look

Not working: https://publiclab.org/wiki/fellowship-teams
Working: https://publiclab.org/wiki/website-basics

### What's your PublicLab.org username?
Liz

**Comment by jywarren** [comment]
Hi, thanks for filing a great issue with so much detail. The key section of code which generates this alert is here:

https://github.com/publiclab/plots2/blob/e646cfd248e46fe9cf11a2eb7860bbf29f949b7d/app/views/wiki/_header.html.erb#L55-L60

It depends on this line:

```ruby
Node.find_by(slug: @node.power_tag('parent'))
```

which is pretty simple, it just gets the "value" for the powertag, which should be "fellows" and then it searches for the node with a matching slug, so https://publiclab.org/wiki/fellows /should/ return. Let me try running this directly in the server console.

Aha:

```
irb(main):002:0> Node.find_by(slug: 'fellows')
=> nil
```

So that wiki page for some reason is missing that slug. Aha, it used to have a different slug:

```
irb(main):003:0> Node.find_by(path: '/wiki/fellows')
=> #<Node nid: 11712, vid: 46231, type: "page", language: "", title: "Public Lab Fellows Program", uid: 9, status: 1, created: 1426973508, changed: 1619209284, comment: 0, promote: 0, moderate: 0, sticky: 0, tnid: 0, translate: 0, cached_likes: 20, comments_count: 0, drupal_node_revisions_count: 92, path: "/wiki/fellows", main_image_id: 34396, slug: "public-lab-fellows-program", views: 4847, latitude: nil, longitude: nil, precision: nil, flag: 5>
```

I can change it in the database to match. I think this might have been a manual database change at some point to "fix" the wiki page slug/URL to be shorter, and it shows some of the risk of direct database edits. Hard to diagnose, though easy to fix!

**Comment by jywarren** [comment]
OK, fixed!

![image](https://user-images.githubusercontent.com/24359/116280176-6a74d600-a756-11eb-9e53-02f327105273.png)

**Comment by ebarry** [comment]
Thank you!!!!! The team's gonna love this
