### ISSUE TITLE
/notes/author/warren template should match /tag/water-quality, not /notes

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#9586]
We have a great new page at https://publiclab.org/notes/ made by @RuthNjeri and it uses a slightly different presentation of types of content by nav, instead of by tab:

Unfortunately it looks like this type of page also got that template:

https://publiclab.org/notes/author/cess/

Actually that should have tabs similarly to https://publiclab.org/tag/water-quality - i think something about how we choose templates by route may have messed this up. 

let's find the place where the template is chosen and it should be an easy fix to return it to the prior template, esp. so that clicking "Questions" shows you questions by that author instead of just all questions at https://publiclab.org/questions

Thanks! This would make a nice first-timers-only issue once we find the line of code!

****
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

**Comment by aliciapaz** [comment]
I'd like to work on this and create the FTO.

**Comment by aliciapaz** [comment]
Looks like this template was deliberately used for this route:

In notes_controller.rb
![image](https://user-images.githubusercontent.com/67963195/116613014-32ac9080-a906-11eb-879b-8a16e0a44423.png)

However, the one used in tag_controller.rb is not really a template:

At the end of `tag#show`
![image](https://user-images.githubusercontent.com/67963195/116613253-6f788780-a906-11eb-9089-c0af9d7783da.png)

In fact, the show view for tags is styled between `<style>` tags in the same file. The links in that view are kind of hardcoded for tags only, so I don't think we can use that view for `notes#author`. 

Possible solutions for this (that I can think of): 
- Stick to the current template, but change the navigation links to be dynamically generated instead of hardcoded, maybe using a partial or defining a method inside `NotesHelper` (?)
- Creating a different template for this based on views/tag/show.html.erb

Personally, I prefer the first solution since it's cleaner and more consistent with the new page. Is this still suitable for an FTO?

**Comment by jywarren** [comment]
Oh no, i'm thinking of `tag/show`, as you say, not `notes/show`. My bad!

**Comment by jywarren** [comment]
So my suggestion to try out might be to try changing `notes/index` to `tag/show`? I hope that would work!

**Comment by aliciapaz** [comment]
Thanks @jywarren 
I tried that, but since the links are hardcoded, when you click on 'questions', it goes to `questions/tag/<TagNameButIsReallyAnAuthorName>`
that's what I meant with:

> In fact, the show view for tags is styled between <style> tags in the same file. The links in that view are kind of hardcoded for tags only, so I don't think we can use that view for notes#author.

**Comment by aliciapaz** [comment]
I think this could work!!

> If not, perhaps we can look at the notes/index template before @RuthNjeri's changes and see what it used to look at, to help us get notes/show working that way.

**Comment by RuthNjeri** [comment]
Hi @aliciapaz and @jywarren, I am having a look at this now, yes I did work on the notes/index view, if you want to have a look at the changes that were made, you can have a look at it [here](https://github.com/publiclab/plots2/pull/8848/files#diff-4fe647349351c7492508c788230b91b7f4445d4b821f6781ac7fcfad5e879f21) 

I have looked at the `tag/show` file, it has a lot of reliance on tags instance variables and tag logic, compared to the `notes/index`, the logic to be updated and changed is minimal...I think having a new page `notes/author` similar to `notes/index` but with the tabs makes sense, just incase we want to update the authors's page design in the future...and I also think it separates the logic for a singular user and all the notes in the system.

**Comment by aliciapaz** [comment]
Thank you @RuthNjeri
So broken down in tasks, this issue would require: 

- Writing unit and functional tests for the tab links in `notes/author`
- Creating a new view for `notes/author` based on `notes/index` but with the contents by tabs instead of nav

Does this make sense?
This would be my first time contributing to the tests of the project 👀

**Comment by jywarren** [comment]
Hi @aliciapaz yes i think that's correct - and i appreciate the idea from @RuthNjeri on separating functions. I /believe/ we can use just the partial template for the tabs, instead of rewriting the tabs, is that right @RuthNjeri?

https://github.com/publiclab/plots2/blob/main/app/views/tag/show/_nav_tabs.html.erb

**Comment by jywarren** [comment]
Thank you!!!! @aliciapaz if you need help on where to begin please reach out!

**Comment by RuthNjeri** [comment]
@aliciapaz yes, that's correct, I am not too sure you can write a unit or functional test for the tab links, testing whether it is a tab sounds like a system test. I think the links have their respective tests, but if they don't, you can add them. I trust your judgement with the testing, you can add them and tag me to review.

@jywarren yes, reusing the nav_tabs template sounds good!
