### ISSUE TITLE
Bug in the search input form in the navbar.

### ISSUE THREAD

**Issue by Priyaraj17** [publiclab/plots2#9593]
### Please describe the problem (or idea)

Whenever we focus on the search input. A vertical blue line appears at the right. Take a look at this image to understand the problem
![WhatsApp Image 2021-05-02 at 9 31 17 PM](https://user-images.githubusercontent.com/40101776/116819462-cfcd2a80-ab8d-11eb-9774-281c8a676bfc.jpeg)

> What did you expect to see that you didn't?

The line should be removed.

### Please show us where to look

https://publiclab.org/
Focus on the search box.

### What's your PublicLab.org username?

> This can help us diagnose the issue: 
priyaraj_17

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!
chrome 
Version 90.0.4430.85
Ubuntu 20.04

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by Elukoye** [comment]
Can I work on this @Priyaraj17 ?

**Comment by Priyaraj17** [comment]
@Elukoye sure go ahead. Let me know if you face any problem.

**Comment by Elukoye** [comment]
@Priyaraj17  thanks ,I will

**Comment by Elukoye** [comment]
Hi @Priyaraj17,
I had a look at this and realized that the blue line is coming from the data-focus-visible-added class
![Screenshot (79)_LI](https://user-images.githubusercontent.com/46542515/116916348-e048d800-ac55-11eb-905b-6e7af6b22e33.jpg).

**Comment by Elukoye** [comment]
Therefore, i don't think it is a bug, let me know your thoughts. 🙂

**Comment by Priyaraj17** [comment]
Ohh, I see. Give me a couple of minutes @Elukoye

**Comment by Priyaraj17** [comment]
You are right, thank you for the effort. I apologise for this. I hope you didn't spend a lot of time on this.

**Comment by Elukoye** [comment]
No problem @Priyaraj17  🙂👍,maybe we could request for this issue to be closed by the mentors ?

**Comment by Priyaraj17** [comment]
Yeah sure. I will ask for their opinion.

**Comment by cesswairimu** [comment]
hi everyone, the above image I believe consists of two elements, the search field, and the search icon as a clickable button....I wouldn't say its a bug because we meant it to be like that...what you could do @Elukoye  @Priyaraj17 you could come up with a mockup of how you would like to improve that section and then we can discuss from there...in the meantime I will label this as "enhancement" ..what do you both think?
Thanks all

**Comment by Priyaraj17** [comment]
> Yeah sure. I will ask for their opinion. 

 I think it's a nice idea. We can definitely come up with a solution.

**Comment by waridrox** [comment]
How about changing the focus state border box shadow style to reflect inside the input field 🙂...That way the user is able to see the border focus shadow clearly which the current search box is unable to achieve due to a dark background around the input field: 
<img width="440" alt="Screenshot 2021-05-04 at 6 50 19 PM" src="https://user-images.githubusercontent.com/58583793/117009958-ec8e6d00-ad09-11eb-9b37-4bea8edfdf18.png">


![sample2](https://user-images.githubusercontent.com/58583793/117010825-d46b1d80-ad0a-11eb-875e-41078117316a.gif)

This could be achieved by simply adding the `inset` keyword for box shadow under focus state.

**Comment by Priyaraj17** [comment]
@waridrox hey, I prefer this over the current one. Let's see what the mentors have to say and also @Elukoye what do you think?

**Comment by Elukoye** [comment]
@Priyaraj17 ,@waridrox ,I like what @waridrox  suggested but I think the box shadowing should be around the border of the input ,like below ![Screenshot_20210504-173712.png](https://user-images.githubusercontent.com/46542515/117020729-62410b80-acff-11eb-93b3-46307f746415.png)

**Comment by Priyaraj17** [comment]
Both of them are good. But, prefer @waridrox's suggestion. Let's see what others have to say.

**Comment by Elukoye** [comment]
Ok then shall I implement @waridrox 's suggestion?

**Comment by Elukoye** [comment]
@cesswairimu ? @ jywarren ?

**Comment by Priyaraj17** [comment]
@Elukoye Hey, I think they are busy. Maybe you can start working on it.

**Comment by waridrox** [comment]
Hi all sorry for the delay 😅, I thought we were just brainstorming here for the ideas...maybe we could try implementing both the ideas and see which one suites better ? It's just a matter of applying the styles to the search box once we find where it lies in the codebase 👍

**Comment by Priyaraj17** [comment]
> Hi all sorry for the delay , I thought we were just brainstorming here for the ideas...maybe we could try implementing both the ideas and see which one suites better ? It's just a matter of applying the styles to the search box once we find where it lies in the codebase

Yeah. Sure. I like this idea. We can compare which one looks better.

**Comment by Elukoye** [comment]
@Priyaraj17 ,@waridrox  I already started playing around with it and I realized that what I suggested was the default Bootstrap style. Also as @cesswairimu  said ,the bootstrap implementation involves 2 buttons. I have seen that some of the files ,they have used inline styling. So was wondering if I could override the default style with inline css.
What do u think @waridrox ,since u suggested adding keyword inset to the box shadow property.
Am going to work on this and hopefully have a sample by tomorrow.

**Comment by Elukoye** [comment]
@Priyaraj17 ,the code is in the views folder , layouts dub folder ,header partial ,line 20.

**Comment by waridrox** [comment]
@Elukoye, I think it's not possible to deal with pseudo classes like `:focus` using inline CSS 😅. Either we need to use the `<style>` tag or we can apply the styles in the file `app/assets/stylesheets/styles.css` and see if that works.

**Comment by Priyaraj17** [comment]
> Ok then shall I implement @waridrox 's suggestion?

    @Elukoye, Thanks, I will take a look too.

**Comment by Priyaraj17** [comment]
@Elukoye Thank you. I will also take a look into it. I think @waridrox it's better if we apply the styles in app/assets/stylesheets/styles.css.

**Comment by Elukoye** [comment]
@Priyaraj17 ,@waridrox what about simply adjusting the color of the navbar ? To make it lighter or blend in nicely with bootstraps light blue focus on the input's border ?

**Comment by waridrox** [comment]
@Priyaraj17 @Elukoye, any updates ?? I tried my option - 

![test](https://user-images.githubusercontent.com/58583793/118099774-55a16f00-b3f3-11eb-9879-0958ebc3dd8e.gif)

What do you guys think. @Elukoye pls share your solution as well so that we can finally come upon a decision...

**Comment by Priyaraj17** [comment]
@waridrox Thanks for sharing your approach.  This looks good. I think we should close this issue today, @Elukoye what do you think?

**Comment by Elukoye** [comment]
@Priyaraj17 ,@waridrox  looks good . Thanks for sharing ,yes we can close this

**Comment by Priyaraj17** [comment]
@waridrox Can you please make the PR?

**Comment by sakshi-2412** [comment]
@waridrox is this issue open? I think it has been resolved

**Comment by TildaDares** [comment]
Hi @sakshi-2412, yes this has been resolved in #9634. Thanks!
