### ISSUE TITLE
Photos are not Loading to Posts/Research Notes

### ISSUE THREAD

**Issue by sarasage** [publiclab/plots2#9758]
When loading photos to posts, the uploads get stuck and stalls at 100%. This problem has been happening for at least a week, to my knowledge. I have tried uploading photos a couple dozen times, with no success over the last week.

Draft post in question:
https://publiclab.org/notes/edit/26745?t=1623080539

Using Chrome Browser
Processor	Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz   1.19 GHz
System type	64-bit operating system, x64-based processor

Will upload screenshot to #chat.

**Comment by icarito** [comment]
Thanks for your report. Indeed the Storage volume seems to be having issues. Restarting it now.

**Comment by icarito** [comment]
The reason for this issue is we're using `gcsfuse` to mount a Google Storage Volume as read-write, in order to be able to write to it. It seems that this package may have some bugs and lock the mountpoint causing read-write requests to it to stall indefinitly. This may have something to do with recent issues where the website was not responsive.

**Comment by sarasage** [comment]
Thank you, again. I will close the issue now since it has been solved.
