### ISSUE TITLE
Weekly Community Check-In #110- Blockchain and CryptoCurrency

### ISSUE THREAD

**Issue by unnati914** [publiclab/plots2#9920]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Title -  Blockchain and CryptoCurrency

This week share about what you know about Blockchain and CryptoCurrency on PublicLab. This could be a project, resource, how you learnt, your path anything :)

## Why Blockchain

It is an immutable public digital ledger, which means when a transaction is recorded, it cannot be modified. Due to the encryption feature, Blockchain is always secure. The transactions are done instantly and transparently, as the ledger is updated automatically.

## This week's focus Issues

These are issues that are of high priority and requests from our
large community that use the software. 

https://github.com/publiclab/plots2/labels/high-priority

We will very much appreciate any help on these issues. Any contributor who is looking for issues to work on please consider taking a look at these.
We will add a thank you message here in next week's check-in if you contribute to any of these. Thanks in advance 😄

### Thank you note to focus issues contributors

@jywarren , @17sushmita , @imajit , @Manasa2850 , @TildaDares , @anirudhprabhakaran3 , @icarito , @lonwabo-mnyaiza , @Shreyas220 , @Shashwat545 , @BajajSmriti , @sab30-webdev , @cgrkzlkn 

💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by Tlazypanda** [comment]
Hey @unnati914 very interesting theme! :100: The vast applications of blockchain and the possibility of a completely decentralised system is very exciting to me. Had made a simple smart contract once during a hackathon project to test out some transactions using the metamask plugin, definitely got me more interested in this domain :) 

Also @publiclab/soc folks! Just noting that since we are nearing the end of soc projects, now would be a good time to break down some future scope tasks for your projects into ftos for our first timers  feel free to open ftos or even a planning issue suggesting what tasks from your project we can break down into ftos.
Here is a reference task from @nstjean publiclab/plots2#6579 that was used for making over 50 ftos  
Here is a list thanks to @cesswairimu publiclab/plots2#9899 for all the contributors looking for ftos, you may comment with your ftos here as well 
Thank you all!! :heart: :heart:

**Comment by daemon1024** [comment]
That's an interesting topic for sure.

I am not really liking where the current Blockchain and cryptocurrency industry is headed to creating hype and being a money making tool rather than being helpful in real world. 

But I really am in favour of decentralisation in general. Just dropping in an awesome article on how/why Tim Berners-Lee ( Inventor of world wide web ) wants to re-decentralise the web. https://www.wired.co.uk/article/tim-berners-lee-reclaim-the-web

**Comment by unnati914** [comment]
Yes even I have been exploring smartpy these days which texos use.. it's only used for decentralized apps and quite secured too

**Comment by unnati914** [comment]
Here is the link from which I'm learning about smartpy

smartpy.io

https://medium.com/coinmonks/building-your-first-dapp-on-tezos-part-1-writing-smart-contract-on-smartpy-d7cdf27476f9

https://www.leewayhertz.com/tezos-smart-contracts/

**Comment by sakshamlamba109** [comment]
Hey there!!
I want to open weekly Check-In

**Comment by unnati914** [comment]
yes go for it :) @sakshamlamba109 :)

**Comment by unnati914** [comment]
https://github.com/publiclab/plots2/issues/new/choose refer this template for opening the issue, 
We usually open issues on Mondays/Tuesdays
Thank you!

**Comment by sakshamlamba109** [comment]
Okay Thanks :)

**Comment by unnati914** [comment]
moved to #9953 💯
