### ISSUE TITLE
Process for finding and adding new strings to the translation system

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#9930]
Some strings like these are added and never get pulled into translation -- @imajit what kind of regular process do you think we could take up to catch them and gradually integrate them?

https://github.com/publiclab/plots2/blob/1afcac6d61715fcd346e3b7148a7505697297ca1/app/views/layouts/_header.html.erb#L89-L92

**Comment by jywarren** [comment]
Noting that, to keep barriers to participation low, we have avoided front-loading translations in favor of gradually integrating them!

**Comment by imajit** [comment]
I too have seen HTML elements where direct strings are added instead of storing these strings as constants in `en.yml` file and using the translation function to call it. 
If we use translation function we can translate them into multiple languages and also if we want to change the string we can directly change it in constants file instead of finding it across the codebase and changing each occurrence.
I think we can create FTO issues to do this. 
This could be a rough idea for the FTO workflow:
- [ ] Find HTML elements where direct strings are used.
- [ ] Create FTO issue to move this to `en.yml`
- [ ] Create follow-up FTOs to replace other instances of a string with translation function calls.

**Comment by Tlazypanda** [comment]
Hey @imajit That sounds like a good workflow to begin with :tada: 

If it's not too much to ask can you start with one example for this so we can share it as an example for our more experienced contributors to take up on and create issues for our first timers? :sweat_smile: Thank you :heart:

**Comment by noi5e** [comment]
Discussion moved to #9945
